### ISSUE TITLE
segmentation fault for multiinter

### ISSUE THREAD

**Issue by tom21100227** [arq5x/bedtools2#1005]
Hi, I was trying to use multiinter to compare 6 different lines, but received a 
`Segmentation fault (core dumped)`
 error message. 

This issue happens after I sorted those .bed files with 
`sort -i <.bed>`
, before the sort, there would be some results output until: 
```
[chan@foxcroft ~/intersectedGoodData]$ bedtools multiinter -cluster -header -names mauMAU melCOL melETH melORE melZIM simZIM -i mauMAU.bed melCOL.bed melETH.bed melORE.bed melZIM.bed simZIM.bed 
chrom	start	end	num	list	mauMAU	melCOL	melETH	melORE	melZIM	simZIM
211000022278100	1829	1932	2	melCOL,melORE	0	1	0	1	0	0
ERROR: input file: (melCOL.bed) is not sorted by chrom then start.
       The start coordinate at line 4 is less than the start at line 3
```

After I sorted all the data, this happens: 
```
[chan@foxcroft ~/sortedData]$ bedtools multiinter -cluster -header -names mauMAU melCOL melETH melORE melZIM simZIM -i mauMAU.bed melCOL.bed melETH.bed melORE.bed melZIM.bed simZIM.bed 
chrom	start	end	num	list	mauMAU	melCOL	melETH	melORE	melZIM	simZIM
Segmentation fault (core dumped)
```

The problem seems to be too much memory used but there isn't a solution like the `-sorted` option in `intersect`. 

Thanks in advance for your help, 

The attached file is unsorted .narrowPeak files generated by macs then intersected in bedtools, creating the results in the first code block: 
[intersectedGoodData.zip](https://github.com/arq5x/bedtools2/files/8874679/intersectedGoodData.zip)

**Comment by arq5x** [comment]
Your files weren't sorted properly.

    sort -k1,1 -k2,2n -c mauMAU.bed
    sort: mauMAU.bed:6: disorder: 211000022278878	84	550	mauMAU_A_peak_4	5728	.	13.5934	576.039	572.874	373

    sort -k1,1 -k2,2n mauMAU.bed > mauMAU.sorted.bed
    sort -k1,1 -k2,2n melCOL.bed > melCOL.sorted.bed
    sort -k1,1 -k2,2n melETH.bed > melETH.sorted.bed
    sort -k1,1 -k2,2n melORE.bed > melORE.sorted.bed
    sort -k1,1 -k2,2n melZIM.bed > melZIM.sorted.bed
    sort -k1,1 -k2,2n simZIM.bed > simZIM.sorted.bed

    bedtools multiinter -cluster -header -names mauMAU melCOL melETH melORE melZIM simZIM -i mauMAU.sorted.bed melCOL.sorted.bed melETH.sorted.bed melORE.sorted.bed melZIM.sorted.bed simZIM.sorted.bed | head
    chrom	start	end	num	list	mauMAU	melCOL	melETH	melORE	melZIM	simZIM
    211000022278100	2632	2665	3	melCOL,melORE,melZIM	0	1	0	1	1	0
    211000022278100	3012	3189	3	melCOL,melORE,melZIM	0	1	0	1	1	0
    211000022278122	791	986	4	melCOL,melETH,melORE,melZIM	0	1	1	1	1	0
    211000022278137	238	366	1	melCOL	0	1	0	0	0	0
    211000022278137	734	914	3	melCOL,melETH,melORE	0	1	1	1	0	0
    211000022278145	122	467	2	melORE,melZIM	0	0	0	1	1	0
    211000022278165	1057	1285	1	melCOL	0	1	0	0	0	0
    211000022278174	652	969	1	melCOL	0	1	0	0	0	0
    211000022278208	1492	1618	4	melCOL,melETH,melORE,melZIM	0	1	1	1	1	0
