### ISSUE TITLE
Bug with mergeBed -s

### ISSUE THREAD

**Issue by duzc-Repos** [arq5x/bedtools2#1009]
Hi, recently I update the bedtools to v2.30.0 and when I use "merge -s" command to merge the exon region annotated by Gencode, the forth column didn't show the strand information.
PS: bedtools were installed by conda

**Comment by arq5x** [comment]
Yes, there was a breaking change a few releases ago. See:
https://bedtools.readthedocs.io/en/latest/content/tools/merge.html

    bedtools merge -i A.bed -s -c 6 -o distinct
    chr1  100 250 +
    chr1  501 1000  +

**Comment by duzc-Repos** [comment]
thank you!
