### ISSUE TITLE
Different sorting in bam and bed

### ISSUE THREAD

**Issue by gubrins** [arq5x/bedtools2#1010]
Heys,

I am having problems when trying to calculate coverage levels of a bed file with genomeCoverageBed (v2.3), as my bam and bed files are sorted differently:

cut -f 1 combined_after_scaffolding.bed |uniq
`scaffold_1
scaffold_10
`

samtools view -H both_not_filtered_sorted.bam
`àHD	VN:1.6	SO:queryname
àSQ	SN:scaffold_1	LN:233710445
àSQ	SN:scaffold_2	LN:214025719`

However, when I try to sort it with the genome.file like this:
bedtools sort -g genomefile.txt -i combined_after_scaffolding.bed > sorted.bed

My computer rans out of memory (250Gb). Any solutions to that?

Thanks in advance!

**Comment by arq5x** [comment]
I would use UNIX sort:

    sort -k1,1 -k2,2n in.bed > in.sorted.bed

You can get further performance by defining locales and providing sort more memory

    LC_ALL=C sort -k1,1 -k2,2n  -S 2G  in.bed > in.sorted.bed
