### ISSUE TITLE
has inconsistent naming convention for record

### ISSUE THREAD

**Issue by CherryX727** [arq5x/bedtools2#1016]
Hi, I am using bedtools intersect to overlap sites with given data 'REDIportal_Human_AG_all_hg38.bed'.
But when I use code
`bedtools intersect -wa -a TTTTGTTGTTGA_call1.out -b REDIportal_Human_AG_all_hg38.bed > TTTTGTTGTTGA_call1_overlap.out`
it warning
```
***** WARNING: File AAACTTGCCCGT_call1.out has inconsistent naming convention for record:
GL000205.2      60017   60018   variant 6.760821593887299       .       5,0,0,0 0,0,5,0 *

***** WARNING: File AAACTTGCCCGT_call1.out has inconsistent naming convention for record:
GL000205.2      60017   60018   variant 6.760821593887299       .       5,0,0,0 0,0,5,0 *
```
It seems that there were conflicting nomenclature.
And I try to use `-nonamecheck`, but it doesn't have any output.

The following is the head of file 'AAACTTGCCCGT_call1.out'
#contig start   end     name    stat    strand  bases11 bases21 info
chr1    7984947 7984948 variant 0.6603734830715382      .       0,0,6,0 1,0,5,0 *
chr1    7985096 7985097 variant 0.6220354087561191      .       0,0,9,0 0,1,8,0 *
chr1    8868047 8868048 variant 0.661881276993924       .       0,6,0,0 0,5,0,1 *
chr1    8871901 8871902 variant 0.5617532856704202      .       0,0,0,16        1,0,0,15        *

and the head of file 'REDIportal_Human_AG_all_hg38.bed'
chr1    10186   10187   NONE,DDX11L1    0       +
chr1    10192   10193   NONE,DDX11L1    0       +
chr1    10210   10211   NONE,DDX11L1    0       +
chr1    10216   10217   NONE,DDX11L1    0       +
chr1    10222   10223   NONE,DDX11L1    0       +
chr1    10228   10229   NONE,DDX11L1    0       +
chr1    10235   10236   NONE,DDX11L1    0       +
chr1    10241   10242   NONE,DDX11L1    0       +
chr1    10248   10249   NONE,DDX11L1    0       +
chr1    10254   10255   NONE,DDX11L1    0       +
chr1    136167  136168  AL627309.1      0       -
chr1    136175  136176  AL627309.1      0       -

How shoud I modify the code or the input file?
Thank you for answering.
Best wishes!

**Comment by lldelisle** [comment]
Hi,
It seems that you are using UCSC style of chromosome naming ('chr1') but you have some records in AAACTTGCCCGT_call1.out for a ensembl chromosome: GL000205.2 which corresponds to chr17_GL000205v2_random in UCSC (see https://github.com/dpryan79/ChromosomeMappings/blob/396f7f3293060cdc5da189490d79b7cebfd3b131/GRCh38_UCSC2ensembl.txt#L75).
I guess the best way to see is is to do:
```
cut -f 1 AAACTTGCCCGT_call1.out | uniq
```
You should see some 'chr' and some `GL000205.2`.

However, this is a warning not an error so bedtools worked fine. If you don't want to see this warning you need to substitute GL000205.2 by chr17_GL000205v2_random in your file AAACTTGCCCGT_call1.out

**Comment by arq5x** [comment]
Thank you for describing the behaviour, @lldelisle !
