### ISSUE TITLE
shuffle produces truncated regions

### ISSUE THREAD

**Issue by liz-is** [arq5x/bedtools2#102]
I've used bedtools shuffle to shuffle a number of ~100kb regions, using the -incl option to specify a set of regions they must be contained in. I used the command below in a shell script to do this 500 times.

`bedtools shuffle -i regions_m100kb.bed -g ~/mm9_data/mm9.chrom.sizes -incl compartmentsA.bed > temp${i}.bed`

5 of my output files contain a region which is less than 100kb. Looking at one of these regions in the UCSC genome browser shows it extends to the very end of the chromosome, so I assume it was extended beyond the chromosome length and then truncated? I didn't use`-allowBeyondChromEnd` so I didn't expect this behaviour!

**Comment by arq5x** [comment]
this is now fixed in master
