### ISSUE TITLE
requested chromosome chr does not exist in the genome file

### ISSUE THREAD

**Issue by ylevmirom** [arq5x/bedtools2#1033]
Hi, 

im using bedtools coverage with this command: 
`bedtools coverage -a chr.bed -b taxa.bam -counts -sorted -g genome.fai> ${TAXA}/${CHR}.DP`
and im getting an error: `requested chromosome chr does not exist in the genome file`

the chromosome names in all files contain a | in it, for example 'lcl|chr1A', 
in this case my bed file looks like this: 
lcl/|chr3A      60500000        60600000
lcl/|chr3A      60600000        60700000
lcl/|chr3A      60700000        60800000
lcl/|chr3A      60800000        60900000
lcl/|chr3A      60900000        61000000

i tried adding the backslash to the genomefile too but im still getting the same error. 

please help? 

thanks

Yael

**Comment by simone-says** [comment]
Pipe characters are typically not tolerated by most programs, I would replace it with an underscore (_) character and get rid of the backslash

**Comment by ylevmirom** [comment]
thanks
