### ISSUE TITLE
Getting gene name with getfasta

### ISSUE THREAD

**Issue by davidaknowles** [arq5x/bedtools2#1044]
Hi Aaron et al. I'm trying to extract a fasta of precursor mRNA, and this is sooo close to what I need: 
`bedtools getfasta -name -s -fi genome.fa -bed genes.gtf -fo precursors.fa`
with the one issue that the fasta header is always "gene" rather than pulling from the GTF attributes. Not sure if there is an easy workaround, if not then I suppose this is a feature request!

**Comment by brentp** [comment]
Hi David, bedtools can use the name column (4th col) in a BED file and use that as the name. It is doing the same for your gtf. For now, I suggest to make such a BED file.

We could try to sniff file formats and handle this for gtf, gff, etc, but I think that will create many new bugs.

**Comment by davidaknowles** [comment]
Thanks. Do you have advice for making that bed file? gtf2bed from bedops doesn't like my Gencode gtf (!) Does bedtools have a way to pull specific attributes from a gtf into the name column? 
Closing this since it's not really an "issue".

**Comment by brentp** [comment]
you can use something like this python script:
```Python
import sys

name_attr = 'gene_name'

for line in sys.stdin:
    if line[0] == '#': continue
    toks = line.rstrip().split('\t')
    name = [x.strip() for x in toks[8].split(';') if x.strip().startswith(name_attr)][0]
    name = name.split()[1].strip('"').strip("'")

    print(f'{toks[0]}\t{int(toks[3])-1}\t{int(toks[4])}\t{name}')
```
then use as:
```
cat $gtf | python gtf2bed.py > $bed
```
I tested on this input:
```
1	transcribed_unprocessed_pseudogene	gene	11869	14409	.	+	.	gene_id "ENSG00000223972"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; 
1	processed_transcript	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; gene_name "DDX11L1"; gene_sourc e "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-002"; transcript_source "havana";
```
and got this output:
```
1	11868	14409	DDX11L1
1	11868	14409	DDX11L1
```
