### ISSUE TITLE
missing include statements

### ISSUE THREAD

**Issue by vpbrendel** [arq5x/bedtools2#1056]
src/utils/general/ParseTools.cpp:#include <cstdint>
src/utils/general/ParseTools.h:#include <cstdint>

Inclusion of the above lines allowed compilation of Fedora 38, all updated.

Volker

**Comment by vpbrendel** [comment]
Sorry - this got truncated. To make the code compile, do this first:

sed -i -e "17a #include <cstdint>/" src/utils/general/ParseTools.h

Volker

**Comment by vpbrendel** [comment]
where the include is followed by cstdint in less than/greater than braces

**Comment by tomp** [comment]
I found the same issue, recently, in trying to build bedtools2 for ArchLinux
