### ISSUE TITLE
bamtofastq writes redundant reads

### ISSUE THREAD

**Issue by slowkow** [arq5x/bedtools2#109]
If a read (or pair of reads) is mapped to multiple locations in your BAM file, then `bedtools bamtofastq` will write multiple copies of that read to your output FASTQ file.

If you have a FASTQ file generated by `bamtofastq`, you can check for duplicate reads with:

(Columns: Line number, Read ID, Cumulative number of duplicates)

```
cat file.end1.fq | perl -e 'while ($a=<>) {$b=<>;$c=<>;$d=<>; chomp $a; if ($H{$a}++) {print "$. $a $H{$a}\n"} }' | head

112 @H7TVLADXX140423:2:1101:1166:90617/1 2
116 @H7TVLADXX140423:2:1101:1166:90617/1 3
120 @H7TVLADXX140423:2:1101:1166:90617/1 4
124 @H7TVLADXX140423:2:1101:1166:90617/1 5
128 @H7TVLADXX140423:2:1101:1166:90617/1 6
220 @H7TVLADXX140423:2:1101:1173:67468/1 2
224 @H7TVLADXX140423:2:1101:1173:67468/1 3
228 @H7TVLADXX140423:2:1101:1173:67468/1 4
232 @H7TVLADXX140423:2:1101:1173:67468/1 5
348 @H7TVLADXX140423:2:1101:1182:83769/1 2
```

Notice that read `@H7T...617` is repeated 6 times, and the last 5 copies are listed on lines 112, 116, 120, 124, and 128 in the file.

To avoid this problem, you can use [Picard SamToFastq.jar](http://picard.sourceforge.net/command-line-overview.shtml#SamToFastq).

**Comment by plijnzaad** [comment]
Hi,

it's actually a bit worse, I get wrong output with multi-mapping paired-end reads if one of the alignment hits is in reverse direction. E.g.

<pre>
_R1.fastq:                                           vs       _R2.fastq;
......
@HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/1                 @HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/2      
AAAGACTCAGCGTCGGTAAAGACTCAGCGTCAGTAAAAGAGTCAGCGTCA           AAAGACTCAGCGTCGGTAAAGACTCAGCGTCAGTAAAAGAGTCAGCGTCA ### NOTE: identical sequence, will give mapping error
+                                                            +                                                 
CCCFFFFFHHHHHJJJGHIJJJJJJIJJIGIJJIJJJIJHJFGIIGIHJI           CCCFFFFFHHHHHJJJGHIJJJJJJIJJIGIJJIJJJIJHJFGIIGIHJI
@HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/1                 @HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/2      
AAAGACTCAGCGTCGGTAAAGACTCAGCGTCAGTAAAAGAGTCAGCGTCA           TAATTAATGCATTCATACAGAGCGCATTTCCAGCATCATTTATTGGATAG
+                                                            +                                                 
CCCFFFFFHHHHHJJJGHIJJJJJJIJJIGIJJIJJJIJHJFGIIGIHJI           CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIIIJII
@HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/1                 @HWI-ST865:341:H9FJ7ADXX:1:1101:1405:93045/2      
TAATTAATGCATTCATACAGAGCGCATTTCCAGCATCATTTATTGGATAG           TAATTAATGCATTCATACAGAGCGCATTTCCAGCATCATTTATTGGATAG ### NOTE: identical sequence, will give mapping error
+                                                            +                                                 
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIIIJII           CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIIIJII

</pre>

(these lines have identical line numbers, so would be taken in pairs by a mapping program)

This behaviour is something to keep in mind while using (and, preferably, fixing :-) bamToFastq

**Comment by marcus1487** [comment]
Hi All,

I just ran into this issue and have submitted a pull request that fixes these issues. @arq5x I don't think the read name hash table is necessary as the BAM file is required to be name sorted anyways. Thus all mate reads are together and the file simply needs to be read in until another read name is encountered.

This pull request should solve both the spurious warnings problem as well as including a read many times in the output fastq.

**Comment by arq5x** [comment]
now fixed in master thanks to PR from @marcus1487
