### ISSUE TITLE
`testNameConventions` in v2.22.1 fails on GRCh37 naming schemes

### ISSUE THREAD

**Issue by chapmanb** [arq5x/bedtools2#166]
Aaron and Neil;
The new naming checks in v2.22.1 complain about BED files containing GRCh37-named haplotype chromosomes. If you have two files, `a.bed`:
```
1	0	100
```
and `b.bed`:
```
1	0	100
GL000207.1	0	4262
```
an intersection errors out due to the zero-padding checks:
```
$ bedtools intersect -a a.bed -b b.bed 
ERROR: File b.bed has inconsistent naming convention (leading zero) for record:
GL000207.1	0	4262
```
Is it possible to skip the checks with a flag or some other approach? It looks like BinTree, CloseSweep and NewChromsweep all run them. It would be awesome to still have an approach that is resilient to sort order, even if slower, so we can handle all those folks with crazy contig naming schemes. Thanks much.

**Comment by arq5x** [comment]
Thanks Brad, I suspect this will be a simple enough fix. We will have a look as soon as possible and thanks for reporting this.
cc / @nkindlon

**Comment by nkindlon** [comment]
Hey Brad, thanks for reporting this.The logic behind testing for leading zeros was that some files might have chroms named like "CHR1" and others would say "CHR01". Thus far I've already altered it to not object when the leading zero follows an underscore, since some of the haplotype chroms have names like "chrUn_gl000224". What I think we should do, since there doesn't seem to be much predictability to chrom naming conventions, change it to specifically ONLY complain if one file has a zero between the letters "chr" (case insensitive), and the first non zero digit, so basically only complain if it  sees things like "CHR01" and "chr1". Does that seem reasonable?

**Comment by chapmanb** [comment]
Neil;
Thanks for looking at this. The checking logic makes good sense and the workaround is good with me. More generally, it might be useful to have a flag to turn off the checking in case we run into other issues with different genomes. As you said, chromosome naming is a big mess and could be literally anything. It might be nice to be able to have a flag if you're not using the `-sorted` option to ignore the checks and proceed with the older approach. What do you think?

**Comment by nkindlon** [comment]
Hi Brad, 
     I think you're right. An option to turn off the check would cover the worst case scenario. I'll add that in. I guess "-notz", for "no test zero", would match our other option naming conventions as well as any.

**Comment by chapmanb** [comment]
Neil;
I was thinking of turning off all naming checks -- essentially reverting to the previous behavior -- in case there are other things in there which might trigger issues. No big preference on flags but something like `-nonamecheck` would be self documenting. Thanks again.

**Comment by nkindlon** [comment]
Oh, I see. Sure, that makes more sense. Thanks!

**Comment by arq5x** [comment]
This issue appears to be resolved in 2.23.0.  However, I didn't see a `-nonamecheck` option.  @nkindlon, did you add a new option or just refine the logic of the namecheck code?

**Comment by nkindlon** [comment]
Whoops. I did both, but forgot to add it to the help. Will fix now.

**Comment by arq5x** [comment]
Thanks Neil.

**Comment by chapmanb** [comment]
Neil and Aaron;
Awesome, thanks so much for this. I pushed updates to bcbio to use this new functionality. Much appreciated.
