### ISSUE TITLE
-s and -S not working properly with -sorted

### ISSUE THREAD

**Issue by arq5x** [arq5x/bedtools2#167]
In short, the chromsweep algorithm is now missing hits when using `-s` and `-S`. Consider the following file:

    cat test.2.bed
    chr1	9550913	9551859	b.C.1	0	-
    chr1	9550913	9621173	b	1	-
    chr1	9551859	9553903	b.I.1	0	-
    chr1	9553903	9553952	b.C.2	0	-
    chr1	9553952	9609630	b.I.2	0	-
    chr1	9602747	9603392	f.I.1	0	+
    chr1	9603392	9603555	f.C.2	0	+
    chr1	9603392	9603555	g.C.3	0	+
    chr1	9603555	9609916	f.I.2	0	+
    chr1	9603555	9609916	g.I.3	0	+

This file is sorted properly:

    sort -k1,1 -k2,2n -c test.2.bed

If we intersect this file against itself with without `-sorted` but with `-s`, we get 22 hits:

    bedtools intersect -a test.2.bed -b test.2.bed -s  -wa -wb
	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9550913	9621173	b	1	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9553952	9609630	b.I.2	0	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9553952	9609630	b.I.2	0	-
	chr1	9602747	9603392	f.I.1	0	+	chr1	9602747	9603392	f.I.1	0	+
	chr1	9603392	9603555	f.C.2	0	+	chr1	9603392	9603555	f.C.2	0	+
	chr1	9603392	9603555	f.C.2	0	+	chr1	9603392	9603555	g.C.3	0	+
	chr1	9603392	9603555	g.C.3	0	+	chr1	9603392	9603555	f.C.2	0	+
	chr1	9603392	9603555	g.C.3	0	+	chr1	9603392	9603555	g.C.3	0	+
	chr1	9603555	9609916	f.I.2	0	+	chr1	9603555	9609916	f.I.2	0	+
	chr1	9603555	9609916	f.I.2	0	+	chr1	9603555	9609916	g.I.3	0	+
	chr1	9603555	9609916	g.I.3	0	+	chr1	9603555	9609916	f.I.2	0	+
	chr1	9603555	9609916	g.I.3	0	+	chr1	9603555	9609916	g.I.3	0	+

However, if we use `-sorted`, we miss 9 hits (13 are reported):

        bedtools intersect -a test.2.bed -b test.2.bed -s  -wa -wb -sorted
	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9550913	9621173	b	1	-	chr1	9553952	9609630	b.I.2	0	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9553952	9609630	b.I.2	0	-

It is a similar story with `-S`. Here is R-tree (20 hits):

        bedtools intersect -a test.2.bed -b test.2.bed -S  -wa -wb
	chr1	9550913	9621173	b	1	-	chr1	9602747	9603392	f.I.1	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	f.C.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	g.C.3	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	f.I.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	g.I.3	0	+
	chr1	9553952	9609630	b.I.2	0	-	chr1	9602747	9603392	f.I.1	0	+
	chr1	9553952	9609630	b.I.2	0	-	chr1	9603392	9603555	f.C.2	0	+
	chr1	9553952	9609630	b.I.2	0	-	chr1	9603392	9603555	g.C.3	0	+
	chr1	9553952	9609630	b.I.2	0	-	chr1	9603555	9609916	f.I.2	0	+
	chr1	9553952	9609630	b.I.2	0	-	chr1	9603555	9609916	g.I.3	0	+
	chr1	9602747	9603392	f.I.1	0	+	chr1	9550913	9621173	b	1	-
	chr1	9602747	9603392	f.I.1	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9553952	9609630	b.I.2	0	-

Now `-sorted` (15 hits):

        bedtools intersect -a test.2.bed -b test.2.bed -S  -wa -wb -sorted
	chr1	9550913	9621173	b	1	-	chr1	9602747	9603392	f.I.1	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	f.C.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	g.C.3	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	f.I.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	g.I.3	0	+
	chr1	9602747	9603392	f.I.1	0	+	chr1	9550913	9621173	b	1	-
	chr1	9602747	9603392	f.I.1	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9553952	9609630	b.I.2	0	-

Here is a side-by-side diff of the difference between chromsweep and R-tree for `-s`. The extra (those that are missed by chromsweep) hits on the right column are obviously from the R-tree algorithm.

	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9551859	b.C.1	0	-		chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9621173	b	1	-		chr1	9550913	9551859	b.C.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9551859	b.C.1	0	-		chr1	9550913	9621173	b	1	-	chr1	9550913	9551859	b.C.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9550913	9621173	b	1	-		chr1	9550913	9621173	b	1	-	chr1	9550913	9621173	b	1	-
	chr1	9550913	9621173	b	1	-	chr1	9551859	9553903	b.I.1	0	-		chr1	9550913	9621173	b	1	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9550913	9621173	b	1	-	chr1	9553903	9553952	b.C.2	0	-		chr1	9550913	9621173	b	1	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9550913	9621173	b	1	-	chr1	9553952	9609630	b.I.2	0	-		chr1	9550913	9621173	b	1	-	chr1	9553952	9609630	b.I.2	0	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9550913	9621173	b	1	-		chr1	9551859	9553903	b.I.1	0	-	chr1	9550913	9621173	b	1	-
	chr1	9551859	9553903	b.I.1	0	-	chr1	9551859	9553903	b.I.1	0	-		chr1	9551859	9553903	b.I.1	0	-	chr1	9551859	9553903	b.I.1	0	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9550913	9621173	b	1	-		chr1	9553903	9553952	b.C.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553903	9553952	b.C.2	0	-	chr1	9553903	9553952	b.C.2	0	-		chr1	9553903	9553952	b.C.2	0	-	chr1	9553903	9553952	b.C.2	0	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9550913	9621173	b	1	-		chr1	9553952	9609630	b.I.2	0	-	chr1	9550913	9621173	b	1	-
	chr1	9553952	9609630	b.I.2	0	-	chr1	9553952	9609630	b.I.2	0	-		chr1	9553952	9609630	b.I.2	0	-	chr1	9553952	9609630	b.I.2	0	-
													   >	chr1	9602747	9603392	f.I.1	0	+	chr1	9602747	9603392	f.I.1	0	+
													   >	chr1	9603392	9603555	f.C.2	0	+	chr1	9603392	9603555	f.C.2	0	+
													   >	chr1	9603392	9603555	f.C.2	0	+	chr1	9603392	9603555	g.C.3	0	+
													   >	chr1	9603392	9603555	g.C.3	0	+	chr1	9603392	9603555	f.C.2	0	+
													   >	chr1	9603392	9603555	g.C.3	0	+	chr1	9603392	9603555	g.C.3	0	+
													   >	chr1	9603555	9609916	f.I.2	0	+	chr1	9603555	9609916	f.I.2	0	+
													   >	chr1	9603555	9609916	f.I.2	0	+	chr1	9603555	9609916	g.I.3	0	+
													   >	chr1	9603555	9609916	g.I.3	0	+	chr1	9603555	9609916	f.I.2	0	+
													   >	chr1	9603555	9609916	g.I.3	0	+	chr1	9603555	9609916	g.I.3	0	+

Here is a side-by-side diff for the same but with `-S`:

	chr1	9550913	9621173	b	1	-	chr1	9602747	9603392	f.I.1	0	+		chr1	9550913	9621173	b	1	-	chr1	9602747	9603392	f.I.1	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	f.C.2	0	+		chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	f.C.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	g.C.3	0	+		chr1	9550913	9621173	b	1	-	chr1	9603392	9603555	g.C.3	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	f.I.2	0	+		chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	f.I.2	0	+
	chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	g.I.3	0	+		chr1	9550913	9621173	b	1	-	chr1	9603555	9609916	g.I.3	0	+
													   >	chr1	9553952	9609630	b.I.2	0	-	chr1	9602747	9603392	f.I.1	0	+
													   >	chr1	9553952	9609630	b.I.2	0	-	chr1	9603392	9603555	f.C.2	0	+
													   >	chr1	9553952	9609630	b.I.2	0	-	chr1	9603392	9603555	g.C.3	0	+
													   >	chr1	9553952	9609630	b.I.2	0	-	chr1	9603555	9609916	f.I.2	0	+
													   >	chr1	9553952	9609630	b.I.2	0	-	chr1	9603555	9609916	g.I.3	0	+
	chr1	9602747	9603392	f.I.1	0	+	chr1	9550913	9621173	b	1	-		chr1	9602747	9603392	f.I.1	0	+	chr1	9550913	9621173	b	1	-
	chr1	9602747	9603392	f.I.1	0	+	chr1	9553952	9609630	b.I.2	0	-		chr1	9602747	9603392	f.I.1	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9550913	9621173	b	1	-		chr1	9603392	9603555	f.C.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	f.C.2	0	+	chr1	9553952	9609630	b.I.2	0	-		chr1	9603392	9603555	f.C.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9550913	9621173	b	1	-		chr1	9603392	9603555	g.C.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603392	9603555	g.C.3	0	+	chr1	9553952	9609630	b.I.2	0	-		chr1	9603392	9603555	g.C.3	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9550913	9621173	b	1	-		chr1	9603555	9609916	f.I.2	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	f.I.2	0	+	chr1	9553952	9609630	b.I.2	0	-		chr1	9603555	9609916	f.I.2	0	+	chr1	9553952	9609630	b.I.2	0	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9550913	9621173	b	1	-		chr1	9603555	9609916	g.I.3	0	+	chr1	9550913	9621173	b	1	-
	chr1	9603555	9609916	g.I.3	0	+	chr1	9553952	9609630	b.I.2	0	-		chr1	9603555	9609916	g.I.3	0	+	chr1	9553952	9609630	b.I.2	0	-

**Comment by nkindlon** [comment]
I took a look at some earlier versions out of curiosity. The -s and -S worked correcty with -sorted up through 2.20.1, but broke in v2.21 when we gave support for multiple databases. I'm surprised we never had a unit test for that.

**Comment by arq5x** [comment]
Fixed with  9d4ed4c
