### ISSUE TITLE
Q / API : how do I write a BED to a given FILE* or ostream ?

### ISSUE THREAD

**Issue by lindenb** [arq5x/bedtools2#169]
Hi, 

Im' playing with the API :-)

I've built a collection of BedFile(s)

```cpp
 vector<BedFile*> pools;
```
and I've added some items

```cpp
pools[index]->addBEDIntoMap(entry);
```
now I want to save each pool  in a `FILE*` or `ostream`.

```cpp
for(i=0;i< pools.size();++i)
  {
  FILE* out= fopen(....);
  pools[i]->save(out) ?
  }

```
is there a function to save a BedFile in a FILE ?  I saw __reportBedNewLine__ in 'befFile.h' but it only prints to stdout using printf.

Thanks

**Comment by arq5x** [comment]
Hi Pierre,

The API unfortunately only has read-based methods, as that is the main focus of the utilities in BEDTOOLS thus far.  We are just now starting to work on evolving the API to be more generalizable for developers like you to use.  Unfortunately, we are not there yet...sorry :(

**Comment by lindenb** [comment]
ok,

would it be OK if I move all call to `printf`  under `reportBedNewLine` to `fprintf(out`  and if I add a new method in `befFile.h`
```
inline void reportBedNewLine(FILE* out,const T &bed)
  {
  (...)
  fprintf (out,"%s\t%d\t%d\n", bed.chrom.c_str(), start, end);
 (...)  
 }

inline void reportBedNewLine(const T &bed)
  {
  reportBedNewLine(stdout,bed);
  }
```

**Comment by arq5x** [comment]
I don't have a problem with multiple signatures here.  @nkindlon are you okay with this?

**Comment by arq5x** [comment]
I guess the only comment is the new file based signature you propose is printing only a subset of the fields that may be present in a BED record.  We could expand upon it over time to be more general, though.

**Comment by nkindlon** [comment]
Hi guys, 
    I don't mind a signature change to the bedFile reporting methods. Be aware, though, while the bedFile class is still in use, it is being phased out, as we continue to convert the tools to the "Bedtools2" approach. In the new system, rather than bedFile and it'sreporting methods, we use the RecordOutputMgr class, which has a method called flush that does the actual writing via a call to fwrite. The last argument to fwrite is a FILE * that is currently hard-coded to stdout. It could easily be adapted to take an argument  (or some other hard-coding) instead. Tools that have been converted thus far include intersect, closest, map, merge, jaccard, and sample, so if those tools are the ones you want to have write to a file, then flush is what needs to be altered. I could also include a -out option that takes a filename to write output to as an enhancement in the next release.

**Comment by arq5x** [comment]
Yeah, good points, Neil.  I think we shout update the bt2 approach as well to support writing to files.

**Comment by lindenb** [comment]
I wrote something today using the code I only  found in master. I'll  soon send a first pull request just to have your thoughts about my tool (should it be included in bedtools, code qual, etc...).
