### ISSUE TITLE
Annotate VCF INFO fields with intersections with N interval files.

### ISSUE THREAD

**Issue by arq5x** [arq5x/bedtools2#171]
Thanks to the numerous improvements by @nkindlon to the chromsweep algorithm,  we now have the ability to quickly intersect a single "query" file against many "database" files, so long as the query and each database file is sorted by chromosome and start coordinate.

We therefore have the ability to create a rather powerful and sophisticated system annotating a VCF file.  For example, imagine we wanted to annotate the INFO field for each variant in a VCF file based on:
    1. it is in a CpG island (BED format)
    2. the observed alternate allele frequency in the ExAC dataset (VCF format)
    3. the gene name from Ensembl if it overlaps an exon.

One could imagine a bedtools command called `vcfanno` as follows:

    # unannotated VCF
    cat my.annotated.vcf
    #CHROM POS ID REF ALT QUAL FILTER INFO FORMAT Quinlan
    20 14370 . G A 29 PASS DP=14;AF=0.5; GT 0|1
    20 24370 . G A 29 PASS DP=24;AF=0.5; GT 0|1
    20 24370 . G A 29 PASS DP=34;AF=0.5; GT 0|1

    # she be annotated 
    bedtools vcfanno -a my.vcf \
       -b cpg.bed \
           exac.vcf \
           ensembl.gff \
       -tags CPG \
            EXAC \
            GENE \
       -rules boolean \
                 INFO:AF \
                 name \
    > my.annotated.vcf

The `-rules` option would define how the annotations from the various files would be used to populate the INFO field for each variant.  The `-tags` option defines the labels slammed into the INFO field. This will require some work and may require (prefer) a YAML config file.
Regardless, the output would look something like:

    cat my.annotated.vcf
    #CHROM POS ID REF ALT QUAL FILTER INFO FORMAT Quinlan
    20 14370 . G A 29 PASS DP=14;AF=0.5;CPG=0;EXAC=0.000023; GT 0|1
    20 24370 . G A 29 PASS DP=24;AF=0.5;CPG=1;EXAC=0.013; GT 0|1
    20 24370 . G A 29 PASS DP=34;AF=0.5;CPG=0;EXAC=0.043;GENE=ATM GT 0|1

**Comment by lindenb** [comment]
I don't get  `-rules boolean INFO:AF  name ` : is it , `if INFO field AF is present: then add name from the annoation bed ` ?

**Comment by lindenb** [comment]
how do you create the `##INFO` field in the VCF header ? (type, description,  cardinality,...)  ?

**Comment by lindenb** [comment]
I had the ~ same idea with the following tool: https://github.com/lindenb/jvarkit/wiki/VCFBed . For the annotation using one column from the BED was not enough: e.g: http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/genomicSuperDups.sql , I want to merge `$otherChrom:$otherChromStart-$otherChromEnd` to I'm using an expression pathern like '${1}:${2}-${3}'

**Comment by arq5x** [comment]
I agree that populating the header will be a challenge, but perhaps a `-types` agrument can be used to pass a list of types/expected number for each of the tags given by `-tags`.  Thanks for the pointer to your tool, that is very helpful.  Perhaps if that already exists, this won't be worth doing!

**Comment by arq5x** [comment]
Won't implement, as @brentp's vcfanno (https://github.com/brentp/vcfanno) does exactly this in a very sophisticated way.
