### ISSUE TITLE
closestBed overlapping nearest genes (features)

### ISSUE THREAD

**Issue by radaniba** [arq5x/bedtools2#173]
Hello

Is there any recipe to use closestBed to get flanking genes (depending on the strand) if the region in A is intergenic ? It would be great if this is something added by default in closestBed

An option like : `-f, --flank` that return the nearest feature in the + strand and in the - strand, a combination of -S and -s together  

Thanks

example

Refgene.bed

```
chr1    1736    4272    DDX11L1    +
chr1    4224    19233    WASH7P    -
chr1    4224    7502    LOC100288778    -
chr1    7231    7299    MIR6859-1    -
chr1    7231    7299    MIR6859-2    -
```

A.bed

```
chr1    1790    4290   
chr1    4225    8000  
chr1    4230    7500   
chr1    7250    7290   
```

I played with closestBed a bit but cannot find a recipe to get  nearest flanking genes for each region in A

anyone with an idea ?

Thanks

**Comment by arq5x** [comment]
Answered here: https://groups.google.com/forum/#!topic/bedtools-discuss/BMYVeHTPZ4M
