### ISSUE TITLE
install fails on ubuntu 14.04....No rule to make target `ContextSpacing.cpp'...

### ISSUE THREAD

**Issue by snewhouse** [arq5x/bedtools2#174]
install fails on ubuntu 14.04

Linux sjndell 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

    git clone https://github.com/arq5x/bedtools2.git && \
    cd bedtools2 && \
    make clean && \
    make all && \
    make install && \

Building BEDTools:
=========================================================
DETECTED_VERSION = v2.22.1-16-g2b1df94
CURRENT_VERSION  = 
Updating version file.
 * Creating BamTools API
- Building in src/utils/bedFile
  * compiling bedFile.cpp
- Building in src/utils/BinTree
  * compiling BinTree.cpp
- Building in src/utils/version
  * compiling version.cpp
- Building in src/utils/bedGraphFile
  * compiling bedGraphFile.cpp
- Building in src/utils/chromsweep
  * compiling chromsweep.cpp
- Building in src/utils/Contexts
make[1]: *** No rule to make target `ContextSpacing.cpp', needed by `../../../obj//ContextBase.o'. Stop.
make: *** [src/utils/Contexts] Error 2

**Comment by arq5x** [comment]
Oops - sorry, missing file.  Added - you should be fine now. Sorry about that.

**Comment by snewhouse** [comment]
perfect - cheers!
