### ISSUE TITLE
bedtools map ignoring -a -b flags, just using position

### ISSUE THREAD

**Issue by semenko** [arq5x/bedtools2#175]
I've been using map to add MACS_peak_# onto a file with overlap, e.g.

bedtools map -o collapse -delim _ -c 4 -a file1_has_names.bed -b file2_no_name.bed

file1_has_names.bed:
```
chr1	4496270	4496664	MACS_peak_1	378.02
chr1	4768378	4768689	MACS_peak_2	129.49
...
```

file2_no_name.bed:
```
chr1	4857404	4858513
chr1	5046708	5046902
...

```
Resulting in something like:
```
chr1	4496270	4496664	MACS_peak_1
chr1	4768378	4770246	MACS_peak_2_MACS_peak_3
chr1	4780121	4786120	MACS_peak_4_MACS_peak_5
...
```

Unfortunately, I think a recent version broke the ordering, so `-a` and `-b` are ignored -- and only the positions matter:

bedtools map -o collapse -delim _ -c 4 -b file2_no_name.bed -a file1_has_names.bed

***** ERROR: Requested column 4, but database file file2_no_name.bed only has fields 1 - 3.

This is particularly bad for pybedtools, which can pass -b before -a.

**Comment by arq5x** [comment]
Thanks for reporting this.  I can replicate it and it looks to be specific to map, as intersect plays nicely still.

**Comment by semenko** [comment]
Quick bisect:

```
git bisect start
# bad: [4356ace74f7be8ef71d2c1680c6b48a07705685c] Setting Release-Version v2.21.0
git bisect bad 4356ace74f7be8ef71d2c1680c6b48a07705685c
# good: [4122ba15717bf79f0c7330aa18a96113df81f6ed] Setting Release-Version v2.20.1
git bisect good 4122ba15717bf79f0c7330aa18a96113df81f6ed
# good: [aa6dcea1d20996d0a683d9a9308b063b02d69c94] Merge pull request #107 from martijnvermaat/hg38
git bisect good aa6dcea1d20996d0a683d9a9308b063b02d69c94
# bad: [7434d8a38b13c4a252f27748f54957c1ac9c9b79] Stop Chromsweeep cache scan when DB is after query; allow BAM unmapped reads/chrom in genome file.
git bisect bad 7434d8a38b13c4a252f27748f54957c1ac9c9b79
# bad: [57ed945c121a6e7d1ea803f19bca10c25b5eff4d] Corrected errors caused during merge-conflict resolution
git bisect bad 57ed945c121a6e7d1ea803f19bca10c25b5eff4d
# bad: [7f0b3f543abec0a4f343f42f30e3c42f9a85a864] First check-in for multi-sweep
git bisect bad 7f0b3f543abec0a4f343f42f30e3c42f9a85a864
# first bad commit: [7f0b3f543abec0a4f343f42f30e3c42f9a85a864] First check-in for multi-sweep
```

**Comment by semenko** [comment]
Built a few times -- the regression is definitely:

commit 7f0b3f543abec0a4f343f42f30e3c42f9a85a864
Author: nkindlon <nek3d@virginia.edu>
Date:   Wed Jun 18 18:47:48 2014 -0400

    First check-in for multi-sweep

I'm not familiar with the codebase, though this *might* be indicated in a comment on line 214 of ContextBase.cpp:
https://github.com/arq5x/bedtools2/commit/7f0b3f543abec0a4f343f42f30e3c42f9a85a864#diff-960e9fc70b331fb58895cb2fd0d3d9bdR214

**Comment by arq5x** [comment]
Thanks for reporting this! Fixed in master.
