### ISSUE TITLE
support for user-specified chromosome sort orders

### ISSUE THREAD

**Issue by cooketho** [arq5x/bedtools2#178]
Not an issue per se, but a nice feature to add to the sort function would be to allow the user to specify an arbitrary chromosome sort order (e.g. in the form of a fasta .dict file). This is a bigger issue for, say, non-model organism genomes that have 10,000+ contigs. The user will always want them sorted in the same order as the genome fasta, but probably doesn't care about the low-level details of how they are actually put in that order, which is why I suggest the program do this in a straightforward way--allowing the fasta .dict itself to specify the correct order.

**Comment by arq5x** [comment]
You should be able to use the -g option for intersect, map, and closest for this exact purpose.
http://bedtools.readthedocs.org/en/latest/content/tools/intersect.html#g-define-an-alternate-chromosome-sort-order-via-a-genome-file

**Comment by cooketho** [comment]
Ah! Sorry for not reading the documentation more carefully. But do I understand correctly that this option is not yet available for merge? It could be useful there. I see in intersect there is '-loj' (left outer join), but no "full outer join".

**Comment by arq5x** [comment]
Merge should not require a specific sorting order. It should just require "grouping": that is, within a given chromosome, the intervals are sorted by start. The precise order of the chroms shouldn't matter.

As for intersect, there is not full outer join available.
