### ISSUE TITLE
GFF with extra fields not detected

### ISSUE THREAD

**Issue by daler** [arq5x/bedtools2#181]
Hi Aaron & Neil - 

Often GFF files have extra fields from operations like `bedtools intersect -c` or `bedtools coverage counts`.  But when there's an extra field, the file doesn't seem to be detected properly:

```
$ bedtools --version
bedtools v2.22.1-17-gd6547b3
```

```
$ cat a.gff 
chr9    .   gene    1   100 .   +   .   ID=gene1
chr1    .   gene    200 500 .   +   .   ID=gene2
chr1    .   gene    1   100 .   +   .   ID=gene3


$ bedtools sort -i a.gff | wc -l 
3
```

```
$ cat b.gff  # has a 10th field
chr9    .   gene    1   100 .   +   .   ID=gene1    0
chr1    .   gene    200 500 .   +   .   ID=gene2    1
chr1    .   gene    1   100 .   +   .   ID=gene3    0

# no output on the file with 10 fields
$ bedtools sort -i b.gff | wc -l 
0
```

```
# it's not just sort
$ bedtools intersect -a a.gff -b b.gff
Error: unable to open file or unable to determine types for file b.gff
```

I'm pretty sure GFF can be uniquely detected among supported formats by the integers in the 4th and 5th fields. I would guess that removing any field count constraints should do the trick. But I can't quite figure out where to fix this -- `FileRecordTypeChecker::isGFFformat()` doesn't seem to be called, and `bedFile.h` sees `b.gff` correctly as a GFF file.

Any ideas?

Thanks.

**Comment by nkindlon** [comment]
Hi Ryan,
   Inside FileRecordTypeChecker::isGffFormat, the first if clause in the method restricts it to a specific number of fields ( which in retrospect shouldnt have been hardcoded like that, sorry.) If you're sure the number of fields shouldn't matter we can alter that clause or remove it altogether.

**Comment by daler** [comment]
Hi Neil -

I had actually tried removing [that clause](https://github.com/arq5x/bedtools2/blob/master/src/utils/fileType/FileRecordTypeChecker.cpp#L244), and was surprised when it didn't make a difference.  It looks like `isGffFormat` doesn't even get called using either the `a.gff` or `b.gff` examples above. 

(Specifically, I replaced that clause with `cerr << "calling isGffFormat" << endl;`and nothing got printed)

Additional troubleshooting: [this GFF detection clause in bedFile.h](https://github.com/arq5x/bedtools2/blob/master/src/utils/bedFile/bedFile.h#L620) does run, and seems to correctly identify `b.gff` as GFF.

But in general, using the logic in `bedFile.h` (>=8 fields; 4th and 5th fields are integers) should work to identify GFF format.

**Comment by arq5x** [comment]
Hey @daler, once Neil is back from vacation we will knock this out.

**Comment by nkindlon** [comment]
Hi Ryan, 
    Sorry about the delay, just got back and didn't have a way to debug this while away. But now that I look at it, I'm unable to get the same result you're seeing. When I run it, It does indeed enter the isGFFformat method and get rejected for the number of fields. My only hunch at this point is that maybe your b.gff file might have some extra whitespace or invisible characters? I realize that's a stretch, but could you e-mail it to me? My address is nek3d@virginia.edu. Thanks.

**Comment by arq5x** [comment]
Is this still an issue?

**Comment by daler** [comment]
Yep, but it boils down to whether or not you want to support "GFFplus" formats. I'll forward you the email conversation I had with Neil on this.
