### ISSUE TITLE
bedtools subtract 

### ISSUE THREAD

**Issue by jewmanchue** [arq5x/bedtools2#184]
Probably user error, but I'm noticing some features aren't subtracting as expected (1bp features).

~/tools/bedtools2/bin/bedtools subtract  -A -a estd214_1000_Genomes_Consortium_Phase_3.2014-10-13.GRCh37.p4.Submitted.gff -b wham.1.8.bed

CURRENT_VERSION  = v2.22.1-17-gd6547b3

bed line:
chr1    247959051       247959104       chr1:247959051:247959104        .

gff line: 
chr1	DGVa	indel	247959051	247959051	.	+	.	ID=1069553;Name=essv10374245;Alias=PHASE3_V1_SV_141_A1_NA12878;variant_call_so_id=SO:1000032;parent=esv3589527;submitter_variant_call_id=PHASE3_V1_SV_141_A1_NA12878;sample_name=NA12878;Zygosity=heterozygous;Variant_seq=.

**Comment by arq5x** [comment]
This is a 0-based versus 1-based coordinate issue. Recall that GFF uses 1-based starts whereas BED uses 0-based starts.  In other words, were the start coordinate of your BED file 247959050 (not 247959051), I think it would do what you expect.

**Comment by jewmanchue** [comment]
I've had enough.  I'm tattooing the coordinate systems for VCF,SAM,BAM,BED,GFF on my arm.
