### ISSUE TITLE
ubuntu bedtools -sorted is slow

### ISSUE THREAD

**Issue by tdhock** [arq5x/bedtools2#185]
I have a big chip-seq.bedGraph file (7,617,673 rows) and a small windows.bed file (413 rows), both sorted, and based on reading the manual I thought that the fastest method would be

```
$ time intersectBed -a windows.bed -b chip-seq.bedGraph -sorted > overlap-sorted.bedGraph
real	154m10.653s
user	153m2.188s
sys	0m20.204s
```

but actually it is much faster without -sorted. Why is that? (the results of the two are the same)

```
$ time intersectBed -a windows.bed -b chip-seq.bedGraph > overlap.bedGraph
real	0m8.733s
user	0m7.932s
sys	0m0.728s
```

If this is a bug, can you please fix it?

If it is a feature, can you please document it?

data files can be downloaded here

http://cbio.ensmp.fr/~thocking/data/overlap-benchmark.tgz

**Comment by tdhock** [comment]
by the way this is with Version: 2.14.3-1

**Comment by arq5x** [comment]
With version 2.21.1, -sorted is more than twice as fast as without. There have been many, many improvements to that algorithm over the last two years. I suggest an upgrade!

    ➜ bedtools --version
    bedtools v2.22.1
    ➜  time bedtools intersect -a windows.bed -b chip-seq.bedGraph -wa -wb > /dev/null
    10.79s user 0.99s system 99% cpu 11.783 total
    ➜  time bedtools intersect -a windows.bed -b chip-seq.bedGraph -wa -wb -sorted > /dev/null
    3.45s user 0.05s system 99% cpu 3.507 total
