### ISSUE TITLE
Unit tests failing (also on Trevis)

### ISSUE THREAD

**Issue by tleonardi** [arq5x/bedtools2#186]
Hi all,
I've just noticed that several unit tests fail when running 'make test' for version 2.22.1.
It looks like they also fail on Trevis (e.g. https://travis-ci.org/arq5x/bedtools2/jobs/47671284), although the build is successful.
I guess that Trevis doesn't fail because the test scripts don't return 1 in case any test fails... A solution could be 'set -e' in the test scripts?

thanks for looking into this!
tom

**Comment by arq5x** [comment]
Thanks so much for pointing this out.  It looks like some of the files we use for unit testing have not been added to the github repo.  @nkindlon and I will work on this, as well as fixing the "return 1" issue as soon as possible.
