### ISSUE TITLE
0 base length coordinates return incorrect results instead of throwing an error

### ISSUE THREAD

**Issue by roryk** [arq5x/bedtools2#187]
Hi Aaron,

I made a poorly formatted BED file with 0 length coordinates and using bedtools on it gives incorrect results. Maybe it could return an error for these lines?

The bad BED is:

    chr7    33059403        33059403        

and intersecting it on

    chr7	32599076	33069221	NA	intron
    chr7	33059336	33060883	NT5C3A	intron

with

    bedtools intersect -wao -a first.bed -b second.bed

gives this the result:

    chr7	33059403	33059403	M01201:48:000000000-A8TG7:1:2103:20848:17130	ACH-clone1	chr7	33059336	33060883	NT5C3A	intron	0
    chr7	33059402	33059404	M01201:48:000000000-A8TG7:1:2103:20848:17130	ACH-clone1	chr7	32599076	33069221	NA	intron	2

I was super confused for a long time before I figured out what the problem was.

Thanks!

**Comment by arq5x** [comment]
Thanks for reporting this, Rory.  It indeed looks like the output is inconsistent - it should have been "chr7    33059403    33059403" for both hits.  Zero length BED features are actually supported, as they are conventionally meant to represent insertions _between_ bases.  It looks like, however, our reporting is somehow inconsistent.

**Comment by roryk** [comment]
Hi Aaron,

Oh sweet, insertion between bases was exactly what I was after with the zero length BED entry.

**Comment by arq5x** [comment]
Fixed with last set of commits.

**Comment by roryk** [comment]
Thanks Aaron!
