### ISSUE TITLE
bedtools makewindows step option error

### ISSUE THREAD

**Issue by igordot** [arq5x/bedtools2#188]
I used to be able to run with a previous version of bedtools:
`bedtools makewindows -g genome.txt -n 1`
Now (v2.22.1), I get an error:
`ERROR: The step (-s) option must be greater than zero. `
It does not mention that the step must be specified, so I don't think I should be getting this error.

**Comment by arq5x** [comment]
Thanks for reporting this, I just pushed a fix.
