### ISSUE TITLE
Unrecognized archive format when unpacking from curl retrieval

### ISSUE THREAD

**Issue by kubu4** [arq5x/bedtools2#189]
OS X 10.9.5
When I download the gzipped tarball that's linked in the repo 
(https://github.com/arq5x/bedtools2/releases/download/v2.22.1/bedtools-2.22.1.tar.gz) using curl

```
$curl -O https://github.com/arq5x/bedtools2/releases/download/v2.22.1/bedtools-2.22.1.tar.gz
```
the unpacking fails:
```
$tar -zxvf bedtools-2.22.1.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Gunzip fails, too:
```
$gunzip bedtools-2.22.1.tar.gz
gunzip: bedtools-2.22.1.tar.gz: not in gzip format
```

The output from curl suggests that the link above isn't downloading the correct file, based on the amount of data that gets downloaded:
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   403    0   403    0     0    704      0 --:--:-- --:--:-- --:--:--   703
```

**Comment by arq5x** [comment]
Your curl command is the problem.  You need `-L`:

    curl -OL https://github.com/arq5x/bedtools2/releases/download/v2.22.1/bedtools-2.22.1.tar.gz

**Comment by kubu4** [comment]
Thanks! That fixed it!
The requirement of the -L flag isn't in the documentation:
http://bedtools.readthedocs.org/en/latest/content/installation.html

**Comment by rsmurali** [comment]
I have a similar issue:

curl -u testuser:welcome1 -k -i -H "Content-type: application/json" -o /tmp/mardl.tar.gz -X GET https://adc.com/iaps/getResource/jdk

The below fetches me a .tar.gz file & file gets stored & the size of the file seems correct.

But when I run tar -xvzf on the file, it says not in gzip format.

Please help.

**Comment by ustcJin** [comment]
-OL really done!

**Comment by onurkarayalcin** [comment]
Thanks, it worked!

**Comment by ale8286** [comment]
Hello, 
I have the same problem but the error remain

curl -O -L http://ftpmirror.gnu.org/autoconf/autoconf-latest.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3428  100  3428    0     0   6359      0 --:--:-- --:--:-- --:--:--  6359
Mac-Pro-di-MAC:swig macpro2014$ tar -xvzf autoconf-latest.tar.gz 
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by nishantgerald** [comment]
For those of you who still have the issue after adding the -L, double-check your file head:
- If the file isn't in binary, then you just have a file name after tar.gz, but not truly a zipped tarball.

I know this sounds weird, but I learned this the hard way!

**Comment by sankita15** [comment]
@nishantgerald response helped me and then I used following command to check whether I have a tarball file or not

`file <filename>`

If its a tar file, it will give you below output:
`my.tar: POSIX tar archive (GNU)`

For my issue, I did curl for wrong distribution and thats why got html file which was having extension .tar.gz. After fixing the distribution version, I got a tarball file and then everything worked fine.

**Comment by damonkg1** [comment]
Holy moley it worked! Thank you!
