### ISSUE TITLE
coverage: Report mean coverage (feature request)

### ISSUE THREAD

**Issue by sjackman** [arq5x/bedtools2#192]
I'd like to calculate mean coverage as per [this post](https://groups.google.com/forum/#!msg/bedtools-discuss/WSNEVuHIpz0/qPPlm2XSDQEJ).

`bedtools coverage` reports the number of *a* features that overlap *b*. Perhaps it could also report mean coverage or alternatively the sum of the lengths of the *a* features that overlap *b*, from which mean coverage could easily be calculated.

This works
```sh
bedtools coverage -d -abam a.bam -b b.bed |datamash -g 1,2,3 mean 5
```

[brew install datamash](http://www.gnu.org/software/datamash/)

**Comment by nkindlon** [comment]
Added -mean option in #247.

**Comment by sjackman** [comment]
Thanks, Neil!
