### ISSUE TITLE
strand-aware makewindows

### ISSUE THREAD

**Issue by jayhesselberth** [arq5x/bedtools2#193]
I didn't much interest on the google group, so thought I would also post here. This issue is coming up more and more often for me. Eventually I will get to this and submit a PR, but thought I would put this on your radar.

https://groups.google.com/forum/#!topic/bedtools-discuss/7KGkI3MYrTk

**Comment by arq5x** [comment]
Hi Jay, 
Thanks for putting this back on our radar. Are you still of the opinion that something like a ``-reverse`` option would suffice?

**Comment by jayhesselberth** [comment]
I have a nearly functional patch, will submit PR soon.

--
Jay Hesselberth
Assistant Professor
Biochemistry & Molecular Genetics
University of Colorado School of Medicine
off: (303) 724-5384
lab: (303) 724-5486
jay.hesselberth@gmail.com
