### ISSUE TITLE
slop only truncates stop position

### ISSUE THREAD

**Issue by daler** [arq5x/bedtools2#195]
This isn't a major issue or anything, just figured it would be useful to report in case it's not intended: it looks like `slop` only truncates the stop position for features completely outside of chromosome boundaries.

If features completely fall outside the chromosome, this means the resulting feature output by slop is invalid, since start > stop.  These features have to be filtered out or modified for downstream processing. For example:

``` bash
$ cat a.bed
chr1    1   100 feature1    0   +
chr1    100 200 feature2    0   +
chr1    150 500 feature3    0   -
chr1    900 950 feature4    0   +

$ cat chromsizes.txt
chr1    200

$ bedtools slop -i a.bed -g chromsizes.txt -b 100 > a2.bed
$ cat a2.bed
chr1    0   200 feature1    0   +
chr1    0   200 feature2    0   +
chr1    50  200 feature3    0   -
chr1    800 200 feature4    0   +
```

The last 2 features are now invalid for downstream processing:

```
$ bedtools sort -i a2.bed 
Error: malformed BED entry at line 4. Start was greater than end. Exiting.
```

I don't know how often this sort of thing occurs in the wild or if it's even a problem -- expecting input to already be within chromosome coords seems a reasonable requirement! But a quick fix within bedtools would be to truncate the start and stop position, resulting a zero-length feature.  Then the result would have all valid features.

**Comment by themantalope** [comment]
Has anyone looked into this issue? I am running into it from time to time.
