### ISSUE TITLE
mergeBed name field request

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#196]
Hi

in the new version of mergeBed, you have provided some useful updates, however one thing I would like to see is the possibility of merging entries and keeping only 1 of the names of the files merged.

i.e
chr1 10 20 A
chr1 15 20 B
chr1 18 20 C

mergeBed -i file.bed -c 4 -o keep_name 

chr1 10 20 A

currently I have to pipe the output to awk to be able to accomplish this.
Ideally it should keep the name of the largest segment being merged or the 1st.

Any plans on including some functionality akin to this ?

Best regards

Duarte

**Comment by arq5x** [comment]
Oops, it looks like we left the "first" and "last" options for -o from the help menu.

    ➜  bedtools merge -i a.bed -c 4 -o first
    chr1	10	20	A
    ➜  bedtools merge -i a.bed -c 4 -o last
    chr1	10	20	C

**Comment by duartemolha** [comment]
GREAT! thanks

**Comment by duartemolha** [comment]
Could I suggest an additional option called "largest", that would output the name of the largest features merged?

**Comment by arq5x** [comment]
Good idea.  Would also need "smallest".  I think "random" could be useful as well.

**Comment by duartemolha** [comment]
Apologies for asking, but in case you were not being sarcastic... shouldn't this request be converted to a feature request then instead of closed?

all the best.

**Comment by arq5x** [comment]
Yep: https://github.com/arq5x/bedtools2/issues/197
