### ISSUE TITLE
bedtools getfasta with bed12

### ISSUE THREAD

**Issue by chadn737** [arq5x/bedtools2#205]
I have been using bedtools getfast with a bed12 file to extract CDS sequences. However, I have found that it does not extract the proper sequence for sequences on the reverse strand when used with the "-s" and "-split" arguments.

**Comment by arq5x** [comment]
What version are you using?  With 2.23.0, this works. Can you show an example?

    cat test.fasta
    >chr1
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

    cat three_blocks_match.bed
    chr1	0	50	three_blocks_match	0	-	0	0	0	3	10,10,10,	0,20,40,

    bedtools getfasta -fi test.fasta -bed three_blocks_match.bed -fo stdout -split
    >chr1:0-50
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

    bedtools getfasta -fi test.fasta -bed three_blocks_match.bed -fo stdout -split -s
    >chr1:0-50(-)
    tttttttttttttttttttttttttttttt

**Comment by chadn737** [comment]
I currently use 2.17.0

**Comment by arq5x** [comment]
Have you tried with the latest version?

**Comment by arq5x** [comment]
Closing.
