### ISSUE TITLE
zlib in non-standard location not found (CPPFLAGS)

### ISSUE THREAD

**Issue by wookietreiber** [arq5x/bedtools2#206]
I have zlib installed in a non-standard location. I usually use `CPPFLAGS` to specify where this installation is, however, bedtools does not pick that up automatically, e.g.:

```
$ echo $CPPFLAGS 
-I/usr/local/zlib/1.2.8-4/include

$ make
Building BEDTools:
...
  * compiling bedFile.cpp
In file included from bedFile.h:16:0,
                 from bedFile.cpp:12:
../../utils//gzstream/gzstream.h:35:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[1]: *** [../../../obj//bedFile.o] Error 1
make: *** [src/utils/bedFile] Error 2
```

What I then usually do is to hack `Makefile` by adding `CPPFLAGS` to the `export CXXFLAGS = ` line and everything works just fine. This is, however, a dirty hack we shouldn't have to do.

I propose to add `CPPFLAGS` to `Makefile` and all compilation tasks (PR pending).

**Comment by HelloYiHan** [comment]
Hello Christian,
I install a software which relies on bedtools-v2.19.1 so I have to install this version of bedtools.
It is not easy to install bedtools v2.19.1. The same problem as you bothers me a lot. 
I export CPPFLAGS="-I/usr/local/zlib/1.2.8-4/include" and then make. But it still does not work.
I was wandering how to solve it and request your kind help.
Best,
Yi Han

**Comment by wookietreiber** [comment]
A relatively clean way would be to get the patch with `wget https://github.com/arq5x/bedtools2/pull/207.patch` and then apply it manually with the `patch` tool. That's effectively back-porting.

One of the dirtier ways is to hack the CPPFLAGS into the compiler variables:

```bash
export CPPFLAGS="-I/usr/local/zlib/1.2.8-4/include"
export CC="$(which gcc) $CPPFLAGS"
export CXX="$(which g++) $CPPFLAGS"
make
```

That's approximately what I did before.

**Comment by HelloYiHan** [comment]
I am so sorry to bother you but I really don't know how to apply .patch file with the patch tool. I google it and guess the command is 
patch < 207.patch
Would it be possible to give me some more detail?
Thanks

**Comment by HelloYiHan** [comment]
Unfortunately, the clean way doesn't work.
So i try the dirty way. However, It doesn't work either.
I find there is no zlib/ in /usr/local/. I was wandering if the point is here.
Thanks.
