### ISSUE TITLE
install fails on ubuntu 14.10 ?

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#209]
install fails on ubuntu 14.10 ?

Linux duarte-linux 3.16.0-31-generic #43-Ubuntu SMP Tue Mar 10 17:37:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

* git clone https://github.com/arq5x/bedtools2.git
* cd bedtools2
* make clean
* make all

```
 * Cleaning-up BamTools API
 * Cleaning up.
duartem@duarte-linux:~/src/bedtools2$ make all
Building BEDTools:
=========================================================
DETECTED_VERSION = v2.23.0-10-g447cb97
CURRENT_VERSION  = v2.23.0-10-g447cb97
 * Creating BamTools API
- Building in src/utils/bedFile
  * compiling bedFile.cpp
In file included from bedFile.h:16:0,
                 from bedFile.cpp:12:
../../utils//gzstream/gzstream.h:35:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
Makefile:22: recipe for target '../../../obj//bedFile.o' failed
make[1]: *** [../../../obj//bedFile.o] Error 1
Makefile:142: recipe for target 'src/utils/bedFile' failed
make: *** [src/utils/bedFile] Error 2
```

**Comment by arq5x** [comment]
Zlib is often not installed by default on vanilla Ubuntu.
http://bedtools.readthedocs.org/en/latest/content/faq.html#why-am-i-getting-all-of-these-zlib-errors

**Comment by wookietreiber** [comment]
To be more explicit:

Ubuntu usually does not install the development packages, i.e. you most likely have installed the `zlib` package, however, not the `zlib*-dev` package. The `*-dev` packages contain the header files, which you need for compilation. You simply need to install this `zlib*-dev` package and the compilation should work out.

**Comment by duartemolha** [comment]
thanks...  worked a charm!
