### ISSUE TITLE
Can bedtools recognize a VCF file that is missing the header?

### ISSUE THREAD

**Issue by barrymoore** [arq5x/bedtools2#213]
Maybe this is a feature, but I noticed that intersectBed (and I assume the other tools) won't process an VCF file that doesn't have a header.  I get 'Error: unable to open file or unable to determine types for file NA12882.vcf', but the file processes fine when I add  '##fileformat=VCFv4.1' to the top of the file.  Is there a way that I can specify the file type to bedtools.  If I could do something like intersectBed --format vcf that would be great. I'd really like to be able to do the following for big VCF files:

parallel -a big_ass_file.vcf  -k --pipepart --block 10m 'intersectBed -a stdin -b exons.gff -wa -u' > exomeized_file.vcf

The call to parallel splits the big file into blocks and passes them to many processes of intersectBed  through STDIN - it runs very fast on BED files, but currently only the first block of a VCF file will process because none of the rest have headers.

**Comment by arq5x** [comment]
Hi Barry,

Yes currently bedtools requires a header to recognize a VCF.  Based on your example, it seems that one workaround might be to use the --header option that GNU parallel provides to pass a header to each chunk:
https://www.gnu.org/software/parallel/parallel_tutorial.html#Header

For example:

    cat foo.txt
    ## header 1
    ## header 2
    ## header 3
    barry
    is
    a
    nice
    guy

    cat foo.txt | parallel -j 4 -k --header '(\#.*\n)*' --pipe -N1 'cat'
    ## header 1
    ## header 2
    ## header 3
    barry
    ## header 1
    ## header 2
    ## header 3
    is
    ## header 1
    ## header 2
    ## header 3 
    a
    ## header 1
    ## header 2
    ## header 3
    nice
    ## header 1
    ## header 2
    ## header 3
    guy

**Comment by barrymoore** [comment]
Thanks Aaron, I’d looked at —header option on the parallel man page, but misunderstood it’s purpose and hadn’t seen the example you gave which made it clear.  Based on your suggestion this is the command line that finally worked for me:

parallel -a big_ass_file.vcf -k --header '(\#.*\n)*' --pipepart --block 100M 'intersectBed -a stdin -b exons.gff -wa -u' > exon_cut.vcf

Gives a 3-10X speedup depending on the size of the file and the size of block used.

B

On Mar 22, 2015, at 2:22 PM, Aaron Quinlan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Barry,

Yes currently bedtools requires a header to recognize a VCF. Based on your example, it seems that one workaround might be to use the --header option that GNU parallel provides to pass a header to each chunk:
https://www.gnu.org/software/parallel/parallel_tutorial.html#Header

For example:

cat foo.txt
## header 1
## header 2
## header 3
barry
is
a
nice
guy

cat foo.txt | parallel -j 4 -k --header '(\#.*\n)*' --pipe -N1 'cat'
## header 1
## header 2
## header 3
barry
## header 1
## header 2
## header 3
is
## header 1
## header 2
## header 3
a
## header 1
## header 2
## header 3
nice
## header 1
## header 2
## header 3
guy

**Comment by arq5x** [comment]
Glad it worked - at some point, hopefully we can add options to force a specific file type from the CL.
