### ISSUE TITLE
groupBy Distinct sort order enhancement?

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#215]
Hi Guys

I was using groupBy and noticed something a bit annoying and I was wondering if you could improve it.

assume I have a file with this content:

MPL NM_005373.2 1
MPL NM_005373.2 2
MPL NM_005373.2 3
MPL NM_005373.2 4
MPL NM_005373.2 5
MPL NM_005373.2 6
MPL NM_005373.2 7
MPL NM_005373.2 8
MPL NM_005373.2 9
MPL NM_005373.2 10
MPL NM_005373.2 11
MPL NM_005373.2 12
MPL XM_005270874.1 1
MPL XM_005270874.1 2
MPL XM_005270874.1 3
MPL XM_005270874.1 4
MPL XM_005270874.1 5
MPL XM_005270874.1 6
MPL XM_005270874.1 7
MPL XM_005270874.1 8
MPL XM_005270874.1 9
MPL XM_005270874.1 10
MPL XM_005270874.1 11
MPL XM_005270874.1 12

the operation

```groupBy -g 1 -c 2,3 -o distinct,distinct```

Outputs:
MPL NM_005373.2,XM_005270874.1 1,10,11,12,2,3,4,5,6,7,8,9

As you can see , even though my input is sorted alphabetically on the 2 column and numerically on the 3rd column, the "distinct" operation does not retain the ordering. and forced alphabetical ordering on the output. would you consider implementing a sorted_num_distinct operation?

Or at least retain the input order of the numbers ?

Thanks

Duarte

**Comment by duartemolha** [comment]
anyone?

**Comment by arq5x** [comment]
Thanks for the ping - this would have to be implemented with a different data structure and we will have a look. Sorry for the delay, my lab is transitioning to another University and development is a bit delayed as a consequence.

**Comment by duartemolha** [comment]
thanks ... sorry...I do not mean to put pressure on you... I just wanted to know your views on this issue and it it would be something you guys would be willing to change.

**Comment by nkindlon** [comment]
Working on this now. I see we use the STL sort algorithm both in the old VectorOps class that groupBy currently uses and the new KeyListOps class that map and merge currently use. As I'm converting groupBy over to the new tools, which are faster and have some new functionality, I'll add a both a stable_sort switch for groupBy that will preserve the original ordering, and an option to sort numerically.

**Comment by duartemolha** [comment]
Fantastic. Many thanks

**Comment by nkindlon** [comment]
Actually, looking at it further, the stable sort is simple enough, but the numeric sort would be quite difficult with the current architecture. Aaron explained that groupBy is one of the few tools that can work on any file, not just bed (or gff/vcf/bam), so the newer tools won't work as they are. The older tools really only look at one column at a time. Will a stable sort by itself be adequate for your needs?

**Comment by duartemolha** [comment]
What do you mean with Stable sort? Do you mean retaining the sort on the input file?

**Comment by nkindlon** [comment]
Oh, sorry. Yes, that is what I mean. Basically, when two items are have an equal value for the column being sorted, they'd be kept in the order they appear in the file.

**Comment by duartemolha** [comment]
yes... that would already be a welcome improvement

=========================
     Duarte Miguel Paulo Molha
         http://about.me/duarte
=========================

**Comment by nkindlon** [comment]
Great, thanks!

**Comment by nkindlon** [comment]
Actually, what you asked for first turned out to be the better thing to do, so I added distinct_sort_num and distinct_sort_num_desc. The former uses ascending order by default, while the latter uses descending. 
Aaron, I added these to KeyListOps as well so that map and merge will get them, too.
The help for groupBy, map, and merge has been updated with these options.
Finished in pull request #247.
