### ISSUE TITLE
Different results with different versions

### ISSUE THREAD

**Issue by fpichon** [arq5x/bedtools2#216]
Hi everybody,

Maybe it's already known, but I obtained different results with different versions of bedtools using intersect :

$ /opt/bedtools/bedtools --version
bedtools v2.21.0
$ /opt/bin/bedtools --version
bedtools 2.15.0

$ /opt/bedtools/bedtools intersect -a file1.bed -b file2.bed | wc -l
29233
$ /opt/bin/bedtools intersect -a file1.bed -b file2.bed | wc -l
29621

Someone could explain me why ? Something changed ? Which one should I believe ?

Thanks,
Fabien

**Comment by nkindlon** [comment]
Hi Fabien,
     Thank you for reporting this. Sorry for the delay in response; I just returned from the holiday weekend. I would need to see your input files to give an accurate explanation. Can you please e-mail them to me at nek3d@virginia.edu? Thanks!
     My guess in the meantime is that v2.21 did have a bug in the handling of zero-length records. This has since been fixed, and you could try updating to version v2.23 to see how it compares. That should be the most accurate of the versions, with emphasis on "should". 
     Please also note that v2.15 is quite old and deprecated at this point. We do strongly recommend upgrading for the many improvements we've made since.
Thanks,
Neil

**Comment by fpichon** [comment]
Well, my files are zero-length records...  so it may be why there are these differences...

**Comment by nkindlon** [comment]
Ah, ok, great. So yeah, either send me those or try 2.23 and let me know how that works.
Thanks,
Neil

**Comment by nkindlon** [comment]
Hi Fabien,
    When I run 2.15, 2.21, and 2.23, I get 29688, 29676, and 29688, respectively. 2.21 is indeed incorrect because of the zero length records.
    As for the differing results, I did indeed also see what you're talking about. We get some errors where BOTH input files contain the same two ADJACENT zero length records. For example, both input files have:

chr1    29259403        29259403        2035    +
chr1    29259404        29259404        2035    -

v2.15 gives the intersection:
chr1    29259403        29259403        2035    +
chr1    29259403        29259403        2035    +
chr1    29259404        29259404        2035    -
chr1    29259404        29259404        2035    -

But v2.23 gives:
chr1    29259403        29259403        2035    +
chr1    29259404        29259404        2035    +
chr1    29259404        29259404        2035    -
chr1    29259404        29259404        2035    -

I don't honestly think either of these are correct, to be honest. Let me confirm with Aaron when he returns later this week, and if needed, we'll get out a patch as fast as possible. Sorry about that.

**Comment by nkindlon** [comment]
My understanding is that the correct results should have been:

chr1 29259403 29259403 2035 +
chr1 29259403 29259404 2035 +
chr1 29259403 29259404 2035 -
chr1 29259404 29259404 2035 -

**Comment by fpichon** [comment]
No, the correct result should be :

chr1 29259403 29259403 2035 +
chr1 29259404 29259404 2035 -

In this case, the behavior of bedtools is indeed the problem, because it's not precise enought, it has a +/-1 base imprecision so it returns both entry for each entry and so, there are thus twice outputs as what expected.... 

In a correct bed files, entries should be constructed as follow :
chr1 29259403 29259404 2035 +
chr1 29259404 29259405 2035 -
And thus, my guess is that there is somewhere a -1 for the ending...

What is REALLY strange and I cannot explain is that a strand is changed for another :
if you look carefully entries : 29259403 is on strand + and 29259404 on strand -.
But in the v2.21 output, suddently, you have a 29259404 on strand +.......... (?????!!!!!!!)

I know these bed files are not standard, but they did like this in the lab before I arrived....
I thus created standard bed files and make again the intersect with version 2.21 and obtained :
29.377 and result seems to be good (at least for these 2 entries). Strand weird effect has disappeared too for these entries.

So I think all these problems emerged because of non standard bed files my group used until now...

**Comment by fpichon** [comment]
I found the first behavior to persist in 2 cases :
Entries in both files
chr17   4224149 4224150 7326    +
chr17   4224149 4224150 7326    -
return
chr17   4224149 4224150 7326    +
chr17   4224149 4224150 7326    +
chr17   4224149 4224150 7326    -
chr17   4224149 4224150 7326    -
with bedtools intersect

and entries in both files
chr6    155605769       155605770       26230   +
chr6    155605769       155605770       26230   -
return
chr6    155605769       155605770       26230   +
chr6    155605769       155605770       26230   +
chr6    155605769       155605770       26230   -
chr6    155605769       155605770       26230   -
with bedtools intersect.
Why these 2 entries and not others? I do not know.... It should be due to this bug of zero-length intervals...

So I will have to wait for the informatician to come back from holidays to test new version of bedtools !

**Comment by fpichon** [comment]
Ok, I get it. I did'nt used strandness. As intervals are the same, it's normal each entry has the two corresponding entries in other file. So this is normal. Thanks !
