### ISSUE TITLE
Missing hits in sorted intersect algorithm

### ISSUE THREAD

**Issue by dzerbino** [arq5x/bedtools2#218]
Hello all,

First of all, thanks a bunch for maintaining this awesome tool, I use it quite intensively on a daily basis. 

I have two sorted files (verified with "sort -k1,1 -k2,2n -c") and yet I get a different result when I run in -sorted mode:

> bedtools intersect -sorted -wa -wb -a my_transcripts.bed -b my_probes.bed | wc -l
173125
> bedtools intersect -wa -wb -a my_transcripts.bed -b my_probes.bed | wc -l
173857

This bug appeared on medium files (200K and 48K row respectively), I can e-mail/upload them where convenient. I did not manage to reproduce the bug on smaller files.

Regards,

Daniel

UPDATE: The above was on 2.17.

On 2.23, I get both different results and warnings:

> ./bin/bedtools intersect -wa -wb -sorted -a ~/my_transcripts.bed -b ~/my_probes.bed | wc -l
***** WARNING: File /nfs/users/nfs_d/dz1/my_transcripts.bed has inconsistent naming convention for record:
CHR_HG142_HG150_NOVEL_TEST	56209880	56212054	ENST00000570683

***** WARNING: File /nfs/users/nfs_d/dz1/my_transcripts.bed has a record where naming convention is inconsistent with other files:
CHR_HG142_HG150_NOVEL_TEST	56209880	56212054	ENST00000570683

ERROR: Database file /nfs/users/nfs_d/dz1/my_probes.bed contains chromosome GL000214.1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
167208

> ./bin/bedtools intersect -wa -wb -a ~/my_transcripts.bed -b ~/my_probes.bed | wc -l
***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has inconsistent naming convention for record:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has a record where naming convention is inconsistent with other files:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has a record where naming convention is inconsistent with other files:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

173857

This is all rather unclear to me as a) these are official GRCh38 sequence names and b) the [manual](http://bedtools.readthedocs.org/en/latest/content/general-usage.html)  explicitly allows any string as chromosome name

**Comment by arq5x** [comment]
Hi @dzerbino - can you try the -nonamecheck option?  If this doesn't work, please send me the files and I will look into it.  Thanks much, sir.

**Comment by dzerbino** [comment]
According to the error messages, -nonamecheck only works with -sorted, correct?

I still get discordant results unfortunately. Sending you files by e-mail.

Daniel

//////////////////////////////////////////

> ./bin/bedtools intersect -wa -wb -sorted -nonamecheck -a ~/my_transcripts.bed -b ~/my_probes.bed | wc -l
ERROR: Database file /nfs/users/nfs_d/dz1/my_probes.bed contains chromosome GL000214.1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
167208


> ./bin/bedtools intersect -wa -wb -a ~/my_transcripts.bed -b ~/my_probes.bed | wc -l
***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has inconsistent naming convention for record:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has a record where naming convention is inconsistent with other files:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

***** WARNING: File /nfs/users/nfs_d/dz1/my_probes.bed has a record where naming convention is inconsistent with other files:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

173857

**Comment by arq5x** [comment]
Hi Daniel,

Sorry for the delay.  @nkindlon has been working on refining the logic for auto-detecting when files employ different chromosome labeling schemes in the interest of alerting users to potential false negatives. Version 2.23 is a bit aggressive in this regard. As such, we recently updated the code (in the github repo) to be less agressive.  As you can see below, the number of hits are identical when using -sorted or not with the code in master:

    ../bin/bedtools intersect -wa -wb -a my_transcripts.sorted.bed -b my_probes.sorted.bed  | wc -l
    ***** WARNING: File my_probes.sorted.bed has inconsistent naming convention for record:
    CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL

***** WARNING: File my_probes.sorted.bed has a record where naming convention is inconsistent with other files:
CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL
    
    ***** WARNING: File my_probes.sorted.bed has a record where naming convention is inconsistent with other files:
    CHR_HSCHR11_1_CTG7	2883878	2884010	-1	30=83D20=	0	32688139	279093	ILMN_1718565	NULL	NULL
    
    173857

**Comment by dzerbino** [comment]
Don't apologise for the delay. I'm in Europe now, I don't work over
weekends anymore ;-)

Thanks for "sorting" this out (sorry)

Daniel

**Comment by dzerbino** [comment]
You may have forgotten to push to master or something, as I could not reproduce your successful run:  

bin/bedtools intersect -wa -wb -sorted -nonamecheck -a ~/lustre2/probe2transcript/my_transcripts.bed -b ~/lustre2/probe2transcript/my_probes.bed | wc -l
ERROR: Database file /nfs/users/nfs_d/dz1/lustre2/probe2transcript/my_probes.bed contains chromosome GL000214.1, but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.
167208

**Comment by arq5x** [comment]
Huh, that is odd as the changes were added the week before last.  What is your version?  Here is what I have:

    bin/bedtools --version
    bedtools v2.23.0-20-gada04b6-dirty

**Comment by dzerbino** [comment]
farm3-head1:~/utils/bedtools2 (master) > bin/bedtools --version

bedtools v2.23.0-22-g43f88db

**Comment by arq5x** [comment]
Oops, I forgot to mention that I had to re-sort your files for this to work. 

    sort -k1,1 -k2,2n -c my_transcripts.bed
    sort: my_transcripts.bed:189528: disorder: CHR_HSCHR12_1_CTG1	12076	14494	ENST00000572276
    sort -k1,1 -k2,2n -c my_probes.bed
    sort: my_probes.bed:45044: disorder: CHR_HSCHR12_1_CTG2_1	57953681	57956727	1	9=2997D41=	0	32609390	170667	ILMN_1767481	NULL	NULL

**Comment by dzerbino** [comment]
Aha, then our locales were set differently, because sort was happy with my
files.

I just set LC_ALL to C, re-sorted my files, and got the announced results.

Thanks!

Daniel

PS: Go to bed.
