### ISSUE TITLE
suggestion : use a C++ reference in `sort` instead of deep copy

### ISSUE THREAD

**Issue by lindenb** [arq5x/bedtools2#220]
A minor suggestion :  when using a std::map::iterator you should use a reference (`&`) instead of making a deep copy of the `iterator->second`.

``` diff
diff --git a/src/sortBed/sortBed.cpp b/src/sortBed/sortBed.cpp

-        vector<BED> bedList = m->second;
+        const vector<BED>& bedList = m->second;

```

it should be faster (no copy constructor for vector invoked )

```
$ wc input.bed 
  8685958  26057874 209367985 input.bed

$ time ./bin/bedtools sort -i input.bed > /dev/null 
real    1m7.074s
user    1m4.896s
sys 0m1.972s
```

after I changed the code

```
$ time ./bin/bedtools sort -i input.bed > /dev/null 

real    1m0.065s
user    0m58.520s
sys 0m1.476s
```

**Comment by arq5x** [comment]
Yep, good catch!

**Comment by nkindlon** [comment]
Deja Vu, we just hit this problem elsewhere yesterday! Thanks for reporting it. I changed all the instances of that in sortBed.cpp. Note that in places where the vector is then sorted, we have to use a reference instead of a const ref (minor detail). Adding some unit tests now.

**Comment by nkindlon** [comment]
Pushed the changes with unit tests. Closeable with pull request #247.
