### ISSUE TITLE
VCF handling for insertions SVs is incorrect

### ISSUE THREAD

**Issue by marghoob** [arq5x/bedtools2#223]
For insertions, (`<INS>` in the ALT column) endpos should be the same as startpos but from the code it appears that endpos = startpos + svlen which is incorrect. The line in point is https://github.com/arq5x/bedtools2/blob/2f90e6a76e87f4e7972b97cbfae77a096a1e20c2/src/utils/FileRecordTools/Records/VcfRecord.cpp#L25

**Comment by arq5x** [comment]
Thanks very much for reporting this, good catch. @nkindlon is having a look today.

**Comment by nkindlon** [comment]
Yeah, definitely a good catch, thanks. I changed it to treat insertions like zero length records. Added a unit test for this. Pull request is #224.
