### ISSUE TITLE
VCF SVLEN tag can have more than two numbers

### ISSUE THREAD

**Issue by nkindlon** [arq5x/bedtools2#226]
As reported by @marghoob, the SVLEN tag in a VCF record for imprecise variants can have more than two numbers. We currently only check for one or two, but need to check them all.

**Comment by nkindlon** [comment]
Actually, I don't think one is in yet.

**Comment by arq5x** [comment]
gotcha, thought it was based on the reference.

**Comment by nkindlon** [comment]
Rafael Kohen pointed out that the "SVLEN=" section can appear anywhere in the info tag, including at the end, where it could be followed by a semi-colon, tab, newline, or EOF. Handling for that and more than 2 numbers are added in pull request #245
