### ISSUE TITLE
merge and mergeBed hang upon calling

### ISSUE THREAD

**Issue by jelber2** [arq5x/bedtools2#227]
It looks as though neither bedtools merge nor mergeBed are functioning properly right now. I've tried calling both just by themselves using either bedtools-2.23.0 or bedtools-2.22.1, which results in nothing happening and the system "hangs". I am using Centos-6.6 OS. All other functions seem to at least provide a help screen if called without arguments.

**Comment by nkindlon** [comment]
Hi, 
    Can you please send me the data file you're using at nek3d@virginia.edu? The problem you're seeing might be an OS dependent issue, but let's rule out the data first. Thanks!
-Neil

**Comment by arq5x** [comment]
Hi all, both bedtools sort and bedtools merge intentionally assume STDIN when no parameters are given. Thus the behavior is as intended.  That said, I am not sure this behavior is ideal, since it differs from every other tool in bedtools.

**Comment by nkindlon** [comment]
Oh, right, sorry, that explains why newer versions are having this problem. It used to be that the -i option was mandatory, and if you didn't use it, you'd get an error, then the help message. We were asked to change that and did so a few versions back, such that -i is no longer needed, but it will now, as Aaron said, assume you're using stdin when -i isn't present. 

Just to confirm, I did run the file you sent (thanks for sending that!), and it works correctly with -i, though you do have a record sorted out of order at line 20 that you'll need to fix:
20:NW_007281546.1       889099  889219  .       0       -

**Comment by jelber2** [comment]
Thanks guys works fine now that I sorted the bed file and use -i

-Jean Elbers
