### ISSUE TITLE
getfasta index corruption checks for .fai files

### ISSUE THREAD

**Issue by dshivak** [arq5x/bedtools2#228]
If the underlying fasta file is changed and the .fai index file is left in place, getfasta will retrieve wrong results.  I had a fasta file replaced by a co-worker (who shall remain nameless).  This led to getfasta generating incorrect sequence due to differing sequence offsets (headers differed, sequence was the same).  This is obviously an edge case but has the potential to corrupt all sequence from that point on.

Perhaps at the minimum an mtime comparison could be done to see if the fasta file is newer than it's index file?  Anything more would involve including sanity check offsets in the .fai file which is a samtools spec issue.  Checking for illegal characters in the output is unlikely to work since the query coordinates would have to be near a header line to output illegal sequence characters.

To reproduce the error case (tested with 2.23.0):

    host:~/Downloads/bedtools2/test/getfasta$ cat t.fa
    >chr1
    cggggggggg
    >chr2
    AAATTTTTTTTTT
    host:~/Downloads/bedtools2/test/getfasta$ echo -e "chr2\t2\t10" | ../../bin/bedtools getfasta -fi t.fa -bed - -fo -
    index file t.fa.fai not found, generating...
    >chr2:2-10
    ATTTTTTT
    # Change header in source, leave .fai in place
    host:~/Downloads/bedtools2/test/getfasta$ cat t.fa
    >chr1 ver 2.2.2.2.2
    cggggggggg
    >chr2
    AAATTTTTTTTTT
    host:~/Downloads/bedtools2/test/getfasta$ echo -e "chr2\t2\t10" | ../../bin/bedtools getfasta -fi t.fa -bed - -fo -
    >chr2:2-10
    ggggg>c

**Comment by gtamazian** [comment]
Added a warning message indicating that an index file is older than the corresponding FASTA file.

**Comment by arq5x** [comment]
Could you possibly create a pull request with just the getfasta changes?  I would like to look more closely at the changes to the other files before merging, but this seems clean and a nice improvement!

**Comment by gtamazian** [comment]
@arq5x I created a separate pull request with **getfasta** fixes, please check PR #242.
