### ISSUE TITLE
File has inconsistent naming convention (leading zero) for record:

### ISSUE THREAD

**Issue by nicolasDelhomme** [arq5x/bedtools2#230]
Hej!

I'm using bedtools v2.23.0 and when using "intersect" I get the error in the title.

I assume that this is related to that entry: https://github.com/arq5x/bedtools2/issues/166; but the genome I use (P. trichocarpa from the JGI) uses chromosome names like Chr01 to Chr19. 

I find the rationale described in issue 166 for this test to be excessively restrictive; I'm not even sure that I  get the rationale for it; what was the reason to introduce that "limitation"?

Anyway, there are many genomes (plants) that use such conventions and as you can imagine it is impossible to alter them or post-process every file to adapt the chromosome names so that they pass that check; hence it would be essential that a solution be provided to de-activate that check. 

I would even suggest that an option be added to activate the check - i.e. that the check be off by default - as I can see that such a restrictive approach is going to significantly affect scores of us working with novel or recently sequenced genomes.

Bedtools is a fantastic tool - which we really appreciate! no flattery intended - so I hope you'll consider my suggestions above :-)

Best,

Nico

**Comment by nicolasDelhomme** [comment]
Actually, there is one more level of checking that further break the use of bedtools intersect. As I mentioned, the genome is still not complete and contains in additions to the 19 chromosomes, about 1000 scaffolds. Hence, the names are a mix of Chr01 to Chr19 and scaffold_20 to scaffold_XXXX. The mix of Chr and scaffold is also breaking the use of bedtools intersect. I'm currently doing
a sed inline replacement (changing Chr to Chr_ and scaffold to Chr) and that does the trick, but that's just moving the issue to the next tool, where I will have to change that back (which implies that I will have to get some record of what was the scaffold and what was a Chr).

**Comment by nkindlon** [comment]
Hi Nicolas, 
    Sounds like you definitely want to run with -nonamecheck to avoid the check altogether.
    The next release will have that error only be a warning instead. The reason we introduced the name check at all is that there've been many cases where a file will have names like chr01, but be intersected with a file that calls it chr1, or just 1. In such a case, many/most hits are missed, meaning lots of false negatives.

**Comment by nicolasDelhomme** [comment]
Hej Neil!

Got it.

Could you update the html page to add this option in the listed options? The only reference I found for it was to this other thread that mentions an altogether different option name (but as I'm travelling right now, I have limited connectivity and may have missed it). 

I know that Bioconductor has faced the same problem and they addressed it in the following way: they check what the overlap is between both lists (trusting the user to know what he is doing and letting him decide on the sequence names) and report a warning listing every sequence name that is not part of the overlap.

Thanks for the answer and the great work!

Cheers,

Nico

---------------------------------------------------------------
Nicolas Delhomme

The Street Lab
Department of Plant Physiology
Umeå Plant Science Center

Tel: +46 90 786 5478
Email: nicolas.delhomme@umu.se
SLU - Umeå universitet
Umeå S-901 87 Sweden
---------------------------------------------------------------

**Comment by nkindlon** [comment]
Yes, we'll definitely make sure all the tools that use intersection get that in the help. Thanks!

**Comment by bio-la** [comment]
Hi, up to now I still have that problem. (I work with susScrofa and there's some scaffold that may cause the error). I can't find the -nonamecheck in listed options in the help and when i type it it simply ignores it.
I'm using bedtools v2.23.0.

thanks for your support!  
biola

**Comment by arq5x** [comment]
Hi @bio-la - which tool are you using?  The intersect, subtract, coverage, and map tools all have this option in the version of bedtools found in github (i.e., not yet a formal release, but subsequent to the release of 2.23.0). Could you trying building from the github repository and see if that fixes your problem?

**Comment by arq5x** [comment]
Please try with 2.24.0 which includes an improved `-nonamecheck` option for each of the tools I mentioned. If this is still an issue, please reopen.

**Comment by edenpi** [comment]
> Hi Nicolas, Sounds like you definitely want to run with -nonamecheck to avoid the check altogether. The next release will have that error only be a warning instead. The reason we introduced the name check at all is that there've been many cases where a file will have names like chr01, but be intersected with a file that calls it chr1, or just 1. In such a case, many/most hits are missed, meaning lots of false negatives.

How do I apply the nonamecheck option in Galaxy?
