### ISSUE TITLE
Support for bedpe

### ISSUE THREAD

**Issue by oursu** [arq5x/bedtools2#236]
Hi,

Would it be possible to add additional methods for bedpe files? These would be very helpful for scientists working with DNA contact maps that are based on DNA-DNA links expressed in bedpe format.

Specifically, I was interested in methods for:
- overlapping/windowing a bed file with a bedpe file (that is, overlap the bed file with each anchor in the bedpe file)
- overlapping 2 bedpe files (basically, a regular intersect but performed for both anchors in the bedpe file at the same time)

I have written code to do this as a bash script. Would it help for me to share it?

Thank you,
Oana

**Comment by DanTheColoradan** [comment]
@oursu, did you figure something out? I would also love to be able to do bedpe intersects and other commands.

**Comment by arq5x** [comment]
Have you looked into `pairtobed` and `pairtopair`?

**Comment by DanTheColoradan** [comment]
I did and I didn't realize that it probably solves my problem. Thanks! I'll report back if I have any problems.

Btw, perhaps the wonderful pictures the other bedtools commands have would be helpful? I like that it has ASCII, but the colored pictures are extremely helpful.

**Comment by arq5x** [comment]
Agreed, they just take time.  I chip away at them when I have some, which is rarely of late!

**Comment by DanTheColoradan** [comment]
Great :) Thanks. :beers:
