### ISSUE TITLE
Bug: BedPlus not properly recognized

### ISSUE THREAD

**Issue by nkindlon** [arq5x/bedtools2#237]
Given the following 12 field line:
chr1    10        20        randomName   0.4  X       Y       0.2  otherName   3rdword        4thword   86.0
We'll currently try to mark it as bed12, which it isn't, and die with an error. 
It should be counted as a BedPlus record.

**Comment by nkindlon** [comment]
Fixed in pull request #225

**Comment by jmarshall** [comment]
What's BedPlus?  (I grepped the `kent` tree without too much elucidation, and Google suggested the [UCSC formats page](https://genome.ucsc.edu/FAQ/FAQformat.html) which wasn't much help either.)

**Comment by arq5x** [comment]
Good question. Bedplus is our colloquial term for any BED-like format that starts with `chrom`, `start`, and `end`, yet is followed by any number of additional columns that do not necessarily conform to the types and values expected by BED6, BED12, etc.  No such format, but such files are used all the time.
