### ISSUE TITLE
'-m' (Merge) in 'fisher' not working

### ISSUE THREAD

**Issue by mdozmorov** [arq5x/bedtools2#240]
bedtools fisher -m -g hg19.genome -a query.bed -b reference.bed 
***** ERROR: Unrecognized parameter: -m *****
Tool:    bedtools fisher (aka fisher)
Version: v2.23.0-48-g54f37af

**Comment by nkindlon** [comment]
Whoops. Yep, that's broken, sorry. Will fix that ASAP.

**Comment by arq5x** [comment]
@nkindlon - let me know when this is patched, as I think it should be fixed before making the new release.

**Comment by mdozmorov** [comment]
Commit e4955d3 fixes the '-m' issue.
