### ISSUE TITLE
record where naming convention warning

### ISSUE THREAD

**Issue by bbimber** [arq5x/bedtools2#248]
Hello,

After updating bedtools, I started seeing this message:

***** WARNING: File BAPstI_25F_coverage_3.bed has a record where naming convention (leading zero) is inconsistent with other files:
chr10   16724   16725   4

my input bed file has padded chromosomes (chr01, chr02 ... chr09, chr10).  i am relatively sure this message is just an overly aggressive warning when progressing from padded 'chr09' to what looks like an un-padded 'chr10'.  

the warning doesnt seem to hurt anything, but i thought i should report it.

**Comment by arq5x** [comment]
Yeah, the intent is to warn about possibly inconsistent naming conventions between files.  You should be able to suppress the warning with the `-nonamecheck` option.
