### ISSUE TITLE
GroupBy change delimiter character

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#252]
Hi guys

I was wondering if we could improve groupBy by adding a --delimiter option to change the default "," delimiter character to something else.

I ask this because my input column to group already as commas and it would be much easier to specify a different delimiter than to have to subtitute all commas on input file to something else, then replace the commas on the grouped file to the delimiter I want and then replace the temporary comma replacement I  used in the first step to regenerate the correct input terms.

many thanks

Duarte

**Comment by nkindlon** [comment]
Sure. Map and merge already had this, so I added it to groupBy as well. 
Completed in pull request #247.
