### ISSUE TITLE
bring up help options when tool is called out with no parameters

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#255]
for many bedtools , if you call them without any options they output the help message.

However this is not used consistently across all tools.

for example sortBed, mergeBed, clusterBed require -h parameter to ouput help

many others don't... could we make this behavior consistent across all tools?

**Comment by nkindlon** [comment]
Hi Duarte,
    I'm afraid that conflicts with two other requests. We were asked to have merge accept stdin without use of the -i option. So when you call it and it does nothing, it's waiting for stdin.

We were also asked to not show the help when there is an error message, since the help can be so long it drives the actual error message off screen. We could at least include the usage with the error message, since it's currently part of the help and thus doesn't show up.

Lastly, I'm afraid the tools are in a "mixed state", in that only some were converted to a new architecture, while other ones were not. This makes consistency a bit challenging in some cases.

**Comment by duartemolha** [comment]
thanks for the explanation. I believe there are ways around this in perl .. but do not know enough about C or C++

**Comment by jmarshall** [comment]
> I'm afraid that conflicts with two other requests. We were asked to have merge accept stdin without use of the -i option. So when you call it and it does nothing, it's waiting for stdin.

The usual way around this (used in samtools etc) is

    #include <unistd.h>
    …
    // when invoked as just "bedtools merge"
    if (isatty(STDIN_FILENO))
        …no redirection, display the usage
    else
        input_filename = "-";

So `blahblah | bedtools merge` (reads stdin) and `$ bedtools merge` (shows usage) work as expected, and if you really really want to type in a bed file yourself you can write `cat | bedtools` or (hopefully) `bedtools -i -`.

**Comment by duartemolha** [comment]
Yes ... I was hoping that this was the case @jmarshall  :) 

this would make perfect sense to me.

**Comment by duartemolha** [comment]
This this , to my knowledge is not fixed.

I believe this is common practice across most linux command line utilities and even with all other commands part of bed tools

However, in bedtools, things are not homogenized 

These commands show help with -h parameter but not when called with no parameters (--help also shows usage, but only because it is interpreted as an unrecognized parameter)

sortBed
clusterBed


This commands show usage if called with no arguments but fail with "-h" or even "--help" 

- intersectBed
- subtractBed
- coverageBed
- closestBed
- mapBed
- complementBed (only shows help because it complains about no genome file being provided)

This commands show usage if called with no arguments, with -h or with --help (this however, when called with no arguments only shows help because it complains about missing arguments, the same with --help; however -h seems to be supported even though there is nothing on the usage to show support for the parameter)

- shiftBed
- slopBed
- flankBed
- randomBed
- shuffleBed


These commands show usage with no arguments or with -h (--help also shows usage, but only because it is interpreted as an unrecognized parameter)

- windowBed 
- genomeCoverageBed
- annotateBed
- multiIntersectBed (on its own shows usage because it is missing arguments; --help complains about missing parameter, but does not show the usage)
- unionBedGraphs (on its own shows usage because it is missing arguments; --help complains about missing parameter, but does not show the usage)

This command does not show help either on its own as a command or with -h or even with --help

- mergeBed


I have not analised all of them... but I beleive the list above can show clearly a lack of consistency that can be a bit confusing.

The mergeBed is really annoying since sometimes I have to revert back to online to find out all thge parameters because I simply fail to get the usage to display. It seems to need a error to occur to display usage

**Comment by arq5x** [comment]
I agree with you. I will try to sort this out for the next release. merge and sort are bit of an issue though, as they were intentionally changed to behave like this from user requests. Changing could affect existing pipelines. But otherwise I agree and thanks for reporting.

**Comment by duartemolha** [comment]
Surely adding a -h or --help flag to all utilities should not break pipelines. Why would it? mergeBed on its own would still read from STDIN

**Comment by arq5x** [comment]
Absolutely, I just meant that typing "bedtools sort" without an option will still just hang.

**Comment by duartemolha** [comment]
Surely adding - h or - - help to bring out help on all commands includind
sort and merge would not break pipelines? Why would it? 1

**Comment by jmarshall** [comment]
> Absolutely, I just meant that typing "bedtools sort" without an option will still just hang.

Can be avoided — see my earlier comment.  You can try this out by comparing `samtools view` (usage) and `cat foo.bam | samtools view` (reads stdin).  Works with samtools 1.3 or later.

**Comment by arq5x** [comment]
I have not standardized all of the behavior, but sort, merge, and cluster no longer hang when no input is provided. Thanks for raising this issue and sorry for the very delayed fix.
