### ISSUE TITLE
Enhancement: support remote files / remote BAM files

### ISSUE THREAD

**Issue by nkindlon** [arq5x/bedtools2#259]
Ryan Dale (@daler) had asked if we did/could support remote BAM files in issue #258. Here is an old thread on the subject:
https://github.com/pezmaster31/bamtools/issues/11

Do we wish to look into this further? If so, would we support all remote files, or just BAM? All formats would make sense, in keeping with the bedtools philosophy of format independence.

**Comment by arq5x** [comment]
This is supported via htslib integration as of version 2.28.0
