### ISSUE TITLE
[BUG bedtools map] bedtools v2.24.0 map does not work with strand specific case

### ISSUE THREAD

**Issue by s6juncheng** [arq5x/bedtools2#262]
Dear bedtools team,

bed1:

1       3215742 3216021 .       0       - 
1       3217007 3218115 .       0       -

bed2:

1       3215742 3216021 .       1       -       0       0       3
1       3217007 3218115 .       1       -       0       0       1

bedtools/2.24.0/bedtools map -a bed1 -b bed2 -s

1	3215742	3216021	.	0	-	.
1	3217007	3218115	.	0	-	.

bedtools/2.22.1/bedtools map -a bed1 -b bed2 -s

1	3215742	3216021	.	0	-	1
1	3217007	3218115	.	0	-	1

Could you please fix this?

Best,
Jun

**Comment by arq5x** [comment]
Thanks for reporting - we are looking into it.
