### ISSUE TITLE
bedtools coverage wrong output format

### ISSUE THREAD

**Issue by guillermomarco** [arq5x/bedtools2#270]
Using `bedtools coverage` output format columns isn't as described on help and on previous versions.

This bug appears on version 2.24. Version 2.23.0 works fine.
```bash
bedtools coverage -b region.bed -abam sample.bam -bed | head
chr1	15733	15834	M01167:337:000000000-AGG04:1:2105:14080:20375/1	23	-	15733	15834	0,0,0	1	101,	0,	0	0	101	0.0000000
chr1	17437	17538	M01167:337:000000000-AGG04:1:2109:11863:9977/2	37	-	17437	17538	0,0,0	1	101,	0,	0	0	101	0.0000000
```

Expected output format is:
```bash
chr13	32890578	32890684	1	150
chr13	32890578	32890684	2	149
```

**Comment by nkindlon** [comment]
Hi Guillermo,
     We did change coverage's behavior in 2.24 such that the A and B files are now swapped, in order to be consistent with the other tools' behavior. So if you instead try:
bedtools coverage -a region.bed -b sample.bam
You should see the result you're looking for. If not, please let us know.
(As an aside, note that the -abam option is deprecated and no longer necessary. BAM files will be detected and handled whether they follow -a and/or -b.)
-Neil

**Comment by guillermomarco** [comment]
I totally forgot to answer, sorry.
Thank you very much for your support! This fixed my problem.
