### ISSUE TITLE
fails to build on debian mipsel

### ISSUE THREAD

**Issue by aborrero** [arq5x/bedtools2#271]
Hi,

bedtools fails to build on debian mipsel [0].

The important error message seems to be:
```
[...]
In file included from BinTree.h:16:0,
                 from BinTree.cpp:1:
../../utils//general/QuickString.h:41:15: error: 'QuickString& QuickString::operator=(size_t)' cannot be overloaded
  QuickString &operator = (size_t);
               ^
[...]
```

Do you have any idea or hint about how to solve that?

Thanks, best regards.

[0] https://buildd.debian.org/status/fetch.php?pkg=bedtools&arch=mipsel&ver=2.24.0-1&stamp=1436289056

**Comment by arq5x** [comment]
I think commit b47dbefcb5 should address this.  Could you clone and try to compile?  Sorry, I don't have debian to test.

**Comment by aborrero** [comment]
Thanks, it seems to work here in my mipsel machine :-)
