### ISSUE TITLE
Memory usage in groupby

### ISSUE THREAD

**Issue by dariober** [arq5x/bedtools2#274]
Hello,
I just noticed that bedtools groupby (v2.24.0) uses a potentially large amount of memory even for operations that shouldn't require much memory. For example, if a.bed is a sorted bed file with just few chomosomes, the following command should use a minimal amount of memory to count the number of records in each chrom:
```groupBy -g 1 -c 1 -ops count -i a.bed```
In practice I see the memory usage grows quite a lot presumably because groupby stores in memory the whole list of chromosomes before counting. Is this intentional? (Or am I missing something?) 

This is the log from a dummy job submitted via bsub to our computer cluster:

```------------------------------------------------------------
# LSBATCH: User input
groupBy -g 1 -c 1 -ops count -i mjb051_E14oxBSAD02.SLX-6278.bwameth.chr4.bdg.gz
------------------------------------------------------------

TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with exit code 130.

Resource usage summary:

    CPU time   :    124.56 sec.
    Max Memory :      2479 MB
    Max Swap   :      2792 MB
```

Thanks!
Dario

**Comment by arq5x** [comment]
Yes, the current implementation loads every observed feature into a list and, for determining the count, it looks at the size of the list. For the `count` operation specifically, this could be done more efficiently. We will look into this as an enhancement for the future.

**Comment by blajoie** [comment]
Just noticed this as well.  Assuming the input is sorted (either required or via --sorted), there is no need to hold all features in memory.  This can be handled with a simple buffer, no?
