### ISSUE TITLE
bedtools segfaults on intersecting .vcf with .bed

### ISSUE THREAD

**Issue by gideonite** [arq5x/bedtools2#276]
Hello,

I am trying to remove SNPs that are in UCSC's gap file from one of the 1000 genome .vcf files:

```sh
$ bedtools intersect -a ALL.chr21.phase3_shapeit2_mvncall_integrated_v5.20130502.genotypes.vcf -b gap.bed
Segmentation fault (core dumped)
```

The gap file is sorted by chr (1,2,...,22,X,Y) and then by gap start position.

Not sure how I should start debugging this.

```sh
$ bedtools --version
bedtools v2.22.1
```

Thanks!

**Comment by arq5x** [comment]
There have been some fixes for VCF files since 2.21.1:
http://bedtools.readthedocs.org/en/latest/content/history.html
Could you try with 2.24.0 and report if there segfault persists?
