### ISSUE TITLE
Feature request - intersect minimal fraction in either interval

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#277]
So I have a use case for an easy-to-implement functionality in the intersect tool.

Currently there is the f parameter to ask for interval A to overlap at least a user-defined fraction of interval B.

There is also the parameter r to ask that A should overlap a defined fraction of B, and B should overlap at least the same fraction of A (an AND operation).

I need the same but with an OR operation (either A overlaps at least a defined fraction of B OR B overlaps at least the same fraction of A).

Use case is intervals of wildly variable length in both A and B, and with f = 0.5 I would miss cases where the B interval is fully contained within A but represent only a small fraction of it, since A is large. With r = True I would miss everything. With an hypothetical parameter that ask if either A or B are intersecting with at least a defined fraction, I would get everything.

Hope that that was clear!

**Comment by arq5x** [comment]
Yes I agree, thanks for the suggestion. I will try to get a prototype going for this soon. I suspect the hardest aspect will be to make the command line arguments sane while also maintaining backwards compatibility.

**Comment by arq5x** [comment]
Thanks for this suggestion. I just pushed the following new options:

``-F`` The fraction overlap required for the B interval
``-e`` Require that the minimum fraction overlap is is achieved in either A or B. 

This should get you what you need. Please give it a try and report any issues - you will have to clone the source code from github.

**Comment by michael-imbeault** [comment]
Thank you for that - I'll test it this week - is it integrated in the fisher tool as well?

**Comment by arq5x** [comment]
Yep, they are available in `fisher`, `map`, `coverage`, `subtract`, etc. Please reopen if you find any issues.
