### ISSUE TITLE
bedtools intersect -sorted is buggy

### ISSUE THREAD

**Issue by stasuofr** [arq5x/bedtools2#278]
Running bedtools v2.22.0
I need to run bedtools intersect on a large -b file. In the manual (http://bedtools.readthedocs.org/en/latest/content/tools/intersect.html) I found that I could use the -sorted option if I presort the files. But it doesn't run properly.
I will just show an example of what is going on:

fileA:
chr1	3988193	3988194	1	1	+
chr1	3988194	3988195	1	1	+

fileB:
chr1	3988180	3988204	1	1	-
chr1	3988180	3988204	1	1	+

Both fileA and fileB have been sorted using "sort -k1,1 -k2,2n in.bed > in.sorted.bed" command as described in the manual.

Here is my first command:

bedtools intersect -s -wa -c -b fileB -a fileA
Here is the correct output:
chr1	3988193	3988194	1	1	+	1
chr1	3988194	3988195	1	1	+	1

Here is my second command:

bedtools intersect -s -wa -sorted -c -b fileB -a fileA
Here is the incorrect output:
chr1	3988193	3988194	1	1	+	1
chr1	3988194	3988195	1	1	+	0

Thank you.

**Comment by arq5x** [comment]
With version 2.24.0, this works as expected. I would suggest updating to 2.24.0
