### ISSUE TITLE
bedtools intersect -v fails for chr10-22

### ISSUE THREAD

**Issue by kippakers** [arq5x/bedtools2#279]
I'm getting very strange behavior with bedtools2.21.0. When I intersect to remove known SNPs like so:
```
bedtools intersect -v -sorted -a myfile.complete.vcf -b dbSNP_142.vcf >no_overlap.vcf
```
It seems that this only work for chromosomes 1-9, and X.  Here's one example of a failure:
```
fgrep 48875910 myfile.complete.vcf dbSNP_142.vcf no_overlap.vcf | fgrep chr19
#returns:
myfile.complete.vcf:chr19	48875910	.	C	T	861.44	PASS	AC=2;AF=0.500;AN=4;BaseQRankSum=4.535;ClippingRankSum=0.205;DP=53;FS=5.646;HRun=0;MLEAC=2;MLEAF=0.500;MQ=60.00;MQ0=0;MQRankSum=-0.472;QD=16.25;ReadPosRankSum=-1.844	GT:AD:DP:GQ:PL	0/1:14,14:28:99:458,0,341	0/1:11,14:25:99:432,0,305
dbSNP_142.vcf:chr19	48875910	rs524	C	T	.	.	RS=524;RSPOS=48875910;RV;dbSNPBuildID=36;SSR=0;SAO=0;VP=0x05010000030513051f000100;WGT=1;VC=SNV;SLO;REF;SYN;ASP;G5A;G5;HD;GNO;KGPhase1;KGPilot123;KGPROD;OTHERKG;PH3
no_overlap.vcf:chr19	48875910	.	C	T	861.44	PASS	AC=2;AF=0.500;AN=4;BaseQRankSum=4.535;ClippingRankSum=0.205;DP=53;FS=5.646;HRun=0;MLEAC=2;MLEAF=0.500;MQ=60.00;MQ0=0;MQRankSum=-0.472;QD=16.25;ReadPosRankSum=-1.844	GT:AD:DP:GQ:PL	0/1:14,14:28:99:458,0,341	0/1:11,14:25:99:432,0,305
```
If I count the lines per chromosome for each of my files, before and after intersection, I get at least 50% decrease for all chromosomes 1-9 and X, and no decrease for chromosomes 10-22.  Bedtools throws no sort order errors.  To be clear, my files are all in chr1-22,X,Y,M order.  I tried using bedtools2.19.0, but got the same issue.  If I take off the -v flag:
```
bedtools intersect -sorted -a myfile.complete.vcf -b dbSNP_142.vcf >overlap.vcf
```
None of the lines "missed" by the above commands are in the overlap.vcf file.  Any ideas why this is happening??

**Comment by arq5x** [comment]
By default, the `-sorted` option assumes that the chromosomes are sorted in lexicographic order.  I suspect your VCF files are not. As such, you will need to give it a genome file that tells intersect the exact order of the chromosomes:

http://bedtools.readthedocs.org/en/latest/content/tools/intersect.html#g-define-an-alternate-chromosome-sort-order-via-a-genome-file

**Comment by kippakers** [comment]
Thanks for your help!  Using a genome file fixed my issue.  

The lexicographic requirement seems to contradict what that doc you linked says:

>"However, since we merely require that the chromsomes are grouped (that is, all records for a given chromosome come in a single block in the file), sorting criteria other than the alphanumeric criteria that is used by the sort utility are fine"

**Comment by arq5x** [comment]
Thanks - stale docs :(
