### ISSUE TITLE
Bedtools shuffle -incl option produces undesired output for strand information. 

### ISSUE THREAD

**Issue by kriemo** [arq5x/bedtools2#280]
I'm not sure if this behavior of bedtools shuffle was an intentional design but for the -incl option the strandedness of the -incl .bed file is ignored. Instead the strand information from the -i .bed file is used, resulting in intervals that are in the correct region, but that have the wrong strand information.

For example here is the output that bedtools produces:

```
$cat test.bed 
chr1    1   100 .   .   -
chr1    100 200 .   .   +
chr1    200 300 .   .   -

$region.bed
chr1    1000    10000   .   .   -

$bedtools shuffle -g chomInfo.txt -incl region.bed -i test.bed
chr1    3928    4027    .   .   -
chr1    7108    7208    .   .   +
chr1    6850    6950    .   .   -
```

The desired output would instead be:

```
$bedtools shuffle -g chomInfo.txt -incl region.bed -i test.bed
chr1    3928    4027    .   .   -
chr1    7108    7208    .   .   -
chr1    6850    6950    .   .   -
```

This difference could cause serious miscalculations if the shuffled intervals are used in coverage calculations involving strand specific overlaps. The bedtools version is v2.24.0. Thanks!

**Comment by hisakatha** [comment]
I confirmed that the same behavior exists for `bedtools v2.28.0`. I'm hoping that the behavior will be documented, and/or a new option for using strand information will be added.

**Comment by arq5x** [comment]
This is now fixed in master. Thanks for reporting.
