### ISSUE TITLE
closestBed fails with  `-S`

### ISSUE THREAD

**Issue by mlovci** [arq5x/bedtools2#281]
closestBed with `-S` fails on some lines and shows that there are no close features.

Here is a minimally replicating example:

https://gist.github.com/mlovci/8f4004073f6645973f2b

**Comment by mlovci** [comment]
A work-around is to flip the strand (`+` --> `-`; `-` --> `+`) for `b.bed` and use `-s` instead of `-S`

**Comment by arq5x** [comment]
Sorry for the delay, will look into this as soon as we can come up for air.

**Comment by mlovci** [comment]
No problem. I am happy with the work around, but wanted to do my civic duty in reporting this.

**Comment by arq5x** [comment]
We appreciate you fulfilling your civic duty!

**Comment by nkindlon** [comment]
Fixed in pull request #294.  Michael, so sorry for the delay.
