### ISSUE TITLE
src/utils/aux is an invalid filename on Windows

### ISSUE THREAD

**Issue by jmarshall** [arq5x/bedtools2#284]
Windows refuses to create files or directories with reserved names like _aux_.  The tragically-long list of reserved characters and names is [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) or at [Wikipedia](https://en.wikipedia.org/wiki/Filename#Reserved%5Fcharacters%5Fand%5Fwords).

Reported at http://seqanswers.com/forums/showthread.php?t=61998
See also samtools/htslib@9b1cb948e78a51b93473fc1dbd5e05a9c5fddf8b and samtools/htsjdk@ca1fe528af80d53e49bbe7cd40035b2fa7c77729 :smile:

**Comment by arq5x** [comment]
Yikes, I had no idea. Will patch it for 2.25.0. Thanks for the report and the detailed explanation!

**Comment by pwwang** [comment]
I have also encounter this.

**Comment by arq5x** [comment]
Thanks so much for reporting this. Fixed with e0e4e5d9be1c.
