### ISSUE TITLE
New feature request Bedtools

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#286]
I would like to propose a new feature to be added to mergeBed

I beleive it would be beneficial to have a -f parameter (similar to subtractBed and intersectBed) where merging would only take place when a specified fraction of a entry on the bedfile was overlapped by another
So 
A command like:

`mergeBed -i file.bed -f 1.0 -r`

would only merge exactly equal entries (-r meaning the overlap fraction had to be reciprocal)

`mergeBed -i file.bed -f 0.5`

would merge any bed entry that had another entry overlapping 50 % of its length.

Do you think this is feasible or even desirable for others? 

I know it would be a great feature from me.

Best regards

Duarte

**Comment by arq5x** [comment]
I like the idea but am worried about controlling the lack of a transitive property among overlapping intervals. That is A overlaps B and B overlaps C but A doesn't overlap C, yet A, B, and C are merged. When C is being tested for -f and -r it would have to be with respect to the merged A+B.

**Comment by duartemolha** [comment]
I understand...  I believe this would have to be an operation applicable only to the root input features and not to the resulting transitive merges.
