### ISSUE TITLE
groupby -delim parameter not working/available

### ISSUE THREAD

**Issue by s1437643** [arq5x/bedtools2#288]
According to the groupby --help message you can specify a custom delimiter for collapse operations. However, whatever delimiter I specify it always uses a comma. I notice that the bedtools documentation doesn't list a -delim parameter, which makes me wonder if the --help message or the official documentation is out of date?

```
bedtools groupby -i sample.bedgraph -g 4-5 -c 7 -o collapse -delim "|"
```

**Comment by arq5x** [comment]
This is only available in the latest repository version of bedtools; it is not available in 2.24.0.  I am, however, about to release 2.25.0 so you can wait for that or clone and compile from github. To confirm, what version are you using?  It works for me using the version is the master branch of the Github repo.

**Comment by s1437643** [comment]
I was using version 2.24.0, I've updated to the latest release and the -delim parameter is working. Is it possible to specify a TAB as the delimiter? Supplying '\t' to the parameter causes \t to be printed. I can use the unix tr command to get around this issue if not. Thanks for the help, and the new release!

**Comment by steffenheyne** [comment]
@jma1991 ``bedtools groupby -delim $'\t' `` is doing likely what you want
