### ISSUE TITLE
failed to open BAM file stdin error in bedtools bamtobed

### ISSUE THREAD

**Issue by jmtoung** [arq5x/bedtools2#290]
per the documentation, you should be able to do the following

http://bedtools.readthedocs.org/en/latest/content/tools/bamtobed.html

$ samtools view -bf 0x2 reads.bam | bedtools bamtobed -i stdin | head
chr7   118970079   118970129   TUPAC_0001:3:1:0:1452#0/1   37   -
chr7   118965072   118965122   TUPAC_0001:3:1:0:1452#0/2   37   +
chr11  46769934    46769984    TUPAC_0001:3:1:0:1472#0/1   37   -
chr11  46765606    46765656    TUPAC_0001:3:1:0:1472#0/2   37   +
chr20  54704674    54704724    TUPAC_0001:3:1:1:1833#0/1   37   +
chr20  54708987    54709037    TUPAC_0001:3:1:1:1833#0/2   37   -
chrX   9380413     9380463     TUPAC_0001:3:1:1:285#0/1    0    -
chrX   9375861     9375911     TUPAC_0001:3:1:1:285#0/2    0    +
chrX   131756978   131757028   TUPAC_0001:3:1:2:523#0/1    37   +
chrX   131761790   131761840   TUPAC_0001:3:1:2:523#0/2    37   -

but when I try, I get the following error...

[jtoung@]$ samtools view full_S1_S1_L001_raw.bam | bedtools bamtobed -i stdin 
Failed to open BAM file stdin

**Comment by arq5x** [comment]
You need to pass BAM format to bedtools.  Your command is passing SAM format. 
This should work (note the -b):

    samtools view -b full_S1_S1_L001_raw.bam | bedtools bamtobed -i stdin
