### ISSUE TITLE
intersectBed does not properly deal with unaligned reads

### ISSUE THREAD

**Issue by jmtoung** [arq5x/bedtools2#291]
when I run intersectbed with a bam file, it recognizes unaligned reads as a different chromosome... and throws the following error. why can't it just ignore an unaligned read?

ERROR: Database file full_S1_S1_L001_raw.bam contains chromosome , but the query file does not.
       Please re-reun with the -g option for a genome file.
       See documentation for details.

running v2.25.0

**Comment by arq5x** [comment]
It should just ignore unmapped reads. Can you share your file?

**Comment by jmtoung** [comment]
the file is here

https://www.dropbox.com/s/ewyw0yhfb0us0ym/full_S1_S1_L001_raw.bam?dl=0

**Comment by arq5x** [comment]
I am unable to reproduce this error with your file and v2.25.0.  Could you a) make sure you are using 2.25.0 (bedtools --version) and b) provide the exact command you are using?  Thanks!

**Comment by jmtoung** [comment]
[jtoung@]$ bedtools --version
bedtools v2.25.0

Command I ran is:
bedtools intersect -wa -c -sorted -a hg19-genomeBins-1000.bed -b full_S1_S1_L001_raw.bam > test.bed

The link to the -a file is

https://www.dropbox.com/s/5xf99v95ukm7r2o/hg19-genomeBins-1000.bed.gz?dl=0

**Comment by arq5x** [comment]
Thanks, I can reproduce now. Looks like the code handles unmapped reads when the A file is BAM but not B. I will have a look into it and provide a fix as soon as I can.  Thanks again.

**Comment by arq5x** [comment]
Thanks again for reporting this and providing a nice test file.  I fixed this issue in commit be44824. If you clone from Github and compile, you should be back in business.

**Comment by jmtoung** [comment]
Thanks
