### ISSUE TITLE
not in gzip format when unpacking file output from curl 

### ISSUE THREAD

**Issue by rsmurali** [arq5x/bedtools2#292]
curl -u testuser:welcome1 -k -i -H "Content-type: application/json" -o /tmp/mardl.tar.gz -X GET https://adc.com:7002/apis/getResource/jdk

The above fetches me a .tar.gz file & file gets stored & the size of the file seems correct.

But when I run tar -xvzf on the file, it says not in gzip format.

Please help.

**Comment by arq5x** [comment]
Sorry, what is this link referring to?  I am lost.

**Comment by rsmurali** [comment]
That's the REST api which returns the tar.gz file

It is not a link.

**Comment by arq5x** [comment]
But how is this URL related to bedtools?: https://adc.com/iaps/getResource/jdk
Sorry if I am being dim.

**Comment by rsmurali** [comment]
Sorry, it is a local API. Since there was a similar issue reported here, I thought someone might help with the curl command. Sorry if this is not the right forum for this.
