### ISSUE TITLE
intersectBed -loj segfaults on 2.25

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#295]
Recently upgraded to 2.25 and found a regression - intersectBed with the -loj parameter segfaults on a simple intersection of two bed files, while reverting to 2.24 works. Have only tested on a few bed files I had, let me know if you can't reproduce so I can dig deeper if need be.

**Comment by arq5x** [comment]
I am unable to reproduce this with my test files. Could you provide an example?

**Comment by michael-imbeault** [comment]
These two small files can reproduce on my end:

testA.bed
GeneScaffold_1019	99570	99633	1	39.6	+	CSECGKSFSRSSNRIRHERIH
GeneScaffold_1019	99654	99717	1	24.8	+	CPNCEESFRRHSDLTTHQQDH
GeneScaffold_1019	99738	99801	1	40.9	+	CDICGKSFSQSSALAVHYRTH
GeneScaffold_1019	99822	99885	1	29.9	+	CCECGKSFSNSSSFGVHHRTH
GeneScaffold_1019	99906	99969	1	32.9	+	CAECGRTFSDISNFGAHQRTH
GeneScaffold_1019	99990	100053	1	39.1	+	CTQCGKHFSRSSNLIRHQKTH
GeneScaffold_1026	317799	317862	1	31.4	+	CIYCAKSFNQKGSLDRHMRLH
GeneScaffold_1026	317883	317946	1	27.0	+	CRMCGKKYTRKDQLEYHIRKH
GeneScaffold_1026	317967	318033	1	23.7	+	CHVCGKSFPFQAILNQHFRKNH
GeneScaffold_1035	131939	132008	3	4.7	+	CEWGSCSFVCSAMEEFCEHVTQH

testB.bed:
GeneScaffold_1	107688	107715	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	107716	107812	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	107823	107877	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	107880	107895	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	107899	107917	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	107918	107987	ENSVPAG00000000407	.	+	pseudogene	exon	Not found	ENSVPAT00000000407
GeneScaffold_1	282501	282607	ENSVPAG00000000410	.	+	protein_coding	exon	HECW1	ENSVPAT00000000411
GeneScaffold_1	313300	313395	ENSVPAG00000000410	.	+	protein_coding	exon	HECW1	ENSVPAT00000000411
GeneScaffold_1	335609	335685	ENSVPAG00000000410	.	+	protein_coding	exon	HECW1	ENSVPAT00000000411
GeneScaffold_1	339285	339455	ENSVPAG00000000410	.	+	protein_coding	exon	HECW1	ENSVPAT00000000411

**Comment by arq5x** [comment]
Are they actually tab-separated on your end?

**Comment by michael-imbeault** [comment]
Yes

**Comment by arq5x** [comment]
Thanks, I will have a look tonight!

**Comment by michael-imbeault** [comment]
So I narrowed it down to testB.bed - if anything is included after the 6th column it segfaults. testA is fine even if stuff is included after the strand.

**Comment by arq5x** [comment]
Thanks, that is helpful - are you using `-sorted`?

**Comment by michael-imbeault** [comment]
The original command does, but I narrowed it down to just -loj - this added to a simple intersect command makes it segfault no matter the other parameters

**Comment by arq5x** [comment]
Thanks a lot for reporting this, it actually affected a fair amount of tools (intersect and closest) and options (-lof and -wao). Commit 788a6b62f2e addresses this.

**Comment by michael-imbeault** [comment]
Fix confirmed working, thanks a lot!
