### ISSUE TITLE
intersectBed -s fails in some cases - regression since 2.23

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#296]
I have pairs of beds that are failing to report the correct results when using -s in 2.24. The same files are fine in 2.23. The weird part is that it still works on the (very simple) tutorial case in the doc (A.bed and B.bed) with 2.24.

Here's a small test case that fails and used to work on 2.23 - everything is on the same strand (+) and yet fails with -s, while excluding -s is fine even on 2.24:

A.bed
GeneScaffold_1019	98054	98092	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	98096	98109	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	98111	98133	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	98135	98149	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	99136	99336	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	99337	99385	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	99386	99450	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	99531	100027	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330
GeneScaffold_1019	100162	100212	ENSVPAG00000011330	.	+	protein_coding	exon	ZNF691	ENSVPAT00000011330

B.bed
GeneScaffold_1019	99570	99633	1	39.6	+	CSECGKSFSRSSNRIRHERIH
GeneScaffold_1019	99654	99717	1	24.8	+	CPNCEESFRRHSDLTTHQQDH
GeneScaffold_1019	99738	99801	1	40.9	+	CDICGKSFSQSSALAVHYRTH
GeneScaffold_1019	99822	99885	1	29.9	+	CCECGKSFSNSSSFGVHHRTH
GeneScaffold_1019	99906	99969	1	32.9	+	CAECGRTFSDISNFGAHQRTH
GeneScaffold_1019	99990	100053	1	39.1	+	CTQCGKHFSRSSNLIRHQKTH

**Comment by arq5x** [comment]
Have you tried 2.25.? I ask because some changes to the code handling strandedness were made in that version.

**Comment by michael-imbeault** [comment]
This one is fine in 2.25, so I'll close this - I only reverted to 2.24 in the first place because of the other -loj segfault issue.
