### ISSUE TITLE
end position before start position in bedGraph file

### ISSUE THREAD

**Issue by liangcmu** [arq5x/bedtools2#297]
I have a BAM file generated using (1) by samtools 1.2.  Then, I converted it into bedgraph file using (2) by bedtools2.  Finally, I tried to get bigwig file from bedgraph file using (3). I got the following errors:

end (403) before start (404) line 405 of A.gsnap.bedGraph
end (307) before start (316) line 317 of A.gsnap.plus.bedGraph
end (292) before start (319) line 320 of A.gsnap.minus.bedGraph

(1) samtools sort -T /tmp/A.sorted -o A.gsnap.sorted.bam A.gsnap.bam.  
(2) bedtools genomecov -ibam -bg -split -i A.gsnap.sorted.bam -g genome.info > A.gsnap.bedGraph
(3) bedGraphToBigWig A.gsnap.plus.bedGraph genome.info A.gsnap.plus.bw 

For the step (2), I have tried three options: "-strand +", "-strand -" and no strand option. That is why I have three bedgraph files shown above.  However, all three options have generated bedgraph files that contain lines with the same problems: end before start. 

Is this a bug or what? Any comment or suggestion will be highly appreciated.

**Comment by ghuls** [comment]
I think I have the same problem with bedtools 2.25.0.

The **-ibam** seems to mess things up:

```
/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -bedGraph -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp//tmp/${bam%.sorted.bam}.minus_bedGraph.bedGraph

/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -bg -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.minus_bg.bedGraph

/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -bga -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.minus_bga.bedGraph

/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -d -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.minus_d.bedGraph

/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -dz -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.minus_dz.bedGraph
```

All those commands generate the same file:
```
$ md5sum /tmp/${bam%.sorted.bam}.*
9bec6563095320b0859a3dfdb41465a1  /tmp/WT_Dana_brain_sup5.minus_bedGraph.bedGraph
9bec6563095320b0859a3dfdb41465a1  /tmp/WT_Dana_brain_sup5.minus_bga.bedGraph
9bec6563095320b0859a3dfdb41465a1  /tmp/WT_Dana_brain_sup5.minus_bg.bedGraph
9bec6563095320b0859a3dfdb41465a1  /tmp/WT_Dana_brain_sup5.minus_d.bedGraph
9bec6563095320b0859a3dfdb41465a1  /tmp/WT_Dana_brain_sup5.minus_dz.bedGraph
```

The output files look like this (not a bedGraph file for sure):
```
$ head /tmp/WT_Dana_brain_sup5.minus_bedGraph.bedGraph
scaffold_0	0	1033	1069	0.966324
scaffold_0	1	36	1069	0.0336763
scaffold_10006	0	5586	5673	0.984664
scaffold_10006	1	66	5673	0.0116341
scaffold_10006	2	21	5673	0.00370175
scaffold_10020	0	15365	15500	0.99129
scaffold_10020	1	101	15500	0.00651613
scaffold_10020	2	34	15500	0.00219355
scaffold_10034	0	1742	1780	0.978652
scaffold_10034	1	4	1780	0.00224719
```

When converting the BAM file to a BED12 file first, I am able to produce a bedGraph file.
```
/software/bedtools2/bedtools2-2.25.0/bin/bedtools bamtobed -split -i ${bam} | /software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov  -bg -split -i stdin -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.bamtobed_minus_bg.bedGraph
```

```
$ head /tmp/${bam%.sorted.bam}.bamtobed_minus_bg.bedGraph
scaffold_0	723	759	1
scaffold_10006	380	416	1
scaffold_10006	522	537	1
scaffold_10006	537	558	2
scaffold_10006	558	573	1
scaffold_10020	14553	14589	1
scaffold_10020	14797	14833	1
scaffold_10020	14887	14912	1
scaffold_10020	14954	14956	1
scaffold_10020	14956	14990	2
```

It would be nice if this could be fixed.

At the same time, it might be a good idea to remove the **-ibam** option as bedtools automagically should detect that the input is a BAM file like what happens in other subprograms of bedtools.

**Comment by arq5x** [comment]
The default output of genomecov is not bedgraph. Use the `-bg` or `-bga` options:
http://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html#bga-reporting-genome-coverage-for-all-positions-in-bedgraph-format

Are these files:

    /tmp/${bam%.sorted.bam}.minus_bg.bedGraph
    /tmp/${bam%.sorted.bam}.minus_bga.bedGraph

not in bedgraph format?

**Comment by ghuls** [comment]
I know only `-bg` and `-bga` should give output in bedGraph format.
I just tried all options to see if I would get different output, but they all generate the same output file.
So `-bg` and `-bga` do not result in a bedGraph file when `-ibam` is used.

**Comment by arq5x** [comment]
Very odd, it works for me.

    bedtools --version
    bedtools v2.25.0
    bedtools genomecov -ibam test/genomecov/y.bam -bg
    1	15	17	1
    1	17	20	2
    1	20	22	1

Can you retry with this invocation?

**Comment by ghuls** [comment]
I found the problem.
`-i` and `-ibam` are not mutually exclusive.

```
# This gives the correct output.
$ /software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -bg -split -ibam ${bam} -g "${SPECIES_CHROM_SIZES}" | head
scaffold_0	723	759	1
scaffold_10006	380	416	1
scaffold_10006	522	537	1
scaffold_10006	537	558	2
scaffold_10006	558	573	1
scaffold_10020	14553	14589	1
scaffold_10020	14797	14833	1
scaffold_10020	14887	14912	1
scaffold_10020	14954	14956	1
scaffold_10020	14956	14990	2
```
```
# This complains about: 
#   *****ERROR: Unrecognized parameter: ${SPECIES_CHROM_SIZES} ***
# because -ibam needs an argument.
$ /software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -bg -split -i ${bam} -ibam -g "${SPECIES_CHROM_SIZES}" | head
```

```
# In my first post, the -ibam option ate the -bedgraph, -bg, -bga, -d, -dz options,
# so that is why it gives the same output.
/software/bedtools2/bedtools2-2.25.0/bin/bedtools genomecov -ibam -bg -split -i ${bam} -g "${SPECIES_CHROM_SIZES}" > /tmp/${bam%.sorted.bam}.minus_bg.bedGraph
```

**Comment by arq5x** [comment]
Ah, I see. I will make them mutually exclusive and yes, I agree that it should autodetect. I will add that soon.
