### ISSUE TITLE
Intersect: display features that have overlap with all B

### ISSUE THREAD

**Issue by bdeonovic** [arq5x/bedtools2#298]
I'd like to use bedtools intersect with multiple B entries. I want to report those features in A which have overlap with some feature in all B files. Is this possible currently in Bedtools? If not could this be implemented. 

Example: 
In the bedtools intersect example picture (http://bedtools.readthedocs.org/en/latest/content/tools/intersect.html) A1 (which overlaps with B1.1, B1.2, and B2.1) would be reported, but not A2 nor A3 which only overlap with a feature in B1 and B2 respectively.

**Comment by nkindlon** [comment]
That should be doable. Internally, in the set of hits found for a given query,  each hit has a fileId that represents which database (B file) it came from. The simplest thing to would be to check that all DBs are represented and only report it if so. A more efficient approach would be to abort the intersection when any database cache fails to show a hit.

**Comment by arq5x** [comment]
While more cumbersome, currently you can also do this by using the `groupby` tool to count the number of distinct files that an interval overlapped and then restricting to the intervals whose distinct count matches the number of input files you provide.

    cat a.bed
    chr1	10	20	a1
    chr1	30	32	a2

    cat b1.bed
    chr1	0	40	b1.1

    cat b2.bed
    chr1	15	18	b2.1

    bedtools intersect -a a.bed -b b1.bed b2.bed -wa -wb
    chr1	10	20	a1	1	chr1	0	40	b1.1
    chr1	10	20	a1	2	chr1	15	18	b2.1
    chr1	30	32	a2	1	chr1	0	40	b1.1

    bedtools intersect -a a.bed -b b1.bed b2.bed -wa -wb \
    | bedtools groupby -g 1-4 -c 5 -o count_distinct
    chr1	10	20	a1	2
    chr1	30	32	a2	1

    bedtools intersect -a a.bed -b b1.bed b2.bed -wa -wb \
    | bedtools groupby -g 1-4 -c 5 -o count_distinct \
    | awk '$5==2'
    chr1	10	20	a1	2

**Comment by bdeonovic** [comment]
This is almost exactly why I need. Is there anyway to use `groupby` but retain the B entries? So in your example ultimately I want my output to be

``hr1    10  20  a1  1   chr1    0   40  b1.1  2   chr1    15  18  b2.1``

or something similar
