### ISSUE TITLE
bedtools merge -s fails with columns added

### ISSUE THREAD

**Issue by mpmeers** [arq5x/bedtools2#299]
I have a .bed file specifying 6 fields (through strand info) that has n extra columns added to it that specify count data from n conditions.  I'd like to use bedtools merge to merge intervals in a strand-specific manner and sum the contents of the count columns for all merged entries.  Sample entry:

bedtools merge -s -i counts.bed -c 7,8,9,10,11,12 -o sum

However, I find that zero lines are output when using the -s flag, while the operation appears to work just fine when the -s flag is not used (though the output is not what I want, since entries from opposite strands are being merged).  I still get the same results if I restrict the input file to entries on one strand, or when I fill out all possible optional .bed fields before adding count columns.  It seems that the -s option is sensitive to column count in a way that the core merge function is not.  Is there a way to circumvent this issue?

**Comment by mpmeers** [comment]
Forgot to include sample input:

2L	67040	67055	peak_2L67040	.	+	94	85	45	32	184	196
2L	67073	67073	peak_2L67073	.	+	1	1	1	0	7	4
2L	67142	67144	peak_2L67142	.	+	0	0	3	0	20	20

**Comment by arq5x** [comment]
I cannot replicate with version 2.25.0. What version are you using?

    cat issue-299.txt.bed
    2L	67040	67055	peak_2L67040	.	+	94	85	45	32	184	196
    2L	67073	67073	peak_2L67073	.	+	1	1	1	0	7	4
    2L	67142	67144	peak_2L67142	.	+	0	0	3	0	20	20

    bedtools merge -s -i issue-299.txt.bed -c 7,8,9,10,11,12 -o sum
    2L	67040	67055	+	94	85	45	32	184	196
    2L	67073	67073	+	1	1	1	0	7	4
    2L	67142	67144	+	0	0	3	0	20	20

**Comment by mpmeers** [comment]
I am using 2.24.0--I will download 2.25.0 and give that a try
