### ISSUE TITLE
Long parameter parsing issue for bedtools groupby in v2.25.0

### ISSUE THREAD

**Issue by chapmanb** [arq5x/bedtools2#300]
Aaron and Neil;
The latest bedtools groupby has an issue with parsing out long parameter names for the initial options that have both long and short choices. The short options are all fine, but the long ones fail:
```
[:~] $ bedtools groupby -g 1,2,3 -c 4 -o first -i test.bed
chr1	1	10	0
[:~] $ bedtools groupby -grp 1,2,3 -opCols 4 -ops first -i test.bed
***** ERROR: -opCols parameter requires a value.
[:~] $ bedtools groupby -grp 1,2,3 -c 4 -ops first -i test.bed

***** ERROR: Unrecognized parameter: -grp *****
***** ERROR: Unrecognized parameter: 1,2,3 *****
***** ERROR: Unrecognized parameter: -ops *****
***** ERROR: Unrecognized parameter: first *****
[:~] $ bedtools groupby -g 1,2,3 -c 4 -ops first -i test.bed

***** ERROR: Unrecognized parameter: -ops *****
***** ERROR: Unrecognized parameter: first *****
```
It looks like there is some new magic specifying commandline parameters from the help strings but I don't totally understand how to fix it. Hope this helps.

**Comment by nkindlon** [comment]
Hey Brad, 
    I see you found the problem already. I had changed groupBy to handle columns and operations on them with the same back-end as the map tool uses. I didn't support the backwards compatibility with groupBy's other syntax, so -o and -c work but -ops and -opCols don't, even though groupBy's help still says they do. Sorry about that.

**Comment by nkindlon** [comment]
This bug should be re-opened, the keyListOps and context will need to be changed to fix the problem.

**Comment by chapmanb** [comment]
Neil;
Thanks for looking at this. I think this one is still open, I did close one in bcbio that references this by swapping over to using the short names one. Thanks again for being so on top of it.

**Comment by nkindlon** [comment]
No problem. Sorry it was wrong in the first place.

**Comment by arq5x** [comment]
Thanks for reporting this, Brad!
