### ISSUE TITLE
windowBed will not add reads inside of "slop zone" when using BAM output

### ISSUE THREAD

**Issue by tdanhorn** [arq5x/bedtools2#301]
Basically, windowBed will do the same thing as intersectBed when applied to BAM files (via -abam).  (Actually in testing I got one extra read over intersectBed, but many others I was expecting when the intervals are widened by several kb were missing.)
I have looked at the source code, and in `BedWindow::FindOneOrMoreWindowOverlaps` there are variables set with the desired boundaries (`aFudgeStart`, `aFudgeEnd`), but then they are never used, and `a.start` and `a.end` are passed to `_bedB->anyHits(...)` instead, so I suspect this is the problem.
`BedWindow::FindOneOrMoreWindowOverlaps` is only used for BAM output, so this issue would not arise when intersecting BEDs, which may be why it has persisted over many years.

**Comment by arq5x** [comment]
Fixed in master. Thanks!
