### ISSUE TITLE
Memory blows up when intersecting sorted files with some chromosomes missing

### ISSUE THREAD

**Issue by mjoud** [arq5x/bedtools2#302]
I intersected dbSNP with some interval file (both sorted) using command line ``bedtools intersect -a snp142.txt.gz -b myfile.bed -wa -wb -sorted``. After a while I noticed a steep rise in memory consumption and I soon realized that my intervals accidentally only had ``chr1`` entries represented. Clearly, there's some unhealthy buffering going on.

This is easily reproducible, simply create a bed file with contents ``chr1\t1000\t2000`` and intersect with some other sorted large file. The buffering doesn't start to build up until after passing this last entry so you'll have to wait for a while with a single chr22 entry.

I'm using v2.25.0.

**Comment by arq5x** [comment]
Thanks for reporting. I can reproduce it and we are looking into it.

**Comment by arq5x** [comment]
Thanks for reporting - there was indeed a memory leak that would be typically minor, but extreme in this case. Fixed with commit 93cb0b1b
cc @nkindlon
