### ISSUE TITLE
slop for both A and B bedpe file

### ISSUE THREAD

**Issue by crazyhottommy** [arq5x/bedtools2#309]
Hi,

The current pairtopair function only slops for A bedpe file. Could you please add some support for slopping both A and B?

Moreover, if I want to do pairt_to_pair for multiple bedpe files, how can I do it?
Is there a function like `mulitbedIntersect` function?

Thanks,
Ming

**Comment by arq5x** [comment]
This is the intended behavior, I think adding slop only to A, the driver file, makes the most sense.
