### ISSUE TITLE
bedtools intersect -wao -S gives no results

### ISSUE THREAD

**Issue by atanzer** [arq5x/bedtools2#314]
hi,

the -wao options is not working when requiring different strands. the programs runs fine, but gives no output. same strand or any strand works, though:
bedtools intersect -a fileA.gtf -b fileA.gtf -wao -S

-wo -S works
bedtools intersect -a fileA.gtf -b fileA.gtf -wo -S

thank you!

**Comment by arq5x** [comment]
Could you comment on what version of bedtools you are using and perhaps provide minimal tests files to reproduce this?
