### ISSUE TITLE
coverageBed behaviour change in 2.24

### ISSUE THREAD

**Issue by AndyMenzies** [arq5x/bedtools2#319]
The decision to change the behaviour of coverageBed in 2.24 rather than create a new function is giving us some crippling headaches when trying to upgrade from 2.23.

We have a centralised install of bedtools shared by several hundred people.  Changing the way that tool works is breaking a variety of systems/scripts, or worse still silently corrupt some of them.

Could the original behaviour be reinstated and a new tool be created for the updated functionality?

Cheers

Andy

**Comment by johnmoll** [comment]
Same problem here. For backward compatibility reasons I'd suggest the same: to rollback the coverageBed tool and to create another with the new functionality (e.g. swappedCoverageBed).

**Comment by bernatgel** [comment]
Same problem here. The change in the API wreak havoc in our pipelines. Can we get back the original behaviour somehow?

**Comment by arq5x** [comment]
I am a bit concerned about having two tools with the same functionality, but I see your point. Let me think about how best to accommodate this

**Comment by sndrtj** [comment]
I have been experiencing the same. It caused our pipelines to consume an insane amount of data, since we now generated 1TB bed files.

**Comment by arq5x** [comment]
This will be addressed in the next release.

**Comment by rmzelle** [comment]
Just adding my voice to this. I appreciate all your work on this piece of software, but I wasted several hours today and yesterday figuring out why an old script that uses coverageBed was taking forever and causing my system to run out of space, until I finally rediscovered that the API had changed.

(assuming bedtools aims to use semantic versioning, point releases shouldn't introduce backwards-incompatible API changes: http://semver.org/)

**Comment by keiranmraine** [comment]
@arq5x, did this get resolved in 2.26.0?

**Comment by arq5x** [comment]
It did not, but will be for 2.27.0

**Comment by portah** [comment]
Yeap, and now for those who already fixed scripts, we have to fix them back again... 2.24. -> 2.27 is a long way. Now I more and more appreciate what Common Workflow Language does for us.

**Comment by arq5x** [comment]
I understand your frustrations and aplogize for the inconvenience. This issue with backwards compatibility did not occur to me at the time the change was made. My plan for 2.27.0 is to keep the current functionality in the `coverage` command, but also create a second command (possibly `coverage_old` that behaves the way coverage did prior to 2.24.0. Does this seem reasonable?

**Comment by rmzelle** [comment]
> My plan for 2.27.0 is to keep the current functionality in the coverage command, but also create a second command (possibly coverage_old that behaves the way coverage did prior to 2.24.0. Does this seem reasonable?

IMHO, if you decide to keep the changed API introduced with 2.24, the main issue I would like to see solved is that coverageBed shouldn't fail silently and in such a disruptive manner (consuming much more CPU time and disk space than normal) if used with what were valid pre-2.24 arguments. Couldn't 2.27.0 check whether the argument selection makes sense, and just end on a warning if it doesn't? E.g. I use coverageBed to calculate average coverage in BAM files for regions defined in BED files, which doesn't really make sense the other way around.

**Comment by keiranmraine** [comment]
Did anything at all happen with this in 2.27.0?

**Comment by arq5x** [comment]
Agreed, changing now will be too disruptive and I apologize for the disruption this change caused.
