### ISSUE TITLE
groupby in v2.25 throws error for "freqasc" or "freqdesc" operations

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#321]
BEDTOOLS groupby command lists "freqasc"  and "freqdesc" as permissible column  operations ("-o" flag). 

In verison 2.20, "groupby"  behaves as expected when passing freqasc/freqdesc for the "-o" flag.

However, in version 2.25, "groupby"  throws an error if you pass it freqasc or freqdesc via the "-o" flag.

**Comment by ycl6** [comment]
Hi, I wanna report the same problem. 

bedtools groupby (v2.25.0) reports freqasc/freqdesc is not a valid operation when it is used, whereas v2.24.0 does not have this problem.

**Comment by arq5x** [comment]
This is fixed in master. Sorry for the delay.
