### ISSUE TITLE
map throws unsorted error for no reason

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#323]
The "map" command complains about non-lexicographically sorted input, even though my input is indeed sorted as such.

The same exact input files to Bedtools 2.20  map command completes correctly, as expected, with no error.

**Comment by arq5x** [comment]
Can you provide an example and state the version you are using?

**Comment by map2085** [comment]
$  bedtools  --version
bedtools v2.25.0


The attached files will cause bedtools 2.25.0  to throw the "unsorted" error:

ERROR: Sort order was unspecified, and file m.b.10 is not sorted lexicographically.
       Please re-reun with the -g option for a genome file.
       See documentation for details.


[m.a.txt](https://github.com/arq5x/bedtools2/files/34159/m.a.txt)
[m.b.txt](https://github.com/arq5x/bedtools2/files/34158/m.b.txt)

**Comment by arq5x** [comment]
On my machine, UNIX `sort` says your B file is not sorted lexico'ly:

    sort -c -k1,1 -k2,2n m.b.txt
    sort: m.b.txt:189: disorder: C0067	0	10

**Comment by map2085** [comment]
$ sort  -c  -k1,1  -k2,2n  m.b.txt 
$ 

My machine thinks its fine.  Is there some kind of locale specificity to bedtools?

**Comment by arq5x** [comment]
No, locales are specific to shell/OS.  I would try sorting with LC_ALL=C

    LC_ALL=C sort -c -k1,1 -k2,2n $file

**Comment by map2085** [comment]
Yes.  Setting LC_ALL="C"  fixed the problem.  Now it works fine for 2.25.0.
