### ISSUE TITLE
bedtools map  fails to detect intersection for consecutive identical entries

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#326]
bedtools   --version
bedtools v2.20.1-16-gbc2f97d

bedtools  map -c 3 -o collapse  -a q.1.txt  -b q.2.txt  >  q.3.txt

File q.1.txt   has the following lines of interest:
iraP	0	10
iraP	0	10
 
i.e. identical entries, appearing consecutively (consecutively because the input files are sorted, of course).

File q.2.txt   has the following lines of interest:
iraP	0	10

Both q.1.txt  and q.2.txt   are sorted via sort  -k1,1  -k2,2n   as usual.

The output files q.3.txt   has the following lines of interest:
iraP	0	10	10
iraP	0	10	.

i.e. bedtools FAILS TO MAP an overlapping entry onto the second of a pair of identical entries.

The example files are attached.

Note:  I would try this with bedtools 2.25.0, but as my other "Issue" on GitHub shows, 2.25.0 throws an erroneous "unsorted" error.

[q.1.txt](https://github.com/arq5x/bedtools2/files/34199/q.1.txt)
[q.2.txt](https://github.com/arq5x/bedtools2/files/34201/q.2.txt)
[q.3.txt](https://github.com/arq5x/bedtools2/files/34200/q.3.txt)

**Comment by map2085** [comment]
Setting LC_ALL="C"  fixed the problem.  Now it works fine for 2.25.0.

**Comment by arq5x** [comment]
Great! Locales are a widespread issue in many cases.
