### ISSUE TITLE
bedtools intersect missing error/usage message 

### ISSUE THREAD

**Issue by d-cameron** [arq5x/bedtools2#331]
bedtools intersect no longer (2.25.0) prints a usage message when invoked with no parameters. It instead outputs:
***** ERROR: No input file given. Exiting. *****

This is considerably less useful than the usage message output in 2.19.1 and behaviour should be reverted to a useful error message if no arguments are given.

**Comment by arq5x** [comment]
Agreed. This will be fixed in the next release.

**Comment by arq5x** [comment]
Thanks for reporting, this is now fixed in the repo.
