### ISSUE TITLE
bug: ragged output from intersect of bed3 and bed4

### ISSUE THREAD

**Issue by dwaggott** [arq5x/bedtools2#334]
Output from intersect on a bed3 and a bed4 results in ragged column output see #333

**Comment by arq5x** [comment]
Can you provide example output?

**Comment by dwaggott** [comment]
https://gist.github.com/3aa2565af083765c5323

The test data and command are in #333

**Comment by arq5x** [comment]
Maybe I am missing something, but all 3 lines contain 7 columns. Are you seeing something different? Or maybe I misunderstand what you mean by ragged?

**Comment by dwaggott** [comment]
More than likely me... 

I see 8 columns on the first line. Column 7 is empty.

```
head -n 1 out1.bed | tail -n 1  | tr "\t" "\n" | cat -n
     1  22
     2  18033198
     3  18033199
     4  .
     5  -1
     6  -1
     7
     8  .
```

**Comment by arq5x** [comment]
Ah, I see. Thanks. Will try to patch this up.
