### ISSUE TITLE
Error if missing values in last column

### ISSUE THREAD

**Issue by dwaggott** [arq5x/bedtools2#336]
I get an error if there are missing values in the last column of input. Adding any value rescues the file. Is this expected? I get quite a files with missing data.

[tmp.bed](https://gist.github.com/ff402724ac88f2fb9f0b)
```
bedtools merge -i tmp.bed 
Error: unable to open file or unable to determine types for file tmp.bed
```

**Comment by arq5x** [comment]
Bedtools expects that every record has the same number of columns. The best thing to do would be to preprocess every file to standardize the records.

**Comment by dwaggott** [comment]
Hmm, the files have the same number of columns. The issue comes up if there are empty i.e. `\t\t` values in the last column. Other columns with empty values don't cause an issue.

**Comment by arq5x** [comment]
Good point - will try to patch this up.

**Comment by dwaggott** [comment]
Were you able to reproduce this? It came up again. The solution was to add dummy values to the last column if it was empty. It felt wrong.

**Comment by arq5x** [comment]
Not sure why this was closed, it is still open.

**Comment by thesyntaxinator** [comment]
Bump -- I am having this issue as well. Any word on when it might be fixed?

**Comment by arq5x** [comment]
This is now fixed in master - thanks for reporting and for the patience.

**Comment by dwaggott** [comment]
Thanks!

**Comment by gh-cweiss** [comment]
I am having this occur using bedtools intersect. Was the bug fixed only for bedtools merge?
