### ISSUE TITLE
bedtools map fails for large regions in b file

### ISSUE THREAD

**Issue by mpi-pebert** [arq5x/bedtools2#337]
bedtools v2.20.1

I have a file A with regions of interest (varying region lengths) and a bedGraph file B with a default resolution of 25bp and generated with bigWigToBedGraph; it appears, though, that in the resulting bedGraph, consecutive regions with the same score (always 0 in my case) have been merged to larger regions (larger than 25bp).

Example:
Region of interest in A file:
```bash
chr10	89089030	89089429	ctcf	100	+
```
Region in B file:
```bash
chr10   89000775    89206650    0
```
bedtools map output:
```bash
bedtools map -c 4 -o sum,max -a Afile.bed -b Bfile.bg
chr10	89089030	89089429	ctcf	100	+	.	.
```

Expected output:
```bash
bedtools map -c 4 -o sum,max -a Afile.bed -b Bfile.bg
chr10	89089030	89089429	ctcf	100	+	0	0
```

**Comment by arq5x** [comment]
Could you test this with the latest version and provide example files if the error still persists?

**Comment by mpi-pebert** [comment]
Using bedtools 2.25.0 revealed part of the problem; there is an invalid region in the region of interest file and with 2.25.0 I get a clear error message. However, testing again with two dummy files

Afile.bed
```bash
chr10   89089030    89089429    ctcf    100 +
```
Bfile.bg
```bash
chr10   89000750    89000775    0.2 
chr10   89000775    89206650    0   
chr10   89206650    89206675    0.5 
```
results in the following output for 2.20.1
```bash
bedtools map -c 4 -o sum,max -a Afile.bed -b Bfile.bg
chr10	89089030	89089429	ctcf	100	+	0	2.22507e-308
```
and 2.25.0
```bash
chr10	89089030	89089429	ctcf	100	+	0	2.225073859e-308
```

**Comment by arq5x** [comment]
Thanks much, I just pushed a fix for this.
