### ISSUE TITLE
[feature request] bedtools fasta output in bed format

### ISSUE THREAD

**Issue by DSLituiev** [arq5x/bedtools2#338]
Hi, 
I wonder if it is possible to make `bedtools fasta` to return bed-formatted tab-delimited file _with original columns preserved_. I need to calculate PWM on bedgraph file, so I will need to use weighted sequences, so bed-formatted output will be useful.

**Comment by arq5x** [comment]
This has been added to the repo via the `-bedOut` option. Please note that along with this change, one no longer specifies `-fo` option. Instead, output is always written to stdout.

Example:

    cat t.fa
    >chr1
    aagaggctgagagcatagacagata
    
    cat a.bed
    chr1	10	20

    bedtools getfasta -fi t.fa -bed a.bed -bedOut
    chr1	10	20	gagcatagac
