### ISSUE TITLE
feature request: max distance for closest

### ISSUE THREAD

**Issue by dwaggott** [arq5x/bedtools2#339]
A helpful parameter to `closest` would be max distance. i.e. top `-k` pathogenic variants within 1kb of a candidate index variant.

**Comment by arq5x** [comment]
This introduces some algorithmic complexity that makes it difficult (at least with our existing algorithm) to have decent average case memory usage.  One workaround would be to add _distance_ "slop" to each variant, `intersect` with pathogenic variants, then choose k closest.

**Comment by dwaggott** [comment]
Thanks, that works.
