### ISSUE TITLE
[feature request] Get N closest features

### ISSUE THREAD

**Issue by kpalin** [arq5x/bedtools2#340]
I would have needed three closest features, not just one. Should be trivial to implement as an option to "closest" but detailed specs need to be defined. 

Maybe it should return "all features at N shortest distances from the query".  This returns N or more features but it is very application specific how to choose exactly N.

**Comment by arq5x** [comment]
Have you had a look at the `-k` option?
http://bedtools.readthedocs.org/en/latest/content/tools/closest.html
