### ISSUE TITLE
Inconsistent name for mouse mm10 genome file.

### ISSUE THREAD

**Issue by charles-plessy** [arq5x/bedtools2#341]
Hi Aaron and everybody

Bedtools needs and distributes files indicating the size of chromosomes for some reference genomes.

```
human.hg18.genome
human.hg19.genome
human.hg38.genome
mouse.mm10.genome.txt
mouse.mm8.genome
mouse.mm9.genome
```

In the case of mm10 only, the file has an extra `.txt` in its name, which slightly complicates scripting.  Would it be possible to rename it `mouse.mm10.genome` in the next release ?

Cheers,

-- 
Charles

**Comment by jmarshall** [comment]
This (and a little more) is PR #289.
