### ISSUE TITLE
Segmentation fault with intersectBed

### ISSUE THREAD

**Issue by sdjebali** [arq5x/bedtools2#344]
Dear bedtools developper,

I am using intersectBed 2.25 with the -sorted option. 

My command takes as input two gff.gz files that are sorted (sort -k1,1 -k4,4n -k5,5n) and a genome file, like this:
bedtools intersect -wao -a contiguousAlignments_chr1.gff.gz -b annot_chr1.gff.gz -sorted -g chromosomes_length.txt | gzip > contiguousAlignments_intersected_test2.txt.gz

however it stops at one point (line 253 of the output file) with a segmentation fault and a 1.5M core file is produced. I checked the input files and I do not see what the problem is.

I placed the 3 input files, the truncated output file and the core file in this archive:
http://genome.crg.es/~sdjebali/BugReport.tar.gz

If someone could have a look and explain me what went wrong I would be very grateful!

Best regards,
Sarah

**Comment by smilefreak** [comment]
Hi Sarah,

I was able to reproduce this error in the release version of 2.25. However, the error disintegrates. when using the latest version of the code from github. I recommend that you download and update you bedtools to this version, it seems the developers have fixed the error with subsequent updates.

Cheers,

James.

**Comment by sdjebali** [comment]
Hi James,

thanks a lot for looking into this.

In fact I have posted the problem both on this list and on the bedtools
github and saw only this morning it had been solved as you said. I should
have said something on this list, sorry about that.

Cheers,
Sarah

On Tue, Jan 12, 2016 at 12:54 PM, James Boocock <notifications@github.com>
wrote:

> Hi Sarah,
>
> I was able to reproduce this error in the release version of 2.25.
> However, the error disintegrates. when using the latest version of the code
> from github. I recommend that you download and update you bedtools to this
> version, it seems the developers have fixed the error with subsequent
> updates.
>
> Cheers,
>
> James.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arq5x/bedtools2/issues/344#issuecomment-170888917>.
>



-- 
***********************************************************
Sarah Djebali Quelen - PhD
INRA GenPhySE, ch. de Borderouge
31326 Castanet-Tolosan, France
Tel. +33 5 61 28 51 22
sarah.djebali-quelen at toulouse dot inra dot fr
