### ISSUE TITLE
genomecov flag -pc?

### ISSUE THREAD

**Issue by AndrewUzilov** [arq5x/bedtools2#346]
I was pretty excited to see the `-pc` flag in the docs for v2.25.0:
http://bedtools.readthedocs.org/en/latest/content/tools/genomecov.html

but... it doesn't seem like it exists in the actual command-line tool?
```text
> bedtools genomecov -pc      


*****ERROR: Unrecognized parameter: -pc *****


*****
*****ERROR: Need both a BED (-i) and a genome (-g) file. 
*****

Tool:    bedtools genomecov (aka genomeCoverageBed)
Version: v2.25.0
Summary: Compute the coverage of a feature file among a genome.

Usage: bedtools genomecov [OPTIONS] -i <bed/gff/vcf> -g <genome>
```

I also do not see it in the help message.

What am I doing wrong?

**Comment by smilefreak** [comment]
I was able to reproduce this using the 2.25 release, however, when using the latest version of github the problem went away. The release should be updated to fix this error.

**Comment by arq5x** [comment]
Sorry all, this functionality is in the repo, but not in a formal release yet. The docs are built from the repo, so things are a bit out of sync. I am hoping for a new formal release in the next few weeks, so hopefully this will resolve itself soon. In the meantime, clone from the repo for the `-pc` functionality.
