### ISSUE TITLE
Genomcov -pc feature for coverage command

### ISSUE THREAD

**Issue by s1437643** [arq5x/bedtools2#347]
Would it be possible to incorporate the new paired-end coverage features in genomecov (a86243d9f03fc5b2b4fe5ec97e7d4e5acc403751) into the coverage command? Apologies @portah  @arq5x for creating a separate issue, I wasn't sure if my post in the closed pull request would generate a notification.

**Comment by portah** [comment]
Thank you for interest in this work. I have not consider it yet. I do not use coverage that much. And do not know how to deal with some situations like: one of the read is out of the segment. So if you are willing to describe all uncommon conditions it might help to integrate my code to the coverage subcommand.

**Comment by s1437643** [comment]
Usually what I do to simulate this is to take only properly paired-end reads and collapse them into a single fragment which spans the start coordinate of the left-most read and the end coordinate of the right-most read. From there I then use bedtools coverage using this fragment representation in BED format.

**Comment by arq5x** [comment]
Sorry all, this functionality is in the repo, but not in a formal release yet. The docs are built from the repo, so things are a bit out of sync. I am hoping for a new formal release in the next few weeks, so hopefully this will resolve itself soon. In the meantime, clone from the repo for the `-pc` functionality.
