### ISSUE TITLE
bedtools intersect segfault

### ISSUE THREAD

**Issue by rekado** [arq5x/bedtools2#351]
I'm using the bedtools 2.25.0 release and experience a segfault running 

    bedtools intersect -b gencode.v19.annotation.gff3 -a grosswendt_mirna_hg19viral.bed  -wao > grosswendt_mirna_hg19viral.intersect.bed

We do not get this with version 2.24 on the same files.

Looking at the previously reported bug reports I applied https://github.com/arq5x/bedtools2/commit/788a6b62f2e297afe6a6cbec4b56ddec430257fc.patch to the sources, just in case, but it doesn't help.  I tried to analyse the core file with gdb but there are too many symbols that I cannot make sense of.

The backtrace tells me that it's a problem in `RecordOutputMgr::null`:

~~~
(gdb) bt full
#0  RecordOutputMgr::null(bool, bool) () at RecordOutputMgr.cpp:519
        std::__ioinit = {static _S_refcount = 173, static _S_synced_with_stdio = true}
#1  0x00000000004f3a03 in RecordOutputMgr::printRecord(RecordKeyVector&, RecordKeyVector*) () at RecordOutputMgr.cpp:245
        std::__ioinit = {static _S_refcount = 173, static _S_synced_with_stdio = true}
#2  0x00000000004f3b16 in RecordOutputMgr::printRecord(RecordKeyVector&) () at RecordOutputMgr.cpp:215
        std::__ioinit = {static _S_refcount = 173, static _S_synced_with_stdio = true}
#3  0x000000000044edcc in BedtoolsDriver::subMain(int, char**) () at BedtoolsDriver.cpp:78
        std::__ioinit = {static _S_refcount = 173, static _S_synced_with_stdio = true}
#4  0x00000000004094d0 in main () at src/bedtools.cpp:97
        std::__ioinit = {static _S_refcount = 173, static _S_synced_with_stdio = true}
~~~

Looking at the code I see that `*dummyRecord` starts out as `NULL` and is then set dependent on the record type.  However, if none of the record types match `dummyRecord` stays at `NULL` and yet is still dereferenced:

    dummyRecord->printNull(_outBuf);

I don't think that's okay.  In the default case where `dummyRecord` is still `NULL` bedtools really should abort with an error and not attempt to dereference `dummyRecord`.  It might also help if bedtools printed what kind of record type it could not identify (i.e. the value of `recordType`).  This would make debugging easier, I suppose.

**Comment by arq5x** [comment]
Thanks very much for reporting this bug. Could you share the test files or at a minimum report the number of columns in each file?

**Comment by rekado** [comment]
The bed file can be obtained here: http://dorina.mdc-berlin.de/api/v1.0/download/regulator/hg19/kshv-miR-K12-4-3p|chimera

There are six columns in the bed file.

The gff file can be downloaded here: ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.annotation.gff3.gz

**Comment by arq5x** [comment]
I am unable to replicate the segfault with these files based on the latest Github version. I note that the BED file you have pointed me to is different than what you used in your command above...

**Comment by rekado** [comment]
I'll try to build the latest version from Github then and try to reproduce this.  The BED file is the same (it's just named differently).

**Comment by arq5x** [comment]
Okay, thanks. Nonetheless your comments about the behavior are well taken. Thanks.

**Comment by rekado** [comment]
I can confirm that this doesn't happen at the latest commit (4e1b658 as of this writing).  I have not yet tried to identify exactly what fixed it, though.
