### ISSUE TITLE
bedCoverage and spliced reads 

### ISSUE THREAD

**Issue by Distue** [arq5x/bedtools2#354]
Dear authors and community,

recently I encountered a strange behaviour of bedCoverage which leads to very confusing results and I hope you can address this issue.

bedCoverage provides a function for counting reads (.bam file) in an interval (.bed file). I am using this to count in various specific regions in RNASeq data (parameters -counts for counts only and -s for the  strand-specific setup we have, to mention it is paired-end). 

I encountered strange counts when checking the consistency of the counting. For example in this interval in IGV browser (v2.3.67) there is only one read, however bedCoverage (v2.17 as well as v2.25) reports 6 reads in this interval.

![image](https://cloud.githubusercontent.com/assets/893668/12641239/c5fab8e4-c5ae-11e5-9d5b-3de792aad0c5.png)

The same interval in GenomeBrowse (v.2.1.0) shows one read and 4 spliced alignments, which does not add up to 6, however gave a hint where this counts might come from.

![image](https://cloud.githubusercontent.com/assets/893668/12641251/d4aae864-c5ae-11e5-8d9d-e17ca3934b79.png)

When converting the bam to bed(6) and then extracting the alignments spanning over the interval, the 5 missing reads show up.

`perl -lane 'print join("\t", @F) if $F[0] == 1 && $F[1] < 911879 && $F[2] > 912004' RNASeq.bed `

5 spliced + 1 mapped = 6

Same thing I saw in different scenarios.

**The conclusion:**

bedCoverage counts reads which do not map even close to the interval. The alignment split spans over 200kb in this cases. Therefore intervals with no reads get an artificial signal. The interval between spliced reads is not supposed to be in a fragment as well. 

Is this a bug, a feature or did I overlook some important detail?

Thanks!

**Comment by dpryan79** [comment]
The `-split` option should have taken care of this in earlier versions. However, 2.25.0 seems to produce incorrect results even when `-split` is used. [Here's a relevant post](https://www.biostars.org/p/180587/) on biostars with an example that can be downloaded for testing.

**Comment by arq5x** [comment]
Thanks for reporting - I just pushed a fix for this and will respond on biostars.org as well

**Comment by dpryan79** [comment]
:+1: Thanks!
