### ISSUE TITLE
intersect -loj adding extra empty field to output when -b file has one additional column

### ISSUE THREAD

**Issue by msto** [arq5x/bedtools2#355]
Hi,

I'm encountering a bug where `bedtools intersect -loj` adds an extra empty space to any null features when the `b` file has one and only one column in addition to chrom, start, and end.

Here are two dummy bed files that demonstrate the issue.

    $ cat a.bed
    1       100     200     a1      ax
    1       300     400     a2      ay
    $ cat b.bed
    1       100     200     b1      bx

Intersecting the two files returns the expected output, where the null feature contains five columns. 

    $ bedtools intersect -loj -a a.bed -b b.bed
    1       100     200     a1      ax      1       100     200     b1      bx
    1       300     400     a2      ay      .       -1      -1      .       .

However, removing the fifth column from the `b` file leads to the addition of an extra, blank field after the null feature's "end".

    $ bedtools intersect -loj -a a.bed -b <(cut -f1-4 b.bed)
    1       100     200     a1      ax      1       100     200     b1
    1       300     400     a2      ay      .       -1      -1              .

And when the `b` file has only the chrom, start, and end columns, no trailing field is added.

    $ bedtools intersect -loj -a a.bed -b <(cut -f1-3 b.bed)
    1       100     200     a1      ax      1       100     200
    1       300     400     a2      ay      .       -1      -1
    $ bedtools intersect -loj -a a.bed -b <(cut -f1-3 b.bed) | awk '{print gsub(/\t/,"")}'
    7
    7

The bug also occurs when using multiple `b` files (as well as with multiple null features, and when the null feature isn't the final feature in the file), though it only occurs when the first `b` file is the file with only four columns.

    $ cat a.bed
    1       100     200     a1      ax
    1       300     400     a2      ay
    1       400     500     a3      az
    1       500     600     a4      aq
    $ cat b.bed
    1       100     200     b1      bx
    $ cat c.bed
    1       500     600     c4      cq

    $ bedtools intersect -loj -a a.bed -b b.bed c.bed
    1       100     200     a1      ax      1       1       100     200     b1      bx
    1       300     400     a2      ay      .       -1      -1      .       .
    1       400     500     a3      az      .       -1      -1      .       .
    1       500     600     a4      aq      2       1       500     600     c4      cq
    $ bedtools intersect -loj -a a.bed -b b.bed <(cut -f1-4 c.bed)
    1       100     200     a1      ax      1       1       100     200     b1      bx
    1       300     400     a2      ay      .       -1      -1      .       .
    1       400     500     a3      az      .       -1      -1      .       .
    1       500     600     a4      aq      2       1       500     600     c4
    $ bedtools intersect -loj -a a.bed -b <(cut -f1-4 b.bed) c.bed
    1       100     200     a1      ax      1       1       100     200     b1
    1       300     400     a2      ay      .       -1      -1              .
    1       400     500     a3      az      .       -1      -1              .
    1       500     600     a4      aq      2       1       500     600     c4      cq

I'm using bedtools 2.25.0 on RHEL 6.5. I did go back to some older versions I had installed and was able to replicate the bug in 2.24.0, 2.22.1, and 2.20.1. 

Could you please take a look into this, and let me know if there is any other information I can provide? Thanks!

**Comment by arq5x** [comment]
Thanks for reporting this - I am working on a resolution now.

**Comment by arq5x** [comment]
I just pushed a fix for this in the repository. Thanks again for reporting.!
