### ISSUE TITLE
Reciprocity in intersect in version bedtools-2.25.0

### ISSUE THREAD

**Issue by mbusby** [arq5x/bedtools2#358]
Hi guys,

I'm getting an odd result in bedtools intersect version bedtools-2.25.0.  I expect -f 0.5 -F 0.5 to give the same answer as -f 0.5 -r. This happens in version 2.24 but it doesn't seem to force the -r in version 0.25.  "Use" is how we call the versions at the Broad.

e.g.

4:11pm mbusby@node1749 myDir/ $ use .bedtools-2.24.0                                                                                                                                 Prepending: .bedtools-2.24.0 (ok)
4:12pm mbusby@node1749 myDir/ $ bedtools intersect -a file1.bed -b file2.bed -f 0.5 -r -wa -wb | wc -l
9829
4:12pm mbusby@node1749 myDir/ $ use .bedtools-2.25.0
Prepending: .bedtools-2.25.0 (ok)
4:12pm mbusby@node1749 myDir/ $ bedtools intersect -a file1.bed -b file2.bed -f 0.5 -r -wa -wb | wc -l
10825
4:12pm mbusby@node1749 myDir/ $ bedtools intersect -a file1.bed -b file2.bed -f 0.5 -F 0.5 -wa -wb | wc -l
9829

**Comment by arq5x** [comment]
Hi Michele,

I believe this bug was fixed in this commit (https://github.com/arq5x/bedtools2/commit/78d74e99a81b1f6537c7e2d97592ebe0e25600cd). Unfortunately, I am not yet ready for a new formal release, but if you build from the repo source, I think you should be back in business.

**Comment by mbusby** [comment]
OK, thanks!
