### ISSUE TITLE
intersect -c option leads to failure

### ISSUE THREAD

**Issue by sarah-thibault** [arq5x/bedtools2#362]
hello!

whenever I try to use the intersect -c option bedtools 2.25.0 fails for some unknown reason.  any other flag works and the files work with any other intersect commands.  

bedtools intersect -a file1.bed -b file2.bed -c > file3with#ofhits.bed

thanks for any help or advice!

**Comment by arq5x** [comment]
I am unable to reproduce this. could you provide an example of the files you are using that cause this?

**Comment by arq5x** [comment]
Closing, as unable to reproduce.
