### ISSUE TITLE
IntersectBed error with gff.gz file as input

### ISSUE THREAD

**Issue by sdjebali** [arq5x/bedtools2#363]
Dear all,

This is the same as issue #353 but using bedtools v2.25.0-69-g401c61d since I am still getting the same error after the fix.

When using two gff.gz files as input to intersectBed I get a format error that stops the program before the end.

I am doing this:
~/bin/bedtools2/bin/bedtools intersect -wao -a contiguousAlignments.gff.gz -b annotatedExons.gff.gz | gzip > contiguousAlignments_intersected.txt.gz 2> intersect.err 

and I am getthing this in standard output
Error: line number 18921599 of file contiguousAlignments.gff.gz has 6 fields, but 9 were expected.

However my file contiguousAlignments.gff.gz is well formatted:
 zcat contiguousAlignments.gff.gz | awk '{n=split($0,a,"\t"); print n}' | sort | uniq -c
18921671 9

Could you please let me know if it is possible to fix this problem or if I should rather use bed files as input?

Thanks,

**Comment by vagarwal87** [comment]
I'm bumping into the exact same bug. Please let me know if any fix is planned!

**Comment by arq5x** [comment]
I reran this with your test data using the latest version in the repository `v2.25.0-114-g780faf7-dirty` and I am still unable to recreate this error:

    bedtools --version
    bedtools v2.25.0-114-g780faf7-dirty
    bedtools intersect -wao -a contiguousAlignments.gff.gz -b annotatedExons.gff.gz > /dev/null

Could you please test this again with the version above?

**Comment by sdjebali** [comment]
Dear Aaaron,

thanks for looking into this again.

With the current version v2.25.0-116-ge88e919 the problem is indeed solved.

Will this fix be incorporated in the next release then?

Best regards,
Sarah

**Comment by arq5x** [comment]
Great news. Yes, this will indeed be in the 2.26.0 release.

**Comment by chrarnold** [comment]
We today encountered this issue also but we already use 2.26.0. Is it possible that the bug is still present?
