### ISSUE TITLE
getfasta: removing -fo breaks backwards compatibility

### ISSUE THREAD

**Issue by kwkroll32** [arq5x/bedtools2#365]
Removing -fo from getfasta breaks some existing software written for older versions of bedtools. I haven't seen the motivation behind this change, but I would prefer to see -fo become optional and print to STDOUT if it's missing. I'm currently using version v2.25.0-70-g577fecf. 

Also, this change is not clearly documented on readthedocs yet. The [changelog](http://bedtools.readthedocs.org/en/latest/content/history.html) doesn't mention it, and the [getfasta documentation](http://bedtools.readthedocs.org/en/latest/content/tools/getfasta.html) still mentions the -fo option.

**Comment by arq5x** [comment]
Agreed - I will correct this before the next formal release.

**Comment by arq5x** [comment]
This has been fixed.
