### ISSUE TITLE
Segmentation fault using -split

### ISSUE THREAD

**Issue by gagnonju** [arq5x/bedtools2#366]
test data:

test.bed:
`1       34677   34866   IP_080139.1|FAM138A     0       -       34677   34866  0
        1       189     0`

test.vcf:
`##fileformat=VCFv4.0`
`1       10019   rs775809821     TA      T       .       .       RS=775809821;RSPOS=10020;dbSNPBuildID=144;SSR=0;SAO=0;VP=0x050000020005000002000200;GENEINFO=DDX11L1:100287102;WGT=1;VC=DIV;R5;ASP`

Bug was introduced between 2.23.0 and 2.24.0

`$ bedtools2-2.23.0/bin/bedtools intersect -loj -split -sorted -nobuf -a test.bed -b test.vcf
1       34677   34866   IP_080139.1|FAM138A     0       -       34677   34866  0
        1       189     0       .       -1      .       .       .       -1     .
        .`
`$ bedtools2-2.24.0/bin/bedtools intersect -loj -split -sorted -nobuf -a test.bed -b test.vcf
Segmentation fault (core dumped)`
`$ bedtools2-2.24.0/bin/bedtools intersect -loj -sorted -nobuf -a test.bed -b test.vcf
1       34677   34866   IP_080139.1|FAM138A     0       -       34677   34866  0
        1       189     0       .       -1      .       .       .       .      .
        .`

**Comment by arq5x** [comment]
Currently, bedtools expects a comma at the end of the list of block starts and lengths (columns 11 and 12). If you can add that, it will work.  I am working on a fix to not require this.

**Comment by arq5x** [comment]
I just pushed a fix for this. Sorry for the trouble and thanks for reporting it.
