### ISSUE TITLE
stdev is not a valid operation in bedtools groupby v2.25.0

### ISSUE THREAD

**Issue by gkudla** [arq5x/bedtools2#367]
Dear bedtools developers,,

groupBy v2.25.0 does not seem to recognize "stdev" as a valid operation. When I run:
$ cat infile | groupBy -g 1 -c 2 -o stdev
I get the following error:
***** ERROR: stdev is not a valid operation.

Other operations, such as "mean", are still recognized. I don't get this error with bedtools v2.23.0.

all the best,
Greg

**Comment by arq5x** [comment]
Thanks for reporting this. I just pushed a fix to the repository. If you clone and recompile, you should be good to go.

**Comment by gkudla** [comment]
thanks for dealing with this so quickly!

Greg

**Comment by jmarshall** [comment]
If I understand the code (and if _KeyListOpsMethods.cpp_ is the relevant code), I think this will produce the square of the stddev rather than the stddev.  (I have a patch to fix this and a few other things that I will try and dust off as a PR tonight.)

**Comment by arq5x** [comment]
Ah - could be - a developer that left the lab wrote that and I am not sure if he tested it. I can fix and put in formal tests. Thanks John!

**Comment by arq5x** [comment]
If you have already cloned, you will want to clone again, as John just pushed a key fix for the stdev function.
