### ISSUE TITLE
Shuffle hangs if record entry exceeds chromosome length.

### ISSUE THREAD

**Issue by PanosFirmpas** [arq5x/bedtools2#377]
Hi, 

The title says it all I guess:

the offending record :
Sc0001815	0	1730

The chromosome size: 
Sc0001815	1729

When encountering the bad record, bedtools v2.25.0 just hangs, 
an error or a warning would be great !

**Comment by arq5x** [comment]
Agreed, I will add a fix to this soon.

**Comment by arq5x** [comment]
Fixed in master
