### ISSUE TITLE
shuffleBed with -incl does not take interval length into account

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#381]
Using shufflebed with the -incl option leads to unexpected behavior, and after checking the source code it appears that it selects a random interval within -incl without taking the length of the intervals into account.

Simple scenario: shuffle a bed within a set of regions comprising 9 regions of 1000 bp and 1 region of 100000 bp leads to an even distribution between all the intervals, when it could reasonably be expected that the large region would receive more intervals from the shuffled bed.

**Comment by arq5x** [comment]
Good point, though it is actually a bit more complicated than this. For example, weighting should more realistically by done first by the total length of inclusion intervals for a given chrom and then by larger intervals within the chrom. Agree?

**Comment by michael-imbeault** [comment]
Only if you want to keep the same distribution chromosome-wise.

For now I'm building an intermediary bedfile chopping each interval of -incl into smaller parts which simulates the desired behavior.

**Comment by arq5x** [comment]
Great. Yes, I see at least two different weighting modes for -incl

**Comment by arq5x** [comment]
Thinking about this some more, simply weighting by length will bias towards chromosomes with a greater total ``-incl`` length anyway. @zeeev just submitted a PR (https://github.com/arq5x/bedtools2/pull/386) with a nice weighted sampling approach that, based on my tests, works the way you'd want:

    cat a.bed
    chr1	0	10

    cat i.bed
    chr1	0	20	A
    chr1	50	70	B
    chr2	50	60	C
    chr3	80	90	D

    cat g.txt 
    chr1	100

So, we would expect intervals to be shuffled to within A 33% of the time, and chr1 67% of the time. Let us see:

    for i in {1..30000}; 
    do; 
        bedtools shuffle -i a.bed -incl i.bed -g g.txt \
        | bedtools intersect -a - -b i.bed -wa -wb \
        | cut -f 7; 
    done 
    | sort | uniq -c
    
    9828 A
    9874 B
    5295 C
    5003 D
