### ISSUE TITLE
complement treats BED input file as GFF or VCF

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#385]
`bedtools  complement  -g genes.sizes   -i genes.bed  >  out.bed`

The output is wrong.

Many of the output entries have start = 1, when it clearly should have start = 0.  (e.g.  "ECK120008921" in out.bed)   This leads me to believe that the output start coordinate is 1-based for some of the entries.  Yet other entries start at 0.

For those sam entries, the end coordinate is 1-base too early  (check "ECK120008921" in out.bed here as well).  This also leads me to believe that some input entries are treated with 1-based start, when in fact i have input a bed file.

It seems that bedtools is treating my input BED file as a GFF or VCF file instead as a BED file.

`bedtools  --version`
`bedtools v2.25.0`

[genes.bed.txt](https://github.com/arq5x/bedtools2/files/192155/genes.bed.txt)
[genes.sizes.txt](https://github.com/arq5x/bedtools2/files/192156/genes.sizes.txt)
[out.bed.txt](https://github.com/arq5x/bedtools2/files/192157/out.bed.txt)

**Comment by arq5x** [comment]
This bug was previously reported and is fixed in the repository. You can clone the repo and compile that source code and you should be GTG.
