### ISSUE TITLE
Intersection of gzipped beds fails after chromosome 1

### ISSUE THREAD

**Issue by mehrankr** [arq5x/bedtools2#388]
Hello,

Thanks a lot for the great software and features.

I am using bedtools 2.23.0 to intersect gzipped bed files and I use:
bedtools intersect -loj -a NarrowPeakFile -b Bed6File

After chromosome 1, I get null for intersections of all the other chromosomes. However when I unzip the files and run the same command, it works perfectly fine:

zcat NarrowPeakFile > bed.a
zcat Bed6File > bed.b
bedtools intersect -loj -a bed.a -b bed.b

Thanks a lot
Mehran

The files that I use are provided below:
[Bed6File](https://github.com/arq5x/bedtools2/files/200181/k100.Unconverted.bed.gz)
[NarrowPeakFile](https://github.com/arq5x/bedtools2/files/200182/MichaelSnyder-Stanford_GM12878_NFE2_No-Treatment_No-Control_ENCSR000DZY_peaks.narrowPeak.gz)

**Comment by arq5x** [comment]
Interesting. I can reproduce this with the .gz files you sent. However, if I uncompress them, then re-gzip them on my laptop (OS X El Capitan), the problem disappears. What version of gzip did you use to create the files you posted?

**Comment by mehrankr** [comment]
I used gzip 1.3.12
However the Bed6File is gzipped with the python module.

**Comment by arq5x** [comment]
I think that is the issue. Python must be creating a ZLIB signature that bedtools doesn't recognize.
