### ISSUE TITLE
intersect -loj: segmentation fault on gff's with non-overlapping regions

### ISSUE THREAD

**Issue by har-wradim** [arq5x/bedtools2#390]
This seems to be a serious bug of `intersect` when used in the left-outer-join mode. I cannot tell in which cases this issue doesn't appear, but it does appear in the following minimal example:

	$ bedtools --version
	bedtools v2.25.0
	$ cat test.gff
	##gff-version 3
	chrom	source	feature	10	20	.	.	.	attribute
	chrom	source	feature	30	40	.	.	.	attribute
	$ cat ref.gff
	##gff-version 3
	chrom	source	feature	30	40	.	.	.	attribute
	$ bedtools intersect -a test.gff -b ref.gff -loj
	Segmentation fault (core dumped)
	$ bedtools intersect -a test.gff -b ref.gff
	chrom	source	feature	30	40	.	.	.	attribute

**Comment by arq5x** [comment]
Yep, this is fixed in the repository version. Sorry, I just haven't been able to wrap up the last few remaining bugs to address before a new formal release. It is coming though!

**Comment by har-wradim** [comment]
Great!
