### ISSUE TITLE
bedtoos intersect ignores -e switch

### ISSUE THREAD

**Issue by ppapasaikas** [arq5x/bedtools2#392]
Noticed when using bed file as file A, BAM file as file B (bedtools v2.25, of course):
Using -f float -F float -e, ignores the -e switch and does not OR the -f , -F thresholds.
Example call to reproduce:
bedtools intersect -c -F 0.5 -f 0.0001 -e -split -sorted -a sortedSegments.bed -b sortedAlignment.bam 
I can post links of the bed and bam files if need be...
Cheers

**Comment by arq5x** [comment]
This has been fixed in the repository version.Can you clone and rerun?

**Comment by ppapasaikas** [comment]
Awesome. Cloned, tested and confirmed fix. Many thanks for all the great work.

**Comment by arq5x** [comment]
Great, thanks.
