### ISSUE TITLE
fastest way to get coverage=0 regions from bam file

### ISSUE THREAD

**Issue by avilella** [arq5x/bedtools2#393]
Currently using (in perl) the bedtools2 command below. Any ideas if there is a faster way? Multithreaded?

```
$cmd = "bedtools2 genomecov -ibam $inputfile -bga | grep -w " . q{ '0$' } . " > $outfile";
```

**Comment by arq5x** [comment]
It could be faster by making genomecov a one pass algorithm and possibly a bit of speedup by using htslib for reading BAMs, but both will require substantial refactoring. In other words, there is nothing that is simple.

**Comment by avilella** [comment]
Thanks. I will run it as it is right now. Feel free to close this ticket
FTM.
