### ISSUE TITLE
bedtools slop permits '-b', '-l', and '-r' to all be specified, ignoring '-b'

### ISSUE THREAD

**Issue by cviner** [arq5x/bedtools2#394]
`bedtools slop` allows `-b`, `-l`, and `-r` to all be specified, resulting in `-b` being ignored, and the values from `-l` and `-r` used instead.

Given that `-b` is intended to be mutually exclusive with `-l` and `-r`, it would be better if these were defined as such and that the use of all three result in an error.

**Comment by arq5x** [comment]
Good call - I will add a check for this.

**Comment by cviner** [comment]
Thanks!

**Comment by arq5x** [comment]
added in master (3 years later) :(
