### ISSUE TITLE
unioinBedGraphs throwing out data for clearly overlapping regions

### ISSUE THREAD

**Issue by ashleywoodfin** [arq5x/bedtools2#395]
I am using unionBedGraphs to select regions of interest out of a larger coverage begraph file that I made with bedtools genomecov, and I am finding that unionBedGraphs is not returning the all the regions consistently. I have also checked and these files are properly sorted.

Here is an example of one of the regions that I would like to select out of the bedtools genomecov output after using unionBedGraphs by selecting column 4==1.
```shell
grep chr15 bac.bg
chr15 28876844 29062518 1
```

There are 310 regions that clearly overlap in my genomeCoverage bedgraph (as determined by intersectBed) including

```
[beginning of overlapping regions]
chr15   28875735        28877027        1
chr15   28877027        28877606        0
chr15   28877606        28877643        1
…
chr15   29059437        29060834        1
chr15   29060834        29062050        0
chr15   29062050        29062554        1
[end of overlapping regions]
```

However, if I run the following commands, I get the following:
```shell
# this awk command should grab all of chr15 that is one of my regions of interest with column 4 
# equal to 1 as a flag
unionBedGraphs -i bac.bg gw_input_rep1.cov.bg | awk -F'\t' '$1=="chr15" && $4==1'
# no output
```

```shell
# however the region is now found if we only give in this case our one region on chr15 to 
# unionBedGraphs
unionBedGraphs -i <(grep -w "^chr15" bac.bg) gw_input_rep1.cov.bg | awk -F'\t' '$1=="chr15" && $4==1'
chr15	28876844	28877027	1	1
chr15	28877027	28877606	1	0
chr15	28877606	28877643	1	1
chr15	28877643	28877918	1	2
...
# we find it
````

```shell
# but if we only give unionBedGraphs chr15 from our input, we can again not find it
unionBedGraphs -i bac.bg <(grep -w "^chr15" gw_input_rep1.cov.bg) | awk -F'\t' '$1=="chr15" && $4==1'
# no output
```

If grep the beginning of this region plus the next line out of the unionBedGraph output without requiring column 4 be equal to 1, the entire region is magically gone in the first file that should be 1.
```shell
# recall this region this example region is chr15 28876844 29062518
unionBedGraphs -i bac.bg gw_input_rep1.cov.bg | grep chr15 $TMP/all.intersect | grep -A1 28876844
chr15	28876403	28876844	0	1
chr15	29062518	29062633	0	0
# the entire region deleted from the bac.bg that should be 1
```

Many thanks

**Comment by arq5x** [comment]
Thank you for the very detailed description of the problem. Could you provide two bedgraph files in which you see this problem?

**Comment by ashleywoodfin** [comment]
When again looking over the data bac file, I found that there are in fact two regions that actually overlap, and I know that this is a prerequisite of unionBedGraphs. Is there way to make this command fail if it does not meet this prerequisite rather then returning a partially complete file. Because while my overlap was in only one region out of my 80 total, it still returned most of the data downstream with some missing as described above.

Many thanks

**Comment by arq5x** [comment]
Could you show an example of what you mean? If they were generated by genomecov that shouldn't happen, though.  Correct? I can probably add a check for this in `ubg`

**Comment by ashleywoodfin** [comment]
Actually only the gw_input was created with genomecov. The bac were
designed regions for the experiment and we often design bac regions to
overlap.
