### ISSUE TITLE
interpreter issue with vcfsort.sh

### ISSUE THREAD

**Issue by avilella** [arq5x/bedtools2#397]
I get this interpreter issue when building an app with bedtools2 embedded in it:

```
./bedtools2/scripts/vcfsort.sh: line 6: syntax error near unexpected token `('
 ./bedtools2/scripts/vcfsort.sh: line 6: `if LC_ALL=C (zless $1 | grep ^#; zless $1 | grep -v ^# | sort -k1,1V -k2,2n);'
WARNING:root:./bedtools2/scripts/vcfsort.sh contained syntax errors, see above for details
```

Any ideas?

**Comment by arq5x** [comment]
I apologize, but the vcfsort.sh script really shouldn't even be in the repo. That is a mistake on my part as it isn't properly tested. I would instead recommend the really nice new gsort program from @brentp : https://github.com/brentp/gsort

**Comment by avilella** [comment]
Great, thanks. I'll simply delete the copy from my git clone then.

A.
