### ISSUE TITLE
-pc

### ISSUE THREAD

**Issue by ssshell** [arq5x/bedtools2#398]
I would like to use the –pc option with bedtools genomecov and I understand that while it is not in the release version, I should be able to use it by cloning the repository. I'm still getting an error message, perhaps because I'm not cloning the repository correctly. I cloned it by entering this into the command line:

git clone https://github.com/arq5x/bedtools2.git

And then I tried this command:

bedtools genomecov -d -pc -scale 1.25 -ibam noHP_1_expr_sorted.bam -g NC_008596.chrom.sizes > noHP_1_expr_sorted.coverage

If anyone can tell me what I'm doing wrong I would greatly appreciate it.

**Comment by portah** [comment]
Have you compiled the repository? What actual error do you get?

PS. you can try CWL, https://github.com/common-workflow-language/workflows/blob/master/tools/bedtools-genomecov.cwl - I wrapped the latest version there

**Comment by ssshell** [comment]
Ah! Not only had I not compiled the repository (I�m a newbie at computational stuff), but I hadn�t correctly deleted the old version of bedtools that I had previously installed. Now I�ve got the repository version up and running the �pc option without any complaints. Thanks!
--
Scarlet S. Shell, PhD
Assistant Professor
Department of Biology and Biotechnology
Worcester Polytechnic Institute
Life Sciences and Bioengineering Center
60 Prescott Street
Room 4034
Worcester, MA 01605
508-831-5917 (office)
858-405-3650 (cell)
