### ISSUE TITLE
bedtools complement outputs invalid bed file when input covers entire chromosome

### ISSUE THREAD

**Issue by dvera** [arq5x/bedtools2#401]
bedtools complement outputs a bed file with coordinates 0 0 when the input covers an entire chromosome. Perhaps nothing should be printed in that case so the files are browser-compliant?

echo -e 'chr1\t0\t249250621' > test.bed
bedtools complement -i test.bed -g hg19.chrom.sizes
chr1	0	0
chr10	1	135534746
chr11	0	135006516
chr12	0	133851895
chr13	0	115169878
chr14	0	107349540
chr15	0	102531392
chr16	0	90354753
chr17	0	81195210
chr18	0	78077248
chr19	0	59128983
chr2	0	243199373
chr20	0	63025520
chr21	0	48129895
chr22	0	51304566
chr3	0	198022430
chr4	0	191154276
chr5	0	180915260
chr6	0	171115067
chr7	0	159138663
chr8	0	146364022
chr9	0	141213431
chrM	0	16571
chrX	0	155270560
chrY	0	59373566

**Comment by dvera** [comment]
Also just realized chr10 has a start of 1 instead of 0.

**Comment by arq5x** [comment]
I think this is resolved in the latest version of the repository. Are you using the formal 2.25.0 release?

**Comment by dvera** [comment]
Looks resolved in latest commit. Sorry about that.

**Comment by arq5x** [comment]
No apologies necessary - I need to put out a new release!
