### ISSUE TITLE
intersectBed reports neighboring bases

### ISSUE THREAD

**Issue by husensofteng** [arq5x/bedtools2#405]
Unexpected overlap is reported in intersecting neighboring SNPs, as in the following example:
cat t1:
chr1    3       3       i1

cat t2:
chr1    4       7       i2
chr1    4       4       i3

bedtools-2.25.0/bin/intersectBed -wo -a t1 -b t2
chr1    3       3       i1      chr1    4       4       i3      0

While it shouldn't have reported any overlap. However when the coordinates are given as chr1:3-4, it works as expected.
I understand this is not a bug but I think it is a weird behaviour. Reporting a message to notify the user about the 0-based indexing might be an option.

**Comment by arq5x** [comment]
This is because BED start==end is interpreted as an insertion between the two bases.
