### ISSUE TITLE
bedtools coverage -d -sorted not working properly 

### ISSUE THREAD

**Issue by kunzej** [arq5x/bedtools2#407]
Hi,
combining the -d and -sorted option in the coverage module does not finish the job.

Extending the coverage -d example from:

*$ cat a.bed*
*chr1  0  10*

to:
*$ cat a.bed*
*chr1	0	10*
*chr1	15	20*
*chr1	21	25*

and then run **bedtools coverage -sorted -d -a a.bed -b b.bed** results in:

*chr1	0	10	1	1*
*chr1	0	10	2	1*
*chr1	0	10	3	1*
*chr1	0	10	4	2*
*chr1	0	10	5	3*
*chr1	0	10	6	3*
*chr1	0	10	7	3*
*chr1	0	10	8	3*
*chr1	0	10	9	1*
*chr1	0	10	10	0*
*chr1	15	20	1	0*
*chr1	15	20	2	0*
*chr1	15	20	3	0*
*chr1	15	20	4	0*
*chr1	15	20	5	0*

So there are no entries for the third line of a.bed. This doesn't change by adding more lines to a.bed.
The result for  **bedtools coverage -d -a a.bed -b b.bed** is complete as expected:

*chr1	0	10	1	1*
*chr1	0	10	2	1*
*chr1	0	10	3	1*
*chr1	0	10	4	2*
*chr1	0	10	5	3*
*chr1	0	10	6	3*
*chr1	0	10	7	3*
*chr1	0	10	8	3*
*chr1	0	10	9	1*
*chr1	0	10	10	0*
*chr1	15	20	1	0*
*chr1	15	20	2	0*
*chr1	15	20	3	0*
*chr1	15	20	4	0*
*chr1	15	20	5	0*
*chr1	21	25	1	0*
*chr1	21	25	2	0*
*chr1	21	25	3	0*
*chr1	21	25	4	0*

Is this a known issue and are there easy workarounds?
Adding a line to b.bed covering the last possible base to avoid this problem is rather unhandy with large bam files.

Thanks for your help :-)

**Comment by arq5x** [comment]
If you switch to version 2.25 (or preferably the version in the repository) things will work fine. Please note that in this version, A and B have been flipped (see the docs):

```
cat a.bed
chr1	0	10
chr1	15	20
chr1	21	25
cat b.bed
chr1	3	15
bedtools coverage -d -a a.bed -b b.bed -sorted
chr1	0	10	1	0
chr1	0	10	2	0
chr1	0	10	3	0
chr1	0	10	4	1
chr1	0	10	5	1
chr1	0	10	6	1
chr1	0	10	7	1
chr1	0	10	8	1
chr1	0	10	9	1
chr1	0	10	10	1
chr1	15	20	1	0
chr1	15	20	2	0
chr1	15	20	3	0
chr1	15	20	4	0
chr1	15	20	5	0
```

**Comment by kunzej** [comment]
I would love to agree with your, but I'm already working with version 2.25. 
In your example the "error" is still present, as for position 21 - 25 there is no output...

Running the command without -sorted as in **bedtools coverage -d -a a.bed -b b.bed** returns the correct result:

*chr1	0	10	1	0*
*chr1	0	10	2	0*
*chr1	0	10	3	0*
*chr1	0	10	4	1*
*chr1	0	10	5	1*
*chr1	0	10	6	1*
*chr1	0	10	7	1*
*chr1	0	10	8	1*
*chr1	0	10	9	1*
*chr1	0	10	10	1*
*chr1	15	20	3	0*
*chr1	15	20	4	0*
*chr1	15	20	5	0*
**chr1	21	25	1	0**
**chr1	21	25	2	0**
**chr1	21	25	3	0**
**chr1	21	25	4	0**

**Comment by arq5x** [comment]
Oops, I see. It works without `-sorted` but not with. Will post a fix soon.

**Comment by kunzej** [comment]
Thanks :+1:

**Comment by arq5x** [comment]
This should be fixed in master now. Thanks for reporting!
