### ISSUE TITLE
bedtools closest segmentation fault (core dumped)

### ISSUE THREAD

**Issue by c-guzman** [arq5x/bedtools2#408]
I am getting this error, when in the past it hadn't occurred. It works for a bit (2.1MB), then completely stops working.
It isn't likely a hardware issue, 32 cores + 128 RAM.

Command used:
`bedtools closest -D a -io -id -sorted -a genes_tss.txt -b MNase_peaks_sorted.txt > pos1.nucleosome.txt`

Error:
`Segmentation fault (core dumped)`

File A:
```
chr1	69091	69091	OR4F5	0	+
chr1	70008	70008	OR4F5	0	+
chr1	367640	367640	OR4F29	0	+
chr1	368634	368634	OR4F29	0	+
chr1	818043	818043	AL645608.2	0	+
```

File B:
```
chr1	10081	10221	peak_749336	10151	.	12.0	57.1091790637
chr1	10191	10331	peak_749337	10261	.	8.0	57.9759165219
chr1	10451	10591	peak_749338	10521	.	136.0	49.834445251
chr1	12921	13061	peak_749339	12991	.	56.0	62.5663582153
chr1	13031	13171	peak_749340	13101	.	132.0	47.7438751249
```

Any advice?

**Comment by arq5x** [comment]
I am unable to reproduce this with the small example you provided with version 2.25.0.  What version are you using can you reproduce the error with the example you provide here?

**Comment by c-guzman** [comment]
I am using version 2.25.0. I cannot reproduce the problem with this sample. I can reproduce it with my files, but they are larger (1.1GB), so I didn't think of an effective way to put them up.

**Comment by arq5x** [comment]
There have been several fixes subsequent to 2.25 that are in the repository. Could you try clone the repo and re-testing?

**Comment by vpbrendel** [comment]
Here is a small example that fails in v2.25.0:
scaffold_1      101     200     .       0       +       101     200     0
scaffold_1      301     400     .       0       -       301     400     0

[]bedtools closest -a test.bed -b test.bed -s -io 
Segmentation fault (core dumped)

Change -s to -S, output is ok.  Similarly, change the second entry to + strand, then -S will work and -s will core dump.

My conclusion: There is something in the code that does not handle the case when only one item is present and thus no nearest neighbor can be found.

**Comment by brentp** [comment]
@vpbrendel your example works for me on master.

**Comment by vpbrendel** [comment]
Indeed.  I just confirmed that as well.

Volker


On 6/16/2016 10:48 PM, Brent Pedersen - Bioinformatics wrote:
>
> @vpbrendel <https://github.com/vpbrendel> your example works for me on 
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/arq5x/bedtools2/issues/408#issuecomment-226667729>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFKLMHLfnwupon9tNDfhgGkQwpZumTDBks5qMgrpgaJpZM4IlpMo>.
>

-- 
Volker Brendel
Professor of Biology and Computer Science
Indiana University
Department of Biology & School of Informatics and Computing
212 South Hawthorne Drive
Simon Hall 205C
Bloomington, IN 47405

Tel.: (812) 855-7074
http://brendelgroup.org/

**Comment by vpbrendel** [comment]
[]bedtools2/bin/bedtools closest -a test.bed -b test.bed -S -io -D ref
scaffold_1	101	200	.	0	+	101	200	0	scaffold_1	301	400	.	0	-	301	400	0	102
scaffold_1	301	400	.	0	-	301	400	0	scaffold_1	101	200	.	0	+	101	200	0	-102

where bedtools2 was cloned from the current repository (later than version 2.25).
Thus, the 2.25 distribution should probably be replaced.
Thanks!

**Comment by Paul-Soloway** [comment]
I had this problem too, getting this error when using bedtools closest:
Segmentation fault (core dumped)
One bed file had rows from ChrX, ChrY and ChrM; whereas the other didn't.  When I removed the rows for those Chr, the problem went away.

**Comment by nkindlon** [comment]
Hi Paul, 
    Can you please some small example files, the bedtools version you ran, and the command you used? I'll take a look.

**Comment by Paul-Soloway** [comment]
I'm running v2.25.0.  
Here is the command:
bedtools closest -s -D ref -t first -io -id -a bed1.bed -b bed2.bed > bed3.bed
Small example files do not replicate the original error, which I don't understand at all; but eliminating the ChrX, ChrY and ChrM records from the original large bed file did.

**Comment by nkindlon** [comment]
I wasn't able to reproduce this with randomly generated data files for either v2.25 or v2.26. If you upgrade to 2.26 and still see this problem, please e-mail your data files (if shareable) to neil.kindlon@jax.org. Thanks.

**Comment by azdaly** [comment]
Quick heads up - I got this same error running v2.25 on two ~20,000 line bed files, and the problem went away when I updated to v2.29.2.

**Comment by arq5x** [comment]
Thank you for reporting.
