### ISSUE TITLE
merge does not merge book-ended features

### ISSUE THREAD

**Issue by rebki** [arq5x/bedtools2#412]
As opposed to the documentation, my book-ended features are not merged without any error using bedtools v2.25.0.

For example using following file

```
$ cat ~/merge_test.bed
chr2L	7529	8116	FBgn0031208:1	.	+
chr2L	8117	9484	intron_FBgn0031208:1_FBgn0031208:2	.	+
```

I get

```
$ bedtools merge -s -i ~/merge_test.short.bed 
chr2L	7529	8116	+
chr2L	8117	9484	+
```

although it should be

```
chr2L	7529	9484	+
```

Also, as noted already [here](https://github.com/arq5x/bedtools2/issues/310), the strand is reported without using -c and -o.

**Comment by arq5x** [comment]
Note that since BED is zero-based, half-open, those intervals are not book-ended.
These are:

    $ cat ~/merge_test.bed
    chr2L   7529    8116    FBgn0031208:1   .   +
    chr2L   8116    9484    intron_FBgn0031208:1_FBgn0031208:2  .   +

**Comment by rebki** [comment]
That explains a lot of course. Thanks!
