### ISSUE TITLE
genomecov -pc option

### ISSUE THREAD

**Issue by lyy005** [arq5x/bedtools2#413]
Hi Aaron 
I tried to use the -pc option to calculate the coverage for paired end reads. The command I use is: 
bedtools genomecov -d -pc -ibam test.bam -g ref.fas > test.bedtools.out 

But I got an error information: 
*****ERROR: Unrecognized parameter: -pc *****

I wonder is the -pc flag not available anymore? I'm using Bedtools v2.25.0

Thank you

YY

**Comment by portah** [comment]
Hi,
Thank you for using bedtools.
I believe It is included in v2.26.0

**Comment by arq5x** [comment]
yep it is in 2.26.0
