### ISSUE TITLE
bedtools coverage -split not working with bam files with N Cigar.

### ISSUE THREAD

**Issue by xiuchengquek** [arq5x/bedtools2#414]
HI there, 

Thank you for your excellent work on bedtools =)

I noticed `bedtools coverage -split  -d` is not working for alignments with N Cigar string.
However, it works when I convert my bam to bed and use bedtools coverage on the bed file.

I have included a small minimal working example below in the following [gist](https://gist.github.com/xiuchengquek/df5c54c25948eb6ea4559326e25cb911)

Please refer to run_example.sh for the workflow
Thanks again!
Cheers,
Quek

**Comment by arq5x** [comment]
What version are you using? There were bug fixes applied to the coverage tool related to this over the last few months. Could you test with the version in the github repository by cloning the repo and compiling from source?

**Comment by arq5x** [comment]
Closing.
