### ISSUE TITLE
bedtools shift returns incorrectly shifted bases

### ISSUE THREAD

**Issue by hryknkgw** [arq5x/bedtools2#415]
% cat b.bed 
    chr1	66999638	67216822	NM_032291	0	+
    chr1	92145899	92351836	NR_036634	0	-

    % cat huge.genome 
    chr1	249250621

    % bedtools shift -i b.bed -s 1000 -g huge.genome
    chr1	67000640	67217824	NM_032291	0	+
    chr1	92146896	92352840	NR_036634	0	-

All of shifted start and end positions are incorrect in this example.

This symptom occur shifting a large genome bed file.

**Comment by clintval** [comment]
On v2.26.0 I am still encountering this issue on the same sized `.genome` file. Can you reproduce?

```
$ cat test.bed

chr1	249250600	249250601	test	0	+
chr1	249250603	249250604	test	0	-
```
```
$ head -n2 hg19.genome 

chrom	size
chr1	249250621
```
```
$ bedtools shift -i test.bed -s 1 -g human_g1k_v37.genome 

chr1	249250592	249250608	test	0	+
chr1	249250608	249250608	test	0	-
```

**Comment by hryknkgw** [comment]
Yes I can reproduce.
Because fix for issue #415 were merged as commit 7384628, but it's not released yet.
I think v2.26.0 is older than commit 7384628 isn't it?

**Comment by clintval** [comment]
You're totally right, this PR missed v2.26.0 release by 2 days. Thanks anyway!

**Comment by hryknkgw** [comment]
I confirmed that the fix was released.
