### ISSUE TITLE
Memory leak for "bedtools coverage -sorted -split" with BAM files, in v2.26.0 but not v2.25.0

### ISSUE THREAD

**Issue by lucventurini** [arq5x/bedtools2#417]
Case: RNA-Seq alignment BAM, approximately 12 GB in size, compared against the exon lines of the _A. thaliana_ GFF reference. Using BEDTools v2.25.0, the analysis is completed in ~approximately 30m, with BEDTools stopping at using ~4GB of RAM.
Typical command line:

```
bedtools coverage -split -sorted -a exons.gff -b alignment.bam -s
```

However,  with version 2.26.0, using this exact command line will result in a massive memory leak because of which BEDTools will start using over 50GB of RAM before finishing analysing Chr1.

The problem is, we are aware of the incorrect handling of RNA-Seq BAM files in v2.25.0 and on the fragmentary output we obtain before running out of memory we do observe some differences. As we presume that those differences reflect incorrect calculations on our current version of the files, we would be interested in being able to run the new version without going out of memory.

**Comment by arq5x** [comment]
Thanks for reporting this - I will look into the cause asap.

**Comment by arq5x** [comment]
I see the cause of the leak. Now I just need to come up with a solid solution. Thanks for reporting this. I hope to have it resolved next week when I return from vacation.

**Comment by lucventurini** [comment]
Any updates on the issue? I hope the well-deserved holidays went well!

**Comment by lucventurini** [comment]
Dear Dr. Quinlan, any update on the issue?

**Comment by arq5x** [comment]
Yes, the massive memory leak in coverage with -split has been addressed. Please test!

**Comment by lucventurini** [comment]
Test done, and passed with flying colours - the memory leak has indeed disappeared. Thanks!
