### ISSUE TITLE
intersectBed runs extremely slowly on some input files

### ISSUE THREAD

**Issue by krttrr** [arq5x/bedtools2#419]
v2.17.0 works fine and returns results in a few seconds but v2.20.1 through 2.26.0 all take over 10 hours to process the same input. Our test input is a 1m-line VCF (-a) intersected with 200k-line BED (-b) and is reproducibly slow using the same input. The intersect runs at normal speed using other similar size VCFs produced by the same pipeline and the same BED file.

**Comment by arq5x** [comment]
Could you post the command and files you are using so that I can investigate?
