### ISSUE TITLE
map does not print null for certain operations

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#425]
`bedtools  map  -c 2   -o distinct_sort_num -a A.bed  -b B.bed`

if a region from A has not overlaps in B, then the new field will be blank, rather than default null value "."

it even fails if you specify null explicitly

`bedtools  map  -c 2   -o distinct_sort_num   -null  "."  -a A.bed  -b B.bed`

```
 $ bedtools  --version
bedtools v2.25.0
```

**Comment by arq5x** [comment]
Can you test this with version 2.26.0?

**Comment by arq5x** [comment]
Thanks for reporting this. It is now fixed in master.
