### ISSUE TITLE
Question regarding coverageBed

### ISSUE THREAD

**Issue by duartemolha** [arq5x/bedtools2#426]
Hi guys

I was wondering if there is way of making sure coverageBed does not include on the coverage depth reads that have that region softclipped

For example:

Say I want to get all the readepth of a bam file over a specific region on a bed file

coverageBed -d -a target.bed -b sample.bam

however... for each bp position calculated, if one or more reads are softclipped at that position they still count for the calculation.

**Comment by arq5x** [comment]
You would have to exclude such reads with samtools or with awk, etc.

**Comment by arq5x** [comment]
e.g.,

    bedtools coverage -d -a target.bed -b <(samtools view -h sample.bam | awk '!($6 ~ S)' | samtools view -Sb -)

**Comment by duartemolha** [comment]
unfortunately not exactly what I needed... since this excludes the entire read... I only wanted to exclude the read over the portion it is softclipped

**Comment by duartemolha** [comment]
I guess I would need to use the cigar string information to hard clip each read using the softclip information... correct?

**Comment by arq5x** [comment]
I see. I would have expected that clipped portions of reads are already excluded, as they should not be part of the aligned interval. Are you seeing otherwise?

**Comment by duartemolha** [comment]
I have not tested... But I assumed that bedtools assumed that the read covered that position even if softclipped ... if it doesn't then I have no request to make :)

**Comment by arq5x** [comment]
It should not, but please reopen if you see otherwise.
