### ISSUE TITLE
bedtools intersect -r option does not work anymore

### ISSUE THREAD

**Issue by lydiasteiner** [arq5x/bedtools2#428]
bedtools intersect's -r (in combination with -f) option does not work anymore. It is compeltely disregarded.

**Comment by arq5x** [comment]
I am rather sure this was fixed in this bug (https://github.com/arq5x/bedtools2/issues/358). Could you try release 2.26, or is that the version you are using?

**Comment by lydiasteiner** [comment]
Yes, 2.26 works. Sorry, for the confusion.
