### ISSUE TITLE
Provide option to have original getfasta -name output

### ISSUE THREAD

**Issue by ifiddes** [arq5x/bedtools2#433]
Version 2.26 of bedtools has no way to produce the original FASTA header when doing `bedtools getfasta`. The update to `-name` that now generates headers in the format `{name}::{location}`, which breaks multiple tools I have written.

I understand why this form of header could be useful, but it would be great if you provided a way to get the plain header again as well.

**Comment by arq5x** [comment]
This is fixed in master. Sorry for the delay.
