### ISSUE TITLE
bedtools closest Segmentation fault

### ISSUE THREAD

**Issue by zhaohuashan** [arq5x/bedtools2#434]
We are analyzing the new assembled chicken gg5 using bedtools tools. This genome version has some unassembled region (an example is attached as test.4). Bedtools closest shows segmentation fault but bedtools intersect can handle that well without problem. Is there way to solve the segmentation fault of bedtools closest? 

test.4
chr11_NT_461881v1_random	115	7987	cluster340	17994.36191	-

test.5
chr1	480154	480316	REP131	361	+	DNA?
chr1	1528456	1528613	REP131	399	+	DNA?
chr1	1528758	1529017	REP131	549	+	DNA?
chr1	1740063	1740217	Eulor7	431	-	DNA?
chr1	1812715	1812846	REP131	348	+	DNA?
chr1	1983509	1983717	UCON2	851	+	DNA?
chr1	1990327	1990416	REP131	238	+	DNA?
chr1	1990426	1990746	REP131	1037	+	DNA?
chr1	2152472	2152607	REP131	241	-	DNA?
chr1	2224542	2224679	REP131	400	+	DNA?

bedtools closest -d -b test.5 -a test.4 
Segmentation fault

Thank you.

**Comment by arq5x** [comment]
This works for me with version 2.26.0. Can you retry with that and reopen this issue if you still have a problem?

**Comment by zhaohuashan** [comment]
Thank you for your prompt reply. I will update to 2.26 and retry it.

Xin

Xin Zhiguo Li
xin_li@urmc.rochester.edu<mailto:xin_li@urmc.rochester.edu>



On Aug 21, 2016, at 4:22 PM, Aaron Quinlan <notifications@github.com<mailto:notifications@github.com>> wrote:


This works for me with version 2.26.0. Can you retry with that and reopen this issue if you still have a problem?

**Comment by zhaohuashan** [comment]
I does not work for version 2.25 but get fixed in version 2.26.
