### ISSUE TITLE
Incorrect grouping in groupBy 2.26.0 

### ISSUE THREAD

**Issue by dariober** [arq5x/bedtools2#435]
Hi- Is this behaviour of groupBy 2.26.0 expected? 

```
head test.bed
chr1	1	11	1
chr1	2	12	2
chr1	3	13	3
chr1	4	14	4
chr1	5	15	5
chr1	6	16	6
chr1	7	17	7
chr1	8	18	8
chr1	9	19	9
chr1	10	20	10

## This is with v2.26.0
head test.bed | groupBy -grp 1,2,3 -c 4 -o count
10
```

It seems the grouping columns do not actually group. With 2.25 I get this:

```
## This is with v2.25.0
head test.bed | groupBy -grp 1,2,3 -c 4 -o count
chr1	1	11	1
chr1	2	12	1
chr1	3	13	1
chr1	4	14	1
chr1	5	15	1
chr1	6	16	1
chr1	7	17	1
chr1	8	18	1
chr1	9	19	1
chr1	10	20	1
```

Thank you!

**Comment by arq5x** [comment]
I think I am confused. If you group by columns 1, 2, and 3, there are only one line per group in your example. Did you want the "sum" operator?

**Comment by dariober** [comment]
Hi Aaron- Thanks for super quick reply! This is just dummy data without real meaning.

> If you group by columns 1, 2, and 3, there are only one line per group in your example

Exactly, version 2.25 gives me ten lines back, each with count 1, as expected. However, version 2.26 gives in output just the number 10.

(Oh, it might be me being confused!)

**Comment by arq5x** [comment]
Ah I see. There are bugs in 2.26 groupby that have been fixed in master. Please try that - should work. Reopen if not, thanks

**Comment by dariober** [comment]
Hi- Unrelated to the original issue... I tried to compile the source from trunk but got this when hitting groupBy:

```
svn co https://github.com/arq5x/bedtools2
cd bedtools2/trunk/

make
...
... ## Goes fine until:
...
- Building in src/groupBy
  * compiling groupBy.cpp
groupBy.cpp: In member function ‘virtual void GroupBy::processHits(RecordOutputMgr*, RecordKeyVector&)’:
groupBy.cpp:85: error: invalid conversion from ‘const Record*’ to ‘Record*’
groupBy.cpp: In member function ‘virtual void GroupBy::cleanupHits(RecordKeyVector&)’:
groupBy.cpp:107: error: ‘iterator_type’ is not a member of ‘RecordKeyVector’
groupBy.cpp:107: error: expected ‘;’ before ‘iter’
groupBy.cpp:108: error: ‘iter’ was not declared in this scope
make[1]: *** [../../obj//groupBy.o] Error 1
make: *** [src/groupBy] Error 2
```

**Comment by arq5x** [comment]
Thanks for reporting - will fix today
