### ISSUE TITLE
Missing positions using genomecov

### ISSUE THREAD

**Issue by neumannf** [arq5x/bedtools2#437]
I used genomecov to determine the coverage of every position in the genome:
`genomeCoverageBed -d -ibam alignments.sam.sorted.bam -g genome.file > coverage.file`
Assuming that it determines the coverage at every position in the genome (which has 196,005,095 bases in our case) the resulting coverage file contains only 195,175,748 lines. Did I got something wrong? The same happens if I use -bga to write bedgraph format. I only compared the first and last positions and I could not see the problem there, that means it shows the first positions of the first scaffold and the last positions of the last scaffold. 
Thanks a lot for your help in advance!

**Comment by arq5x** [comment]
What do the chrom lengths look like in the header of the BAM?

**Comment by neumannf** [comment]
I extracted the header using 
`samtools view -H` 
and summed the length and it gives me the correct number of 196,005,095. 
Here is a part of the header:

`@HD	VN:1.5	SO:coordinate	pb:3.0.1
@SQ	SN:Scaffold_1	LN:888910	M5:3988daf0558cbc808ba7b8c1fad8ead9
@SQ	SN:Scaffold_2	LN:1123237	M5:00c717168bbc0a02108a1903b2710558
@SQ	SN:Scaffold_3	LN:1302841	M5:1bdc3c588eb3d75f4cc4285e9a9ea776
@SQ	SN:Scaffold_4	LN:1572669	M5:2d74199fcd6d20afac16cc3c66a8afe9
@SQ	SN:Scaffold_5	LN:1608692	M5:431c1071267e6e5973f5bcdbb61cf818
@SQ	SN:Scaffold_6	LN:1708715	M5:e980617d9a2cc246cbffdbedf622bc94
@SQ	SN:Scaffold_7	LN:836364	M5:f6a2b7c3de8cde426c6f3f73f027d553
@SQ	SN:Scaffold_8	LN:1856458	M5:5474848aca65e43b9ca23b057ff18368
@SQ	SN:Scaffold_9	LN:803787	M5:57d960fb8a1e5f2db02261b3df91ef11
@SQ	SN:Scaffold_10	LN:1944274	M5:c691bd086e9fe526e8e05cd1afb9e837
@SQ	SN:Scaffold_11	LN:745508	M5:313fdfbb4d4694808604ba9a1d5b50b0
@SQ	SN:Scaffold_12	LN:1289709	M5:18adf967b8869fde4317eb0c848d4dcb
@SQ	SN:Scaffold_13	LN:719485	M5:9eb3dde385f6d250af2779a3c595accb
@SQ	SN:Scaffold_14	LN:619847	M5:1e816f0d89b54196614704e91e75b48d
@SQ	SN:Scaffold_15	LN:1254565	M5:dbaaa172ae747e8cc065015997cbaae5
@SQ	SN:Scaffold_16	LN:851675	M5:a9940b1bf649a14c72afa4fd9f4cf7a2
@SQ	SN:Scaffold_17	LN:871864	M5:09ca61df001db67c7584113ae1955814
@SQ	SN:Scaffold_18	LN:1400249	M5:40e23497c9a0edd9b343b542b30be391
@SQ	SN:Scaffold_19	LN:2358613	M5:b6ae958c1cc21ae41096f1385968d993
@SQ	SN:Scaffold_20	LN:564741	M5:ce0fc4ff38269eb3a24de564edc41b7e
@SQ	SN:Scaffold_21	LN:2539303	M5:33c177090261cb838cb4085b9da4ffba
...`
I also tried 
`samtools depth -a -a alignments.sam.sorted.bam > coverage_sam.bed `
for comparison and it gave also the correct number of position.

**Comment by arq5x** [comment]
Okay, thanks for checking. What version of bedtools are you using?

**Comment by neumannf** [comment]
I use v2.17.0.

**Comment by arq5x** [comment]
Please use version 2.25.0 or the current master in github. This was fixed about a year ago.

**Comment by neumannf** [comment]
Thanks for your support!
