### ISSUE TITLE
shuffle -incl in 2.26 is unusably slow when -incl is large

### ISSUE THREAD

**Issue by michael-imbeault** [arq5x/bedtools2#441]
So I finally found time to test out the new shuffle with -incl in 2.26 which takes into account length of intervals... and at least for my use case it is unusably slow - it produces one random interval every 5s or so, and I have thousands of them.

It might be related to my -incl being a bed of all transposable elements in the human genome, but still I cannot imagine that this speed is the result of a properly implemented roulette sampling.

In the meantime I will keep using the hackish way to do it - I use 2.25 and split my -incl bed in small fragments (20 bp).

**Comment by arq5x** [comment]
I am not seeing the same poor performance. Could you share the files and command you are using?

**Comment by arq5x** [comment]
Nevermind - I can reproduce this. Will try to come up with a more performant approach to roulette sampling.

**Comment by arq5x** [comment]
I just implemented a much faster method that addresses this problem and still shuffles records to the -incl intervals proportional to their size:

    cat foo.bed
    chr1   	0      	1000   	A
    chr2   	0      	100    	B
    chr3   	0      	110    	C
    chr4   	0      	10     	D

    bedtools shuffle -i <(bedtools random -n 1000000 -l 50 -g genomes/human.hg19.genome) -incl foo.bed -g genomes/human.hg19.genome \
    | bedtools intersect -a - -b foo.bed -wa -wb \
    | cut -f 7-10 \
    | sort | uniq -c
     819945 chr1   	0      	1000   	A
      81919 chr2   	0      	100    	B
      90133 chr3   	0      	110    	C
       8003 chr4   	0      	10     	D

**Comment by arq5x** [comment]
shuffling 1 million randomly generated intervals among all of the human simple repeats track (N=962715) took ~6 seconds:

    time bedtools shuffle -i <(bedtools random -n 1000000 -l 50 -g human.hg19.genome) -incl simplerepeats.bed.gz -g human.hg19.genome > /dev/null
    bin/bedtools shuffle -i  -incl  -g genomes/human.hg19.genome > /dev/null  5.97s user 0.32s system 99% cpu 6.294 total
