### ISSUE TITLE
Clarify sorting requirements in documentation

### ISSUE THREAD

**Issue by rmzelle** [arq5x/bedtools2#446]
I'm using _coverageBed_ to determine the average read coverage of genomic features (defined in BED files) in BAM files, and I can't get the `-sorted` option to work. And without the `-sorted` option, I'm running out of memory for large BAM files (> 1 GB). I'm currently using bedtools 2.25 because _groupBy_ is broken in the latest 2.26 release (https://github.com/arq5x/bedtools2/issues/435).

Since the benefits of sorting are stressed at https://github.com/arq5x/bedtools2#performance and http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html, I'm wondering if the online _coverageBed_ documentation could be made a bit more explicit in how to prepare the input files and how to use `-sorted`. In particular:
- What should the genome file mentioned at http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html look like (`-g` option; "Specify a genome file the [_sic_] defines the expected chromosome order in the input files for use with the -sorted option."). Is there a description of the expected file format somewhere?
- Could you add instructions to http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html on how to deal with BAM files ? I tried sorting my BAM file with `samtools sort unsorted.bam > sorted.bam`, and my BED files with `sortBed -i unsorted.bed > sorted.bed`, but this still gives errors:

**Case 1, "A.bed" and "sorted.bam"**
Output of `samtools view -H sorted.bam`:

```
@HD VN:1.0  SO:coordinate
@SQ SN:chrI LN:230218
@SQ SN:chrII    LN:813184
@SQ SN:chrIII   LN:316620
@SQ SN:chrIV    LN:1531933
@SQ SN:chrIX    LN:439888
@SQ SN:chrmt    LN:85779
@SQ SN:chrV LN:576874
@SQ SN:chrVI    LN:270161
@SQ SN:chrVII   LN:1090940
@SQ SN:chrVIII  LN:562643
@SQ SN:chrX LN:745751
@SQ SN:chrXI    LN:666816
@SQ SN:chrXII   LN:1078177
@SQ SN:chrXIII  LN:924431
@SQ SN:chrXIV   LN:784333
@SQ SN:chrXV    LN:1091291
@SQ SN:chrXVI   LN:948066
...
```

Output of `cut -f 1 A.bed | uniq`:

```
chrI
chrII
chrIII
chrIV
chrV
chrVI
chrVII
chrVIII
chrIX
chrX
chrXI
chrXII
chrXIII
chrXIV
chrXV
chrXVI
chrmt
```

When I run `coverageBed -b sorted.bam -a A.bed -d -sorted` for these files, I get:

> ERROR: chromomsome [_sic_] sort ordering for file sorted.bam is inconsistent with other files.

Here it's clear that the BED and BAM files have different orderings. Apparently _samtools_ doesn't seem to reorder chromosomes in a sort (https://github.com/arq5x/bedtools/issues/109#issuecomment-114932058). Is there any way to easily sort chromosomes in BAM files, or is the only solution to sort the BED file to match the BAM file and use a genome file with the `-g` option, as suggested at https://github.com/arq5x/bedtools/issues/109#issuecomment-114942096?

**Case 2, "B.bed" and "sorted.bam"**
With a different BED file, with output of `cut -f 1 B.bed | uniq`:

```
chrIV
chrX
chrXVI
```

I get for `coverageBed -b sorted.bam -a B.bed -d -sorted`:

> ERROR: Sort order was unspecified, and file sorted.bam is not sorted lexicographically.
>        Please re-reun [_sic_] with the -g option for a genome file.
>       See documentation for details.

I'm more confused here, since the three chromosomes in the BED file are in the same order as the chromosomes in the BAM file. Is _coverageBed_ thrown off here because the chromosomes in the BED file are a subset of the chromosomes in the BAM file?

**Comment by rmzelle** [comment]
Related, is it really necessary to require the same chromosome order in the BED and BAM files when using *coverageBed* with `-sorted`? Does matching chromosome orders really bring significant performance gains?

If the requirements could be relaxed so that the chromosomes in input features files of *coverageBed* don't need to be sorted in the same order, `-sorted` would be much easier to use.

**Comment by arq5x** [comment]
Sorry for your troubles. Yes, it is absolutely necessary and it really does make a tremendous speed difference. What version are you using? If you can share minimal files, I can also test, as this should work.

**Comment by rmzelle** [comment]
> If you can share minimal files, I can also test, as this should work.

You mean the second case?

For the first, I guess I should follow the steps you described at https://github.com/arq5x/bedtools/issues/109#issuecomment-114942096 (if this information could be added to http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html, that would be great). Are the `chromosome names.txt file` and genome file both supposed to be single-column text files?

**Comment by arq5x** [comment]
Yes, the second case. Two column files: first column is chromosome label, second is length. The chrom order in this file specifies the expected order in all data files.

**Comment by rmzelle** [comment]
> Two column files: first column is chromosome label, second is length. The chrom order in this file specifies the expected order in all data files.

So tab-delimited, then? Is this documented anywhere?

> What version are you using?

2.25 (I use groupBy which is broken in 2.26)

My BAM file is 600 MB, but I should be able to create a smaller one. What would be the easiest way to privately share files? I could give you a Dropbox link if there is an email address I can send it to.

**Comment by arq5x** [comment]
http://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format

groupby works in the repo version, I just haven't had time to finalize all fixes for the next release. Sorry.  Email is aaronquinlan. gmail.
