### ISSUE TITLE
Autotool the build system

### ISSUE THREAD

**Issue by SoapGentoo** [arq5x/bedtools2#447]
Dear @arq5x 
would you consider fully autotooling the build system? This makes consuming your package much easier for the following reasons:
- Automake enforces some practical conventions. This includes `VPATH` builds, but also installing in the standard paths of the filesystem (think about doc/datafiles/etc).
- Writing non-recursive Makefile's are much easier using Automake, as the rules are much easier to write leading to more parallelism when building. The current buildsystem includes a ton of boilerplate code that would vanish with Automake.
- Autoconf's produced `configure` script easily allows for specifying other compilers (change `CXX`, `CXXFLAGS` etc).
- Autoconf+Automake strongly discourage developers from setting `CXXFLAGS`/`CPPFLAGS`/`LDFLAGS` themselves, as these are user flags and not to be changed (think about cross-compiling, where being able to modify `CXX` and `CXXFLAGS` is crucial for the build to succeed).

More reasons for following standard packaging guidelines: http://www.dwheeler.com/essays/releasing-floss-software.html
Using the autotools makes downstream packaging **much** easier and less cumbersome. Writing Makefile's from scratch that handle all of these conventions is close to impossible. I'm willing to help with autotooling it, and I'm sure my allies from Arch (@wookietreiber :wink:) would be willing to pitch in. Please, think of the downstream distributions!

**Comment by wookietreiber** [comment]
Yes, I would also like to see an autotooled build. I would also be able and willing to help with the transition.

**Comment by wookietreiber** [comment]
FYI, this would probably also fix #210.

**Comment by arq5x** [comment]
Hi all, I am open to this, but have a couple of concerns. First, I have no experience with this at all and don't have the bandwidth or anyone in my lab who can take learning this on. Second, what additional dependencies with this create? Not cmake, correct? Anything else?

**Comment by SoapGentoo** [comment]
@arq5x We're always glad to help with willing upstreams, mainly because it significantly eases the burden on our side too. The autotools have 0 to do with cmake (which I don't like for a number of reasons). The autotools have the big advantage that **no additional tools** are required **for consumers** of your package, whereas for the developers (i.e., you and us) it requires installing the latest Autoconf + Automake (and maybe libtool and m4). Preparing a release tarball (using `make distcheck`) has the advantage of checking that the build succeeds. If you're willing, we can provide a PR (and help if you have problems).

**Comment by SoapGentoo** [comment]
Please check out my PR in https://github.com/arq5x/bedtools2/pull/454

**Comment by jmarshall** [comment]
Another priority for bedtools's build system is that it be familiar to Aaron and the other maintainers, who deal with it every day.  At the moment they are very familiar with their existing build system (which has served bedtools well for a number of years), but they are not familiar with, in particular, automake.

Bedtools has existed for years without major complaint without a configure script.  So there is not really a demonstrated need for it to get one, though if configure decisions were desired, **autoconf** (i.e., _configure.ac_/_configure_) could be added to the existing build system or to an automake one.

Bedtools has been using GNU Make functionality for years without complaint.  For a project already taking advantage of GNU Make facilities, IMHO **automake** doesn't offer anything other than a massive increase in complexity for maintainers, particularly for maintainers who are not already automake experts.

Rather a long time ago now, I offered to @arq5x that I would revamp the existing build system in a non-recursive way but more or less maintaining its existing style.  That is now PR #455, which minimally alters the existing build system to ensure the actual functionality you desire: the usual install path variables, separate objdir builds (currently a work-in-progress), non-recursiveness, not overriding the user's `$(CXXFLAGS)`/etc.

So I guess Aaron might like to consider these two PRs and pick a direction (or the status quo!).  If he wishes, I would be happy to review the automake PR.

**Comment by SoapGentoo** [comment]
@jmarshall given the somewhat simple nature of everything involved, my PR really just adds one `Makefile.am`, which given the current situation of multiple includes, is far simpler (seeing as it pretty much only relies on defining a list of files). I believe automake is a gain in functionality, as enforcing a minimal set of (in this case, GNU) conventions is a gain, since downstream users know its conventions, can work with these and can adapt them through `--docdir` and such, none of which is guaranteed through the current build system. With the configure script, `--enable-doc` builds the documentation, and installs pdf and html files according to `pdfdir` and `htmldir` options.

**Comment by SoapGentoo** [comment]
@arq5x is there no chance of getting the build system modernised? The current build system is cumbersome and doesn't parallelise well.

**Comment by arq5x** [comment]
Bedtools now has a non-recursive Makefile structure that prevents unnecessary recompilation and enables parallelization. `make -j 4` completes in less than a minute. Since I am unfamiliar with working with automake and we have had very few complaints about building, I am hesitant to change.
