### ISSUE TITLE
Request: Paired-end function for bedtools coverage

### ISSUE THREAD

**Issue by ATpoint** [arq5x/bedtools2#448]
Hi,

is there any change that you are working on a paired-end function for bedtools coverage if -b is a paired-end bam?
Currently, it treates each mate of a pair independeltly and does not consider TLEN for coverage calculation. Would be great!

best,
Alex

**Comment by mschilli87** [comment]
@ATpoint: Why did you close this issue? Is the feature there,not needed, or the request a duplicate?

**Comment by ATpoint** [comment]
No, but > 1 year old without reaction.

**Comment by mschilli87** [comment]
I still think it's a valid request that should not be forgotten. There simply are very pressing issues currently delaying the planned next release afaik, so I wouldn't consider this as something that will never happen.

**Comment by asteif** [comment]
Hello, would it be possible to reopen this issue?

I'd like to get paired-end "fragment coverage" histograms for specific genomic intervals. Essentially adding the genomecov -pc option to the coverage tool:

`bedtools coverage -hist -pc
-a intervals.bed
-b paired_end_input.bam`

Alternatively, a way of specifying a bed file with intervals of interest to genomecov would be useful. 

Thanks!
