### ISSUE TITLE
intersect result abnormally pasted

### ISSUE THREAD

**Issue by yewero** [arq5x/bedtools2#452]
I am using the version in master branch.
For example,
bedtools intersect -nonamecheck -wo -a A.bed -b B.gtf

Result:
chr1    130472  130530  ENST00000493797.1_2     Line_48 -       chr1    StringTie       exon    130268  130530  1000    -       .    **MG_panTro4.1MG_panTro4.1.1**       1       58

Why these two columns were pasted?
In my input file, they are two closed column.

**Comment by arq5x** [comment]
I have no idea, can you show me what the A and B files look like?

**Comment by lcscs12345** [comment]
What about formatting your files with the following command and try again?
```
awk '{sub("\r$", ""); print}'
```

**Comment by yewero** [comment]
I think it is because my A.bed contained more than 9 columns (seperated by tab), so the results showed pasted content in the last 2 columns.
