### ISSUE TITLE
intersect -f -F switch

### ISSUE THREAD

**Issue by yangjiekun** [arq5x/bedtools2#456]
Hi Aaron,

It seems the following bedtools intersect command is not working as expected. I was using bedtools 2.26.0.

$ cat A.bed
chr1    1    1
chr1    2    2

$ cat B.bed
chr1    1    2 

$ bedtools intersect -a A.bed -b B.bed -c -f 1.0
chr1    1    1    0
chr1    2    2    0

$ bedtools intersect -a A.bed -b B.bed -c -F 1.0
chr1    1    1    1
chr1    2    2    1

I think the -f and -F options in this context are switched. Is this a known bug?

Thanks,
Jackie

**Comment by arq5x** [comment]
I think this is because you are using zero length records in A.bed. BED format uses zero-based starts and 1-based ends.

**Comment by yangjiekun** [comment]
I see. Thanks for the clarification.
