### ISSUE TITLE
Strange outputs from reldist

### ISSUE THREAD

**Issue by rmccole** [arq5x/bedtools2#459]
Dear arq5x:
I have been using the bedtools reldist function (though admittedly not the latest version; I am using version 2.25.0). The issue is that I often get a different output every time I run the function! From reading the documentation, I did not expect this. I have attached 15 output files and my input files (called a_input.txt and b_input.txt). I wonder if the extra columns in the input files are causing this, but I can't understand why they would do that. 

Normally I would shrug and move on but this seems like such strange behavior to me.
Many thanks.

[b_input.txt](https://github.com/arq5x/bedtools2/files/607760/b_input.txt)
[a_input.txt](https://github.com/arq5x/bedtools2/files/607761/a_input.txt)
[redist1.txt](https://github.com/arq5x/bedtools2/files/607762/redist1.txt)
[redist2.txt](https://github.com/arq5x/bedtools2/files/607763/redist2.txt)
[redist3.txt](https://github.com/arq5x/bedtools2/files/607765/redist3.txt)
[redist4.txt](https://github.com/arq5x/bedtools2/files/607766/redist4.txt)
[redist5.txt](https://github.com/arq5x/bedtools2/files/607767/redist5.txt)
[redist6.txt](https://github.com/arq5x/bedtools2/files/607769/redist6.txt)
[redist7.txt](https://github.com/arq5x/bedtools2/files/607770/redist7.txt)
[redist8.txt](https://github.com/arq5x/bedtools2/files/607771/redist8.txt)
[redist9.txt](https://github.com/arq5x/bedtools2/files/607772/redist9.txt)
[redist10.txt](https://github.com/arq5x/bedtools2/files/607773/redist10.txt)
[reldist11.txt](https://github.com/arq5x/bedtools2/files/607774/reldist11.txt)
[reldist12.txt](https://github.com/arq5x/bedtools2/files/607775/reldist12.txt)
[reldist13.txt](https://github.com/arq5x/bedtools2/files/607776/reldist13.txt)
[reldist14.txt](https://github.com/arq5x/bedtools2/files/607777/reldist14.txt)
[reldist15.txt](https://github.com/arq5x/bedtools2/files/607779/reldist15.txt)

**Comment by arq5x** [comment]
This is fixed by @LukeGoodsell in master.
