### ISSUE TITLE
memory usage bedtools coverage 

### ISSUE THREAD

**Issue by AnnaMontaner** [arq5x/bedtools2#460]
Hi, I amb having memory problems when using the bedtools coverage command. The BAM file I want to analyze is quite big and the program runs out of memory, so I tried the option -sorted as specified in the bedtools docs. I sorted the bed interval file by chromosome and starting position. My BAM file is sorted by chromosome and starting position too. 

That's my command line : 

coverageBed -sorted -a sortedIntervals.bed -b fileZ.bam > fileZ.cov.txt

However, I am getting the following error, which is similar to other BAM files I tried: 

ERROR: chromomsome sort ordering for file fileZ.bam is inconsistent with other files. Record was:
chr10	63368	63517	NB501377:5:H7GYWAFXX:1:21206:12148:4880/2	0	+

ERROR: chromomsome sort ordering for file fileB.bam is inconsistent with other files. Record was:
chr10	67230	67381	NB501377:5:H7GYWAFXX:4:21407:17065:4955/1	0	+

ERROR: chromomsome sort ordering for file fileC.bam is inconsistent with other files. Record was:
chr10	61264	61416	NB501377:5:H7GYWAFXX:2:21203:3758:16177/1	47	+

ERROR: chromomsome sort ordering for file fileD.bam is inconsistent with other files. Record was:
chr10	63035	63092	NB501377:42:HF5VGAFXX:1:21209:5943:7898/2	0	+_

 Can anyone tell me what can be going on? 

Thank you very much!! 

Anna

**Comment by rmzelle** [comment]
@AnnaMontaner, I had similar problems at https://github.com/arq5x/bedtools2/issues/446.

Have you checked whether your BAM and BED files really have the same sort order? (I got those details with `samtools view -H fileZ.bam` and `cut -f 1 sortedIntervals.bed | uniq`

**Comment by ghuls** [comment]
It would be nice if BEDtools could use the BAM index file in cases like this. Then the ordering by chromosome could be different (and it should not need to parse the whole BAM file).

**Comment by ghuls** [comment]
"bedtools multicov" might work for you. It needs an sorted and indexed BAM file.

**Comment by ghuls** [comment]
@AnnaMontaner See #492 for a workaround.

**Comment by rmzelle** [comment]
@AnnaMontaner, I had success with bedtools 2.25 and samtools 1.3, and the following commands:

```bash
# First create a genome file (http://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format) from the coordinate-sorted BAM file
samtools idxstats alignment.bam | cut -f 1-2 > chromosomes.txt
# Then sort the BED file according to this genome file
bedtools sort -faidx chromosomes.txt -i features.bed > features-sorted.bed
# Finally use coverageBed with "-sorted", sorted BED file, and genome file
coverageBed -a features-sorted.bed -b alignment.bam -g chromosomes.txt -sorted -d | sort -k1,1 -k2,2n | groupBy -g 1,2,3,4 -c 6 -o mean > features-coverage.txt
```
