### ISSUE TITLE
Bedtools slop not controlling for start coordinate going over the chromosome length, also not controlling for end coordinate when reaching beginning.

### ISSUE THREAD

**Issue by jaime11** [arq5x/bedtools2#461]
Consider the following example:

cat A.bed
chr1    200     220

cat my.genome
chr1    250

bedtools slop -s -l -80 -r 80 -i A.bed -g my.genome
chr1    **280**     250

The start coordinate exceeds the end of the chromosome and the start coordinate of the result is higher than the end.

Also, this happens in the beginning of the chromosome:

cat A.bed
chr1    40      60      name    5       -

cat my.genome
chr1    250

bedtools slop -s -l -70 -r 70 -i A.bed -g my.genome
chr1    0       **250**     name    5       -

Trying to subtract a longer distance than the end coordinate will result in the end coordinate becoming the chrosome's length instead of 0.

**Comment by arq5x** [comment]
Looks like negative slop is not handled appropriately. I will try to create a fix.

**Comment by jaime11** [comment]
Thank you!

I have also found another behaviour in this regard which might want to be rectified:

cat A.bed
chr1    50      60      name    6       -

cat my.genome
chr1    250

bedtools slop -s -l -60 -r 60 -i A.bed -g my.genome
chr1    0       0       name    6       -

If the negative strand is subtracted the number of coordinates of the end coordinate, the result is a 0-0 range which in theory doesn't exists.

Thanks again!

**Comment by rishavray** [comment]
I have corrected the negative slop issue and also adjusted the start and end values in edge cases as demonstrated. Moreover, due to negative slops if the start value becomes more than the end value, the start and end are swapped. I'll be issuing a pull request shortly after I go through all possible test cases.

**Comment by jaime11** [comment]
Hello,

I have been testing this again, I am using bedtools v2.27.1

After the fix, for the cases outlined above where the resulting ranges are invalid (after slopping, start and end are both beyond the chromosome limits), the resulting bed range is 1bp:

**Case for surpassing end:**
cat my.genome
chr1    250

cat 1.bed
chr1    200     220

bedtools slop -s -l -80 -r 80 -i 1.bed -g my.genome
chr1    249     250


**Case for surpassing beginning:**
cat 1.bed
chr1    40      60      name    5       -

bedtools slop -s -l -70 -r 70 -i 1.bed -g my.genome
chr1    0       1       name    5       -


**Case for just about surpassing beginning:**

cat 1.bed
chr1    50      60      name    6       -

bedtools slop -s -l -60 -r 60 -i 1.bed -g my.genome
chr1    0       1       name    6       -


As mentioned, in theory, all these commands should be returning invalid regions, since all of them have start and end beyond the chromosome limits. Can we just omit to output these regions as a default behavior or at least create a switch in the bedtools slop command which omits them? I can look into implementing this if need be.

Thanks!
