### ISSUE TITLE
intersect with split option has a "strand" bug when using on BED12 files with blocks

### ISSUE THREAD

**Issue by sajeevbatra** [arq5x/bedtools2#470]
Thanks for the awesome set of tools.    I'm using Version: v2.26.0
Input files:
cat toy_probe2.bed 
chr1	1000000	1000025	probe	1084	-	1000075	1000075	255,0,0	1	25	0

cat toy_mrna.bed 
chr1	1000000	1002000	mrna	1084	+	1000000	1000000	255,0,0	5	40,400,160,200,300,	0,300,1000,1200,1700

bedtools intersect -split  -wao   -a toy_probe2.bed -b toy_mrna.bed
chr1	1000000	1000025	probe	1084	-	1000075	1000075	255,0,0	1	25	0	chr1	1000000	1002000	mrna	1084	+	1000000	1000000	255,0,0	5	40,400,160,200,300,	0,300,1000,1200,1700	25

The output shows a 25 base overlap however "probe" is on the minus strand and myna is on the plus strand.

This seems to be a bug.

Thanks, Sajeev

**Comment by nkindlon** [comment]
Hi Sajeev,
     By default, intersect ignores strandedness, but you can use the -s and -S options to enforce it. From the docs page:

-s 	Force “strandedness”. That is, only report hits in B that overlap A on the same strand. By default, overlaps are reported without respect to strand.
-S 	Require different strandedness. That is, only report hits in B that overlap A on the _opposite_ strand. By default, overlaps are reported without respect to strand.

**Comment by sajeevbatra** [comment]
Yes, thanks for letting me know.  
-s works as intended.
