### ISSUE TITLE
Coordinates of gaps of Ns

### ISSUE THREAD

**Issue by sjackman** [arq5x/bedtools2#480]
Is there a tool that takes a FASTA file and produces a BED file of the gaps of Ns, that is, the opposite operation of maskfasta?

**Comment by sjackman** [comment]
I found this tool `generate_masked_ranges.py`: http://www.danielecook.com/generate-masked-ranges-bedfile-fasta/
Does `bedtools` have such a tool?

**Comment by arq5x** [comment]
Sorry, no tool for this :(

**Comment by sjackman** [comment]
`seqtk cutN -g` does what I want. `seqtk` version 1.3 has a small bag where it omits those gaps starting at the first base of the chromosome. Seems like it would be straight forward enough to fix. https://github.com/lh3/seqtk/blob/ca4785c620d34cf5934b89ae8e00f6dc71a5bf1e/seqtk.c#L959

**Comment by sjackman** [comment]
Also see these two tweets (nearly two years apart to the day):
https://twitter.com/sjackman/status/748259285151293440
https://twitter.com/sjackman/status/1144080588980142080
