### ISSUE TITLE
intersect -wo showed 1bp error

### ISSUE THREAD

**Issue by yewero** [arq5x/bedtools2#482]
Here is the result of `bedtools intersect -wo -a XXX -b YYY`

> Chr1    PHAST   phastCons_predicted     4109    4111    11.7179378236474        +       .       gene_ID "12";        Chr1    3995    4276    2

Actually the overlapped length should be 3bp (4109, 4110 and 4111) rather than 2.

**Comment by arq5x** [comment]
Can you please show the original intervals from XXX and YYY?

**Comment by yewero** [comment]
XXX
> Chr1    PHAST   phastCons_predicted     4109    4111    11.7179378236474        +       .       gene_ID "12";

YYY

> Chr1    3995    4276

**Comment by ghuls** [comment]
```
$ bedtools intersect -wo -a /tmp/a.gtf -b /tmp/b.bed
Chr1	PHAST	phastCons_predicted	4109	4111	11.7179378236474	+	.	gene_ID "12";	Chr1	3995	4276	2

# Switching the files gives the correct result for  the overlap.
$ bedtools intersect -wo -b /tmp/a.gtf -a /tmp/b.bed
Chr1	3995	4276	Chr1	PHAST	phastCons_predicted	4109	4111	11.7179378236474	+.	gene_ID "12";	3

```

**Comment by yewero** [comment]
Thanks. But how to avoid this except switching files?

**Comment by ATpoint** [comment]
Are you aware that the bed file format is 0-based and half-closed, which means that the end coordinate is not included in intersection calculations? That is why the overlap is 2.

**Comment by yewero** [comment]
The XXX file is `gtf` format instead of `bed`

**Comment by yewero** [comment]
@arq5x This problem still happens, could you please show how to fix it?

**Comment by ghuls** [comment]
@yewero 
The following commit fixes this problem: **-wo must report 1 bp of overlap b/w VCF SNP and overlapping 1bp BED. …** https://github.com/arq5x/bedtools2/commit/5e74a17da4c044c732050349271b20bd46cb07c3 as it checks if the input record is zero or one based when it calculates the number of overlapping bases.

```
$ ./bedtools intersect -wo -a /tmp/a.gtf -b /tmp/b.bed
Chr1    PHAST   phastCons_predicted     4109    4111    11.7179378236474        +       .       gene_ID "12";       Chr1    3995    4276    3

$ ./bedtools intersect -wo -b /tmp/a.gtf -a /tmp/b.bed
Chr1    3995    4276    Chr1    PHAST   phastCons_predicted     4109    4111    11.7179378236474   +.       gene_ID "12";   3

```

**Comment by yewero** [comment]
@ghuls Thanks. So can the lastest version produce correct output?
