### ISSUE TITLE
Spacing tool shows 0 for overlapping intervals

### ISSUE THREAD

**Issue by victor-lin** [arq5x/bedtools2#483]
The CLI documentation specifies:

    	(1)  Input must be sorted by chrom,start (sort -k1,1 -k2,2n for BED).
    	(2)  The 1st element for each chrom will have NULL distance. (".").
    	(3)  Distance for overlapping intervaks is -1 and bookended is 0.

However, given this file:

    $ cat test.bed
    chr1	0	10
    chr1	10	20
    chr1	19	30
    chr1	35	45
    chr1	100	200

    $ bedtools spacing -i test.bed
    chr1	0	10	.
    chr1	10	20	0
    chr1	19	30	0
    chr1	35	45	5
    chr1	100	200	55

The spacing for `10,20` and `19,30` should be `-1`, not `0`.

**Comment by ghuls** [comment]
I think the correct output should be this:
```
$ bedtools spacing -i test.bed
chr1	0	10	.
chr1	10	20	0
chr1	19	30	-1
chr1	35	45	5
chr1	100	200	55
```

The first 2 regions are not overlapping, as the end coordinate in a BED file is not included in the region itself.

**Comment by arq5x** [comment]
Hmm, I thought this was fixed. What version?

**Comment by ghuls** [comment]
Still in the last git

**Comment by victor-lin** [comment]
I am using `bedtools v2.26.0`.

**Comment by ghuls** [comment]
If I understand the code correctly, it will put 0 for overlapping regions.

https://github.com/arq5x/bedtools2/blob/master/src/spacingFile/spacingFile.cpp
```c++
			// _currRecent and _prevRecious records are on the same chromosome.
			if (_currRec->getChrName() == _prevRec->getChrName())
			{
				// do _currRec and _prevRec overlap?
				if (_currRec->sameChromIntersects(_prevRec, false, false, 1E-9, 1E-9, false, false))
					_distance.append("0");
				else
				{
					int distance = _currRec->getStartPos() - _prevRec->getEndPos();
					ostringstream s;
					s << distance;
					_distance.append(s.str());
				}
}
```

There is also a typo in https://github.com/arq5x/bedtools2/blob/master/src/spacingFile/spacingHelp.cpp
```c++
 cerr << "\t(3)  Distance for overlapping intervaks is -1 and bookended is 0." << endl << endl;
```
Change to:
```c++
 cerr << "\t(3)  Distance for overlapping intervals is -1 and bookended is 0." << endl << endl;
```

I was not famliliar with the word "bookended". Would it be better to use "adjacent".
```c++
 cerr << "\t(3)  Distance for overlapping intervals is -1 and 0 for adjacent intervals." << endl << endl;
```
