### ISSUE TITLE
groupby doesn't work well in v2.26.0

### ISSUE THREAD

**Issue by dijunchen** [arq5x/bedtools2#484]
I'm using the **groupby** function in the new version (2.26.0): 

`bedtools groupby -i file.bed -g 5 -c 6 -o mean,stdev -delim "\t"

But the final results contain only two values: the mean and stdev. Could you check this?

**Comment by arq5x** [comment]
Please clone the main repository, as this has been fixed in Github, but it is not yet part of a formal release.
