### ISSUE TITLE
Segmentation fault with closestBed

### ISSUE THREAD

**Issue by necoli1822** [arq5x/bedtools2#486]
Hi there, sorry for the issue.
I was running ISmapper and got the segmentation fault with the commend,
'closestBed -a /media/necoli/Data/Genomes/AB_BL_Result/IS_mapper/Results/ISdb_BL01/ISAba24/BL18_ISAba24_temp/BL18_5_BL01_ISAba24_cov_merged.sorted.bed -b /media/necoli/Data/Genomes/AB_BL_Result/IS_mapper/Results/ISdb_BL01/ISAba24/BL18_3_BL01_ISAba24_merged.sorted.bed -d'

As there were several reports about the same issue and it was recommanded to update with the latest version, I updated bedtools to v.2.26, but still it does not work.

The bash messages are below,
closestBed -a /media/necoli/Data/Genomes/AB_BL_Result/IS_mapper/Results/ISdb_BL01/ISAba24/BL18_ISAba24_temp/BL18_5_BL01_ISAba24_cov_merged.sorted.bed -b /media/necoli/Data/Genomes/AB_BL_Result/IS_mapper/Results/ISdb_BL01/ISAba24/BL18_3_BL01_ISAba24_merged.sorted.bed -d
Segmentation fault (core dumped)

Links for the files are below.
1. BL18_5_BL01_ISAba24_cov_merged.sorted.bed = https://drive.google.com/open?id=0B9L_dB5U6nHZcU13VUlMNnZodzQ
2. BL18_3_BL01_ISAba24_merged.sorted.bed = https://drive.google.com/open?id=0B9L_dB5U6nHZcWcyb1N3Y1YtUm8

**Comment by ghuls** [comment]
The segfault happens when the -b file is empty.

```
printf '' | bedtools closest -a BL18_ISAba24_temp/BL18_5_BL01_ISAba24_cov_merged.sorted.bed -b -
```
