### ISSUE TITLE
BEDtools Coverage high RAM usage with the -sorted option

### ISSUE THREAD

**Issue by uros-sipetic** [arq5x/bedtools2#492]
Hi
I'm using BEDtools Coverage, my input BAM is around 5.3GB and my genome, BED and BAM files are all coordinate sorted. 
The problem I'm having is with RAM, as it skyrockets past 60GB that I have available (I actually got a successful run on a machine with 240GB, and RAM usage was around 62GB-64GB).
I was first running BEDtools 2.25.0 unsuccessfully and I saw that there is a bug fix in 2.26.0 addressed as:
>Fixed a major memory leak when using -sorted.

So I tried running 2.26.0 as well, but I'm still getting the same problem - my run fails because of exceeded RAM on a 60GB machine. 

Am I missing something important that I need to do when using the -sorted option, or is the memory leak bug still present, or am I doing something else wrong here?
My command line is:
> bedtools coverage -g organism.genome -sorted -a organism.exons.bed -b sample.sorted.bam > sample.bed

Thanks for any answer.

**Comment by ghuls** [comment]
You can try the last git version.

Or you can use this shortcut:
  - First get the all BAM regions that overlap with your input.
  - Then use this output to calculate the coverage.

``` bash
bedtools intersect -bed -g organism.genome -sorted -a sample.sorted.bam -b organism.exons.bed \
  | bedtools coverage -g organism.genome -sorted -a organism.exons.bed -b - \
  > sample.bed
```

As the -b file is loaded in memory, reducing the size of the -b file will make a big difference.

**Comment by uros-sipetic** [comment]
Hi, thanks for the answer.
I tried using your command, and now I'm getting the error
> Error: Sorted input specified, but the file - has the following out of order record

Just to check, at the intersect step I'm using -a with my BAM and -b with my BED, and at the coverage step it's the other way around?

Also, I think I'm already using the last git version, I got it with git clone. 
Is the command you suggested not needed anymore with the last git version? I tried it anyway, and the error I mentioned came up.

**Comment by ghuls** [comment]
> Just to check, at the intersect step I'm using -a with my BAM and -b with my BED, and at the coverage step it's the other way around?

Yes this is correct.

Remove the -sorted option in the coverage command.
```bash
bedtools intersect -bed -g organism.genome -sorted -a sample.sorted.bam -b organism.exons.bed \
  | bedtools coverage -g organism.genome -a organism.exons.bed -b - \
  > sample.bed
```

Or you can sort the output of the first command (untested, but should work):
```bash
bedtools intersect -bed -g organism.genome -sorted -a sample.sorted.bam -b organism.exons.bed \
  | bedtools faidx organism.genome  -i - \
  | bedtools coverage -g organism.genome -sorted -a organism.exons.bed -b - \
  > sample.bed
```

I used something similar a few months ago (the awk gibberish can be replaced with just a plain BED file as I made here a BED file on the fly):
```bash
    # Calculate coverage for the BAM file for each position of the regions in
    # the BED file after taking the center of the region and taking a window
    # size up and down from this center.
    bedtools coverage -d \
        -a <("${AWK}" \
                -F '\t' \
                -v OFS='\t' \
                -v window_size="${window_size}" '
                    {
                        # Calculate the center of the region and take window_size up and down this center.
                        region_center = $2 + int(($3 - $2) / 2);
                        print $1, region_center - window_size, region_center + window_size + 1;
                    }' \
                    "${regions_bed_filename}" \
            ) \
        -b <(bedtools intersect \
                -bed \
                -sorted \
                -g <(cut -f 1-2 "${bam_filename}.faidx") \
                -a "${bam_filename}" \
                -b <("${AWK}" \
                        -F '\t' \
                        -v OFS='\t' \
                        -v window_size="${window_size}" \
                        -v faidx_filename="${bam_filename}.faidx" '
                            BEGIN {
                                # Read chromosome names from faidx file (made from BAM file).
                                while ( (getline < faidx_filename) > 0 ) {
                                    chromosomes_array[$1] = $1;
                                }
                            }
                            {
                                # Only use regions which chromosome is available in the BAM file.
                                if ($1 in chromosomes_array) {
                                    # Calculate the center of the region and take window_size up and down this center.
                                    region_center = $2 + int(($3 - $2) / 2);
                                    print $1, region_center - window_size, region_center + window_size + 1;
                                }
                            }' \
                            "${regions_bed_filename}" \
                        | bedtools sort -faidx "${bam_filename}.faidx" -i - \
                    ) \
               | cut -f 1-6 \
            ) \
  > output.bed
```

**Comment by uros-sipetic** [comment]
Hi, thanks for the answer
This did actually help a bit, the RAM usage dropped from around 63GB to just under 60GB, so I am able to get successful runs on my machine. Though RAM usage is still pretty high.

Just one note, since BEDtools version 2.24.0, the behavior of Coverage tool was changed to be the same as other tools, as I had to use the -a parameter with my BED file and the -b parameter with my BAM file both in Intersect and Coverage steps.

**Comment by ghuls** [comment]
> Just one note, since BEDtools version 2.24.0, the behavior of Coverage tool was changed to be the same as other tools, as I had to use the -a parameter with my BED file and the -b parameter with my BAM file both in Intersect and Coverage steps.

In the intersect step the -a parameter should be the BAM file.
In the coverage step the -a parameter should be the BED file.

What is the output of the following commands?
```bash
bedtools intersect -bed -u \
    -g organism.genome -sorted \
    -a sample.sorted.bam \
    -b organism.exons.bed \
  | head

bedtools intersect -bed -u \
    -g organism.genome -sorted \
    -a sample.sorted.bam \
    -b organism.exons.bed \
  | wc -c
```
If the intersection of all regions in organism.exons.bed with your BAM file, is almost the same than your whole BAM file, then this solution doesn't help that much.

In that case you might need to create multiple BED files (e.g. one for each chromsome) and run them after eachother, so the amount of RAM used per iteration is limited.
```bash
genome_file='organism.genome'
bed_input_file='organism.exons.bed'
bam_file='sample.sorted.bam'

for chrom in $(cut -f 1 ${genome_file}) ; do
    bedtools intersect -bed -u -sorted \
        -g ${genome_file} \
        -a ${bam_file} \
        -b <(awk -v "chrom=${chrom}" '$1 == chrom' ${bed_input_file}) \
      | bedtools faidx ${genome_file}  -i - \
      | bedtools coverage -sorted \
        -g ${genome_file} \
        -a <(awk -v "chrom=${chrom}" '$1 == chrom' ${bed_input_file}) \
        -b -
done > sample.bed
```

**Comment by uros-sipetic** [comment]
Hi 
@ghuls thank you for your answers before. 
I tried all of the solutions, but it seems the problem is very specific. 
The RAM issues don't seem to be dependent on the input BAM size, but rather on the sample itself. 
These issues are happening when I provide samples that have a huge number of reads aligning to just one chromosome. So in the case of these pile-ups, RAM just skyrockets to 100% and my execution fails. 
I guess this isn't something that can be fixed within the BEDtools toolkit itself or there are still some solutions I can try?

**Comment by vtadigotla** [comment]
I'm seeing similar RAM usage on a 12GB RNASeq bam aligned to the transcriptome with v2.26.0. The memory usage skyrocketed to 108 GB.  The only way I could get coverageBed to complete was to up the memory limit.

**Comment by arq5x** [comment]
Would you be able to share the command you are using?

**Comment by vtadigotla** [comment]
@arq5x  please see below
```
coverageBed -a gencodev25basic_transcriptome.bed -b postSample.bam -sorted  -g transcriptome_chromSizes.txt
```

**Comment by vtadigotla** [comment]
@arq5x I can provide a link to the bam and bed files, if it helps to debug.

**Comment by arq5x** [comment]
That would be great, thanks!

**Comment by vtadigotla** [comment]
@arq5x I've sent you the location via email. Thanks for looking into the issue.

**Comment by arq5x** [comment]
What is the largest interval size in `gencodev25basic_transcriptome.bed`?

Check with

    awk '{print $3-$2}' gencodev25basic_transcriptome.bed | sort -nr | head

**Comment by vtadigotla** [comment]
@arq5x  Were you able to reproduce the issue?

**Comment by ralonso-igenomix** [comment]
I am experiencing the same issue, but if it use 2.17 version everything works fine, bu I have to use this command:
bedtools coverage -b $bed -abam $bam

**Comment by aerijman** [comment]
Hi, this might be relevant. Using **-g MyGenome -sorted** ` bedtools coverage` dropped memory AND cpu usage by order/s of magnitude.   
The 64GB might go to ~1GB or even less.
