### ISSUE TITLE
Update on shuffle -incl issue?

### ISSUE THREAD

**Issue by ATpoint** [arq5x/bedtools2#493]
Dear all,

I am referring to #441 , where it has been issued that bedtools shuffle is unusably slow when using the -incl parameter. Aaron then mentioned that he implemented an improvement towards this issue. Is this already available somewhere? In the current 2.26.0. from GitHub, it is still unusably slow. In my case, I use ~25000 regions for -i, the ENCODE list for mappable regions for hg19 as -incl and the ENCODE blacklist for -excl. Running for 3days now and still not finished.

Is there any update on the issue?

best wishes,
-Alex

EDIT: I circumvented the problem now by just merging the -excl blacklist with the complement of my -incl regions, which is fine for my purpose. Just wondering if you plan to release an optimized version of shuffle with a fast -incl.

**Comment by ghuls** [comment]
I assume it is fixed in commit:
https://github.com/arq5x/bedtools2/commit/1b16530d89dfd727adb2be7f5b58957ae97c56c6

Clone bedtools from github and compile it, to have this fix.

**Comment by arq5x** [comment]
This indeed should resolve your issue. Please reopen if not.

Thanks for your help in responding to issues, @ghuls !
