### ISSUE TITLE
Zlib install problem 

### ISSUE THREAD

**Issue by natestockham** [arq5x/bedtools2#494]
Hi all,
I've have trouble installing bedtools due to a problem with zlib. I get this error regardless of what I do 

- Building main bedtools binary.
obj/gzstream.o: In function `gzstreambuf::open(char const*, int)':
gzstream.C:(.text+0xf2): undefined reference to `gzopen64'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

which seems similar to issue #430 

I have tried installing zlib 1.2.11 in a local directory, pointing my include CPPFLAGS to the local zlib/include/ folder there, adding the local zlib/lib folder to the LIBRARY_PATH and LD_LIBRARY_PATH variables, and changing the name of the binaries in the local zlib/lib from libz.so.1.2.11 to just libz.so. But, none of that works. 

I am working on a HPC cluster, and so I don't have root access. The version of zlib currently installed a /usr/lib64/libz.so is a link to a zlib at 1.2.3 version. 

Any ideas on how to redirect bedtools install to a local version of zlib? 

Thank you!

**Comment by natestockham** [comment]
I was able to resolve this on our system, but it required editing the Makefile. The instructions on how I solved it are here. 

https://groups.google.com/forum/#!topic/bedtools-discuss/70mDVWPz7RQ

basically, you have to add the path to the libz.a file to the BUILT_OBJECTS variable, so instead of 

BUILT_OBJECTS = $(OBJ_DIR)/*.o 

you need

BUILT_OBJECTS = $(OBJ_DIR)/*.o /PATH/TO/ZLIB/lib/libz.a

Can we add this into the current source, or at least put a notice on the FAQs in the documentation? It took a while to figure this out.

Thank you

**Comment by jmarshall** [comment]
There should already be facilities in the current source to do this, though perhaps they're not noted much in the documentation.  You should be able to override this without editing anything with

    make LIBS='/PATH/TO/ZLIB/lib/libz.a'

**Comment by arq5x** [comment]
Thanks for this solution, @jmarshall ! I have updated the docs.
http://bedtools.readthedocs.io/en/latest/content/faq.html#compiling-with-a-specific-zlib-library
