### ISSUE TITLE
Assertion failure when running the bedtools unionbedg example

### ISSUE THREAD

**Issue by klmr** [arq5x/bedtools2#496]
When running the “Default behaviour” [example](http://bedtools.readthedocs.io/en/latest/content/tools/unionbedg.html) for the `bedtools unionbedg` command, I reproducibly get an assertion failure:

```bash
⟩⟩⟩ more 1.bg
chr1 1000 1500 10
chr1 2000 2100 20
⟩⟩⟩ more 2.bg
chr1 900 1600 60
chr1 1700 2050 50
⟩⟩⟩ more 3.bg
chr1 1980 2070 80
chr1 2090 2100 20
⟩⟩⟩ bedtools unionbedg -i 1.bg 2.bg 3.bg
Assertion failed: (!queue.empty()), function ConsumeNextCoordinate, file unionBedGraphs.cpp, line 99.
Abort trap: 6
```

**Comment by arq5x** [comment]
This works fine for me using 2.26.0 and the latest version in github. I suspect that whn you copy and pasted the example files from the web page, you may have not replaced spaces with tabs to delimit the columns or perhaps the newlines became garbled.

Please test for this using `cat -t`.

**Comment by klmr** [comment]
Indeed, that was it. I had previously had the same problem with my own BedGraph files. Turns out they were wrong, too (note to self: `awk`’s `FS` doesn’t set `OFS`).

That said, faulty user input shouldn’t really trigger an assertion. It would be nice if there were an explicit error message about this.
