### ISSUE TITLE
Broken rendering of literal blocks in documentation

### ISSUE THREAD

**Issue by rmzelle** [arq5x/bedtools2#500]
All the reStructuredText literal blocks (http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks) render incorrectly in the bedtools documentation. They seem to be rendered as HTML definition lists instead. See e.g.:

http://bedtools.readthedocs.io/en/latest/content/tools/sort.html

Source (https://raw.githubusercontent.com/arq5x/bedtools2/74e17388a4e8616f0570cbe330f6c0b102c4f746/docs/content/tools/sort.rst): 

```
::
  sortBed [OPTIONS] -i <BED/GFF/VCF>
```

Screenshot:

![image](https://cloud.githubusercontent.com/assets/77951/23872580/35515614-0805-11e7-968a-5dd30492fc77.png)

HTML:

```html
<dl class="docutils">
<dt>::</dt>
<dd>sortBed [OPTIONS] -i &lt;BED/GFF/VCF&gt;</dd>
</dl>
```

**Comment by rmzelle** [comment]
I looked a bit closer at this (by building the docs locally with Sphinx, and by using the online reStructuredText editors http://rst.ninjs.org/ and https://livesphinx.herokuapp.com/, and looking at http://docutils.sourceforge.net/docs/user/rst/quickref.html#literal-blocks again), and it's now clear to me that this is a markup problem. The `::` indicates that the next block/paragraph is a literal block, so there should be an additional separating line after it.

Sphinx 1.5.3 output for

```rst
For example:

::
  cat A.bed
  chr1 800 1000
  chr1 80  180
  chr1 1   10
  chr1 750 10000

  sortBed -i A.bed
  chr1 1   10
  chr1 80  180
  chr1 750 10000
  chr1 800 1000

For example:

::

  cat A.bed
  chr1 800 1000
  chr1 80  180
  chr1 1   10
  chr1 750 10000

  sortBed -i A.bed
  chr1 1   10
  chr1 80  180
  chr1 750 10000
  chr1 800 1000
```

![image](https://cloud.githubusercontent.com/assets/77951/23919464/49b36be2-08cd-11e7-9dff-2b9df3d6c387.png)

(top is excerpt from http://bedtools.readthedocs.io/en/latest/content/tools/sort.html, bottom is corrected excerpt)

**Comment by rmzelle** [comment]
@arq5x, would you take a PR to fix all occurrences in the documentation files?

**Comment by arq5x** [comment]
Of course! Thanks for tracking this down!
