### ISSUE TITLE
intersectBed -c returning more "hits" than files being compared

### ISSUE THREAD

**Issue by ssefick** [arq5x/bedtools2#505]
Hello,

I am having an issue when using intersect bed. I am using 4 pre-sorted bed files, and intersectBed -sorted -c -a file1 -b file2 file3 file4. I am receiving count values from 0-6. I was expecting 0-3. Any help would be greatly appreciated.
kindest regards,

Stephen Sefick

**Comment by arq5x** [comment]
It is returning the number of hits per file, not the number of files with hits.
