### ISSUE TITLE
test_sort.sh not found

### ISSUE THREAD

**Issue by simone-rizzetto** [arq5x/bedtools2#506]
Apologies if this was already reported, I didn't find anything in the reported issues

version 2.26.0 
bash: test-sort.sh: No such file or directory

test/test.sh line 59:
cd **slop**; bash test-sort.sh; cd ..
I think it should be
cd **sort**; bash test-sort.sh; cd ..

**Comment by ghuls** [comment]
This should be fixed in git.
**test/test.sh** is completely rewritten.
