### ISSUE TITLE
Intersect multiple databases

### ISSUE THREAD

**Issue by Dr-Drosophila** [arq5x/bedtools2#509]
# Cannot see filenames for intersecting multiple databases.

bedtools intersect -filenames -a A.bed -b B*.bed | less
# has the same output as 
bedtools intersect  -a A.bed -b B*.bed | less

**Comment by arq5x** [comment]
What version?  Here is what I see with what is in github:

```
➜  cat a.bed
chr1	10	20
➜  cat b1.bed
chr1	11	21
➜  cat b2.bed
chr1	12	22
➜  bedtools intersect -a a.bed -b b*.bed -wa -wb
chr1	10	20	1	chr1	11	21
chr1	10	20	2	chr1	12	22
➜  bedtools intersect -filenames -a a.bed -b b*.bed -wa -wb
chr1	10	20	b1.bed	chr1	11	21
chr1	10	20	b2.bed	chr1	12	22
```
