### ISSUE TITLE
subtractBed on vcfs duplicates the indels from the first file

### ISSUE THREAD

**Issue by rvijaya** [arq5x/bedtools2#51]
discovered it is 2.17, but replicated it is latest version from git (v2.19.1-10-g377f1b1):

If an indel in the first file overlaps multiple variants from the second file, the indel is repeated multiple times in subtractBed output. Here is an example:

rvijaya@ubuntu:~/misc/temp$ cat testbed1.vcf
##fileformat=VCFv4.1
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample
chr1    5935162 rs1287637       AAAAAAAAAAAAAAA T       14677.8 PASS    AC=2;AF=1.00;AN=2;DP=625;Dels=0.00      GT:AD:DP:GQ:PL  1/1:0,625:625:99:14706,1035,0
rvijaya@ubuntu:~/misc/temp$ cat testbed2.vcf
##fileformat=VCFv4.1
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample
chr1    5935162 rs1287637       A       T       14677.8 PASS    AC=2;AF=1.00;AN=2;DP=625;Dels=0.00      GT:AD:DP:GQ:PL  1/1:0,625:625:99:14706,1035,0
chr1    5935168 rs3747992;COSM426517    G       A       20400.8 PASS    AC=1;AF=0.500;AN=2;BaseQRankSum=24.992;DP=2096;Dels=0.00        GT:AD:DP:GQ:PL  0/1:1048,1046:2096:99:20429,0,19945
rvijaya@ubuntu:~/misc/temp$ ~/software/bedtools2/bin/subtractBed -a testbed1.vcf -b testbed2.vcf
chr1    5935162 rs1287637       AAAAAAAAAAAAAAA T       14677.8 PASS    AC=2;AF=1.00;AN=2;DP=625;Dels=0.00      GT:AD:DP:GQ:PL  1/1:0,625:625:99:14706,1035,0
chr1    5935162 rs1287637       AAAAAAAAAAAAAAA T       14677.8 PASS    AC=2;AF=1.00;AN=2;DP=625;Dels=0.00      GT:AD:DP:GQ:PL  1/1:0,625:625:99:14706,1035,0

**Comment by freeseek** [comment]
I have a similar issue with bedtools intersect. It duplicates variants when intersecting with a bed file. Here is an example:
(echo "##fileformat=VCFv4.1"
echo -e "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"
echo -e "1\t1172783\t.\tCCTCTGTCCTGGTCGCGTTGCCCAGCG\tC\t.\t.\t."
echo -e "1\t1172784\t.\tC\tT\t.\t.\t.") > in.vcf
(echo -e "1\t1172777\t1172804"
echo -e "1\t1172806\t1172808") > in.bed
bedtools intersect -a in.vcf -b in.bed

**Comment by nkindlon** [comment]
That's actually the intended default behavior for intersect. If you instead only want one entry for each query record (variant, in this case), regardless of the number of database records it intersects, you can use the -u option. You could also use -c to get the variant just once along with the count of records it intersected. Here's the docs page for more details:
http://bedtools.readthedocs.org/en/latest/content/tools/intersect.html

Hope this helps. Please let us know if it's not clear or there are other question. 
Thanks,
Neil

**Comment by freeseek** [comment]
Apologies, as I did not properly read the documentation. In retrospect it makes sense, but it was counter-intuitive that this is the default behavior for VCFs.

**Comment by nkindlon** [comment]
No prob. Where possible, the tools do try to use the same behavior for all formats so that they can be used interchangeably with minimal effort for the user. We can always make changes for specific formats, of course, if they don't hinder what people are expecting (we try not make changes that will break existing scripts, for example).

**Comment by nkindlon** [comment]
So I guess we can close this one?

**Comment by rvijaya** [comment]
Yes
