### ISSUE TITLE
Strand-aware merge (-s and -S) create malformed Bed6 files

### ISSUE THREAD

**Issue by ingolia** [arq5x/bedtools2#514]
The output from a strand-aware merge (either merge -s that obeys strandedness when merging, or merge -S that filters for one strand) writes strand information into the **4th** column of the output, but the strand should be the **6th** column when it's present. 

This behavior was introduced in #254 to address the fact that the strand info was discarded entirely unless the -c and -o options were used. However, the current solution adds the strand information in the wrong place.

**Comment by ghuls** [comment]
I think it is difficult to create valid BED6 files as it is not easy to choose what to put in column 4 and 5:
```
$ ./bedtools merge -s -d 10 -i test/merge/a.full.bed 
chr1	10	100	+
chr1	40	50	-
chr2	10	50	+
chr2	45	100	-

$ ./bedtools merge -s -d 10 -c 4,5 -o collapse,collapse -i test/merge/a.full.bed 
chr1	10	100	+	a1,a2,a4	1,2,4
chr1	40	50	-	a3	3
chr2	10	50	+	a1,a2,a3	5,6,7
chr2	45	100	-	a4	8

$ ./bedtools merge -s -d 10 -c 4,5 -o collapse,collapse -i test/merge/a.full.bed | awk -F '\t' -v 'OFS=\t' '{ strand = $4; name = $5; score = $6; $4 = name; $5 = score; $6 = strand; print $0; }' 
chr1	10	100	a1,a2,a4	1,2,4	+
chr1	40	50	a3	3	-
chr2	10	50	a1,a2,a3	5,6,7	+
chr2	45	100	a4	8	-

```
