### ISSUE TITLE
intersect with multiple BAM files and count option

### ISSUE THREAD

**Issue by chrarnold** [arq5x/bedtools2#520]
Hi,

I noticed that when using intersect with multiple BAM files as input and the count option, the output does not contain any reference to the file the overlap comes from, and -filenames is ignored. Also, -wa and -wb cannot be used with -c, so I currently see no way how to do that?

bedtools intersect  -a bed  -b *.bam  -c  -sorted -filenames > out.bed

**Comment by arq5x** [comment]
This currently isn't implemented, but using -wa and -wb together with groupby, you can get the desired effect.

```
bedtools intersect -filenames -a a.bed -b b.bed c.bed -wa -wb
chr1	10	20	b.bed	chr1	11	21
chr1	10	20	c.bed	chr1	12	22
chr1	20	30	b.bed	chr1	11	21
chr1	20	30	b.bed	chr1	21	31
chr1	20	30	c.bed	chr1	12	22
chr1	20	30	c.bed	chr1	22	32
chr1	29	40	b.bed	chr1	21	31
chr1	29	40	b.bed	chr1	30	41
chr1	29	40	c.bed	chr1	22	32
chr1	29	40	c.bed	chr1	32	42
chr1	100	200	b.bed	chr1	101	201
chr1	100	200	c.bed	chr1	102	202
```

Use groupby (get the latest version from github) to count:

```
bedtools intersect -filenames -a a.bed -b b.bed c.bed -wa -wb | bedtools groupby -g 1-4, -o count -c 4
chr1	10	20	b.bed	1
chr1	10	20	c.bed	1
chr1	20	30	b.bed	2
chr1	20	30	c.bed	2
chr1	29	40	b.bed	2
chr1	29	40	c.bed	2
chr1	100	200	b.bed	1
chr1	100	200	c.bed	1
```

**Comment by gupta567varun** [comment]
Hi,
I have 4 bam files, and I want to use this command 
`intersectBed -f 1 -c -split -sorted -a test.bed -b A1.bam A2.bam B1.bam B2.bam`

I only get 1 extra column which gives the sum of all the counts for that particular bed interval  from all 4 bam files. Is it possible to get 4 additional count columns for every bed interval?

Thanks
