### ISSUE TITLE
Output merged adjacent ranges in BED format

### ISSUE THREAD

**Issue by mmokrejs** [arq5x/bedtools2#524]
I wan to get region having coverage above a certain threshold. Seems this is not yet implemented. The closest seems to me:

```
bedtools genomecov -bg -ibam $f | awk '$4 > 15' > $p.coverage.bed

scaffold3	2254	2374	67
scaffold3	2374	2375	66
scaffold3	2375	2378	64
scaffold3	2380	2401	66
scaffold10	6970	6993	10
scaffold10	6993	6994	16
scaffold10	6994	7003	15
scaffold10	7003	7022	16
scaffold10	7022	7027	17
scaffold10	7027	7030	18
```

but I have adjacent ranges on multiple lines, whenever the coverage differs. It would be nice if one could get less lines output by merging the coverage across mutiple rows (computing some average coverage), possibly overcoming some uncovered distance between two ranges.

That would give lines only, and the coverage could be a sum of the coverages divided by covered length:

```
scaffold3	2254	2401	sum($range2coverage[i]) / sum($len[i])
scaffold10	6970	7030	sum($range2coverage[i]) / sum($len[i])
```

**Comment by arq5x** [comment]
If you pipe your input into this it should work. First it uses awk to print the length of the interval and the _scaled_ (depth*length) coverage. Then it uses `merge` to compute the total length and total scaled coverage for all of the overlapping intervals. Then it uses awk again to report the scaled averaged coverage for the combined region.

```
cat genomecov.bed
scaffold3	2254	2374	67
scaffold3	2374	2375	66
scaffold3	2375	2378	64
scaffold3	2380	2401	66
scaffold10	6970	6993	10
scaffold10	6993	6994	16
scaffold10	6994	7003	15
scaffold10	7003	7022	16
scaffold10	7022	7027	17
scaffold10	7027	7030	18
```

Then:
```
awk '{OFS="\t"; print $0,$3-$2,$4*($3-$2)}' genomecov.bed | bedtools merge -i - -c 5,6 -o sum,sum | awk '{print $0"\t"$5/$4}'
scaffold3	2254	2378	124	8298	66.9194
scaffold3	2380	2401	21	1386	66
scaffold10	6970	7030	60	824	13.7333
```

If you want "nearby" intervals to be merged, you could use -d (in this case merge intervals separated by at most 2 bp.

``` awk '{OFS="\t"; print $0,$3-$2,$4*($3-$2)}' genomecov.bed | bedtools merge -i - -d 2 -c 5,6 -o sum,sum | awk '{print $0"\t"$5/$4}'
scaffold3	2254	2401	145	9684	66.7862
scaffold10	6970	7030	60	824	13.7333
```

**Comment by arq5x** [comment]
The obvious problem you have here is that you need a minimum to break up the output of `genomecov`, else you will compute the weighted mean of the whole chromosome.

**Comment by mmokrejs** [comment]
Hi Aaron, yes this is exactly what I wanted. I think this should be exposed directly through bedtools without the need for awk hackery. Getting a BED file directly out of bedtools sound like an expected feature. Yes, supposedly one does not want to merge the coverage across a whole chromosome but overcoming short gaps is necessary.
