### ISSUE TITLE
Report clear error message if BED file columns are not separated by TAB

### ISSUE THREAD

**Issue by mmokrejs** [arq5x/bedtools2#525]
I hit the following error with 2.26.0:

`Received illegal bin number 4294967295 from getBin call`

I see this relevant for #368. I wanted to sort the BED files to be sure I know what I feed into `bedtools coverage -hist -abam {} -b $p.coverage.3cols.bed` and it complained (luckily) the colums are not separated by a TAB. After `awk -F=\t '{print $1,$2,$3}' $f | bedtools sort` step I could proceed with `bedtools coverage`. Please improve `bedtools coverage` to check its input.

**Comment by arq5x** [comment]
Could you provide a simple example file that produces this error?
