### ISSUE TITLE
Lines starting with "all" missing in coverage output

### ISSUE THREAD

**Issue by gk-bioin4m8x** [arq5x/bedtools2#526]
Hi,
I am using bedtools v2.26.0 and used following command to find coverage of my sample (paired-end exome). Acoording to <http://tagteam.harvard.edu/hub_feeds/1981/feed_items/382070> and <https://groups.google.com/forum/#!msg/bedtools-discuss/n2rNbRGRTvI/gg8TcbnT698J;context-place=searchin/bedtools-discuss/coverage$20histogram%7Csort:relevance> there are lines starting with all, but they are missing from my output. Kindly guide how I should go further to plot.

`bedtools coverage -hist -a sample.bed -b cds.bed > out.coveragehist`

> ############### sample.bed has been generated as follows: ########################

> extracting properly-paired reads

`samtools view -bf 0x2 sample.bam | bedtools bamtobed -i stdin -bedpe > sample.bedpe`

>bedpe to bed conversion  

`cut -f 1,2,6 sample.bedpe > sample.bed`
	
> already sorted by chromosome and location, so did not use: `sort -k1,1 -k2,2n sample.bed` 
############################################################################

Thanks !

**Comment by gk-bioin4m8x** [comment]
Any hints please?

**Comment by gk-bioin4m8x** [comment]
@arq5x  I am still waiting for the answer. :P

**Comment by arq5x** [comment]
I cannot reproduce this problem. Can you send minimal data files that create this issue?
