### ISSUE TITLE
missing output after intersect

### ISSUE THREAD

**Issue by geshtin** [arq5x/bedtools2#528]
ls,

I have two bed files, containing these lines:
file 1
....
SL2.40ch08      2942462 2947561 Solyc08g008550.2        0       -
SL2.40ch08      2940546 2945645 Solyc08g008560.1        0       +
....
file 2
...
SL2.40ch08      2942446 2942464 Solyc03g118160.1        0       +
SL2.40ch08      2942446 2942464 Solyc03g118160.1        0       -
...
executing bedtools intersect -a file1 -b file2
Only two records are retrieved:

SL2.40ch08      2942462 2942464 Solyc08g008550.2        0       -
SL2.40ch08      2942462 2942464 Solyc08g008550.2        0       -

, while I expect 4
executing with the -s option: bedtools intersect -a file1 -b file2 -s
I retrieve NO records.

I checked for \r symbols:
sed -i 's/\r\n/\n/g' file*
I checked that they were tab delimited:
grep -c $'[A-Za-c0-9}*\t[0-9*\t[0-9]*' file*
and obtained correct counts.
and finally I checked the scaffold names:
 cat file* | cut -f 1 | sort -u
and obtained the expected entries

What else could be wrong?
btw i'm 
Running bedtools v2.26.0
Linux: Scientific Linux release 6.0 (Carbon).

Thnx Raymond

**Comment by arq5x** [comment]
I am unable to reproduce this with version 2.26 using the examples you provided. I would check for trailing whitespace after the strand infor in both files. Will try to think of other causes.

**Comment by geshtin** [comment]
thanks for the input. In rerunning it with an adjusted bash script solved the problem. I linked to the wrong file most likely. As now I get the expected result. Anyhow, thanks again, sorry for the inconvenience.
