### ISSUE TITLE
Different outcomes from genomecov and coverage?

### ISSUE THREAD

**Issue by laura-oikkonen** [arq5x/bedtools2#534]
Hello,
I have tried out both genomecov and coverage for comparison purposes on the same dataset. I am aware that they don't produce identically formatted output or total counts, but I still think that for a specific chromosome or scaffold (ERCC-00002 in this case), the counts ber base should be the same when the same input bam file is used. With bedtools coverage, I have only computed the coverage histogram for ERCC-00002. This is an example of what I get with coverage:

ERCC-00002      0       1061    29697   1       1061    0.0009425
ERCC-00002      0       1061    37470   1       1061    0.0009425
ERCC-00002      0       1061    46738   1       1061    0.0009425
ERCC-00002      0       1061    57404   1       1061    0.0009425
ERCC-00002      0       1061    69852   1       1061    0.0009425
ERCC-00002      0       1061    83488   1       1061    0.0009425
ERCC-00002      0       1061    87132   1       1061    0.0009425
ERCC-00002      0       1061    92616   1       1061    0.0009425
ERCC-00002      0       1061    97783   1       1061    0.0009425
ERCC-00002      0       1061    111559  1       1061    0.0009425
ERCC-00002      0       1061    122200  1       1061    0.0009425
ERCC-00002      0       1061    124039  1       1061    0.0009425
ERCC-00002      0       1061    127261  1       1061    0.0009425
ERCC-00002      0       1061    133507  1       1061    0.0009425
ERCC-00002      0       1061    135795  1       1061    0.0009425
ERCC-00002      0       1061    136020  1       1061    0.0009425
ERCC-00002      0       1061    139408  1       1061    0.0009425
....

and genomecov:
ERCC-00002      29697   1       1061    0.000942507
ERCC-00002      37470   1       1061    0.000942507
ERCC-00002      46738   1       1061    0.000942507
ERCC-00002      57404   1       1061    0.000942507
ERCC-00002      69852   1       1061    0.000942507
ERCC-00002      83488   1       1061    0.000942507
ERCC-00002      87132   1       1061    0.000942507
ERCC-00002      92616   1       1061    0.000942507
ERCC-00002      97783   1       1061    0.000942507
ERCC-00002      111559  1       1061    0.000942507
ERCC-00002      122200  1       1061    0.000942507
ERCC-00002      124039  1       1061    0.000942507
ERCC-00002      126686  1       1061    0.000942507
ERCC-00002      126918  1       1061    0.000942507
ERCC-00002      132478  1       1061    0.000942507
ERCC-00002      133247  1       1061    0.000942507
ERCC-00002      135358  1       1061    0.000942507
ERCC-00002      136020  1       1061    0.000942507
ERCC-00002      138243  1       1061    0.000942507
ERCC-00002      138313  1       1061    0.000942507
ERCC-00002      139361  1       1061    0.000942507
ERCC-00002      140509  1       1061    0.000942507
ERCC-00002      144432  1       1061    0.000942507
ERCC-00002      145274  1       1061    0.000942507
ERCC-00002      145432  1       1061    0.000942507

So the output is the same until row 13, and then the discrepancies start. I was wondering, is there an explanation for this, or which numbers should I be using? I am using bedtools 2.26.

Many thanks,
Laura

**Comment by arq5x** [comment]
It is hard to know exactly what might be going on without seeing your commands and the files you used. Could you update the issue accordingly?

**Comment by laura-oikkonen** [comment]
Here are the commands and input files I used:

bedtools genomecov -ibam ERCC-00002.bam

bedtools coverage -b ERCC-00002.bam -a ERCC.bed -hist

The bam file is here: http://www.well.ox.ac.uk/~loikkone/bedtools-file/

And the ERCC.bed file is simply:
ERCC-00002      0       1061

**Comment by arq5x** [comment]
Hi Laura,

I looked at the alignments in IGV and this comes from the fact that `genomecov` does not count coverage when there are gaps in the alignment whereas the `coverage` tool does.
For example, in the snapshot below, position 6 has a depth of 132478 if gaps in the alignment are not counted.
![image](https://cloud.githubusercontent.com/assets/72291/26645132/509f4bb0-45f4-11e7-8751-57ef15553bcc.png)

This is the value from `genomecov`:

```
bedtools genomecov -ibam ERCC-00002.bam -d | head -20
ERCC-00002	1	87132
ERCC-00002	2	92616
ERCC-00002	3	122200
ERCC-00002	4	126686
ERCC-00002	5	133247
ERCC-00002	6	132478
ERCC-00002	7	135358
ERCC-00002	8	138313
ERCC-00002	9	138243
ERCC-00002	10	140509
ERCC-00002	11	126918
ERCC-00002	12	144432
ERCC-00002	13	148415
ERCC-00002	14	159117
ERCC-00002	15	160738
ERCC-00002	16	154287
ERCC-00002	17	163536
ERCC-00002	18	161148
ERCC-00002	19	145432
ERCC-00002	20	153972
```

Yet, `coverage` counts the gaps:

```bedtools coverage -a ERCC.bed -b ERCC-00002.bam -d | head -20
ERCC-00002	0	1061	1	87132
ERCC-00002	0	1061	2	92616
ERCC-00002	0	1061	3	122200
ERCC-00002	0	1061	4	127261
ERCC-00002	0	1061	5	133507
ERCC-00002	0	1061	6	135795
ERCC-00002	0	1061	7	139408
ERCC-00002	0	1061	8	141498
ERCC-00002	0	1061	9	142849
ERCC-00002	0	1061	10	148624
ERCC-00002	0	1061	11	154160
ERCC-00002	0	1061	12	156346
ERCC-00002	0	1061	13	159690
ERCC-00002	0	1061	14	163200
ERCC-00002	0	1061	15	164868
ERCC-00002	0	1061	16	165779
ERCC-00002	0	1061	17	167941
ERCC-00002	0	1061	18	169059
ERCC-00002	0	1061	19	169459
ERCC-00002	0	1061	20	170733```

I think the `genomecov` is technically more correct, but it depends on your needs.

**Comment by laura-oikkonen** [comment]
Many thanks Aaron for the clarification! I think that genomecov would be better suited for my work, so I will stick with it then.
