### ISSUE TITLE
Is there a proposed release calendar for the 2.27 version?

### ISSUE THREAD

**Issue by lucventurini** [arq5x/bedtools2#535]
I am asking as version 2.26 was released a while ago, and some notable bugs (eg performance of coverage with sorted BAMs) have been fixed in the master branch since. For reproducibility, it would be nice to use an official release, rather than a tagged clone of the master branch.

**Comment by arq5x** [comment]
Yep, the goal is August 2017. Thanks for asking.

**Comment by lucventurini** [comment]
Dear Aaron, any news on this front?

**Comment by arq5x** [comment]
Hi,

Yes, we are working towards this goal, but a critical barrier is solving a memory leak in one of the core algorithms. I am working with @nkindlon on this, but it will likely take several more weeks given our workloads.  Sorry for the delay.

Aaron
