### ISSUE TITLE
Bedtools subtract : non-overlapping regions

### ISSUE THREAD

**Issue by tedtoal** [arq5x/bedtools2#541]
The bedtools subtract command documentation indicates that the output will not include regions of A that do not overlap B by at least one base pair.  An error occurs if one attempts to set -f or -F to 0.  However, the pictorial example in the documentation shows such a region being included in the output.  It is sometimes desireable to include non-overlapping A regions in the output, so it should be possible to do that.

**Comment by arq5x** [comment]
Can you provide an example that shows `subtract` not doing what you want?  It seems to work as expected for me.

```
cat a.bed
chr1	1	100	feature1	0	+
chr1	100	200	feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	-

cat b.bed
chr1	110	120

bedtools subtract -a a.bed -b b.bed
chr1	1	100	feature1	0	+
chr1	100	110	feature2	0	+
chr1	120	200	feature2	0	+
chr1	150	500	feature3	0	-
chr1	900	950	feature4	0	-
```

**Comment by tedtoal** [comment]
I no longer remember exactly what I was doing here, and what I write doesn't make complete sense to me.  As your example AND the documentation show, the program seems to do what I seem to be saying I want.

Here's what I recommend: change the first paragraph of the "subtract" documentation to:

```
bedtools` subtract searches for features in B that overlap A by at least the number of base pairs given by the -f option. If an overlapping feature is found in B, the overlapping portion is removed from A and the remaining portion of A is reported. If a feature in B overlaps all of a feature in A, the A feature will not be reported.  If a feature in B does not overlap a feature in A by at least the -f amount, the A feature will be reported in its entirety.
```
Another possibility is to add an option that causes the A feature to not be reported at all when there is insufficient overlap, but I don't know if that would actually be useful.

**Comment by arq5x** [comment]
Thank you for the nice suggestion. Will do.
