### ISSUE TITLE
Shift not found

### ISSUE THREAD

**Issue by SumNeuron** [arq5x/bedtools2#542]
Installing bedtools following:

```
$ wget https://github.com/arq5x/bedtools2/releases/download/v2.25.0/bedtools-2.25.0.tar.gz
$ tar -zxvf bedtools-2.25.0.tar.gz
$ cd bedtools2
$ make
```

and moving the contents of bedtools2/bin to /usr/local/bin

results in a lack of the command shift

**Comment by arq5x** [comment]
Install the latest version from github.
