### ISSUE TITLE
groupby does not work

### ISSUE THREAD

**Issue by map2085** [arq5x/bedtools2#543]
`groupby` is not working correctly in 2.26.0
please see the following example:

> $ cat mt
> a	18	0.999851
> a	18	0.999982
> a	18	0.999993
> a	18	0.999995
> a	18	0.999999
> a	19	0.0803295
> a	19	0.0803296
> a	19	0.999997
> a	20	1
> a	20	1
> $ bedtools  groupby  -g 1,2  -c 3  -o sum  -i mt
> 8.1604761
> $ bedtools  --version
> bedtools v2.26.0

**Comment by arq5x** [comment]
this is fixed in master and will be part of the 2.27 release
