### ISSUE TITLE
Print values for each base pair including missing values in bedtools map

### ISSUE THREAD

**Issue by yewero** [arq5x/bedtools2#548]
Bedtools map usually print the values for regions not each base pair, also it may skip the missing values in the output, for example:
> $ cat a.bed
> chr1        11      16      a1      1       +

> $ cat b.bed
> chr1        12      13      b1      2       +
> chr1        13      15      b2      5       -

> $ bedtools map -a a.bed -b b.bed -c 5 -o collapse
> chr1        11      16      a1      1       +       2,5

The output `2,5,5` only covered the 3 base pairs but other missing values were skipped.
How could these missing values be printed for each base pair? Such as:
> chr1        11      16      a1      1       +       NA,2,5,5,NA

So that the length of output equals the length of input region in a.bed

**Comment by arq5x** [comment]
The `map` tool reports info from the `-b` file based upon _interval_ overlaps, not specific base pairs within the interval. What you want to do is not possible with the `map` tool. However, you could "expand" your records in the A file into 1 bp intervals with the `makewindows` tool:

    bedtools makewindows -b a.bed -w 1 -i src \
    | bedtools map -a - -b b.bed -c 5 -o collapse
    chr1	11	12	a1	.
    chr1	12	13	a1	2
    chr1	13	14	a1	5
    chr1	14	15	a1	5
    chr1	15	16	a1	.

If you wanted the values as a comma-separated list, you could use `groupby` (grouping on the chrom (1st) name (4th) column) and taking the min of the starts, the max of the ends and collapsing the values from B in the `map` command:

    bedtools makewindows -b a.bed -w 1 -i src \
    | bedtools map -a - -b b.bed -c 5 -o collapse \
    | bedtools groupby -g 1,4 -c 1,2,3,5 -o distinct,min,max,collapse
