### ISSUE TITLE
bedtools intersect "-r"

### ISSUE THREAD

**Issue by zhangaaaaa** [arq5x/bedtools2#550]
$ cat a.bed 
chr1    98      100
$ cat b.bed 
chr1    99      200
$ bedtools intersect -a a.bed -b b.bed  -f 0.5 -r -wa -wb
chr1    98      100     chr1    99      200

-r : Require that the fraction overlap be reciprocal for A AND  B. 
In this case the overlap( chr1:99-100) is note reciprocal for a.bed AND  b.bed

**Comment by arq5x** [comment]
This works as expected with the latest release in github.
