### ISSUE TITLE
Suggestion: basic error handling in fastaFromBed

### ISSUE THREAD

**Issue by SumNeuron** [arq5x/bedtools2#551]
So my text file is also used by another language which can read types based on basic semantics, e.g. all ints in the file is interpreted as an int type, and characters wrapped in quotes are taken as strings, etc. Previously running fastaFromBed with such a file (e.g. "chr1" 100 150 ...) worked, but now it does not take "chr1" but just chr1.

It would be nice if bedtools auto-stripped quotes

**Comment by arq5x** [comment]
Bedtools will not support this, but it is simple to fix:

    sed -e 's/\"//g' file.fa > file.noquotes.fa
