### ISSUE TITLE
multicov bug?

### ISSUE THREAD

**Issue by sterding** [arq5x/bedtools2#552]
I found that if the input bam file repeats (or reoccurs) in the input list, it will output 0 for the first occurrence, and the cumulative sum for the last occurrence, which is strange. Is this designed like this?

$ bedtools multicov -split -bams $i  -bed test.bed 
chr10	100380464	100380466	chr10_100242392_100380465	0
chr10	100242391	100242393	chr10_100242392_100380465	0
chr10	101165616	101165618	chr10_101165512_101165617	86
chr10	101165511	101165513	chr10_101165512_101165617	82
chr10	101480824	101480826	chr10_101480743_101480825	48
chr10	101480742	101480744	chr10_101480743_101480825	67
chr10	101923851	101923853	chr10_101923760_101923852	9
chr10	101923759	101923761	chr10_101923760_101923852	7
chr10	101934037	101934039	chr10_101923760_101934038	11
chr10	101923759	101923761	chr10_101923760_101934038	7

$ bedtools multicov -split -bams $i $i  -bed test.bed 
chr10	100380464	100380466	chr10_100242392_100380465	0	0
chr10	100242391	100242393	chr10_100242392_100380465	0	0
chr10	101165616	101165618	chr10_101165512_101165617	0	172
chr10	101165511	101165513	chr10_101165512_101165617	0	164
chr10	101480824	101480826	chr10_101480743_101480825	0	96
chr10	101480742	101480744	chr10_101480743_101480825	0	134
chr10	101923851	101923853	chr10_101923760_101923852	0	18
chr10	101923759	101923761	chr10_101923760_101923852	0	14
chr10	101934037	101934039	chr10_101923760_101934038	0	22
chr10	101923759	101923761	chr10_101923760_101934038	0	14

$ bedtools multicov -split -bams $i $i $i -bed test.bed 
chr10	100380464	100380466	chr10_100242392_100380465	0	0	0
chr10	100242391	100242393	chr10_100242392_100380465	0	0	0
chr10	101165616	101165618	chr10_101165512_101165617	0	0	258
chr10	101165511	101165513	chr10_101165512_101165617	0	0	246
chr10	101480824	101480826	chr10_101480743_101480825	0	0	144
chr10	101480742	101480744	chr10_101480743_101480825	0	0	201
chr10	101923851	101923853	chr10_101923760_101923852	0	0	27
chr10	101923759	101923761	chr10_101923760_101923852	0	0	21
chr10	101934037	101934039	chr10_101923760_101934038	0	0	33
chr10	101923759	101923761	chr10_101923760_101934038	0	0	21

Even if I insert a differnet bam file between:

$ bedtools multicov -split -bams $i $j $i -bed test.bed 
chr10	100380464	100380466	chr10_100242392_100380465	0	12	0
chr10	100242391	100242393	chr10_100242392_100380465	0	380	0
chr10	101165616	101165618	chr10_101165512_101165617	0	4	172
chr10	101165511	101165513	chr10_101165512_101165617	0	0	164
chr10	101480824	101480826	chr10_101480743_101480825	0	0	96
chr10	101480742	101480744	chr10_101480743_101480825	0	0	134
chr10	101923851	101923853	chr10_101923760_101923852	0	0	18
chr10	101923759	101923761	chr10_101923760_101923852	0	0	14
chr10	101934037	101934039	chr10_101923760_101934038	0	0	22
chr10	101923759	101923761	chr10_101923760_101934038	0	0	14

I'm using the v2.26.0 version.

**Comment by arq5x** [comment]
you would need to have distinct file names.
