### ISSUE TITLE
Error Message for Unsorted Files Would Be Helpful in groupBy

### ISSUE THREAD

**Issue by imk1** [arq5x/bedtools2#556]
groupBy requires that the bed file be sorted in the order of the columns specified by -g.  It would be helpful if bedtools through an error when this is not the case.  (I think that bedtools already does this for mergeBed, which is very helpful.)  Thanks!

**Comment by arq5x** [comment]
I understand the desire here, but `groupby` only requires that the data for the grouping column arq "grouped" together. It doesn't expect a specific sorting order because it cannot know how the column was sorted (asc, desc, numeric, alpha, etc).
