### ISSUE TITLE
groupBy did not group

### ISSUE THREAD

**Issue by bchen4** [arq5x/bedtools2#558]
Hi, I am using Bedtools 2.26 groupBy function and I have a demo.bed.

```
chr1  3803892 3803908 BRN_IP_WT_A_pos_1 14  +
chr1  3803892 3803908 BRN_IP_A_S2_positive_1  14  +
chr1  4493610 4493620 BRN_IP_WT_A_pos_2 3 +
chr1  4493610 4493620 BRN_IP_A_S2_positive_2  3 +
chr1  4529016 4529066 BRN_IP_WT_A_pos_3 7 +
chr1  4529016 4529066 BRN_IP_A_S2_positive_3  7 +
chr1  4529070 4529123 BRN_IP_WT_A_pos_4 29  +
chr1  4529070 4529123 BRN_IP_A_S2_positive_4  29  +
chr1  4815570 4815584 BRN_IP_WT_A_pos_5 3 +
chr1  4815570 4815584 BRN_IP_A_S2_positive_5  3 +
chr1  4845221 4845223 BRN_IP_WT_A_pos_6 3 +
chr1  4845221 4845223 BRN_IP_A_S2_positive_6  3 +
```
And the commend and output I got was:
```
groupBy -i demo.bed -c 5 -g 1,2,3 -o sum
148

```
Basically, it did not really group my bed records, and the output is a single number which sum up all the scores of all records.

I also changed g and o but I got the similar no-groupby results.

From the help I think I was doing the correct thing.

```
	$ cat ex1.out
	chr1 10  20  A   chr1    15  25  B.1 1000    ATAT
	chr1 10  20  A   chr1    25  35  B.2 10000   CGCG

	$ groupBy -i ex1.out -g 1,2,3,4 -c 9 -o sum
	chr1 10  20  A   11000
```
I should expect the columns I used to do the grouping (specified by -g) should be printed out, correct?
I am confused why this happened and by search Google I did not find any case like this.

I appreciate your help.

**Comment by arq5x** [comment]
This has been fixed in the github repo and the fix has not yet made it to a new formal release - please clone the repo and you should be fine.
