### ISSUE TITLE
Erro in bedtools merge function

### ISSUE THREAD

**Issue by fzuguo** [arq5x/bedtools2#560]
> cat test2.bed 
1       123     128
1       128     128

 > bedtools merge -i test2.bed
1       123     129

 > bedtools --version
bedtools v2.21.0

the correct result should be  1       123     128

**Comment by arq5x** [comment]
1bp intervals in BED format should have the start 1 less than the end, as starts are zero-based and ends are 1-based. Insertions are understood when start==end, thus bedtools treats an insertion at 128 as affecting bases 127 and 129
