### ISSUE TITLE
bedtools subtract: combination of -f and -r is not handled properly

### ISSUE THREAD

**Issue by ajank** [arq5x/bedtools2#563]
Take the following files, `a.bed`:
```chr1	10	20```
and `b.bed`:
```chr1	0	30```.
Now `bedtools subtract -f 1 -r -a a.bed -b b.bed`, with `-r` requiring the fraction of overlap to be reciprocal, should return the original file `a.bed`. Unfortunately, we get an empty output (bedtools v2.26.0).

Interestingly, `bedtools subtract -f 1 -F 1 -a a.bed -b b.bed` works as expected and returns the original file `a.bed`.

**Comment by arq5x** [comment]
Thanks for reporting this - pushed fix to master!
