### ISSUE TITLE
bedtools intersect using massive amount of memory when counting in a densely covered region

### ISSUE THREAD

**Issue by blaiseli** [arq5x/bedtools2#565]
I'm using the latest git version (`bedtools v2.26.0-130-g42640cb-dirty`) and experience some massive memory usage in some cases when using `bedtools intersect`, with the `-sorted` option.

The file I provide to the `-g` option is the following:
```
$ cat /tmp/chrom_sizes.txt 
I	15072434
II	15279421
III	13783801
IV	17493829
MtDNA	13794
V	20924180
X	17718942
```

The bed file I provide to the `-a` option is the following:
```
$ cat /tmp/test.bed 
I	6169083	6169195	"WBGene00235197"	+	.
I	15062082	15063836	"WBGene00004512"	+	.
I	15064300	15064453	"WBGene00004567"	+	.
I	15064837	15068346	"WBGene00004622"	+	.
I	15069279	15071033	"WBGene00004513"	+	.
II	10	20	"test"	+	.
III	20	40	"test2"	+	.
IV	30	60	"test3"	+	.
MtDNA	897	1593	"WBGene00014454"	+	.
MtDNA	10402	11354	"WBGene00014472"	+	.
V	17115902	17116021	"WBGene00077465"	+	.
V	17117862	17117981	"WBGene00077466"	+	.
V	17118836	17118935	"WBGene00077467"	+	.
V	17120012	17120111	"WBGene00077468"	+	.
V	17120967	17121086	"WBGene00014621"	+	.
V	17121943	17122062	"WBGene00077469"	+	.
V	17122919	17123038	"WBGene00077470"	+	.
V	17123895	17124014	"WBGene00077471"	+	.
V	17124871	17124990	"WBGene00077472"	+	.
V	17125847	17125966	"WBGene00077473"	+	.
V	17128403	17128522	"WBGene00077474"	+	.
V	17129375	17129494	"WBGene00077475"	+	.
V	17130361	17130480	"WBGene00077476"	+	.
V	17131337	17131456	"WBGene00077477"	+	.
V	17428878	17428996	"WBGene00189966"	+	.
X	50	100	"test4"	+	.
```

(I added entries for chromosomes that were not represented in the original bed file, in case this could have caused the issue, but this is not the case)

The command I run is the following:

```
bedtools intersect -a /tmp/test.bed -b mapping_48hph/hisat2/mapped_C_elegans/WT_RT_2_on_C_elegans_sorted.bam -sorted -g /tmp/chrom_sizes.txt -c > /tmp/counts_2.txt
```

Where the bam file is a 3GB sorted and indexed bam file with the following header:

```
$ samtools view -H mapping_48hph/hisat2/mapped_C_elegans/WT_RT_2_on_C_elegans_sorted.bam
@HD	VN:1.0	SO:coordinate
@SQ	SN:I	LN:15072434
@SQ	SN:II	LN:15279421
@SQ	SN:III	LN:13783801
@SQ	SN:IV	LN:17493829
@SQ	SN:MtDNA	LN:13794
@SQ	SN:V	LN:20924180
@SQ	SN:X	LN:17718942
@PG	ID:hisat2	PN:hisat2	VN:2.0.4	CL:"/home/bli/src/hisat2-2.0.4/hisat2-align-s --wrapper basic-0 -p 4 --dta --seed 123 -t --mm -x /home/bli/Genomes/C_elegans/hisat2/wbcel235/genome --passthrough -U /tmp/722.unp"
```

It was sorted using `samtools sort` and indexed with `samtools index`.

Just to check that the chromosome order is at least correct:
```
$ samtools view mapping_48hph/hisat2/mapped_C_elegans/WT_RT_2_on_C_elegans_sorted.bam | cut -f3 | uniq
I
II
III
IV
MtDNA
V
X
```

The run eats about 11 GB in one minute on my Xubuntu 16.04 workstation. If I let it run too long, my computer becomes unresponsive, probably due to massive swapping.

I have other bam files for which the behaviour looks normal (with the same options, same bed and genome files): Reasonable memory usage, completes in about 2 minutes.

One example of such bam file, obtained from the same pipeline, but different initial fastq file has the following header (almost identical to the above):

```
$ samtools view -H mapping_prg1_CRISPR/hisat2/mapped_C_elegans/prg1KOF4_1_on_C_elegans_sorted.bam
@HD	VN:1.0	SO:coordinate
@SQ	SN:I	LN:15072434
@SQ	SN:II	LN:15279421
@SQ	SN:III	LN:13783801
@SQ	SN:IV	LN:17493829
@SQ	SN:MtDNA	LN:13794
@SQ	SN:V	LN:20924180
@SQ	SN:X	LN:17718942
@PG	ID:hisat2	PN:hisat2	VN:2.0.4	CL:"/home/bli/src/hisat2-2.0.4/hisat2-align-s --wrapper basic-0 -p 4 --dta --seed 123 -t --mm -x /home/bli/Genomes/C_elegans/hisat2/wbcel235/genome --passthrough -U /tmp/13268.unp"
```

This one is 2.1GB

I suspect this may have to do with the library content. The bed file corresponds to rRNA annotations, and it happens that in the memory-eating case, the library has 30 times higher (normalized) peak coverage in the rRNA region than the normally-behaving one.

Is it expected that this results in so much memory being used?

**Comment by vtadigotla** [comment]
This sounds similar to #492. I've had similar issues with samples that have high rRNA content.

**Comment by arq5x** [comment]
This is resolved in prior patches and is best mitigated with `-sorted`. That said, memory can still rise if a region in `-a` has a massive number of intersections in `-b`
