### ISSUE TITLE
segfault with bedtools intersect --split

### ISSUE THREAD

**Issue by dmaticzka** [arq5x/bedtools2#567]
I get a segfault for intersect with --split argument set. Works fine in 2.26.0 but crashes with current master (and bioconda bedtools_2.26.0gx @mvdbeek).

So far this is the smallest call I found to reproduce this:

```bash
bedtools intersect -split \
-a <(printf 'chr1\t861000\t869000\tSEQ1\t0\t+\t861000\t869000\t0\t1\t10,\t0,\nchr1\t861000\t869000\tSEQ2\t0\t+\t861000\t869000\t0\t1\t10,\t0,\n') \
-b <(printf 'chr1\t868100\t868150\tID\t10\t+\n')
```

**Comment by arq5x** [comment]
I can't reproduce this with master. Can you test their and reopen if it persists?

**Comment by dmaticzka** [comment]
I can confirm it's running fine now, thanks!
