### ISSUE TITLE
Intersect adds binary header of bam to the end of the output

### ISSUE THREAD

**Issue by luidale** [arq5x/bedtools2#568]
When I use intersect to count reads in bam matching features in bed file. Then the intersect adds to the end of the output binary header of the bam file. This is the case for versions 2.26.0, 2.25.0, 2.21.0. Version 2.19 works perfectly.
Just I noticed that version 2.21.0 is the first which is able to use multiple input files.

Is there a bug in intersect or there is something wrong with my bam file?
Multi cov with the same bam and bed file works nicely. I do not see otherways also any problems with the bam file.

My command and output:
nice ~/bin/bedtools2.20/bin/intersectBed -b bam/HLRPI1_Pos.bam -a A.bed -c
chr     10      28      0
chr     30      110     0
▒BC▒sr▒e,d``p▒p▒
▒2▒3▒
▒*▒+▒/*IM▒▒
▒J▒(▒▒▒213▒437▒r▒▒t▒▒3▒▒M▒/▒(JM13▒OO,05▒K%嗗d▒q▒▒@Ӎ▒
▒
t▒RK͹▒▒▒1▒h▒ݧ▒
▒▒BCuTTY-bash-4.2$ PuTTY

**Comment by luidale** [comment]
In addition I noticed that the same output files are faulty.
If I parse the output BED files with python3 then I get error close to the end of the file:
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 543: invalid start byte"
Different files has the error in the beginning of different lines but it is was 12-130 line before end (total lines where (~900-3100). Different bam files caused file line error in different places.
In case of short bed file (2 lanes) the start byte was wrong already in first line.

Again version 2.19.1 worked fine.

I was able to reproduce the error also with this bam file:
http://data-science-sequencing.github.io/assets/assignment2/E.coli.alignments.EE372.bam

**Comment by luidale** [comment]
All tested version work properly when I use order of pratmeters : -a -b. Starting from version 2.21 there is problem when parameters are ordered as -b -a.

It is similar for [#497](https://github.com/arq5x/bedtools2/issues/497) which should be fixed. But in my hands also the latest version 2.26 does not work properly.

**Comment by jmarshall** [comment]
This too was fixed in the development version by PR #499. However the 2.26 release was from well before that fix was made and there has not yet been another release, so the problem still exists in formal bedtools releases.
