### ISSUE TITLE
groupBy ERROR: illegal character '+'

### ISSUE THREAD

**Issue by gwbell** [arq5x/bedtools2#569]
Something doesn't appear quite right with groupBy (bedtools v2.26.0) or perhaps my command (or file input) is wrong.  The same commands work fine with v2.23.0.

With a tab-delimited input file (Problem.txt) like
AAAACAATTGGTATTCTTGGAGG	Foo	3009041	3009064	+	NM:i:0	0
AAAACAATTGGTATTCTTGGAGG	Foo	3009041	3009064	+	NM:i:1	1
and the command
groupBy -i Problem.txt -g 1 -c 3,4 -o distinct,min
I get
***** ERROR: illegal character '+' found in integer conversion of string "+". Exiting...

whereas this file (Fixed.txt) works fine:
AAAACAATTGGTATTCTTGGAGG	Foo	3009041	3009064	+	NM:i:0
AAAACAATTGGTATTCTTGGAGG	Foo	3009041	3009064	+	NM:i:1
groupBy -i Fixed.txt -g 1 -c 3,4 -o distinct,min
AAAACAATTGGTATTCTTGGAGG 3009041 3009064

Any help would be appreciated!

**Comment by nkindlon** [comment]
Corrections made in pull request #575 . There were errors in src/utils/general/ParseTools for handling a '+' sign. Also pre-empted fileType format checking for groupby.

**Comment by arq5x** [comment]
Pull request #575 merged and this is now fixed in master. Thanks @nkindlon !
