### ISSUE TITLE
Query regarding bedtools coverage option

### ISSUE THREAD

**Issue by h-joshi** [arq5x/bedtools2#570]
Hi,
I am using bedtools 2.26.0 and am struggling to properly utilise the coverage feature. I've outlined the 2 commands I attempted below ... 
`bedtools coverage -abam sample.bam -b neb.bed`
`bedtools coverage -a sample.bam -b neb.bed`

Given that neb.bed is restricted to chr2 (within the NEB transcripts start/end regions), I expected the coverage output to chr2 as well ... however the output displayed commences from chr1 onwards.
(Note: I ensured the bam file was sorted)

What is the correct way to use the bedtools coverage functionality - with a bam file + a bed file at hand?

**bed file**:
```
chr2	152341852	152342447	NM_001164507_exon_0_0_chr2_152341853_r	0	-
chr2	152346484	152346591	NM_001164507_exon_1_0_chr2_152346485_r	0	-
```

**output**: (This is where I expected the output to be restricted to the regions outlined above only)
```
chr1	1169365	1169585	MRFEI:05584:03212	90	-	1169365	1169585	0,0,0	1	220,	0,	0	220	220	1.0000000
chr1	1169368	1169510	MRFEI:07518:01112	91	-	1169368	1169510	0,0,0	1	142,	0,	0	142	142	1.0000000
....
```

**Comment by h-joshi** [comment]
So ... this works
bedtools coverage -a neb.bed -b sample.bam

It'd be great if the examples outlined http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html made this clear. Unfortunately some of the nuances can't be intuitively deduced.

**Comment by arq5x** [comment]
I agree, I will try to make this clearer in the docs.
