### ISSUE TITLE
"-bedOut" argument does not work

### ISSUE THREAD

**Issue by stevekm** [arq5x/bedtools2#571]
It looks like both the documentation and the program are messed up here

In the documentation [here](http://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html) for bedtools v2.26.0 `getfasta`, it lists the argument `-bedOut`:

Option | Description
-- | --
-bedOut | Report extract sequences in a tab-delimited BED format instead of in FASTA format.

However, later in the documentation [here](http://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html#bedout-creating-a-tab-delimited-bed-file-in-lieu-of-fasta-output), this is described as such:

_Using the -tab option, the -fo output file will be tab-delimited instead of in FASTA format._
```bash
$ cat test.fa
>chr1
AAAAAAAACCCCCCCCCCCCCGCTACTGGGGGGGGGGGGGGGGGG

$ cat test.bed
chr1 5 10 myseq

$ bedtools getfasta -fi test.fa -bed test.bed -tab
chr1 5 10 AAACC
```

The `-bedOut` arg is not actually used here, so I am not sure what the syntax is supposed to be for this arg. Because, when I try to use it like this, it does not appear to work properly:

```bash
$ cat target_regions_head.bed
chr1	2985824	2985860
chr1	3102689	3103038
chr1	3160651	3160701
chr1	3301713	3301850
chr1	3313055	3313157
chr1	3319355	3319562
chr1	3321303	3321450
chr1	3322059	3322212
chr1	3327948	3329364
chr1	3331124	3331211

$ /local/apps/bedtools/2.26.0/bin/bedtools getfasta -fi "$hg19_fa" -bed tar
get_regions_head.bed -fo target_regions_head_fasta.bed -bedOut
Warning: the index file is older than the FASTA file.
chr1	2985824	2985860	chr1	3102689	3103038	chr1	3160651	3160701	chr1	3301713	3301850	chr1	3313055	3313157	chr1	3319355	3319562	chr1	3321303	3321450	chr1	3322059	3322212	chr1	3327948	3329364	chr1	3331124	3331211

$ /local/apps/bedtools/2.26.0/bin/bedtools getfasta -fi "$hg19_fa" -bed target_regions_head.bed -fo target_regions_head_fasta.bed -bedOut 1> /dev/null
Warning: the index file is older than the FASTA file.

$ head -3 target_regions_head_fasta.bed
TGCGATCCAAGGCGAGGGCGAGGAAGCTAGCCAAAA
TGACGGTGACGTTGTAAATAATATGTATGAGCCCAACCGGGACCTGCTGGCCAGCCACAGCGCGGAGGACGAGGCCGAGGACAGTGCCATGTCGCCCATCCCCGTGGGGCCACCGTCCCCCTTCCCCACCAGCGAGGACTTCACCCCCAAGGAGGGCTCGCCGTACGAGGCCCCTGTCTACATTCCTGAAGACATTCCGATCCCAGCAGACTTCGAGCTCCGAGAGTCCTCCATCCCAGGGGCTGGCCTGGGGGTCTGGGCCAAGAGGAAGATGGAAGCCGGGGAGAGGCTGGGCCCCTGCGTGGTGGTGCCCCGGGCGGCGGCAAAGGAGACAGACTTCGGATGGGAG
AAATACTGACGGACGTGGAAGTGTCGCCCCAGGAAGGCTGCATCACAAAG
``` 
Here, the fasta sequence has been written to the file, one per line, and the chromosome coordinates from the .bed file have written to stdout in a single line.

Its not supposed to do this, is it?

**Comment by saygingulec** [comment]
3 years later, I find this comment with the same issue. This is the exact thing I need but it doesn't work. Did you find an alternative?

**Comment by arq5x** [comment]
Sorry, this has been fixed in master for awhile.  Just use `-bedOut`
