### ISSUE TITLE
Cannot install v2.26.0 on macOS 10.12.6

### ISSUE THREAD

**Issue by gaotc200** [arq5x/bedtools2#573]
I have tried brew install and make from source code, neither could work.
The error are shown exactly the same as in this post:
https://github.com/Homebrew/homebrew-science/issues/6334
Any solutions will be really helpful. Thank you very much!

**Comment by arjanvandervelde** [comment]
this has been reported for the macports build too: https://trac.macports.org/ticket/54896#comment:5

**Comment by JohnUrban** [comment]
Same here. Long time user of BEDtools. Just got a new Mac - 10.12.6 OS. Can't successfully install bedtools. Tried:
- git clone
- latest release
- brew install

**Comment by arjanvandervelde** [comment]
macports should work.

**Comment by roseperrone** [comment]
I got this error when trying to install bedtools v2.26.0 on Mac 10.12.6:
http://lpaste.net/359206

First error:
In file included from ./StrandQueue.h:11:
/Library/Developer/CommandLineTools/usr/include/c++/v1/queue:405:5: error: 
      static_assert failed ""
    static_assert((is_same<_Tp, value_type>::value), "" );
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by arq5x** [comment]
Clearly I need a new MacBook as well.  Have you tested with this patch: https://github.com/arq5x/bedtools2/pull/574

**Comment by gaotc200** [comment]
@arq5x I tried the patch 574 and it does fix this problem

**Comment by arq5x** [comment]
Thank you - I will integrate ASAP

**Comment by roseperrone** [comment]
The build advanced farther, but now I get this error:

```
- Building main bedtools binary.
Undefined symbols for architecture x86_64:
  "StrandQueue::pop(Record::strandType) const", referenced from:
      FileRecordMergeMgr::tryToTakeFromStorage(Record::strandType) in FileRecordMergeMgr.o
  "StrandQueue::top(Record::strandType) const", referenced from:
      FileRecordMergeMgr::tryToTakeFromStorage(Record::strandType) in FileRecordMergeMgr.o
  "StrandQueue::top() const", referenced from:
      FileRecordMergeMgr::tryToTakeFromStorage() in FileRecordMergeMgr.o
  "StrandQueue::empty() const", referenced from:
      FileRecordMergeMgr::eof() in FileRecordMergeMgr.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
```

**Comment by arq5x** [comment]
@roseperrone - have you tried `make clean; make`

**Comment by JohnUrban** [comment]
I can confirm that the latest git clone installs on Mac OS 10.12.6.
Thanks for your continued dedication to BEDtools Aaron et al.

**Comment by arq5x** [comment]
Not at all, thanks for reporting.

**Comment by roseperrone** [comment]
@arq5x `make clean` fixed the problem. Thanks!

**Comment by KathieM** [comment]
Hi,
I have downloaded the latest version of bedtools: bedtools-2.26.0.tar.gz on macOS Sierra 10.12.6, unzipped it and moved the unzipped folder to: /Applications/bedtools2-2.26.0. I then got the patch that should allow me to compile it:
cd /Applications/bedtools2-2.26.0/
curl -L https://github.com/arq5x/bedtools2/pull/574.patch > /tmp/574.patch
git apply /tmp/574.patch

I then ran make clean
make clean
 * Cleaning-up BamTools API
 * Cleaning up.
 
followed by make, but I get this response
[bedtools.make.output.txt](https://github.com/arq5x/bedtools2/files/1447469/bedtools.make.output.txt)
:

When I type "which bedtools", I do not get a path, and when I try to use the bedtools:
bamtofastq -i 008.minus.UNmapped.bam -fq 008.minus.UNmapped.fastq
-bash: bamtofastq: command not found

Can you please tell me where I am in error?

Thank you,
Kathie
