### ISSUE TITLE
segfault with -loj

### ISSUE THREAD

**Issue by davidaknowles** [arq5x/bedtools2#576]
So it's possible this is just invalid but segfaults are never good. 
a.bed:
```
chr1    1421490 1421491
```
b.bed
```
chr1    12179   12180   "DDX11L1"       0       +       a
```
Now run
```
bedtools intersect -a a.bed -b b.bed -loj 
```
I get `Segmentation fault: 11`. Bedtools version v2.26.0. I'm on Mac but I get the same on Ubuntu 14.

**Comment by davidaknowles** [comment]
I still get the segfault with b.bed being 12 column, but not if it's 6 column (removing `a`).

**Comment by arq5x** [comment]
I can't reproduce this with either 2.26 or master, but I recall a bug fix for this a while ago that was made subsequent to 2.26.  Could you test with the version in master?

**Comment by davidaknowles** [comment]
Yup will do.

**Comment by davidaknowles** [comment]
You're right, this appears to be fixed in master. That'll teach me to bother compiling from source I guess...
