### ISSUE TITLE
Documentation appears to be out of date in places

### ISSUE THREAD

**Issue by adrowe1** [arq5x/bedtools2#581]
Don't know whether you compile the documentation from a separate source, or write raw .rst files, but working through a couple of examples I had to make changes to the code blocks for steps 1 and 3 in Advanced usage documentation (See below) in order to get them to work. I also added a short potential note re the -g genome input, as I'm probably not the only one who read this as requiring a complete .fa reference genome by default!

Let me know if I should just edit the .rst file and send a pull request.

Regards,

A

*******

###############
Advanced usage
###############

==========================================================================
Mask all regions in a genome except for targeted capture regions.
==========================================================================

Step 1. Add 500 bp up and downstream of each probe

.. code-block:: bash

  bedtools slop -i probes.bed -g hg18.genome -b 500 > probes.500bp.bed
  
NB genome is two column chromosome size list - i.e. https://genome.ucsc.edu/goldenpath/help/hg18.chrom.sizes

Step 2. Get a BED file of all regions not covered by the probes (+500 bp up/down)

.. code-block:: bash

  bedtools complement -i probes.500bp.bed -g hg18.genome > probes.500bp.complement.bed
  

Step 3. Create a masked genome where all bases are masked except for the probes +500bp

.. code-block:: bash

  bedtools maskfasta -fi hg18.fa -bed probes.500bp.complement.bed \
  -fo hg18.probecomplement.masked.fa

**Comment by arq5x** [comment]
Nice catch, thank you. Would you mind sending a PR?

**Comment by adrowe1** [comment]
No problem. Nice software! 
PR sent
