### ISSUE TITLE
How to compute coverage of bam file for exome data

### ISSUE THREAD

**Issue by fbrundu** [arq5x/bedtools2#583]
Hi,
I am trying to compute bam coverage using [genomecov](http://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html):

    bedtools genomecov -ibam <bam_file> -g <chrom_sizes_file> > coverage.txt

However, I am working with exome data and I am unsure if it can compute correctly the coverage in this case. In particular, `genomecov` doesn't have the `-b` option similar to `coverage`, which would allow to pass the file containing the targeted regions by the exome sequencing kit.

Can it work in this case?

Thanks,
Francesco

**Comment by arq5x** [comment]
`genomecove` will give genome-wide coverage. `coverage` will report coverage for the intervals in your `-a` file if given a BAM/CRAM as the `-b` file.
