### ISSUE TITLE
Cannot brew install bedtools

### ISSUE THREAD

**Issue by willshyr** [arq5x/bedtools2#586]
Using brew install bedtools on MacOSX Sierra is giving me this error:

StrandQueue.cpp:101:26: error: no member named 'size' in 'std::__1::priority_queue<Record *, std::__1::vector<const Record *, std::__1::allocator<const Record *> >, RecordPtrSortDescFunctor>'
                sumSize += _queues[i]->size();
                           ~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [../../../../obj//StrandQueue.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  * compiling ContextJaccard.cpp
  * compiling ContextClosest.cpp
  * compiling ContextSubtract.cpp
  * compiling ContextCoverage.cpp
  * compiling ContextComplement.cpp
  * compiling ContextGroupBy.cpp
make[1]: *** [Records] Error 2
make: *** [src/utils/FileRecordTools] Error 2

**Comment by arq5x** [comment]
Please compile from source from the latest version in the repo. I will be releasing a point release soon that addresses this.
