### ISSUE TITLE
Feature Suggestion: getFasta -subtract

### ISSUE THREAD

**Issue by zachcp** [arq5x/bedtools2#589]
Hi Team Bedtools,

Than you for your excellent software.  I would like to propose a feature that would be useful to those of us who are using bedtools for removing vector sequences from long reads.

`Propose: getFasta -v <fasta> <bed>`  

would getFasta sequences from regions in a fasta file that are NOT contained in the bed. I don't believe this feature currently exists and it would be a handy to have.

zach cp

**Comment by arq5x** [comment]
This is already possible by using the complement tool to get the complement of your BED, then use getFasta on that.

**Comment by zachcp** [comment]
nice! (thanks)
