### ISSUE TITLE
bedtools intersect -c output adds an extra newline character to each line

### ISSUE THREAD

**Issue by groverj3** [arq5x/bedtools2#592]
I've been running bedtools intersect quite a bit as of late and noticed some peculiar things with its output. When outputting to terminal window:
```
bedtools intersect -nonamecheck -c -a A.bed -b B.bed
```

returns lines in the format of:
```
chromosome	start	stop	featureID	score	strand
```

Notably it is missing the count column at the end entirely.

When I > it to an output file I, instead, get what looks like:
```
chromosome	start	stop	featureID	score	strand
	count
```

The count is, strangely, located on the next line.

I can parse this output without too much difficulty, but it is strange that this behavior is seen with intersect but not other tools like window which outputs the -c option appropriately.

Also, it seems the documentation is incorrect on the output format, the intersect docs don't indicate that the featureID from A will end up in the output (to be clear, I like this, it just doesn't match the docs).

I haven't tried running without -nonamecheck because my genome contains several thousand contigs in addition to assembled chromosomes and without it an error is thrown.

Have I broken something or is this a bug

**Comment by arq5x** [comment]
What version are you using?  I am unable to reproduce this with the latest version in the github repository.

**Comment by groverj3** [comment]
2.26.0

I assume then it has been fixed since the last official release?

Additionally, I think I've narrowed down the problem.

```
file out.txt
out.txt: ASCII text, with CR, LF line terminators
```

And

```
cat -e out.txt
chromosome start      featureID score       strand^M     count$
```
Looks like there are windows carriage returns in there.

**Comment by groverj3** [comment]
After checking my files. It looks like this is my problem, my A bed file has carriage returns.

Lesson learned!
