### ISSUE TITLE
bedtools subtract (version 2.7.0) with 2 bed file is too slow, but version 2.6.0 is OK

### ISSUE THREAD

**Issue by wangyugui** [arq5x/bedtools2#594]
Hi.

bedtools subtract (version 2.6.0+git) with 2 bed file is too slow, but version 2.6.0 is OK

both v2.26.0-137-g87d545c2 and v2.26.0-148-gd1953b65 are slow.

v2.26.0-137-g87d545c2: 159.47s
v2.26.0 release:2.5s

but it OK when subtract -a bed -b gff.

**Comment by wangyugui** [comment]
Version 2.26.0
```
bedtools-2.26.0 subtract -a /usr/bio-ref/GRCh38.p11.dnaref/gene-only.bed -b /usr/bio-ref/GRCh38.p11.dnaref/DoC.CDS.bed
times: 1.85s
```

Version 2.27.0
```
time:81.39s
```

**Comment by arq5x** [comment]
Thank you - I will look into what is causing this. It would be great if you could share minimal test files that reproduce the dramatic slow down.

**Comment by wangyugui** [comment]
I attachment these two bed file.
[test.zip](https://github.com/arq5x/bedtools2/files/1551888/test.zip)

If a minimal test file is ready, I will share it too.

**Comment by wangyugui** [comment]
[test.zip](https://github.com/arq5x/bedtools2/files/1551893/test.zip)

I attachment these two bed file.
If a min test file is ready, I will share it too.

**Comment by wangyugui** [comment]
another test case.

head -n 20 DoC.CDS.bed >h20.bed
bedtools-2.27.0 subtract -a gene-only.bed -b h20.bed    =>0.25s
bedtools-2.26.0 subtract -a gene-only.bed -b h20.bed    =>0.08s

**Comment by arq5x** [comment]
Thanks very much for reporting this - it has been corrected in master.  Was caused by a regression that removed important compilation switches from the Makefile.

**Comment by wangyugui** [comment]
thanks for this fix.

It works well.
