### ISSUE TITLE
IntersectBED error issue #363 , once again

### ISSUE THREAD

**Issue by chrarnold** [arq5x/bedtools2#595]
We today encountered again issue #363 (it was closed and my posting today did not even seem to bring it up, so I am opening a new issue to make people aware of it)) also but we already use 2.26.0. Is it possible that the bug is still present?

I can provide two files and a concrete example that results in the same error message as described above.

When checking the archive, I get an OK, so the archive is ok:

gzip -tv fileNotWorking.bed.gz
fileNotWorking.bed.gz:	OK

gunzip works fine on the fileNotWorking.bed.gz , no errors, then bedtools also runs without issues. If I gzip the file again on the command line, bedtools however suddenly works.

Nevertheless, $zcmp and $zdiff with the old, non working file and the new one shows no differences.

Strangely, I find the following:
$gzip -v -l fileNotWorking.bed.gz
method crc date time compressed uncompressed ratio uncompressed_name
defla 4780bdc8 Nov 14 13:43 155656 510757 69.5%

$gzip -v -l fileNotWorkingUncompressAndRecompress.bed.gz
method crc date time compressed uncompressed ratio uncompressed_name
defla 4780bdc8 Nov 14 13:40 155695 510757 69.5%

Note the difference in the compressed file size?

**Comment by chrarnold** [comment]
Nobody has any idea or comment, really? We are facing this issue with multiple files, and we have no idea why it happens. Any help is greatly appreciated. I can provide an example file.

**Comment by arq5x** [comment]
Given that decompression and subsequent compression with gizp works, it sounds to me like you have a problem with the originally compressed files.
