### ISSUE TITLE
Piping BAM files between bedtools commands

### ISSUE THREAD

**Issue by jma1991** [arq5x/bedtools2#597]
I am filtering reads in a BAM file based on their intersection with regions in two BED files. Separately the commands both work, but when I use a pipe to connect them, the command doesn't finish and an empty BAM file is created:

**Working 1**
```bedtools intersect -v -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam Dam_Sequin_ESC_1M_Rep1_raw.bam -b Mmusculus_UCSC_mm10_ENCODE.bed > working1.bam```

**Working 2**
```bedtools intersect -f 1.0 -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam Dam_Sequin_ESC_1M_Rep1_raw.bam -b Mmusculus_UCSC_mm10_SEQUIN.bed > working2.bam```

**Broken**
```bedtools intersect -v -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam Dam_Sequin_ESC_1M_Rep1_raw.bam -b Mmusculus_UCSC_mm10_ENCODE.bed | bedtools intersect -f 1.0 -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam stdin -b Mmusculus_UCSC_mm10_SEQUIN.bed > broken.bam```

I am using version:
**bedtools v2.26.0-148-gd1953b6**

**Comment by arq5x** [comment]
Can you elaborate on what "doesn't finish" means?  Are you sure that an empty bam is not the correct result?

**Comment by jma1991** [comment]
The command runs without end (cancelled it after a few hours), and the output file created when the command is executed is just zero bytes.

**Comment by arq5x** [comment]
I think the control experiment you need to do is to take the ouput of command 1 as input to command 2. If that runs quickly and has non-zero output, let me know.

```
bedtools intersect -v -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam Dam_Sequin_ESC_1M_Rep1_raw.bam -b Mmusculus_UCSC_mm10_ENCODE.bed > working1.bam

bedtools intersect -f 1.0 -g Mmusculus_UCSC_mm10_SEQUIN.fasta.fai -sorted -abam working1.bam -b Mmusculus_UCSC_mm10_SEQUIN.bed > out.bam
```

**Comment by jma1991** [comment]
After more testing I've worked out that it is the second bedtools command which is giving me the problem. It simply doesn't finish, no matter how long I leave the command running. The first command is meant to remove any reads aligned to ENCODE blacklist regions, and the second command is meant to keep only reads aligned completely within the regions listed in the bed file (fragments.bed). Here is an image showing that at least one read should pass both filters: https://ibb.co/iXvmzb

I've uploaded files which reproduce the problem (at least for myself) along with a script to run the two separate bedtools commands: https://www.dropbox.com/s/n2cn22imxgol9k8/Issue.zip?dl=0

**Comment by mschilli87** [comment]
Looks like you might need to sort alphabetically (`"chr1" < "chr10" < "chr11" < ... < "chr2" < "chr20" ... < "chr3" < ... < "chr9" < "chrM" < "chrX"`)...

**Comment by jma1991** [comment]
@mschilli87 I thought by providing a genome file I could use any chromosome order I wanted, so long as the files provided to -a / -b / -g have the same chromosome order?

**Comment by mschilli87** [comment]
@jma1991: But you didn't specify a genome fiel to the `bedops` call giving you the "Bed file not properly sorted by first column." error. :wink: 

I'm just saying this error is expected, not that this should have any effect on your `bedtools intersect` call(s).

[Here](https://github.com/bedops/bedops/blob/2c93b6090229d6b667508de1bf0d9ff315731f2e/interfaces/general-headers/data/bed/BedCheckIterator.hpp#L608-L610) you can see the `strcmp` call triggering your `bedops` error:
