### ISSUE TITLE
bedtools fails with "Unable to open file" for large number of input files

### ISSUE THREAD

**Issue by chrarnold** [arq5x/bedtools2#598]
We are using the newest 2.26.0 and intersect, and when called like this:

`bedtools intersect  -a a.bed   -b *.sorted.bed`

, we receive a "Error: Unable to open file {file}. Exiting. message
This is clearly a bedtools error because:
a) all files exist and can be opened, and the specific file name that is given is actually not relevant (see b)
b) If I replace the * by the explicit file names, the same message. If I limit the files to all files BEFORE the file that causes the error, it works. Similarly, if I replace the last file that still works with the file that caused the error, it works. So it seems to be about the number of files or the combined length of their filenames or something. In this case, it works for 511 files, but crashed with 512 and more ( a suspicious number, 2^9, but before we run bedtools intersect with 640 files and it worked also)

Any idea?

**Comment by mschilli87** [comment]
Which OS are you on?

On Linux, the max. number of files that can be openend at the same time by a single process can be queried with `ulimit -n`.

On my system (x86_64 Ubuntu 16.4), this is 1024 (so 2^10), maybe on yours it's 512?
So maybe the 640 file run was on a different machine/OS?

If that's your issue (and you're on Linux), `uname -n 2048` will increase this limit to 2^11 for the current shell session.

**Comment by chrarnold** [comment]
Thanks for the comment and suggestion! First, we are using Linux on all systems.
I just tested this with the following results:
1. The limit is set to 1024 on different systems, and even on those systems where I can override this, higher values (up to 4096) result in the same message.
2. In the specific case, this happens when specifying 964 bed files for -b, so even 1024 should be fine.

Any other ideas what this might be related to? This is what ulimit -a shows me:

```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       62917
-n: file descriptors                4096
-l: locked-in-memory size (kbytes)  64
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 62917
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```

**Comment by arq5x** [comment]
Hi @chrarnold , yes it looks as though you are hitting an OS ulimit issue.

**Comment by mschilli87** [comment]
@chrarnold: bedtools needs to open all input files, the output file, maybe some temp-files in between(?) (@arq5x will know better than me), and probably also some shared libraries etc., try `lsof -p <PID of bedtools process>`  to get a better idea.
