### ISSUE TITLE
bedtools fisher varying 'number of db intervals'

### ISSUE THREAD

**Issue by johnmoll** [arq5x/bedtools2#605]
Hi,

Just found that bedtools fisher does not get the actual number of features of the b file, as you reported at the output 'Number of db intervals' field.

For instance, a 10221 intervals-long file (b.bed) would get sampled depending on which a file do you work with (data attached).

wc -l b.bed 
 . 10221 b.bed

"$BEDTOOLS" fisher  -a a1.bed  -b b.bed  -g hg19.genome > a1.fisher
"$BEDTOOLS" fisher  -a a2.bed  -b b.bed  -g hg19.genome > a2.fisher

fgrep "db intervals" *fisher
 . a1.fisher:# Number of db intervals: 4339
 . a2.fisher:# Number of db intervals: 10097

This happens with v2.27.0 (compiled today) and v2.26.0; nonetheless, the v2-2.23.0 reports 10221 as the 'number of db intervals' (which I guess is the expected output).

The doc speaks about estimating the number of non overlapping features, but it does not cover this apparent sampling of the b file. Is this behaviour expected?

[fisher.zip](https://github.com/arq5x/bedtools2/files/1556345/fisher.zip)

Thanks,

John

**Comment by arq5x** [comment]
Hi John,

The `fisher` tool "flattens" overlapping intevals in each file to prevent inflating the statistic when multiple overlapping intervals in one file overlap 1 or more intervals in the other. Thus, the final bookkeeping of intervals reflects the number of unique, non-overlapping intervals in each set.
