### ISSUE TITLE
intersect reports wrong number of fields in .gz file

### ISSUE THREAD

**Issue by jaime11** [arq5x/bedtools2#606]
Hello,

I am using bedtools intersect on some files and for one of them it reports the wrong number of fields:

```
bedtools intersect -sorted -c -a file1.bed.gz -b file2.bed.gz > /fastdata/mbp15ja/tmp/1.bed
Error: line number 2881 of file file2.bed.gz has 2 fields, but 6 were expected.
```

I have run a script to verify the number of fields in each the problematic file and it seems to have the same number of fields (6) for all lines:

```
zcat file2.bed.gz | awk 'BEGIN { FS ="\t"} { print NF }' | awk '{c[$0]++} END {for (line in c) print c[line], line}'
3027 6
```

If I run using gunzip to previously extract file2, I don't get any error:
`bedtools intersect -sorted -c -a file1.bed.gz -b <(gunzip -c file2.bed.gz) > 1.bed`

Format of the files:

File1:

chr1    9999    10000   1       1000    .
chr1    10097   10098   2       1000    .
chr1    10138   10139   3       1000    .

File 2:

chr1    2256065 2256284 1       13.9848 .
chr1    2557005 2557224 2       15.197  .
chr1    4614373 4614592 3       16.1061 .

The links for the files:
File1.bed.gz
https://www.dropbox.com/s/whe7b1xhpo6h1s0/file1.bed.gz?dl=0

File2.bed.gz
https://www.dropbox.com/s/8bavue4k18etvhr/file2.bed.gz?dl=0

Thanks

**Comment by arq5x** [comment]
Hi, I am unable to reproduce this with version [2.27.1](https://github.com/arq5x/bedtools2/releases/tag/v2.27.1). I suggest you update your version and give it another go.

**Comment by jaime11** [comment]
I am using bedtools v2.27.1 through conda from bioconda and still get the same error and no error when I use gunzip -c file2.bed.gz

**Comment by arq5x** [comment]
Odd, okay I will try to dig deeper into why this is happening for you and not me.  You are certain that the bedtools executable you are running is indeed 2.27.1 and not an older version on your system?

**Comment by jaime11** [comment]
When I run
`bedtools intersect`

I get:

```
Tool:    bedtools intersect (aka intersectBed)
Version: v2.27.1
Summary: Report overlaps between two feature files.
```

**Comment by rodriguesk** [comment]
I can confirm, the same issue happened to me with one of my files and was avoided by doing gunzip  . very strange!

**Comment by arq5x** [comment]
please provide an example file and the version of bedtools. I suspect this will not be the case in version 2.30.0
