### ISSUE TITLE
double-check on output differences between v2.26 and v2.27

### ISSUE THREAD

**Issue by daler** [arq5x/bedtools2#607]
Hi Aaron - 

I'm updating the pybedtools tests to work with BEDTools 2.27.1 and want to verify some things that have changed. Can you verify that the 2.27.1 results below are the correct/expected results?

These examples use files from the [pybedtools test data](https://github.com/daler/pybedtools/tree/master/pybedtools/test/data), but for convenience here they are:

```
$ cat a.bed 
chr1    1       100     feature1        0       +
chr1    100     200     feature2        0       +
chr1    150     500     feature3        0       -
chr1    900     950     feature4        0       +

$ cat b.bed
chr1    155     200     feature5        0       -
chr1    800     901     feature6        0       +
```

### shuffle
Looks like shuffle is returning different results now despite setting the same seed as before; is this expected?

### reldist
`reldist` output has changed.

```bash
# v2.26
$ bedtools reldist -a a.bed -b b.bed
reldist count   total   fraction
0.15    1       3       0.333
0.21    1       3       0.333
0.28    1       3       0.333

# v2.27.1
$ bedtools reldist -a a.bed -b b.bed
reldist count   total   fraction
0.21    1       1       1.000
```
Which should be considered correct?

### merge
`merge` when used with `-s` no longer reports strand:

```bash
# v2.26
$ bedtools merge -i a.bed -s
chr1    1       200     +
chr1    150     500     -
chr1    900     950     +

# v2.27.1
$ bedtools merge -i a.bed -s
chr1    1       200
chr1    150     500
chr1    900     950
```

thanks.

**Comment by arq5x** [comment]
Thanks for bringing this up @daler!


1. As for shuffle, I am unable to replicate this. I get the same results with the same seed. Can you double check?

2. Yes, the behavior for -s in merge is now to use strand to detect overlaps, but one must use -c and -o for reporting.

3. As for `reldist`, I am not sure what is going on there. It may be a bug. Thanks for reporting!

**Comment by duartemolha** [comment]
@arq5x I just had a whole bunch of my script break because of the change in output behaviour of -s .
Whilst I think it is a good change I do not see this change referenced anywhere in the release logs. 

Could I kindly ask that when changes are made to the default output behavior of any of the utilities this is well emphasised on the changes done on the stable releases?

Thank you!

**Comment by arq5x** [comment]
Apologies for the trouble this caused!
