### ISSUE TITLE
stranded bedtools merge does not return bed file

### ISSUE THREAD

**Issue by croth1** [arq5x/bedtools2#608]
Is there a way to obtain a bed file from `bedtools merge -s`?

I'm obtaining something like
```
chrM    1     100  +
chrM    151   200  -
```

It seems that I would have to reformat into bed before I can continue feeding it into *intersect*.

Is there a way to either output a bed file directly, or read the 4-columned format directly with bedtools intersect?

**Comment by mschilli87** [comment]
see https://github.com/arq5x/bedtools2/issues/607
