### ISSUE TITLE
Change in getfasta output 2.26.0 vs 2.27.1

### ISSUE THREAD

**Issue by tseemann** [arq5x/bedtools2#609]
I'm not sure if this change fell under changelog item 15 "Other bug fixes" or not, but it has affected our pipelines in terms of the header format for `getfasta` when using `-name` and/or `-s`. I assume the new `-name+` option in v27 is meant to do the `-name` output for v26 ?  Backward compatibility has been  broken?

Inputs

```
>myseq
AAAAAAGGGGGG

myseq   0       5       myname  1       -
```

2.26.0

```
bedtools getfasta -fi test.fa -bed test.bed
>myseq:0-5
AAAAA
bedtools getfasta -fi test.fa -bed test.bed -s
>myseq:0-5(-)
TTTTT
bedtools getfasta -fi test.fa -bed test.bed -s -name
>myname::myseq:0-5(-)
TTTTT
bedtools getfasta -fi test.fa -bed test.bed  -name
>myname::myseq:0-5
AAAAA
```

2.27.1

```
bedtools getfasta -fi test.fa -bed test.bed
>myseq:0-5
AAAAA
bedtools getfasta -fi test.fa -bed test.bed -s
>myseq:0-5(-)
TTTTT
bedtools getfasta -fi test.fa -bed test.bed -s -name
>myname(-)
TTTTT
bedtools getfasta -fi test.fa -bed test.bed  -name
>myname
AAAAA

#name+
bedtools getfasta -fi test.fa -bed test.bed -s -name+
>myname::myseq:0-5(-)
TTTTT
```

**Comment by andrewjpage** [comment]
Roary has been fixed to handle this change in output

**Comment by tseemann** [comment]
1.5 years later and now I'm not sure whether backward compatibility is important or not

**Comment by arq5x** [comment]
I understood this to be addressed based upon @andrewjpage's comment. If not, I will reopen. To make sure I understand, you wanted this behavior?

    bedtools getfasta -fi test.fa -bed test.bed -s -name
    >myname::myseq:0-5(-)
    TTTTT

**Comment by tseemann** [comment]
Roary was just one example of software that broke when v27 came out.
I had to patch some of my tools too.
Debian still has v26 as default I believe, so this was coming up in TRAVIS/CIRCLE testing.

**Comment by arq5x** [comment]
Thanks for letting me know. A fix is on the schedule for the next release.

**Comment by arq5x** [comment]
This is now fixed in master. Thanks for your patience.
