### ISSUE TITLE
Running bedtools -sorted coverage error

### ISSUE THREAD

**Issue by Dare-IC** [arq5x/bedtools2#612]
Thank you for your reading.

When I used 50K's bed file to run my BAM, this was the problem:
ERROR: chromomsome sort ordering for file /home/biosoft/newsample1.bam is inconsistent with other files. Record was:
chrX    21910    22059    ST-E00522:288:HCKNLCCXY:8:1108:22465:10099/1    6    +

When l used 100K's bed file to run my BAM,this was the problem:
Error: Sorted input specified, but the file /home/biosoft/old100k.bed has the following out of order record
chr5    1    100000

My instructions are:
/home/biosoft/bedtools2/bin/bedtools coverage -sorted -a /home/biosoft/50k.bed -b /home/biosoft/newsample1.bam >/home/biosoft/tt1-50k.txt

I want to ask where my question is. How should we solve it?

I look forward to your reply.

**Comment by arq5x** [comment]
The error is telling you that your input files have different sort orders for the chromosomes. They must be the same sort order (e.g., `sort -k1,1 -k2,2n`).
