### ISSUE TITLE
bedtools treats tabs as part of seq id

### ISSUE THREAD

**Issue by fgvieira** [arq5x/bedtools2#613]
Dear all,

when trying to use maskFastaFromBed, just noticed that tabs (\t) on a FASTA file sequence descriptor are treated as part of the name. For example:
```
>Scaffold1418 q23423
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

if the header of the sequence has only spaces, bedtools will properly mask it. But if instead of a space we have a tab (\t), then it won't recognize the sequence and nothing is masked.

cheers,

**Comment by arq5x** [comment]
Could you also share an example BED record that causes this?

**Comment by fgvieira** [comment]
It seems to have already been fixed.
thanks,
