### ISSUE TITLE
intersect error: Type Checker Found Wrong Number of Fields While Tokenizing Data?

### ISSUE THREAD

**Issue by lokeyCEU** [arq5x/bedtools2#617]
Very simply I have 2 xxx.bed files and am trying to intersect them and am getting a weird error I don't understand. The error message isn't informative for my case. Tl;dr using the last version of bedtools solved the problem. Maybe something to look into?

My data;
hg38.repeatmasker.fa.out converted to a bed file with awk > hg38.repeatmasker.bed
PhastCons.hg38.bed downloaded from UCSC Table Browser

Command I ran (using bedtools2-2.26.0);
bedtools -u -a <(sort -k1,1 -k2,2n A.bed) -b <(sort -k1,1 -k2,2n B.bed) | head

Error I get;
Error: Type checker found wrong number of fields while tokenizing data line.

I checked number of fields for both files with;
awk '{print NF}' xxx.bed | sort | uniq
4

Solution I found that makes no sense;
bedtools2-2.25.0/bin/bedtools -u -a <(sort -k1,1 -k2,2n A.bed) -b <(sort -k1,1 -k2,2n B.bed) | head

Hope this helps fix a bug or anyone else getting this error.

**Comment by lokeyCEU** [comment]
Haha figured it out!
Got the same error on a different set of .bed's and with the new error message
Error: Type checker found wrong number of fields while tokenizing data line.
Perhaps you have extra TAB at the end of your line? Check with "cat -t"

I found I did have an extra tab at the end.
However I used cat -t .bed | head

So if you do not see this error update your bedtools.

**Comment by FilipeFerreiraMOCHSL** [comment]
Thank you so much for figuring this out @lokeyCEU!

I also had this issue and due to your comment I realized that applying a simple sed to the .bed file soled the problem!

`sed -i 's/\t*$//' your_input.bed"`
