### ISSUE TITLE
issue using bedtools merge and bedtools maskfasta

### ISSUE THREAD

**Issue by mdubarry** [arq5x/bedtools2#624]
Hi,

I would like to use **bedtools merge** and **bedtools maskfasta** but they don't produced the result I expect, probably I misunderstand some parameters ?!

I have a gff file containing several intervals that I want to mask on my fasta file. So I first merge those intervals : 
`cat pos2mask.gff | bedtools merge -d 0 > pos2msk`

Then I mask those positions on my fasta file : 
`bedtools maskfasta -fi genome.fasta -bed pos2msk -fo genome.msk.fa`

The problem is that bedtools miss some positions. After the merge if I have some intervals such as : 
24-55 and 56-60. The base at the position 56 will not be mask, and I don't really understand why... 
So I put the parameter -d at 1 in bedtools merge. It solved the problem with the previous interval and collapse it at 24-60. The problem is with intervals separates with 2 basis, it collapse them too, for example 24-55 and 57-60 because (I guess) it change the intervals with +1 and -1 respectively at end and start intervals, so those intervals know overlaps. By putting -d at 1 it mask too many bp.

Is there a way to mask all basis, even when the intervals are contiguous ?

I hope my text is understandable,
Thanks in advance for any clue,
Marion

**Comment by arq5x** [comment]
I am unable to reproduce this. If you can share a minimal example, I can try again.
