### ISSUE TITLE
Is 127 the maximum number of samples bedtools intersect can take as b argument?

### ISSUE THREAD

**Issue by VJalili** [arq5x/bedtools2#627]
Consider the following command: 

```shell
bedtools intersect -a ref.narrowPeak -b X > res.narrowPeak
```
where `X` is a list of `n` sorted `.narrowPeak` files. When `n <= 127` this command works fine. But when `n > 127` I receive the following error: 

```shell
Error: Unable to open file F. Exiting.
```
where `F` is the name of the 128-th file. Note that `bedtools intersect` works fine for the file `F` individually. In other words, the following command works fine: 

```shell
bedtools intersect -a ref.narrowPeak -b F
```

I also tried wildcard (*) character as the following, but still it throws the aforementioned error.

```shell
bedtools intersect -a ref.narrowPeak -b PATH_TO_THE_128_FILES/*
```

Therefore, would that be a correct reasoning to say `bedtools intersect` can take at most `127` files as for it's `-b` argument?

**Comment by auberginekenobi** [comment]
Getting the same error, but for me the limit seems to be 2047.

**Comment by mschilli87** [comment]
This seems unrelated to `bedtools` (to some extend):
Depending on your operating system, there is a maximum number files one can open at the same time.
On linux, `ulimit -n` will give you this number (on my system it is 1024, so I guess I could open 1023 inout files for `bedtools intersect`.
So my guess is `bedtools intersect` opens all input files in parallel. Why it might be possible to keep track of the position in each file and open, seek, and close each file at a time, I wonder if the resulting increas in code-complexity would be worth the gain. After all, the limit *can* be increased on the system level (by the administrator) or `bedtools intersect` *could* be run recursively on batches of all input files (by the user) to work around this problem.

**Comment by arq5x** [comment]
Yes, this is a OS limitation.
https://www.tecmint.com/increase-set-open-file-limits-in-linux/
