### ISSUE TITLE
Inconsistent naming convention for record results in no output

### ISSUE THREAD

**Issue by mjgage** [arq5x/bedtools2#628]
I am new to bedtools and am trying to reproduce a process that was published in a Current Protocols article to analyze a dataset we recently created from an RNA-Seq experiment.  I have installed bedtools v2.27.1 and it seemed to work fine with the coverageBed command to count the number of alignments. When I tried to run the next steps in the protocol, I encountered an error when I ran that set of commands.  First, I ran the following string where 2B_TopHat1.reads.pair.1.list.junctions.bed is the output from the TopHat alignment we did.  

sed 's/,/\t/g' 2B_TopHat1.reads.pair.1.list.junctions.bed | awk 'BEGIN{OFS="\t"} {print $1,$2,$2+$13,$4,$5,$6}' > left.bed

Next, I ran the following string:

intersectBed -u -s -a left.bed -b GRCm38.92_exonic_parts.gff > left.overlap

GRCm38.92_exonic_parts.gff was created from the annotated mouse genome, which I downloaded from ENSEMBL.  When I run this script, I get the following error:

***** WARNING: File left.bed has inconsistent naming convention for record:
chr1	3216958	3216960	JUNC00000001	1	-

***** WARNING: File left.bed has inconsistent naming convention for record:
chr1	3216958	3216960	JUNC00000001	1	-

I have searched around online haven't been able to find a solution to this issue.  The closest thing I have found is to use the -nonamecheck command but I haven't figured out where to put this in the string.  I have attached the "left.bed" file as a .txt document in case that helps diagnose the issue.

Any help would be greatly appreciated.

Thanks,

Matt

[left.bed.txt](https://github.com/arq5x/bedtools2/files/1901291/left.bed.txt)

**Comment by arq5x** [comment]
Can you post the first few lines of `GRCm38.92_exonic_parts.gff`?

I am able to intersect left.bed against itself without problem using version 2.27.1, so I suspect this might arise from a conflict in the chromosome naming between `left.bed` and `GRCm38.92_exonic_parts.gff`.

To use `-nonamecheck`, use:

    bedtools intersect -nonamecheck -u -s -a left.bed -b GRCm38.92_exonic_parts.gff > left.overlap

**Comment by arq5x** [comment]
Correct.  "chr1" in your BED and "1" in you GFF won't work.  You can add "chr" to the GFF with:

    awk '{print "chr"$0}' GRCm38.92_exonic_parts.gff > GRCm38.92_exonic_parts.chromlabel.gff
