### ISSUE TITLE
Feature-request: makewindows produce windows that start at multiples of windowsize

### ISSUE THREAD

**Issue by endrebak** [arq5x/bedtools2#629]
Often I have a file

```
chr1 162 177
chr1 344 414
```

and want to produce genome windows like this (with a window-size of 50):

```
chr1 150 200
chr1 300 350
chr1 350 400
chr1 400 450
```

The formula is 

`start = start - (start - windowsize % 50)`

and 

`end = end - (end - windowsize % 50) + windowsize`

This can be done in awk, but tiling the genome is a useful feature and much used for experiments where base-pair precision is not of interest, such as broad histone marks in ChIP-Seq.

**Comment by arq5x** [comment]
My feeling is that this is a sufficiently "custom" scenario that it is best done with awk.  Could you create a simple bash script that invokes this logic and call that?
