### ISSUE TITLE
Subtraction with -s is no-op?

### ISSUE THREAD

**Issue by endrebak** [arq5x/bedtools2#637]
I'd expect the two final commands to give the same result. Is this a bug?

```
biocore-home ~/c/pyranges (master DSgU=) bedtools --version
bedtools v2.27.1
biocore-home ~/c/pyranges (master DSgU=) head tests/data/f*.bed
==> tests/data/f1.bed <==
chr1	1	4	+

==> tests/data/f2.bed <==
chr1	2	3	+
biocore-home ~/c/pyranges (master DSgU=) bedtools subtract -a tests/data/f1.bed -b tests/data/f2.bed
chr1	1	2	+
chr1	3	4	+
biocore-home ~/c/pyranges (master DSgU=) bedtools subtract -s -a tests/data/f1.bed -b tests/data/f2.bed
chr1	1	4	+
```

**Comment by arq5x** [comment]
Hmm, that sure looks like one. I will try to look into that tonight.

**Comment by endrebak** [comment]
The provenance of my bedtools is anaconda:

```
biocore-home ~/c/pyranges (master DU=) which bedtools
/mnt/work/endrebak/software/anaconda/bin/bedtools
```

Same bug seems to exist for intersect:

```
biocore-home ~/c/pyranges (master DU=) head tests/data/m1.bed
chr1    1       2       +
biocore-home ~/c/pyranges (master DU=) bedtools intersect -a tests/data/m1.bed -b tests/data/m1.bed
chr1    1       2       +
biocore-home ~/c/pyranges (master DU=) bedtools intersect -s -a tests/data/m1.bed -b tests/data/m1.bed
```

**Comment by endrebak** [comment]
Instead of writing a new thread for each potential teensy bug, I will just add them here. (The reason I am finding a few edge cases is that I am using [hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html) to generate random genomic data and then testing my new pyranges library using bedtools as an oracle.) 

Another one:

```
biocore-home ~/c/pyranges (master DU=) head tests/data/join*.bed
==> tests/data/join1.bed <==
chr1    2       3       +

==> tests/data/join2.bed <==
chr1    2       3       -
biocore-home ~/c/pyranges (master DU=) bedtools intersect -wo -a tests/data/join1.bed -b tests/data/join2.bed
chr1    2       3       +       chr1    2       3       -       1
biocore-home ~/c/pyranges (master DU=) bedtools intersect -wo -S -a tests/data/join1.bed -b tests/data/join2.bed
```

Here I'd expect the last two commands to give the same result.

**Comment by arq5x** [comment]
Ah, I see the issue with both of these examples.  In BED format, the strand column is supposed to be the 6th not 4th column.  Therefore, bedtools doesn't recognize "+" and "-" as strands but rather "names", as the 4th column in BED format is a name field. Please retest with 6-column BED files.

**Comment by endrebak** [comment]
Ah, I see, I was almost certain something like this would be reported if it were an actual bug. Thanks. Would a warning be in order if the strand is not the sixth field? Or an attempt to guess the strand col? This might have drawbacks I cannot immediately see though.

**Comment by arq5x** [comment]
I am against guessing, as these file formats are well defined.
