### ISSUE TITLE
Makefile issues?

### ISSUE THREAD

**Issue by pjlmac** [arq5x/bedtools2#640]
Sorry for my naivete in this matter, but I'm trying to install bedtools on cygwin and I keep getting this error in the latest bedtools version. 

![image](https://user-images.githubusercontent.com/11742340/41815390-62d43726-7737-11e8-8f7b-7bac1191acb3.png)

**Comment by arq5x** [comment]
I suspect this issue is specific to cygwin and we don't have an easy way to test for or support cygwin. Sorry.
