### ISSUE TITLE
nonamecheck not working in bedtools coverage

### ISSUE THREAD

**Issue by ralonso-igenomix** [arq5x/bedtools2#641]
Hello,

I am running this command line in bedtools 2.27.1
<pre>
bedtools coverage -nonamecheck -d -sorted -a file.bed -b file.bam  > file.cov
</pre>
and I get this error
<pre>
ERROR: Database file file.bam contains chromosome chrM, but the query file does not.
       Please rerun with the -g option for a genome file.
       See documentation for details.
</pre>
I don't have access to the genome file and I guess nonamecheck is not working,

Thanks a lot

Best regards

**Comment by nkindlon** [comment]
@arq5x, I can't seem to assign this to myself, but you can pass it to me.
@ralonso-igenomix, Hi, I'm Neil Kindlon. I used to work for Aaron, and wrote most of the current version of the coverage tool. I'd like to see if I can help with this, and have some guesses but would like to check them myself before suggesting anything. Can you please send me your data files? You can mail them to neil.kindlon@jax.org. If they're too big for e-mail, please let me know, and we can arrange for a different method. Thanks!

**Comment by ralonso-igenomix** [comment]
Hello, don't worry, it was solved here. You may find the thread interesting:
https://www.biostars.org/p/323555

Thanks

**Comment by nkindlon** [comment]
Great, glad you found it. Thanks!
