### ISSUE TITLE
Potential error in jaccard?

### ISSUE THREAD

**Issue by endrebak** [arq5x/bedtools2#645]
Here you have two files:

```
head bedtools_counterexamples/*bed
==> bedtools_counterexamples/f1.bed <==
chr1	1	2	a	0	+
chr2	1	2	a	0	+
chr3	1	2	a	0	+

==> bedtools_counterexamples/f2.bed <==
chr1	1	2	a	0	+
```

The length of the first is 3 and the length of the second is 1. The union is then 3 + 1 = 4 and the intersection is 1. This means that the Jaccard score should be 1 / (4 - 1) = .3333.

However, bedtools Jaccard gives .5.

```
bedtools jaccard  -b bedtools_counterexamples/f1.bed  -a bedtools_counterexamples/f2.bed
intersection	union-intersection	jaccard	n_intersections
1	2	0.5	1
```

This makes sense if the union were defined as the length of the two files merged, but that is not what the example at http://bedtools.readthedocs.io/en/latest/content/tools/jaccard.html shows.

Is this a teensy bug?

**Comment by endrebak** [comment]
Waah, reverted the `-a` and `-b` flags :/

**Comment by endrebak** [comment]
Okay, this seems like it is legitimately different from the illustration:

```
head bedtools_counterexamples/*bed
==> bedtools_counterexamples/f1.bed <==
chr1	1	2	a	0	+
chr2	1	2	a	0	+
chr3	1	2	a	0	+

==> bedtools_counterexamples/f2.bed <==
chr1	1	2	a	0	+

==> bedtools_counterexamples/f3.bed <==
chr1	1	3	a	0	+
```

Here the union of f2 and f1 is 4 and the intersection is 1.
For f2 and f3 the union is 3 and the intersection is also 1.

Yet they give the same jaccard score:

```
biocore-home ~/c/pyranges_paper (master DU=) bedtools jaccard -a bedtools_counterexamples/f2.bed -b  bedtools_counterexamples/f1.bed

intersection	union-intersection	jaccard	n_intersections
1	2	0.5	1
biocore-home ~/c/pyranges_paper (master DU=) bedtools jaccard -a bedtools_counterexamples/f2.bed -b  bedtools_counterexamples/f3.bed

intersection	union-intersection	jaccard	n_intersections
1	2	0.5	1
```

**Comment by endrebak** [comment]
The above result does not seem to make any sense if the definition of union was set_union either:

The the length of u(f2, f3) would be 2  and u(f2, f1) would be 3:

```
bedtools merge -i <(cat bedtools_counterexamples/f2.bed bedtools_counterexamples/f1.bed)chr1	1	2
chr2	1	2
chr3	1	2
endrebak@biocore-home:~/code/pyranges_paper$ bedtools merge -i <(cat bedtools_counterexamples/f2.bed bedtools_counterexamples/f3.bed)
chr1	1	3
```

so the two results should still give a different jaccard.

**Comment by arq5x** [comment]
Thanks for reporting, I will make my way through this soon to figure out if there is a bug.
