### ISSUE TITLE
sorting large BED on machine with limited memory gives misleading error

### ISSUE THREAD

**Issue by bernt-matthias** [arq5x/bedtools2#647]
I use `bedtools sort` (I know I should use the GNU version :) .. ) on a machine with insufficient RAM I get: 

`Differing number of GFF fields encountered at line: 8231957. Exiting..` and an exit code of 1.

Is it possible to detect the actual out of memory condition and print an appropriate error message?

**Comment by jmarshall** [comment]
Is the GFF file gzip-compressed? If so, this is likely to be #643 rather than a memory issue.

**Comment by chrarnold** [comment]
If this is the problem, try de- and recompressing the file. The error should be gone then, at least for all files that I found with this issue this worked.

**Comment by arq5x** [comment]
Also, my plan is to integrate @jmarshall's fix (thank you!) for #643 next week. I am buried in manuscript revisions before I leave for vacation but hoping to pull that and other fixes off before I leave.

**Comment by bernt-matthias** [comment]
Thanks for your reply. My input file is plain uncompressed GFF with ~30,000,000 lines. I tested without memory limit and bedtools needed about 20GB. But on our compute nodes we have only 6GB per default. I can resubmit it to our high memory nodes, but I need a way to detect the out of memory condition automatically (we are using bedtools through Galaxy).
