### ISSUE TITLE
Problem outputting file to nfs storage?

### ISSUE THREAD

**Issue by yo54233154** [arq5x/bedtools2#653]
Hi, 
We are using bedtools(v 2.27.1) intersect on a cluster. Our compute nodes write to an NFS storage. Similar to issue 229 , we keep getting the following error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
bedtools_intersect.sh: line 1: 12607 Aborted

It works fine if we output to /tmp or other locally mounted partitions , but that would be quite inconvenient. Any proper solutions here?

Thank you.

**Comment by mschilli87** [comment]
I've written to NFS many time. Maybe there was a problem with your share? Check the output of `mount` to make sure it's writable, check `df` to make sure it's not full, or contact your local admin to trouble-shoot.
bedtools definitely works over NFS.

**Comment by yo54233154** [comment]
Well , many other tools (bwa/bowtie , samtools , picard , GATK ) work on the same storage even as we speak , and we have plenty of free space. 
Anything special about bedtools that I should know before trying to troubleshoot ?

**Comment by yo54233154** [comment]
Ok, I now have a workaround. Output ubam to stdout and then use samtools view to get bam output.
This doesn't actually "solve" the problem, but gets the work done.
