### ISSUE TITLE
bedtools genomecov with -bga option places 0 coverage chromosomes at the end

### ISSUE THREAD

**Issue by gunnarsc** [arq5x/bedtools2#655]
Hi,

I'm using version 2.27.1 and noticed that chromosomes with 0 coverage get sorted
to the end of a bedgraph file when running bedtools genomecov on a bam file with -bga option.

This is only the case if there are absolutely no reads mapping to the respective chromosomes. Otherwise sequence records are placed in order as expected. 

Not a critical issue but in my case created some issues with downstream processing (especially when sorting the resulting bedgraph file is not an option). 

Great if that could be fixed.
Cheers!

**Comment by arq5x** [comment]
This is a bit difficult to address and since sorting the output is a simple solution, I think I will close this.
