### ISSUE TITLE
ERROR: Received illegal bin number 37458 from getBin call. ERROR: Unable to add record to tree.

### ISSUE THREAD

**Issue by biozzq** [arq5x/bedtools2#656]
Dear all,

When I ran `bedtools intersect -a bug.bed -b bug.bed` it always gave me the error liking the title. I really do not know why, hope your help. (version v2.27.1)

The bug.bed file likes following
`1	613726905	613727702`

Best
Zhuqing

**Comment by biozzq** [comment]
Dear all,

When intersecting with the -sorted option, bedtools can handle the files.

Best
Zhuqing

**Comment by homonecloco** [comment]
It would be nice to at least have a more meaningful error message, so you know you have to have the input sorted and use the corresponding flag.

**Comment by arq5x** [comment]
Agreed - we will address this and other messages soon.
