### ISSUE TITLE
groupby not behaving properly

### ISSUE THREAD

**Issue by dbrg77** [arq5x/bedtools2#657]
Hello,

I recently had a problem with `groupby`.

bedtools version: 2.27.1

Input file `test.tsv` can be downloaded from here: `https://www.ebi.ac.uk/~xichen/test.tsv`. The content of `test.tsv` is like this:

```
$ head -2 test.tsv
HS_uPk_6835    chr1:214958061-214958394|MLT1A0|LTR|ERVL-MaLR
HS_uPk_2306    chr1:55443402-55443465|CR1-L3A_Croc|LINE|CR1
```

When I ran `groupby` to group on the 1st column and collapse the 2nd column:

```
cat test.tsv | bedtools groupby -g 1 -c 2 -o collapse
```

The 1st column of the output should be unique, since we group the 1st column. It works in most cases, but there are a few records (35 in total) that `groupby` fails to collapse:

```
$ cat test.tsv | bedtools groupby -g 1 -c 2 -o collapse | cut -f 1 | sort | uniq -c | sort -b -k1,1nr | head

      2 HS_uPk_12157
      2 HS_uPk_14954
      2 HS_uPk_15383
      2 HS_uPk_18199
      2 HS_uPk_18914
      2 HS_uPk_19805
      2 HS_uPk_24796
      2 HS_uPk_24812
      2 HS_uPk_29274
      2 HS_uPk_29467
```

Not sure what caused the problem.

Thank you.

Regards,
Xi

**Comment by arq5x** [comment]
Hi there. It looks like you need to sort your file by the grouping key.
    
    ➜  cut -f 1 test.tsv| sort | uniq | wc -l
    38093
    ➜  cat test.tsv | bedtools groupby -g 1 -c 2 -o collapse | wc -l
    38128
    ➜  sort -k1,1 test.tsv | bedtools groupby -g 1 -c 2 -o collapse | wc -l
    38093

**Comment by dbrg77** [comment]
oh, stupid me ...

That helped.

Thanks!
