### ISSUE TITLE
bedtools is trimming too much whitespace

### ISSUE THREAD

**Issue by Ahhgust** [arq5x/bedtools2#659]
It looks like bedtools is trimming off too much whitespace at the end of lines. This is an issue when you have an empty record at the end of the string. 
See:

bedtools --version
bedtools v2.27.1

(echo "chr5 100 200 "; echo "chr5 200 300 foo") | tr ' ' '\t' | bedtools sort
Differing number of BED fields encountered at line: 2.  Exiting...

While empty records in the middle is OK:
(echo "chr5 100 200  f"; echo "chr5 200 300  foo") | tr ' ' '\t' | bedtools sort
chr5    100     200             f
chr5    200     300             foo

Thanks!
-August

**Comment by arq5x** [comment]
But your first example indeed has one line with 3 columns and 1 with 4.

**Comment by Ahhgust** [comment]
There's a trailing tab-- all rows have 4 columns, the first row has no information in the last. I'm guessing that you're trimming trailing whitespace (including tabs) first and then evaluating whether there is the appropriate number of columns.

Here's another example:


augustw@odin:~$ (echo "chr1 10 100 bar foo" ; echo "chr1 1000 10000  foo") | tr ' ' '\t' | bedtools sort
chr1    10      100     bar     foo
chr1    1000    10000           foo
augustw@odin:~$ (echo "chr1 10 100 bar" ; echo "chr1 1000 10000 ") | tr ' ' '\t' | bedtools sort
Differing number of BED fields encountered at line: 2.  Exiting...

In which a bed file is only valid if it has 5 columns, but not if it has 4.


It's a fine point, I realize, but I have real-world examples with a CSV list in the last column of a bed, and when that list has 0 elements in it bedtools crashes.


-August





________________________________

**Comment by mschilli87** [comment]
@Ahhgust: Have a look at [the BED format specifications](https://genome.ucsc.edu/FAQ/FAQformat.html#format1), specifically this part:
> BED information should not be mixed as explained above (BED3 should not be mixed with BED4), rather additional column information must be filled for consistency, for example with a "." in some circumstances, if the field content is to be empty.

So instead of leaving field empty, you should use `.` to indicate missing values, at least if you expect tools implementing the BED standard to 'just work' with your file.
