### ISSUE TITLE
Feature request - Append BAM tag information to read name in bamtofastq

### ISSUE THREAD

**Issue by dburkhardt** [arq5x/bedtools2#660]
Hello, I have a feature request for the `bamtofastq` tool. I have a single cell RNA-seq BAM file that has crucial information about the UMI and cell barcode encoded in various BAM tags.  It would be great if there was an option here that allowed me to pass in a list of tag keys and a delimiter that could be used for this purpose. I've implemented a solution in python, but it's unsurprisingly slow.

For example, I would like this line:
```
SRR6890846.27763451	    0	1	33538	255	34M	*	0	0	GTACGTCTGGGATCTGGAGGTGGAAGATCCACAT	AAAAAEEEEEEEEEEEEEEEEEEEEEAEEEEEEE	NH:i:1	HI:i:1	AS:i:33	nM:i:0	NM:i:0	MD:Z:34	jM:B:c,-1	jI:B:i,-1	XC:Z:AACGAAACG-AGTGAAAG	XM:Z:TCAAGA	XS:Z:Assigned	XN:i:1	XT:Z:ENSDARG00000099640
```

to be reported as:

```
>SRR6890846.27763451#XC:AACGAAACG-AGTGAAAG#XM:CAAGA	
GTACGTCTGGGATCTGGAGGTGGAAGATCCACAT	
+
AAAAAEEEEEEEEEEEEEEEEEEEEEAEEEEEEE
```

Thank you for your consideration and for all of your work on this tool kit!

**Comment by jmarshall** [comment]
In these miscellaneous utility commands like conversion to FASTQ, there is a lot of overlap between bedtools and samtools and various other tools. So for example, `samtools fastq` already does this.

**Comment by mschilli87** [comment]
@arq5x: Maybe such a recommendation should be part of `bedtools --help` and/or `bedtools bamtofastq --help`/`BamToFastq --help`?

**Comment by arq5x** [comment]
good suggestion, yes I should do that.

**Comment by arq5x** [comment]
in master.
