### ISSUE TITLE
Intersect -loj with empty bed file doesn't output NULL features

### ISSUE THREAD

**Issue by VorontsovIE** [arq5x/bedtools2#661]
Left-outer-join intersection is supposed to return NULL-features instead of B-intervals when no one interval from file B overlapped the interval from file A. Usually this works well but when the second file is empty, bedtools doesn't output such pseudo-matches for B. This results in a file with less columns than expected - and can ruin some pipelines in which intermediate results are generated by `bedtools intersect -loj`. That was exactly my case: with some inputs pipeline worked, but others generated empty file which then was fed into intersect-loj and resulted in a file with 3 columns instead of 6. The next stage of pipeline was intended to work well with NULL-features but failed when not even a NULL-feature was present.

In my case I found a workaround: instead of 
```bedtools intersect -loj -a intervals.bed -b empty.bed```
I invoke smth like
```bedtools intersect -loj -a intervals.bed -b <( echo $'chr1\t1\t1'; cat empty.bed )```

I guess such a solution is implemented because we don't know number of columns in an empty file so can't properly generate an empty match. I see three options to resolve this problem:
* Treat empty files as files with just 3 columns: chromosome, start, end.
* Manually specify expected number of columns in the file. When file is empty it would be used to properly fill NULL features. When file is not empty it helps to additionally verify that input file has correct structure.
* Manually specify NULL-feature as a whole - similarly as was done in my workaround.

I think that the second option is the best one.
In any case, a notice about peculiarity of empty files would help people to track errors in their pipelines.

**Comment by arq5x** [comment]
Thanks for reporting this. I just pushed a change that defaults to BED3 when -b is empty. In my view, adding an option to state how many columns "should" be in a file (but aren't) is too much complexity.
