### ISSUE TITLE
bedtools coverage: using wildcard characters

### ISSUE THREAD

**Issue by etvedte** [arq5x/bedtools2#662]
Hello,

I am using bedtools v 2.25.0 to calculate depth of coverage for several BAM files over my genome regions of interest. The documentation suggests using wildcard characters for multiple files. When I run the command, I get no output. Below is my command:

bedtools-2.25.0/bin/bedtools coverage -d -a /projects/regions.bed -b /projects/*target_sorted.bam > output.coverage.txt

Is this how wildcards are supposed to be implemented? Do you need to execute the command in the directory where the bam files are kept when using wildcards? 

Feedback appreciated, thanks!

Eric

**Comment by arq5x** [comment]
the number of files should only be limited by the OS. If you are not getting output, I suspect your chromosome labels in the A and B files do not match (e.g., "1" versus "chr1")

**Comment by etvedte** [comment]
Thanks for the prompt response. The sequence IDs in my BED/BAM files are the same. The command works fine if I specify a single BAM file in the -b parameter. Mostly interested if my command above was a correct implementation of wildcards. I'll work on it some more.
