### ISSUE TITLE
Bedtools shuffle produces gibberish when using -chrom

### ISSUE THREAD

**Issue by foriin** [arq5x/bedtools2#663]
I'm trying to use bedtools shuffle on drosophila data, but when I use -chrom option (because it has much more sense to shuffle intervals across one chromosome), it produces erroneous output with negative intervals and intervals exceeding chromosome length

**Comment by arq5x** [comment]
could you let me know the version of bedtools you are using and show example input and output?

**Comment by foriin** [comment]
@arq5x 2.27 but it doesn't matter, I figured the issue was in genome file. 90% of mistakes in Drosophila NGS analysis are due to "chr" added or not to the names of chromosomes. However, I think that it would be better if bedtools produced error when there are discrepancies between chromosome names in different files.

**Comment by arq5x** [comment]
thanks for following up!
