### ISSUE TITLE
bedtools2 is not working properly

### ISSUE THREAD

**Issue by khaled-rahman** [arq5x/bedtools2#664]
In A.bed file I have:
chr1	0	100
chr1	100	200
chr2	0	100

In B.bed file I have:
chr1	10	20
chr1	20	30
chr1	30	40
chr1	100	200

When I ran:
coverageBed -a A.bed -b B.bed

It shows me following errors:
***** ERROR: -counts, -d, -mean, and -hist are all mutually exclusive options. *****

Why is this happening?

I have tried an earlier version (v2.25.0) which is installed on a server. Only that version is working. All latter versions I installed, or installed in other servers are not working. I have installed that v2.25.0 on a server but still this new installation is not working. It would be very helpful, you could respond.

**Comment by arq5x** [comment]
I cannot replicate this problem wirth version 2.27.1, after adjusting your files to use tabs instead of spaces between each column. Also, I used the following command syntax:

    cat A.bed
    chr1	0	100
    chr1	100	200
    chr2	0	100

    cat B.bed
    chr1	10	20
    chr1	20	30
    chr1	30	40
    chr1	100	200

    bedtools coverage -a A.bed -b B.bed
    chr1	0	100	3	30	100	0.3000000
    chr1	100	200	1	100	100	1.0000000
    chr2	0	100	0	0	100	0.0000000
