### ISSUE TITLE
bedtools genomecov - Cannot use both -d and -bg

### ISSUE THREAD

**Issue by goodez** [arq5x/bedtools2#665]
```
*****
*****ERROR: Use -d/-dz or -bg, not both
*****

```
I really need the combination of these options, and I don't understand why they wouldn't work together. I need to output bedgraph format, so I used `-bg`. I also need it to report every single genomic position, so I used `-d`. In other words, I need it to output 1 bp bins in bedgraph format.

**Comment by arq5x** [comment]
Closing, as that, by definition is not bedgraph output.  You can just use -dz and pipe to a simple awk command.

    bedtools genomecov -i bed -g genomes/human.hg19.genome -d \
    | awk '{print $1"\t"$2-1"\t"$2"\t"$3}' \
    | head 
    chr2	0	1	0
    chr2	1	2	0
    chr2	2	3	0
    chr2	3	4	0
    chr2	4	5	0
    chr2	5	6	0
    chr2	6	7	0
    chr2	7	8	0
    chr2	8	9	0
    chr2	9	10	0
