### ISSUE TITLE
errror result about slopBed

### ISSUE THREAD

**Issue by hmyh1202** [arq5x/bedtools2#668]
my test BED file is like below:
![default](https://user-images.githubusercontent.com/18067365/47978791-b6e97880-e0fa-11e8-9e39-2b0569c54b47.png)

**Comment by hmyh1202** [comment]
![default](https://user-images.githubusercontent.com/18067365/47978942-56a70680-e0fb-11e8-88c6-4ea5d4468cb1.png)
The sloped  results was unreasonable for the first region.
My bedtools version is 2-2.20.1.

**Comment by arq5x** [comment]
Please upgrade to the latest version and test there. I am confident this will fix your error.
