### ISSUE TITLE
Bedtools failed to recognize output of intersect on two vcf files

### ISSUE THREAD

**Issue by khlab** [arq5x/bedtools2#670]
Hi,
The following command generates an Error:

`Bedtools intersect -a a.vcf.gz -b b.vcf.gz | bedtools intersect -a - -b c.vcf.gz `

"Error: unable to open file or unable to determine types for file -"

Using a regular file instead of "stdin" generates the same error...

Any hint?

NB: bedtools v2.27.1-9-g5f83cac

Thanks,

**Comment by arq5x** [comment]
Typically this comes from malformed VCFs. Do you have valid headers in both files?
