### ISSUE TITLE
Number of possible intervals in bedtools fisher

### ISSUE THREAD

**Issue by jergosh** [arq5x/bedtools2#672]
I'm having some trouble understanding how the Fisher's exact test for interval overlaps works. I had a look at the example in the bedtools documentation (https://bedtools.readthedocs.io/en/latest/content/tools/fisher.html) but couldn't work out how the number of possible intervals is calculated. I thought it's the 'number of non-overlapping intervals of the size equal to the mean size of input interval size that would fit in the genome' but that doesn't seem to agree with the number in the example. 

I then had a look at how it's implemented in bedtools2/src/fisher/fisher.cpp. In particular, the mean interval size is calculated like so:

```
long double dMean = 1.0 + _dbUnion / (long double)_dbCounts;
long double qMean = 1.0 + _queryUnion / (long double)_queryCounts;

long double bMean = (qMean + dMean);
```

As far as I can tell, this means that the bMean is effectively equal to the sum of mean interval sizes in the two input files + 2.0. What's the rationale for this (though perhaps I'm misinterpreting what's being calculated)?

**Comment by brentp** [comment]
this is a heuristic that I came up with. It worked on fairly disparate sets of data better than ( possibly more intuitive) other formulations that I tried.

**Comment by okurman** [comment]
Hi @brentp, is there a document for understanding the heuristics used in fisher method, by any chance? 
Short, long, supp material, blog post, etc. , anything would work :) 

Thanks in advance!
