### ISSUE TITLE
Test failures on 32 bit architectures

### ISSUE THREAD

**Issue by tillea** [arq5x/bedtools2#675]
Hi,
there is a bug [report in Debian](https://bugs.debian.org/890116) about test failures for 32 Bit architectures:

    ...
    --------------------------
     Test Results         
    --------------------------
    Tools passing:  bamtobed bamtofastq bed12tobed6 closest cluster complement expand fisher flank general genomecov getfasta groupby jaccard makewindows map merge multicov sample shift slop sort spacing       subtract
    Tools failing:  coverage intersect negativecontrol reldist shuffle split
    NB: the 'negativecontrol' test is supposed to fail. If it wasn't caught,
    something went wrong with this test script.
    Makefile:196: recipe for target 'test' failed

You can find a [full build log for i386](https://buildd.debian.org/status/fetch.php?pkg=bedtools&arch=i386&ver=2.27.1%2Bdfsg-2&stamp=1527025121&raw=0) (see quite at the end for the actuall error).
Kind regards, Andreas.

**Comment by arq5x** [comment]
This test is expected to fail.

**Comment by tillea** [comment]
I'm not convinced that this is correct.  Have you read only the quote above which is only the end of the test output.  So sorry for misleading you by quoting to less but here comes a more relevant part:

    Testing bedtools reldist:
        reldist.t01...ok
        reldist.t02...25,26c25,26
    < 0.23 945 43408 0.022
    < 0.24 903 43408 0.021
    ---
    > 0.23 944 43408 0.022
    > 0.24 904 43408 0.021
    fail
        reldist.t03...2,10c2,10
    < 0.00 20645 43422 0.475
    < 0.01 2624 43422 0.060
    < 0.02 1417 43422 0.033
    < 0.03 999 43422 0.023
    < 0.04 882 43422 0.020
    < 0.05 764 43422 0.018
    < 0.06 659 43422 0.015
    < 0.07 566 43422 0.013
    < 0.08 594 43422 0.014
    ---
    > 0.00 20629 43422 0.475
    > 0.01 2629 43422 0.061
    > 0.02 1427 43422 0.033
    > 0.03 985 43422 0.023
    > 0.04 897 43422 0.021
    > 0.05 756 43422 0.017
    > 0.06 667 43422 0.015
    > 0.07 557 43422 0.013
    > 0.08 603 43422 0.014
    12,14c12,14
    < 0.10 464 43422 0.011
    < 0.11 428 43422 0.010
    < 0.12 419 43422 0.010
    ---
    > 0.10 461 43422 0.011
    > 0.11 423 43422 0.010
    > 0.12 427 43422 0.010
    17,18c17,18
    < 0.15 373 43422 0.009
    < 0.16 373 43422 0.009
    ---
    > 0.15 367 43422 0.008
    > 0.16 379 43422 0.009
    25,28c25,28
    < 0.23 354 43422 0.008
    < 0.24 332 43422 0.008
    < 0.25 319 43422 0.007
    < 0.26 366 43422 0.008
    ---
    > 0.23 352 43422 0.008
    > 0.24 334 43422 0.008
    > 0.25 315 43422 0.007
    > 0.26 370 43422 0.009
    30,31c30,31
    < 0.28 332 43422 0.008
    < 0.29 278 43422 0.006
    ---
    > 0.28 330 43422 0.008
    > 0.29 280 43422 0.006
    33,34c33,34
    < 0.31 341 43422 0.008
    < 0.32 272 43422 0.006
    ---
    > 0.31 326 43422 0.008
    > 0.32 287 43422 0.007
    36,37c36,37
    < 0.34 320 43422 0.007
    < 0.35 293 43422 0.007
    ---
    > 0.34 306 43422 0.007
    > 0.35 307 43422 0.007
    39,47c39,47
    < 0.37 273 43422 0.006
    < 0.38 292 43422 0.007
    < 0.39 310 43422 0.007
    < 0.40 336 43422 0.008
    < 0.41 319 43422 0.007
    < 0.42 295 43422 0.007
    < 0.43 335 43422 0.008
    < 0.44 314 43422 0.007
    < 0.45 325 43422 0.007
    ---
    > 0.37 271 43422 0.006
    > 0.38 293 43422 0.007
    > 0.39 311 43422 0.007
    > 0.40 331 43422 0.008
    > 0.41 320 43422 0.007
    > 0.42 299 43422 0.007
    > 0.43 327 43422 0.008
    > 0.44 321 43422 0.007
    > 0.45 326 43422 0.008
    49,50c49,50
    < 0.47 358 43422 0.008
    < 0.48 361 43422 0.008
    ---
    > 0.47 354 43422 0.008
    > 0.48 365 43422 0.008
    fail

I think this bug remains open for the said 32bit architectures.
Kind regards, Andreas.

**Comment by jmarshall** [comment]
> Tools failing:  coverage intersect negativecontrol reldist shuffle split
> NB: the 'negativecontrol' test is supposed to fail.

This is not really about 32-bit architectures at all, but rather about the vagaries of floating point arithmetic — and of i387 arithmetic in particular.

* The coverage tests are failing because they are outputting `3.0799999` rather than `3.0800000` and so on, which might be a case of emitting unjustifiable excess decimal places.

* The intersect t52 test case fails because `0.2` can't be expressed precisely in floating point and the `>=` test is right on the boundary for 0.2.

* The reldist, split, and shuffle tests fail because various fp arithmetic (e.g., stddev calculations; RNGs probably) are coming out slightly differently on i387.

So the i386 test outputs are still reasonable and in isolation not erroneous. The question is whether bedtools attempts to produce identical results on different platforms and avoid minor differences due to differences in floating point arithmetic.

**Comment by mr-c** [comment]
Adding `-ffloat-store` to `CXXFLAGS` fixes all the tests on i386 except for `shuffle`:

Can this issue be re-opened and this failure examined?

```
Testing bedtools shuffle:
    shuffle.t1...1,10c1,10
< chr2	34697611	34698079	trf	789
< chr4	97373990	97374163	trf	346
< chr1	211569500	211569740	trf	434
< chr15	100895645	100895867	trf	273
< chr10	79193410	79193587	trf	187
< chr2	180138393	180138558	trf	199
< chr11	1280504	1280642	trf	242
< chr2	194322764	194322799	trf	70
< chr18	24454309	24454406	trf	79
< chr18	58907072	58907113	trf	73
---
> chr1	49390118	49390586	trf	789
> chr13	60419956	60420129	trf	346
> chr9	88507701	88507941	trf	434
> chr1	176220424	176220646	trf	273
> chr7	69225121	69225298	trf	187
> chr2	25938602	25938767	trf	199
> chr7	133111177	133111315	trf	242
> chr3	5894626	5894661	trf	70
> chr7	144738233	144738330	trf	79
> chr9	28526037	28526078	trf	73
fail
    shuffle.t2...1c1
< chr1	2158771	2159239	trf	789
---
> chr1	3126067	3126535	trf	789
3,20c3,20
< chr1	1837113	1837353	trf	434
< chr1	1389014	1389236	trf	273
< chr1	458954	459131	trf	187
< chr4	267572	267737	trf	199
< chr2	608295	608433	trf	242
< chr1	285876	285911	trf	70
< chr1	1344769	1344866	trf	79
< chr1	548923	548964	trf	73
< chr1	95584	95616	trf	64
< chr1	1063033	1063138	trf	149
< chr1	4349564	4349602	trf	58
< chr1	3052376	3052846	trf	278
< chr1	1922714	1923184	trf	339
< chr2	389822	390250	trf	202
< chr1	1427519	1427562	trf	59
< chr1	1280827	1280867	trf	62
< chr1	3745294	3745329	trf	52
< chr1	4151677	4151854	trf	302
---
> chr3	747335	747575	trf	434
> chr2	451924	452146	trf	273
> chr1	1837113	1837290	trf	187
> chr1	1389014	1389179	trf	199
> chr1	458954	459092	trf	242
> chr4	267572	267607	trf	70
> chr2	608295	608392	trf	79
> chr3	544706	544747	trf	73
> chr1	285876	285908	trf	64
> chr5	961111	961216	trf	149
> chr4	53213	53251	trf	58
> chr1	1344769	1345239	trf	278
> chr1	1516219	1516689	trf	339
> chr1	1062880	1063308	trf	202
> chr1	2030329	2030372	trf	59
> chr1	4349564	4349604	trf	62
> chr1	3052376	3052411	trf	52
> chr1	2890010	2890187	trf	302
fail
    shuffle.t3...1c1
< chr1	2158771	2159239	trf	789
---
> chr1	3126067	3126535	trf	789
3,20c3,20
< chr1	1837113	1837353	trf	434
< chr1	1389014	1389236	trf	273
< chr1	458954	459131	trf	187
< chr4	267572	267737	trf	199
< chr2	608295	608433	trf	242
< chr1	285876	285911	trf	70
< chr1	1344769	1344866	trf	79
< chr1	548923	548964	trf	73
< chr1	95584	95616	trf	64
< chr1	1063033	1063138	trf	149
< chr1	4349564	4349602	trf	58
< chr1	3052376	3052846	trf	278
< chr1	1922714	1923184	trf	339
< chr2	389822	390250	trf	202
< chr1	1427519	1427562	trf	59
< chr1	1280827	1280867	trf	62
< chr1	3745294	3745329	trf	52
< chr1	4151677	4151854	trf	302
---
> chr3	747335	747575	trf	434
> chr2	451924	452146	trf	273
> chr1	1837113	1837290	trf	187
> chr1	1389014	1389179	trf	199
> chr1	458954	459092	trf	242
> chr4	267572	267607	trf	70
> chr2	608295	608392	trf	79
> chr3	544706	544747	trf	73
> chr1	285876	285908	trf	64
> chr5	961111	961216	trf	149
> chr4	53213	53251	trf	58
> chr1	1344769	1345239	trf	278
> chr1	1516219	1516689	trf	339
> chr1	1062880	1063308	trf	202
> chr1	2030329	2030372	trf	59
> chr1	4349564	4349604	trf	62
> chr1	3052376	3052411	trf	52
> chr1	2890010	2890187	trf	302
fail
    shuffle.t4...ok
    shuffle.t5...1,10c1,10
< chr2	34697611	34698079	trf	789
< chr4	97373990	97374163	trf	346
< chr1	211569500	211569740	trf	434
< chr1	211569500	211569740	trf	434
< chr5	12248678	12248716	trf	58
< chr1	10051107	10051141	trf	68
< chr3	63788079	63788115	trf	63
< chr1	56972561	56972612	trf	66
< chr1	56972561	56972612	trf	66
< chr5	27921185	27921353	trf	150
---
> chr1	49390118	49390586	trf	789
> chr1	49390118	49390586	trf	789
> chr1	176220424	176220646	trf	273
> chr1	176220424	176220646	trf	273
> chr2	25938602	25938767	trf	199
> chr3	5894626	5894661	trf	70
> chr2	57803306	57803344	trf	58
> chr4	13407024	13407058	trf	68
> chr3	18198257	18198308	trf	66
> chr1	71587801	71587968	trf	159
fail
    shuffle.t6...ok
```

**Comment by arq5x** [comment]
Looks like the tests could stand to be updated to avoid subtle differences owing to floating point differences (ugh!).  The shuffle tests _should_ be the same as a seed is used, but I gather there are also architecture differences there as well.

**Comment by arq5x** [comment]
I can add the `-ffloat-store` option, but I don't have a way to test in i386.

**Comment by mr-c** [comment]
Thanks @arq5x 

Alas we htslib and tabix no longer support i386, so samtools was removed for i386 and therefore we won't be building bedtools for i386 either; so this issue can be closed again.
