### ISSUE TITLE
bedtools getfasta split option

### ISSUE THREAD

**Issue by rsalz** [arq5x/bedtools2#678]
The "-split" command line option didn't work when using getfasta with my bed file. The introns were being retained (with "-split" and without produced the same output).

**Comment by arq5x** [comment]
Could you comment on the version you are using and provide minimal file examples that reproduce the problem. Such details are essential to focus efforts to debug and heklp you.

**Comment by arq5x** [comment]
I m not able to reproduce this. I suspect you have a BED file that is not in proper BED12 format:

```
cat a.bed12
chr1	0	20	ENST00000466557.1	0	+	0	20	0	2	5,5,	0,15,

cat a.fa
>chr1
aaaaannnnnnnnnnttttt

bedtools2 arq5x$ bin/bedtools getfasta -fi a.fa -bed a.bed12 -split
>chr1:0-20
aaaaattttt
```
