### ISSUE TITLE
v2.27.1 getfasta stranded option not working on RNA; it does not reverse complement "U" nucleotides

### ISSUE THREAD

**Issue by Iaguilaror** [arq5x/bedtools2#682]
Running getfasta using the -s option on a minus stranded bed line, over the following data:
>Sample_sequence
GCUCCA

Returns:
>Reverse_complemented_sequence
TGGUGC

The "U" in the middle of the sequence should have been complemented to an "A".

It would be great if getfasta could:

1. Autodetect when input is RNA
2. Reverse complement U to A

**Comment by arq5x** [comment]
Thanks for reporting this, and it should be an easy fix.

**Comment by arq5x** [comment]
This is now fixed in master.
