### ISSUE TITLE
bedtools getfasta - Error: malformed BED entry

### ISSUE THREAD

**Issue by ethering** [arq5x/bedtools2#686]
Is there a limit to the length of fasta sequence that bedtools can use? I'm using `bedtools getfasta` on sequences that are 2.4Gb long and I cannot get it to work extract sub-sequences towards the end of the input sequences.
I have 24 samples/sequences, all exactly the same length (2410758013 bps). I need to chop my genomes into ~250Mb chunks so that they will work with a downstream genome introgression tool.
Example of my samples.fasta.fai file (to confirm the length of my genomes) is:

```
weasel  2410758013      8       60      61
LIB18995        2410758013      2450937332      60      61
LIB18991        2410758013      4901874656      60      61
```
I have created 10 bed files, which each provide 250Mb intervals, e.g. 
1.bed

```
LLIB18989        0       250000000
LIB18990        0       250000000
LIB18991        0       250000000
```
2.bed
```
LIB18989        250000001       500000000
LIB18990        250000001       500000000
LIB18991        250000001       500000000
```
etc.

Running the command...
```
$ bedtools --version
bedtools v2.27.1
$ bedtools getfasta -fi samples.fasta -bed 1.bed -fo 1.fasta
```
..works as expected, but once I provide the following bed file (which is my penultimate bed file):

9.bed
```
LIB18989        2000000001      2250000000
LIB18990        2000000001      2250000000
LIB18991        2000000001      2250000000
```
I get the error

```
Error: malformed BED entry at line 1. End Coordinate detected that is < 0. Exiting.
```
Also, when I provide my final bed file..

10.bed
``` 
LIB18989        2250000001      2410758012
LIB18990        2250000001      2410758012
LIB18991        2250000001      2410758012
```
I get the following error

```
Error: malformed BED entry at line 1. Start Coordinate detected that is < 0. Exiting.
```

Note the end co-ordinate throws the error in the first instance and the start coordinate in the second.
It appears that `bedtools getfasta` doesn't like coordinates that are in excess of somewhere in the region of 2-2.5Gb. Is this a bug, or am I doing something wrong?
Many thanks,
Graham

**Comment by arq5x** [comment]
I was initially worried that you are running into a limitation of 32 bit integers, but bedtools uses an unsigned, 32-bit integers which have a max of 4,294,967,295. The fact that you are running into this suggests we are using signed 32 bit integers (max of 2,147,483,647) somewhere in the getfasta logic. If you have the relevant FASTA handy somewhere for download, please share it. Otherwise, I will try to create a test set.

**Comment by ethering** [comment]
Unfortunately the full file is 55Gb in size and I'm also not sure my collaborators would be happy for me to share all the data. Would you be able to generate one?

**Comment by arq5x** [comment]
Yep, can make a synthetic example easily. Thanks

**Comment by arq5x** [comment]
Update: we have a fix for this coming soon, as we are refactoring the way coordinates are handled to support much larger chromosomes.

**Comment by arq5x** [comment]
This is fixed - we now support massive chromosomes!

**Comment by ronahuel** [comment]
I have the same issue... what was the solution?

**Comment by Subhanita** [comment]
chrIV	WormBase	gene	-305	695	.	+	.	ID=Gene:WBGene00021406;Name=WBGene00021406;locus=frm-5.2;sequence_name=Y38C1AB.4;biotype=protein_coding;Alias=frm-5.2,Y38C1AB.4


I have the same issue. How did you solve it?
Thanks
Su
