### ISSUE TITLE
Bedtools subtract misses whole chromosomes when -sorted -g ref.dict

### ISSUE THREAD

**Issue by nh13** [arq5x/bedtools2#687]
If I leave out the `-sorted -g ref.dict` options it works just fine.

The `-b` file is missing some chromosomes from the `-a` file.  I cannot share the BED files as they are confidential, but I'll keep trying to find a small reproducible test case.  Version 2.27.1.

The input BED files are sorted similarly.

**Comment by nh13** [comment]
https://github.com/arq5x/bedtools/issues/142

**Comment by nh13** [comment]
I confirmed sort order of the inputs with `bedtools sort -i <in.bed> -faidx /path/to/ref.fa.fai` and then checking that the resulting file was exactly the same as the input file.

**Comment by arq5x** [comment]
Thanks for reporting this. I tried and failed to make a test set that reproduces this using either lexicographical chrom orders or atypical, custom sort orders. I suspect your case involves a sort order that I have not yet tested. A minimal test set would be very helpful if you have the time.

**Comment by nh13** [comment]
@arq5x I was able to come up with a reproducible test case!

#### commands
```bash
$ bedtools subtract -a a.bed -b b.bed -sorted -g ref.fasta.fai
chrX	1	10	.	500	+
$ bedtools subtract -a a.bed -b b.bed
chrX	1	10	.	500	+
chrX	100	110	.	500	+
```

#### `a.bed`
```
chrX	1	10	.	500	+
chrX	100	110	.	500	+
```
#### `b.bed`
```
chr2	10	20	rsid
chr15	110	120	rsid
```

#### `ref.fasta.fai`
```
chr1	249250621	6	50	51
chr2	243199373	254235646	50	51
chr3	198022430	502299013	50	51
chr4	191154276	704281898	50	51
chr5	180915260	899259266	50	51
chr6	171115067	1083792838	50	51
chr7	159138663	1258330213	50	51
chr8	146364022	1420651656	50	51
chr9	141213431	1569942965	50	51
chr10	135534747	1713980672	50	51
chr11	135006516	1852226121	50	51
chr12	133851895	1989932775	50	51
chr13	115169878	2126461715	50	51
chr14	107349540	2243934998	50	51
chr15	102531392	2353431536	50	51
chr16	90354753	2458013563	50	51
chr17	81195210	2550175419	50	51
chr18	78077248	2632994541	50	51
chr19	59128983	2712633341	50	51
chr20	63025520	2772944911	50	51
chr21	48129895	2837230949	50	51
chr22	51304566	2886323449	50	51
chrX	155270560	2938654113	50	51
chrY	59373566	3097030091	50	51
chrM	16571	3157591135	50	51
```

**Comment by arq5x** [comment]
Thanks for reporting this! Fix pushed to master.
