### ISSUE TITLE
Error using bedtools genome file in bedtobam

### ISSUE THREAD

**Issue by Bminnie90** [arq5x/bedtools2#694]
Version: bedtools-2.27.1
I am trying to convert my file_name.bed file to file_name.bam file using bedtobam.
However I get an error every time. I am using the provided genome file from bedtools-2.27.1.tar.gz. I have also tried it with the UCSC genome txt file chromInfo.txt.

My command: 
$ bedtools bedToBam -i GWASchr22.bed -g human.hg19.genome -i - > GWASchr22.bam

Error:
It looks as though you have less than 3 columns at line: 1.  Are you sure your files are tab-delimited?

**Comment by arq5x** [comment]
Please provide examples of your data with
`head GWASchr22.bed`
and
`head human.hg19.genome`

**Comment by Bminnie90** [comment]
$ head chromInfo.txt 
chr1	249250621	/gbdb/hg19/hg19.2bit
chr2	243199373	/gbdb/hg19/hg19.2bit
chr3 198022430	/gbdb/hg19/hg19.2bit

$ head human.hg19.genome 
chr1	249250621	/gbdb/hg19/hg19.2bit
chr2	243199373	/gbdb/hg19/hg19.2bit
chr3 198022430	/gbdb/hg19/hg19.2bit

**Comment by jianshuwuxian** [comment]
Bminnie90, you can refer to UCSC Genome Browser's BED format page
https://genome.ucsc.edu/FAQ/FAQformat.html#format1

It seems that something wrong in your bed file. The third column of bed file should be the chromEnd.

I also meet the ERROR same as yours. And your bed file should be tab-delimited.Be careful!
