### ISSUE TITLE
Error in makewindows : window length not respected

### ISSUE THREAD

**Issue by ranjit58** [arq5x/bedtools2#700]
# a bed file with single entry from 1 to 100.
echo -e "test\t1\t100" > test.bed

I want to make 50 base windows at interval of 10.
bedtools makewindows -w 50 -s 10 -b test.bed
test	1	51
test	11	61
test	21	71
test	31	81
test	41	91
test	51	100
test	61	100
test	71	100
test	81	100
test	91	100

This produces windows smaller than 50 bases toward the end of the file. Is there any option to restrict the window length to 50?

**Comment by arq5x** [comment]
I am a bit worried about doing that as it leads to a bias in what portions of the original intervals are represented.  A simple way to do this would be the following:

bedtools makewindows -w 50 -s 10 -b test.bed | awk '$3-$2 == 50'

**Comment by ranjit58** [comment]
ok.
Thanks for quick response.
