### ISSUE TITLE
build w/ clang fails

### ISSUE THREAD

**Issue by arjanvandervelde** [arq5x/bedtools2#705]
Hi!

Since 2.28.0, bedtools no longer builds w/ clang, which is the preferred compiler on Mac OS X and the BSD UNIX-es. It used to be straight-forward switching out gcc/g++ for clang but it now fails to build. It'd be great if this could be fixed.

Thanks!

-- Arjan

**Comment by arq5x** [comment]
It compiles fine on my OSX 10.14 machine which uses clang. Can you share the transcript of your build and tell what version of OSX and clang you are using?

**Comment by arjanvandervelde** [comment]
you're right. i must have done something weird in my environment. oh well. thanks!
