### ISSUE TITLE
Cannot compile 2.28.0 on OS X 10.4.3

### ISSUE THREAD

**Issue by jil24** [arq5x/bedtools2#707]
Compilation of htslib fails due to absence of lzma.h
Apparently this (xz) is an optional library for htslib that would be caught in htslib's configure script, but htslib's makefile as packaged assumes that it's installed.

**Comment by jmarshall** [comment]
Recent vanilla macOS is in the unusual position of having LZMA libraries but not header files. HTSlib's configure script has tests to activate a workaround for this, and with PR #709 this will be activated on macOS for bedtools's non-configure build system too.

I don't know whether Mac OS X Tiger has /usr/lib/liblzma.dylib as the more recent releases do. If not, you would want to hack _src/utils/htslib/Makefile_ to remove the line

    echo '#define HAVE_LIBLZMA 1' >> $@

regenerate _src/utils/htslib/config.h_ and rebuild.
