### ISSUE TITLE
Potential error in reldist?

### ISSUE THREAD

**Issue by endrebak** [arq5x/bedtools2#711]
```
bedtools reldist -a <(sort -k1,1 -k2,2n f7.bed) -b <(sort -k1,1 -k2,2n f8.bed)
reldist count   total   fraction
-nan    2       2       1.000
```

```
==> f7.bed <==
chr1    1       2       a       0        +
chr1    2       3       a       0        +

==> f8.bed <==
chr1    3       4       a       0        +
chr1    1       2       a       0        +
chr1    1       2       a       0        +
```

I think the correct answer is 

```
reldist  count  total  fraction
0.0      1      2       0.5
0.5      1      2       0.5
```

**Comment by arq5x** [comment]
I think you are right, looks like a bug. I will try to dig into this over the weekend. If you have a sense of where the bug is, a PR would also be welcome.

**Comment by endrebak** [comment]
I looked at https://github.com/arq5x/bedtools2/blob/e5ad7e48108681fe93ee4600d07699ab278e3c56/src/reldist/reldist.cpp, but could not immediately see anything. I am computing reldist using numpy arrays myself, so I do not think my code would be of much help :/

**Comment by arq5x** [comment]
No sweat, I will dig in

**Comment by arq5x** [comment]
Just pushed a fix. Thanks!
