### ISSUE TITLE
maskFasta slow due to line flush

### ISSUE THREAD

**Issue by tfwillems** [arq5x/bedtools2#720]
Hi bedtools team,

First off, thank you for making such a fantastic tool! 

I've been using the **bedtools maskfasta** command but noticed that it's quite slow. Using a test case of a FASTA file with a single chromosome (*chr16*, *hg19*) and a BED file with no chr16 regions, it still takes ~20min to output the masked FASTA file.

I managed to track this down to the *PrettyPrintChrom()* function, in which the masked chromosome is output line-by-line : https://github.com/arq5x/bedtools2/blob/fe2b92c00f02a9e7a4164cc2acd231f9a8dc07a6/src/maskFastaFromBed/maskFastaFromBed.cpp#L149-L158

The issue is that **endl** is used to output every line, causing a flush of the output buffer and resulting in slow performance. Changing endl to "\n" and adding a single final call to flush reduced the runtime for my test case from **~20min** to **10 seconds** 

```
void MaskFastaFromBed::PrettyPrintChrom(ofstream &out, string chrom, const string &sequence, CHRPOS width) { 
  
     CHRPOS seqLength = sequence.size(); 
  
     out << ">" << chrom << endl; 
     for(CHRPOS i = 0; i < seqLength; i += (CHRPOS)width)  { 
         if (i + width < seqLength) out << sequence.substr(i, width) << "\n"; 
         else out << sequence.substr(i, seqLength-i) << "\n"; 
     } 
     out.flush();
 } 
```
It'd be great if we could incorporate these 3 minor edits into the code base to speed things up.

Best,
Thomas

**Comment by arq5x** [comment]
wow, thank you. adding now.

**Comment by arq5x** [comment]
fixed in master. thanks!
