### ISSUE TITLE
bedtools coverage segmentation fault

### ISSUE THREAD

**Issue by AlaaBadredine** [arq5x/bedtools2#723]
Hello,

When using bedtools `2.27`, I could use

```
samtools view -b sample.bam chrY:2786855-2787699 > sample_SRY.bam
bedtools coverage -a sry.bed -b sample_SRY.bam -counts > sample.tsv 
```

where `sry.bed` contains `chrY    2786855 2787699` only and `sample_SRY.bam` contains the reads mapped to a particular region. Sometimes, this region is empty and sometimes its not, so the BAM file may be empty. Looks like in the new version, it doesn't allow that the BAM file to be empty.

Executing the same lines in `2.28` gives `segmentation fault` error.

**Comment by arq5x** [comment]
Thank you for reporting - could you share the two example files (the empty BAM and the BED) here?

**Comment by arq5x** [comment]
This should be fixed in master via #725 from @38. Please test on your end and reopen if you still have a problem.

**Comment by AlaaBadredine** [comment]
Sorry for the late reply and thanks for your effort @38 and @arq5x. I just did a `git pull`  on the master, got the changes and tried again on the BAM files. The error still persists.

I am joining you 2 examples of BAM files and the BED used.  Please note that I didn't include the whole BAM file, only the BAM after extracting reads in a particular region (explained below).
https://drive.google.com/open?id=16Sa8a0SOFQJlU79TbxpthNSDGLgpxFx8
https://drive.google.com/open?id=1AQ67bNilpP5gqB5TCrGVhFyHZIpTUbfQ
https://drive.google.com/open?id=1Uv44PfYr3MVO91ujpZLZoef_USGD_Raj

From my whole BAM file, I only extracted the reads mapped on `chrY:2786855-2787699` region. Sometimes, there may be reads that align to that region and sometimes not. I use `bedtools` to count the number of reads that align to that region.

Here are the commands I used again:
```
samtools view -b 20694.bam chrY:2786855-2787699 > 20694_SRY.bam
bedtools coverage -a sry.bed -b 20694_SRY.bam -counts > 20694.tsv
```

These commands works well in `2.27`.

Thanks

**Comment by 38** [comment]
Could you please send us version number using 
```
bedtools --version
```

I tried the file you send to me, it works with empty file.
```
$ bin/bedtools --version
bedtools v2.28.0-31-g9ac03000
$ bin/bedtools coverage -a /tmp/sry.bed -b /tmp/test.bam -counts
chrY    2786855 2787699 0
```

**Comment by arq5x** [comment]
The changes work for me as well. 

    bin/bedtools --version
    bedtools v2.28.0-27-g9ac0300
    bin/bedtools coverage -a sry.bed -b 20694_SRY.bam -counts
    chrY	2786855	2787699	331
    bin/bedtools coverage -a sry.bed -b 21530_SRY.bam -counts
    chrY	2786855	2787699	0

**Comment by AlaaBadredine** [comment]
So the `bedtools --version` gives `bedtools c7519a52` only. Not sure if this how it should be, maybe I am on the wrong version ?

Thanks for checking, it must be an issue from my side then.

**Comment by valleem** [comment]
We experienced a Segmentation fault on 2.28.0 at my lab, where the same command worked under 2.26.0 (same BED, same BAM, replicated both locally and on our cluster) :
```
$ bedtools --version
bedtools v2.26.0
$ ./bedtools2/bin/bedtools --version
bedtools v2.28.0
$ bedtools coverage -d -a test.bed -b BC289_chr22.bam | head -n 1
chr22   24133868        24134124        SMARCB1 0       +       .       .       1       282
$ ./bedtools2/bin/bedtools coverage -d -a test.bed -b BC289_chr22.bam
Segmentation fault (core dumped)
```
