### ISSUE TITLE
Error: The genome file grch38_full.fa has no valid entries. Exiting

### ISSUE THREAD

**Issue by aerijman** [arq5x/bedtools2#726]
I just installed a fresh bedtools from bioconda (btw, it's 2.27 shouldn't be 2.28?). 

I still have this problem:  
 
`bedtools genomecov -dz -ibam MyBam -g grch38_full.fa > MyBed` worked great. 
`bedtools coverage -g grch38_full.fa -sorted -counts -a chr1-120.bed -b MyBam > MyBed` threw me:   
> Error: The genome file grch38_full.fa has no valid entries. Exiting.   
  
Bam files have been indexed with samtools (if relevant).

Thank you,
Ariel

**Comment by arq5x** [comment]
The genome file should be a tab delimited file with the first column as the chromosome label and the second column the length of the chromosome. It should not be a FASTA file.
https://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format
