### ISSUE TITLE
Bedtools MakeWindows ignores "-s" when asking for a fixed number of windows

### ISSUE THREAD

**Issue by lucventurini** [arq5x/bedtools2#731]
Example:
```
$ echo -e "chr1\t10000" > /tmp/test.txt
$ bedtools makewindows -w 5000 -s 5500 -g /tmp/test.txt 
chr1	0	5000
chr1	5500	10000
$ bedtools makewindows -n 2 -s 5500 -g /tmp/test.txt 
chr1	0	5000
chr1	5000	10000
```

Ideally the tool should produce the same answer with both commands. Alternatively, it would be better if `makewindows ` explicitly stated in the help that the `-s` parameter is ignored when the `-n` option is selected.

**Comment by arq5x** [comment]
Thanks for reporting. I updated master to error when `-s` and `-n` are used together.
