### ISSUE TITLE
Would be nice to have a warning if [options] are placed at the end of the command

### ISSUE THREAD

**Issue by aerijman** [arq5x/bedtools2#734]
`bedtools coverage -a foo.bed -b foo.bam -sorted` silently ignored the `-sorted` argument.

Thank you!

**Comment by arq5x** [comment]
For what version are you seeing this behavior?

**Comment by aerijman** [comment]
2.25.0

**Comment by arq5x** [comment]
I am rather sure this has been fixed. Please update to 2.28.0

**Comment by aerijman** [comment]
ok thanks
