### ISSUE TITLE
windowMaker does not recognise - as stdin 

### ISSUE THREAD

**Issue by dariober** [arq5x/bedtools2#735]
Hi- Possibly a small bug here. In contrast to other bedtools commands, windowMaker does not recognise `-` as stdin. Using `/dev/stdin` is ok: 
 
```
echo -e "chr1\t1000" | windowMaker -g /dev/stdin -w 300
chr1	0	300
chr1	300	600
chr1	600	900
chr1	900	1000
```

Using `-` instead:

```
echo -e "chr1\t1000" | windowMaker -g - -w 300
Error: The requested genome file (-) could not be opened. Exiting!
```

```
bedtools --version
bedtools v2.27.1
```

(Edit: happens also with v2.28.0)

**Comment by arq5x** [comment]
sorry, bedtools doesn't have stdin support for `-g` file, as the typical use case for other tools is to use stdin for the BED files.

**Comment by dariober** [comment]
Hi Aaron - Thanks for your reply,

>  bedtools doesn't have stdin support for -g file

I see, but I was puzzled by the fact that `windowMaker -g /dev/stdin` does work. So it seems stdin in `-g` is supported if using "`/dev/stdin`" but fails if using "`-`" instead. If this is intentional and not an oversight than all good!

**Comment by arq5x** [comment]
I misunderstood - you are correct. Fix pushed to master. Thanks!

**Comment by arq5x** [comment]
Just for clarity, `/dev/stdin` is treated as an actual file by the OS.
