### ISSUE TITLE
Unexpected bedtools intersect behavior

### ISSUE THREAD

**Issue by kmcquisten** [arq5x/bedtools2#740]
In the course of doing some debugging on an analysis pipeline I've written, I've found some unexpected behavior in bedtools intersect.  

As we know, bed intervals are half-open, so the interval [a,b) contains the position a, but not the position b.  As a result, the intervals [a,b) and [b,c) do not overlap, and should not be output as intersecting by bedtools intersect. Indeed, this is indeed the case when c > b. 

However, in the bed file I'm using for file B, some records are annotated with the same start and stop coordinate. In this instance, if you have an interval [a,b) in file A and an interval [b,b) in file B, bedtools intersect will report this as a valid intersection and return an intersection record, even though position b does not overlap the interval [a,b). 

I’ve been able to reproduce this behavior in bedtools 2.25, 2.26, 2.27, and 2.28.

Is there a rational reason for this behavior?  It seems like it would be more reasonable for bedtools intersect to return nothing in this case.

Thank you very much,
Kyle

**Comment by arq5x** [comment]
when start == end, bedtools interprets this as an insertion between the two flanking bases and thus intersections arise with the two flanking bases.
