### ISSUE TITLE
Add a counting option per database

### ISSUE THREAD

**Issue by cljacobs** [arq5x/bedtools2#744]
This is a feature request, not really an issue. I find myself wanting to do this kind of thing a lot:

```
bedtools intersect -c a 0.bed -b 1.bed > tmp1.bed
bedtools intersect -c a tmp1.bed -b 2.bed > tmp2.bed
...
```

Unfortunately (for me) when you combine the `-c` option and multiple databases for a `-b` option you get the sum total of counts across all the databases. I'm not suggesting this is the incorrect behavior or anything like that, but it would be helpful if there were another option to split the counts per database.

**Comment by arq5x** [comment]
This is a useful option and I will look into implementing it soon.

**Comment by arq5x** [comment]
I have looked into this and it is doable. For backwards compatibility, however, I will need add a new option (perhaps `-C` versus `-c`)

**Comment by cljacobs** [comment]
That sounds great. I was thinking about this recently as well, and I probably should have fleshed out (one of) the potential usage pitfalls a bit more as well. Specifically, making sure to know what your database input order is --- assuming the output order of count-columns matches the input order of the databases. It's all well and good to type in something like:

```
bedtools intersect -C -a query.bed -b subjects* > hits.bed
```

until you move machines, or execute in a directory with some mixed filename capitalization (shudder), or whatever and find that `*` expands in a different order than you might have expected. Even relatively benign usage can bite you if you aren't sure what order command line expansions work in.

All of that to say, I don't think bedtools would need to do anything special here, but a gentle reminder/alert in the docs that points out this particular pitfall might be a nice addition as well.

**Comment by arq5x** [comment]
This has been addressed in master with a new -C option. Docs forthcoming, but here is an example:

    bedtools intersect -a query.bed -b d1.bed d2.bed d3.bed -C -f 0.5 -names d1 d2 d3
    chr1	1	20	d1	1
    chr1	1	20	d2	0
    chr1	1	20	d3	0
    chr1	40	45	d1	0
    chr1	40	45	d2	1
    chr1	40	45	d3	0
    chr1	70	90	d1	0
    chr1	70	90	d2	0
    chr1	70	90	d3	0
    chr1	105	120	d1	0
    chr1	105	120	d2	1
    chr1	105	120	d3	1
    chr2	1	20	d1	1
    chr2	1	20	d2	0
    chr2	1	20	d3	0
    chr2	40	45	d1	0
    chr2	40	45	d2	1
    chr2	40	45	d3	0
    chr2	70	90	d1	0
    chr2	70	90	d2	0
    chr2	70	90	d3	0
    chr2	105	120	d1	0
    chr2	105	120	d2	1
    chr2	105	120	d3	1
    chr3	1	20	d1	1
    chr3	1	20	d2	0
    chr3	1	20	d3	0
    chr3	40	45	d1	0
    chr3	40	45	d2	1
    chr3	40	45	d3	0
    chr3	70	90	d1	0
    chr3	70	90	d2	0
    chr3	70	90	d3	0
    chr3	105	120	d1	0
    chr3	105	120	d2	1
    chr3	105	120	d3	1

**Comment by arq5x** [comment]
To get the "collapsed" format you describe, just use the `groupby` command.

    bedtools intersect -a query.bed -b d1.bed d2.bed d3.bed -C -names d1 d2 d3 -f 0.5 \
      | bedtools groupby -g 1,2,3 -c 4,5 -o collapse
    chr1	1	20	d1,d2,d3	1,0,0
    chr1	40	45	d1,d2,d3	0,1,0
    chr1	70	90	d1,d2,d3	0,0,0
    chr1	105	120	d1,d2,d3	0,1,1
    chr2	1	20	d1,d2,d3	1,0,0
    chr2	40	45	d1,d2,d3	0,1,0
    chr2	70	90	d1,d2,d3	0,0,0
    chr2	105	120	d1,d2,d3	0,1,1
    chr3	1	20	d1,d2,d3	1,0,0
    chr3	40	45	d1,d2,d3	0,1,0
    chr3	70	90	d1,d2,d3	0,0,0
    chr3	105	120	d1,d2,d3	0,1,1
