### ISSUE TITLE
bamtobed CIGAR string option does not recognize "="

### ISSUE THREAD

**Issue by hd00ljy** [arq5x/bedtools2#747]
Hello

  I mapped my sequence using LAST that gives .maf file

  The conversion of .maf file to BAM gives CIGAR string like this.

```
884312H91=1D33=1D53=1D7=1X4=1D98=1D87=4D13=1D133=1X62=1D57=1I34=1D62=1D6=1D
```

  But when I convert this BAM to BED with -cigar option, the cigar strings don't have "=" characters

```
884312H1D1D1D1D1D4D1D1D1I1D1D1D2D1D1D1D1D1D1D2D1D2D1D1D1D1D1D1D1D1D1I1D1D1I2D1D1D1D1D2D1D1D1D2D1D1D1D1D1D1I1D1D1D3D1I2D1D1D1D1D1I1D1D2D1I1D3D1D
1D1D1I2D2D1D1D1D1D1D1D1D1D1D1D1D1D1D1D3D2D1D1D1D1D1D1D1D1D1D1D1D1I1D1D1D1D1D4D1D2D1D1D2D
```

"=" seems to be CIGAR string characters  documented  in SAM specification but not widely used.

**Comment by arq5x** [comment]
What version of bedtools are you using?

**Comment by hd00ljy** [comment]
The bedtools version I am using is

v2.27.1

**Comment by arq5x** [comment]
Thanks for reporting. This has been fixed in master.
