### ISSUE TITLE
Genomecov -bga  negative values....

### ISSUE THREAD

**Issue by dantaki** [arq5x/bedtools2#749]
I'm getting some weird behavior with `bedtools genomecov  -bga` 

I am seeing a lot of negative values. 

I am using the most recent Linux static build of bedtools. 

I have a file with just chr1 segments. This is some of my output...

```
chr1	245306699	245926509	-2039
chr1	245926509	246246810	-2038
chr1	246246810	246847432	-2037
chr1	246847432	247009262	-2035
chr1	247009262	247073072	-2034
chr1	247073072	247238342	-2035
chr1	247238342	247238344	-2034
chr1	247238344	247415139	-2035
chr1	247415139	247565382	-2041
chr1	247565382	248406068	-2042
chr1	248406068	248772173	-2043
chr1	248772173	248781178	-2047
chr1	248781178	248956422	-2048
chr2	0	150380207	0
chr2	150380207	242193529	-2048
chr3	0	77351599	0
chr3	77351599	198295559	-2048
chr4	0	140444335	0
chr4	140444335	190214555	-2048
chr5	0	77415087	0
chr5	77415087	181538259	-2048
chr6	0	136826031	0
chr6	136826031	170805979	-2048
```

Here is a selection of my input bed file
```
chr1    245195317       247073072
chr1    245306699       247565382
chr1    245926509       247415139
```

I definitely have segments in those regions with negative values. Not sure what's going on here ... 

Thanks!

**Comment by dantaki** [comment]
Actually I get the correct result running the same command on a different (Cent OS) computer. The error occurred on a Ubuntu 18.04.2 computer running Linux 4.15. Maybe that would explain it?

**Comment by arq5x** [comment]
Are you sure it is the same version on each computer? Is one 32 bit and the other 64 bit?
