### ISSUE TITLE
slop works differently on small vs. large files

### ISSUE THREAD

**Issue by kwcurrin** [arq5x/bedtools2#752]
Hello,

I found a very strange issue where bedtools slop appears to behave differently in large vs. small files. My goal is to clip bedgraph regions that fall outside of chromosome edges using slopBed with -b set to 0. This works correctly for a small file:
cat test3.bed
chr17   81195191        81195210        2.00000
chr17   81195210        81195213        1.00000

cat hg19.chromsizes | grep "chr17"
chr17   81195210

If I run slopBed on just the small test3.bed file, it works correctly:
slopBed -b 0 -i test3.bed -g hg19.chromsizes
chr17   81195191        81195210        2.00000
chr17   81195209        81195210        1.00000

However, if I run the same command on a much larger file (11gb, whole genome bedgraph file) and then restrict to the same two regions on chr17, the second region that extends past the chromosome edge is not removed:
slopBed -b 0 -i 662_treat_pileup.bdg -g hg19.chromsizes | intersectBed -u -a stdin -b test3.bed
chr17   81195191        81195210        2.00000
chr17   81195210        81195213        1.00000

Thanks for any help you can provide on this!

**Comment by kwcurrin** [comment]
Hello,

I was wrong on the exact cause of this issue. The larger file I was working with (662_treat_pileup.bdg) contained a record completely outside of the upper bound of chr17:
chr17   81195213        81195261        1.00000

When I ran slopBed on this file, this record was converted to:
chr17   81195210        81195213        1.00000

In the case when a record is completely outside of the upper boundary of a chromosome, it looks like slopBed is decreasing the start coordinate to the chromosome upper boundary and then decreasing the stop coordinate to the previous start coordinate. So the issue is that slop doesn't correctly handle records completely outside chromosome boundaries, not an issue with file size.

**Comment by arq5x** [comment]
Thanks! Have you tested this with version 2.28.0?

**Comment by kwcurrin** [comment]
Unfortunately it occurs in 2.28.0 (initially tested on 2.27.1 as well)

**Comment by arq5x** [comment]
This is now fixed in master. Thanks!
