### ISSUE TITLE
Output of bedtools intersect -wao is incorrect in v2.26

### ISSUE THREAD

**Issue by kietoparao** [arq5x/bedtools2#757]
I've found what I think is a bug when running `bedtools intersect -wao` or `bedtools intersect -wo` with version 2.26. Strangely (at least for me), it doesn't happen when running `bedtools intersect`, `bedtools intersect -wa` or `bedtools intersect -wb`. Also, this issue does not happen in previous version 2.25, and later version 2.27.1 and 2.28.

A minimal test case is provided here (using Ubuntu 18.04.3 LTS 64-bit):

```bash
$ cat a.bed
1	45794976	45795110	MUTYH
$ cat b.bed
1	45794911	45795175	MUTYH
$ ./bedtools2.25/bin/bedtools intersect -wao -a a.bed -b b.bed
1	45794976	45795110	MUTYH	1	45794911	45795175	MUTYH	134
$ ./bedtools2.26/bin/bedtools intersect -wao -a a.bed -b b.bed 
1	13494976	45795110	MUTYH	1	45794911	45795175	MUTYH
$ ./bedtools2.27.1/bin/bedtools intersect -wao -a a.bed -b b.bed 
1	45794976	45795110	MUTYH	1	45794911	45795175	MUTYH	134
$ ./bedtools2.28/bin/bedtools intersect -wao -a a.bed -b b.bed 
1	45794976	45795110	MUTYH	1	45794911	45795175	MUTYH	134
```

As you can see, output is consistent between versions 2.25, 2.27.1 and 2.28, but is incorrect in version 2.26 (which is the one that Ubuntu 18.04.3 LTS 64-bit is packaging right now): the second column outputs a `13494976` instead of `45794976`, and the last column is empty where a `134` is expected.

Thanks so much for such a great tool, by the way! :)

**Comment by arq5x** [comment]
Yes, a bug was introduced in 2.26 that has since been fixed.

**Comment by kietoparao** [comment]
Great, thanks!
