### ISSUE TITLE
bedtools v2.28 multicov outputs zero counts for all BAMs if one of them has zero counts

### ISSUE THREAD

**Issue by kietoparao** [arq5x/bedtools2#758]
The command `bedtools multicov` outputs different results than previous versions if only one of the BAM files used has zero counts for a BED interval. In that case, it outputs zero counts for all BAM files even though some of them might have positive counts.

Minimal test case provided here. BAM files used:

* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/alignment/HG00096.chrom20.ILLUMINA.bwa.GBR.low_coverage.20120522.bam>
* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/alignment/HG00096.chrom20.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai>
* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00097/alignment/HG00097.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam>
* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00097/alignment/HG00097.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam.bai>
* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00099/alignment/HG00099.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam>
* <ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00099/alignment/HG00099.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam.bai>

BED file used:

```bash
$ cat chr20_hg38_toy.bed 
20	1392899	1392961	NR_106929.1
20	2654211	2654286	NR_003078.1
20	2655066	2655198	NR_002981.1
20	2656096	2656182	NR_004399.1
20	2656623	2656694	NR_002739.1
20	3917493	3917571	NR_029519.1
20	3917501	3917563	NR_031722.1
```

Test runs:

```bash
$ ./bedtools2.27.1/bin/bedtools multicov -bams HG00096.chrom20.ILLUMINA.bwa.GBR.exome.20120522.bam HG00097.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam HG00099.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam -bed chr20_hg38_toy.bed
20	1392899	1392961	NR_106929.1	0	16	15
20	2654211	2654286	NR_003078.1	1	18	15
20	2655066	2655198	NR_002981.1	0	20	17
20	2656096	2656182	NR_004399.1	0	9	17
20	2656623	2656694	NR_002739.1	1	20	10
20	3917493	3917571	NR_029519.1	0	18	11
20	3917501	3917563	NR_031722.1	0	18	8

$ ./bedtools2.28/bin/bedtools multicov -bams HG00096.chrom20.ILLUMINA.bwa.GBR.exome.20120522.bam HG00097.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam HG00099.chrom20.ILLUMINA.bwa.GBR.low_coverage.20130415.bam -bed chr20_hg38_toy.bed
20	1392899	1392961	NR_106929.1	0	0	0
20	2654211	2654286	NR_003078.1	1	18	15
20	2655066	2655198	NR_002981.1	0	0	0
20	2656096	2656182	NR_004399.1	0	0	0
20	2656623	2656694	NR_002739.1	1	20	10
20	3917493	3917571	NR_029519.1	0	0	0
20	3917501	3917563	NR_031722.1	0	0	0
```

I've tested it with previous versions 2.25, 2.26 and 2.27.1 (in Ubuntu 18.04.3 LTS 64-bit), and results are equal between them.

Edited: URLs

**Comment by arq5x** [comment]
Thanks for reporting. This is now fixed in master.
