### ISSUE TITLE
bedtools complement too picky and docs out of date

### ISSUE THREAD

**Issue by SumNeuron** [arq5x/bedtools2#763]
I try calling:

```
bedtools complement -i my_file.bed -g genome.chrom.sizes > not_in_my_file.bed
```

and get

```
Error: Sorted input specified, but the file my_file.bed has the following record with a different sort order than the genomeFile genome.chrom.sizes
chr1	67092175	67093604	ENST00000371006.5_exon_0_0_chr1_67092176_r	0	-
```

so, I - perhaps naively - thought that sorting my input file would fix this:

```
bedtools sort -i my_file.bed -chrThenSizeA > my_file_sorted.bed
```

and then run

```
bedtools complement -i my_file_sorted.bed -g genome.chrom.sizes > not_in_my_file.bed
```

```
Error: Sorted input specified, but the file my_file_sorted.bed has the following record with a different sort order than the genomeFile genome.chrom.sizes
chr11	112966	113111	ENST00000622626.1_exon_0_0_chr11_112967_r	0	-
```

so then I figured, well maybe sorted will work on the "genome" file:

```
bedtools sort -i genome.chrom.sizes

It looks as though you have less than 3 columns at line: 1.  Are you sure your files are tab-delimited?
```

which it doesn't.

using `unix` `sort -k 1,1 genome.chrom.sizes` doesn't work either as the proceeding string of `chr` doesn't help.

Long story short, I do not know why my input file is not in the right order. I would assume that `bedtools sort` would fix it, or the complement would sort it if it detects that it is out of order.

my `genome.chrom.sizes` is just `hg38.chrom.sizes`:

```
chr1	248956422
chr2	242193529
chr3	198295559
chr4	190214555
chr5	181538259
chr6	170805979
chr7	159345973
chrX	156040895
chr8	145138636
chr9	138394717
chr11	135086622
chr10	133797422
chr12	133275309
chr13	114364328
chr14	107043718
chr15	101991189
chr16	90338345
chr17	83257441
chr18	80373285
chr20	64444167
chr19	58617616
chrY	57227415
chr22	50818468
chr21	46709983
...
```

In the docs it states:

```
-L Only report chromosomes that are in the -i file
```

but using `-L` results in

```
***** ERROR: Unrecognized parameter: -L *****
```

**Comment by arq5x** [comment]
Could you share your file `my_file.bed`? I would like to take a look. Also, the `-L` option is new to 2.29.0 (I will update the docs), but should not get around the issue you are having.

**Comment by SumNeuron** [comment]
@arq5x it is 

```
cat filtered_encode_gencode_comp_v28_*.bed > my_file.bed
```
where `*` is either `exons` or `introns` and this file has been filtered to only contain the numberic chromsomes 

```
chr1,
...
chr22
```

if you do not have these files, they are from the Genome Browser but can also be retrieved via


```
 from ntai.fetch.utils import (
      fetch_exons, fetch_introns,
      fetch_hg38_chrom_sizes,
      decompress
    )

    directory = os.path.join(path, to, output, directory)

   # these two files are then filtered for just chr1, chr2, ..., chr22
    fetch_exons(directory=directory)
    fetch_introns(directory=directory)
    # file I use as genome file
    fetch_hg38_chrom_sizes(directory=directory)

```

**Comment by arq5x** [comment]
This really should work. Can you try this and let me know what you get with version 2.29?

    sort -k1,1 -k2,2n my_file.bed > my_file.sorted.bed
    sort -k1,1 hg38.chrom.sizes > hg38.chrom.sorted.sizes
    bedtools complement -i my_file.sorted.bed -g hg38.chrom.sorted.sizes

**Comment by SumNeuron** [comment]
Same errors, I also tried that :/

**Comment by arq5x** [comment]
Okay, will try to recreate but struggling to install your ntai package. May take me a bit to look into what is causing this.

**Comment by SumNeuron** [comment]
Oh, well the code for downloading the files is [here](https://gitlab.com/SumNeuron/ntai/blob/master/ntai/fetch/utils.py)

```python
import urllib.parse, requests, os, gzip, shutil


HG_TABLES_URL = 'http://genome.ucsc.edu/cgi-bin/hgTables'

HG_DOWNLOAD_DIRECTORY_URL = 'http://hgdownload.soe.ucsc.edu'

HG38_DOWNLOAD_DIRECTORY_URL = '{}/goldenPath/hg38/bigZips'.format(HG_DOWNLOAD_DIRECTORY_URL)

HG38_FASTA_URL = '{}/hg38.fa.gz'.format(HG38_DOWNLOAD_DIRECTORY_URL)
HG38_CHROM_SIZES_URL = '{}/hg38.chrom.sizes'.format(HG38_DOWNLOAD_DIRECTORY_URL)



DEFAULT_PARAMS = {
    'ignoreCookie': 1,
    'hgta_track': 'wgEncodeGencodeCompV28',
    'boolshad.hgta_printCustomTrackHeaders':0,
    'hgta_ctName':'tb_wgEncodeGencodeCompV28',
    'hgta_ctDesc': 'table+browser+query+on+wgEncodeGencodeCompV28',
    'hgta_ctVis': 'pack',
    'hgta_ctUrl': None,
    'fbUpBases': 200,
    'fbQual': 'exon',
    'fbExonBases': 0,
    'fbIntronBases': 0,
    'fbDownBases': 200,
    'hgta_doGetBed': 'get+BED'
}


def fname(file:str, directory:str=None):
    '''
    Notes:
        1. if directory is None and file is just the basename, directory is set
            to '~/Downloads'
        2. if file is the full path and directory is set to none, directory is
            ignored.
        3. if file is partial path and directory is not none, directory is
            prepended to the file.
    Arguments:
        file (str): the file's name, either basename or full path.
        directory (str): the directory of the file. Default is None.
    Returns:
        fullpath (str): full path of the file given the directory

    '''
    # user passes just the filename. Then defaults to download directory
    if directory is None and os.path.basename(file) == file:
        directory = '~/Downloads'

    if directory is None:
        directory = ''

    name = os.path.expanduser(os.path.join(directory, file))
    return name




def fetch_exons(
    file:str='encode_gencode_comp_v28_exons.bed',
    directory:str=None
):
    params = {'fbQual': 'exon'}
    request = requests.get(HG_TABLES_URL, params={**DEFAULT_PARAMS, **params})
    if request.status_code == 200:
        with open(fname(file, directory), 'w') as f:
            f.write(request.text)

def fetch_introns(
    file:str='encode_gencode_comp_v28_introns.bed',
    directory:str=None
):
    params = {'fbQual': 'intron'}
    request = requests.get(HG_TABLES_URL, params={**DEFAULT_PARAMS, **params})
    if request.status_code == 200:
        with open(fname(file, directory), 'w') as f:
            f.write(request.text)

def fetch_hg38_chrom_sizes(
    file:str='hg38.chrom.sizes',
    directory:str=None
):
    request = requests.get(HG38_CHROM_SIZES_URL)
    if request.status_code == 200:
        with open(fname(file, directory), 'w') as f:
            f.write(request.text)

def fetch_hg38(
    file:str="hg38.fa.gz",
    directory:str=None
):
    request = requests.get(HG38_FASTA_URL)
    if request.status_code == 200:
        with open(fname(file, directory), 'wb') as f:
            # f.write(request.raw.read())
            f.write(request.content)

def decompress(path:str, odir:str=None):
    '''
    Decompresses the .gz file specified by path. Decompressed file keeps the
    same basename e.g. my_file.txt.gz --> my_file.txt

    Arguments:
        path (str): full path to a .gz compressed file
        odir (str): optional. A new output directory for the file. By default None.

    Returns:
        None.
    '''
    ofile = os.path.splitext(os.path.expanduser(path))[0]
    if odir is not None:
        ofile = os.path.join(odir, os.path.basename(ofile))
    with gzip.open(path, 'rb') as f_in:
        with open(ofile, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)


def fetch_files(directory:str):
    fetch_exons(directory=directory)
    fetch_introns(directory=directory)
    fetch_hg38_chrom_sizes(directory=directory)
    fetch_hg38(directory=directory)
    decompress(os.path.join(directory, 'hg38.fa.gz'))
```

**Comment by arq5x** [comment]
I ran your script and received the following files.

    encode_gencode_comp_v28_exons.bed
    encode_gencode_comp_v28_introns.bed
    hg38.chrom.sorted.sizes

The I ran:
    
    sort -k1,1 -k2,2n encode_gencode_comp_v28_exons.bed > encode_gencode_comp_v28_exons.sorted.bed
    sort -k1,1 hg38.chrom.sizes > hg38.chrom.sorted.sizes

Then I ran the following with no problem:

    bedtools complement -i encode_gencode_comp_v28_exons.sorted.bed -g hg38.chrom.sorted.sizes

I suspect you either did a different sort or didn't use the sorted files in your bedtools run.

**Comment by SumNeuron** [comment]
@arq5x I use the sorted file in my script, there is a post-processing step that is missing. I remove all chromosomes which are not strictly numeric (e.g. `chr1`, ... `chr22` only). I suspect that this is the issue as genome file has `chrX` and other such chromosomes.

**Comment by SumNeuron** [comment]
I'm sorry, I don't understand why `bedtools complement` should fail if not every chromosome in genome file is not in the input file

**Comment by arq5x** [comment]
Sorry, I meant I think something is wrong with your script. Filtering input as you describe works for me.

    awk '!($1 ~ /_/)' encode_gencode_comp_v28_exons.sorted.bed | grep -vw chrX | grep -vw chrY | grep -vw chrM  > encode_gencode_comp_v28_exons.sorted.filtered.bed
    # report the chroms in genome file not in data file
    bin/bedtools complement -i encode_gencode_comp_v28_exons.sorted.filtered.bed -g hg38.chrom.sorted.sizes
    # report solely the chroms in genome file and in data file    
    bin/bedtools complement -L -i encode_gencode_comp_v28_exons.sorted.filtered.bed -g hg38.chrom.sorted.sizes

**Comment by arq5x** [comment]
bin/bedtools --version
    bedtools v2.29.0

**Comment by SumNeuron** [comment]
```
bedtools is already the newest version (2.25.0-1).
```

**Comment by arq5x** [comment]
Hi @SumNeuron, I am not sure what you mean. The latest version available is 2.29. The version you cite (2.25) is from 2015.
https://github.com/arq5x/bedtools2/releases

**Comment by SumNeuron** [comment]
result of:

```
sudo apt-get --only-upgrade install bedtools
```

**Comment by arq5x** [comment]
I apologize, but I have no control over the versions available via apt-get.

**Comment by SumNeuron** [comment]
whelp, ok :P maybe let whoever manages those packages know because users who rather use a package manager on Ubuntu, following the install guide, are stuck there :P

**Comment by jmarshall** [comment]
@SumNeuron: Presumably you are using Ubuntu Xenial then, which is itself rather long in the tooth. 

As an Ubuntu user, you probably want to report the package-update bug to Ubuntu yourself:
see <https://packages.ubuntu.com/> and <https://launchpad.net/ubuntu/+source/bedtools/+bugs>.
