### ISSUE TITLE
Bedtools coverage errors when unused chromosome is missing

### ISSUE THREAD

**Issue by jnasser3** [arq5x/bedtools2#769]
Bedtools coverage errors if a chromosome is not defined in the genomes file, even when the chromosome is not present in -a.

$ cat > a.bed
1	1	10

$cat > b.bed
1	2	5
2	2	5

$ cat > genomes.bed
1	10

$ bedtools coverage -counts  -g genomes.bed -a a.bed -b b.bed
Error: requested chromosome 2 does not exist in the genome file genomes.bed. Exiting.

This is using 2.26.0.

Given that chr2 will not be returned in the output, it seems unnecessary to require it to be present in the genome file. Is it possible to bypass this requirement?

**Comment by arq5x** [comment]
Unfortunately, no. The point of the genome file is to tell bedtools the list of chromosomes that are valid and their sort order, when your chromosomes are not lexicographically sorted. However, in your case, you could just sort the files lexicographically (`sort -k1,1 -k2,2n`) and then omit the genome file. It should work fine.
