### ISSUE TITLE
bedtools lexicographically sorted chromosmes

### ISSUE THREAD

**Issue by agolicz** [arq5x/bedtools2#775]
Hi,
I've put this question of bedtools-discuss, but think this might be a better place.

I have just noticed that according to documentation when chromosomes are not lexicographically sorted
one should provide a genome (-g) file. However I see no difference between providing the file and not,
as long as both files are in the same order:

bedtools map -a NP.0.4.tads.m -b Oryza_sativa_CHG_Leaf_12d.bg -c 4 -o sum -null 0 -F 1.0 > t1.test
bedtools map -a NP.0.4.tads.m -b Oryza_sativa_CHG_Leaf_12d.bg -c 4 -o sum -null 0 -F 1.0 -g chrs.len.bed > t2.test

diff t1.test t2.test -> no difference

BEDTools/2.28.0 (same seems to be true for 2.25) and for closestBed. Also it looks like for intersect -sorted only grouping by chromosome is required. Is that true for all the tools now and when was the change implemented?

I never really worried about lexicographical sorting, just made sure the same sort was used until I looked at the documentation again.

Could you please help me understand the documentation? 

All the best,
Agnieszka

cut -f 1 NP.0.4.tads.m | uniq
Chr1
Chr2
Chr3
Chr4
Chr5
Chr6
Chr7
Chr8
Chr9
Chr10
Chr11
Chr12

cut -f 1 Oryza_sativa_CHG_Leaf_12d.bg | uniq
Chr1
Chr2
Chr3
Chr4
Chr5
Chr6
Chr7
Chr8
Chr9
Chr10
Chr11
Chr12

cat chrs.len.bed
Chr1    43270923
Chr2    35937250
Chr3    36413819
Chr4    35502694
Chr5    29958434
Chr6    31248787
Chr7    29697621
Chr8    28443022
Chr9    23012720
Chr10   23207287
Chr11   29021106
Chr12   27531856

sort -k 1,1 -k 2,2n chrs.len.bed
Chr1    43270923
Chr10   23207287
Chr11   29021106
Chr12   27531856
Chr2    35937250
Chr3    36413819
Chr4    35502694
Chr5    29958434
Chr6    31248787
Chr7    29697621
Chr8    28443022
Chr9    23012720

**Comment by arq5x** [comment]
It does matter, but bedtools cannot detect that there is a problem for all input files. In your case, it seems that it could not detect a problem and it was able to detect all overlaps via the chromosome grouping.

**Comment by agolicz** [comment]
So chromosome grouping is also used for map and closest commands?

Agnieszka
