### ISSUE TITLE
getfasta with forced strandedness has unexpected result?

### ISSUE THREAD

**Issue by SumNeuron** [arq5x/bedtools2#778]
I wanted to run a sanity check on `getfasta`, so I have a test fasta file which is just all the fasta characters

### test.fa
```txt
>chr1
ACGTURYKMSWBDHVN-
```

### test.bed
```tsv
chr1	0	17	for	1	+
chr1	0	17	rev	1	-
```

and then run 

```
bedtools getfasta -fi test.fa -bed test.bed -fo test.out -s
```

resulting in 

### test.out
```
>chr1:0-17(+)
ACGTURYKMSWBDHVN-

>chr1:0-17(-)
-NBDHVWSKMRYUACGT
```

if we take the reverse complement (a result from the forced strandedness argument `-s`) and reverse it so that it is the complement, then we have

```
forward: ACGTURYKMSWBDHVN-
reverse: TGCAUYRMKSWVHDBN-
```

while fasta characters with clear opposites are complement (e.g. R (ag) --> Y (ctu)), others like (S)trong  (cg) and (W)eak (atu) are not. Is that correct?

Further the "not" series (B, D, H, V) are paired with each other. While not C paired to not G makes sens, is not A - B (cgtu) - complement not U - V (acg)?

**Comment by kehey** [comment]
For S (C or G): C and G are complements so the complement of S is S again. Same for W.  So that is correct.

For B (not A, so C, G or T), the complementary options are G,C or A -> V
