### ISSUE TITLE
genomecov segfault

### ISSUE THREAD

**Issue by iminkin** [arq5x/bedtools2#792]
Hi,

I used bedtools v2.29.0-14-gea5e914, installed from the github repo (ea5e914168c880d5c6d83246c3e0902b423b20d9). Running the following command results in a segfault (files attached, [crash.zip](https://github.com/arq5x/bedtools2/files/3879112/crash.zip)):

`bedtools genomecov -i blocks.bed -g genome.bed`

**Comment by arq5x** [comment]
Thanks for reporting this. We will look into it ASAP.

**Comment by arq5x** [comment]
The genome file should be just two columns: chrom, then length.

Instead of
```cat genome.bed
SE001	0	1453005
SE002	0	1450581
SE003	0	1456197
SE004	0	1459554
SE005	0	1458219
SE006	0	1453434
SE007	0	1459092
SE008	0	1459320
SE009	0	1456596
SE010	0	1453512```

Make it:
```cat genome.bed
SE001	1453005
SE002	1450581
SE003	1456197
SE004	1459554
SE005	1458219
SE006	1453434
SE007	1459092
SE008	1459320
SE009	1456596
SE010	1453512```

**Comment by arq5x** [comment]
I am also adding code to detect this and not segfault.

**Comment by iminkin** [comment]
@arq5x

Oh, my bad, did not realize the genome file should not be in BED format. Thank you for a quick reply!
