### ISSUE TITLE
Bedtools closest is giving less genes than expected

### ISSUE THREAD

**Issue by amitjavilaventura** [arq5x/bedtools2#793]
Hello!

I am having a problem with `bedtools closest`. 

I have some .bed files with the coordinates of several random regions which I have created with `bedtools random`. In one file, concretely, I have 2275 regions. 

Then, I am calling `bedtools closest` with the following code:
```
closestBed \
-k 10 -d -t first \
-a random_regions.bed \
-b all_genes.bed > \
10_closest_genes_to_random_regions.bed
``` 
It seems that it should be OK, I have even tried without `-d` and/or without `-t first`. However, when I look at how many genes i have in the output file, I see that there are only 22723 genes, when one would expect to find 22750 (< number of random regions > * < number of closest genes to call with bedtools closest >). 

Normally this would not be a problem, since there are only 27 out of 22750 genes missing, but now I need the correct number of genes to do the downstream analysis.

If someone could give me the reason why is this happening and, if it is possible, give me some advice, it would be perfect. 

Thank you very much.

**Comment by arq5x** [comment]
Is it possible that you have random regions that lie on chromosomes with less than 10 total genes?  If you share your files, I could also look at this, but I suspect this is your problem. If there are less than 10 genes on a given chromosome, then the tool cannot collect 10 for you. That said, it should raise a warning if this is the case. I will address this. Please let me know if you see that this is the case with the following command:   

    cut -f 1 all_genes.bed | sort | uniq -c | awk '$1 < 10'

**Comment by arq5x** [comment]
I have confirmed that this is the cause and have added a warning to alert users that this is happening.
