### ISSUE TITLE
Loss of reads when using bamToFastq

### ISSUE THREAD

**Issue by elcortegano** [arq5x/bedtools2#797]
Using bamToFastq on a set of data, I have noticed that there is an important loss of reads after generating the fastq files from BAM files. The command used was:

     ./bamToFastq -i file.bam -fq file_1.fq -fq2 file_2.fq

To give an idea of the extent of the problem. The original fastq files with the reads had a size of ~1.4GB in size each, after alignment (bwa mem + samtools sort) the resultant BAM file had a size of ~2.3GB. When fastq files are generated with the command above, these files have a size in the order of 70MB. If new BAM files are generated, it can be seen in IGV an evident loss of coverage along all the sequence.

A workaround for me has been to use samtools fastq instead, but I hope this can also been fixed in bedtools! All the best

**Comment by tolot27** [comment]
Please can you check whether all reads have quality values assigned (column 11 <> `*`)?
A minimal sample bam file with reads getting lost would be helpful, too.

**Comment by elcortegano** [comment]
Yes, all reads seem to have a value of QUAL indicating the quality of the bases in the read.

Please find attached a small BAM file that reproduces the problem above.
[example.zip](https://github.com/arq5x/bedtools2/files/3922320/example.zip)

**Comment by tolot27** [comment]
Please can you provide the bedtools version you are using.

If I check the `example.bam`, i can't see any paired read:
```
samtools flagstat example.bam 
1394 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
2 + 0 supplementary
221 + 0 duplicates
1394 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
and later conversion to fastq without paired parameter: 
```
bamToFastq -i example.bam -fq example.fastq
seqkit stats example.fastq 
file           format  type  num_seqs  sum_len  min_len  avg_len  max_len
example.fastq  FASTQ   DNA      1,394  139,277       31     99.9      100
```
... I get the same number of reads.

**Comment by tolot27** [comment]
BTW: If I run `bamToFastq -i example.sorted.bam -fq example_1.fastq -fq2 example_2.fastq` I'm getting lots of warnings like `*****WARNING: Query FCC85WNANXX:7:2108:10675:4448#0 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping. ` even if I sort the bam file by name. Don't you get these warnings?
That is a clear indication that the bam file does not contain properly paired reads, as can be seen with `samtools flagstat example.bam`.

**Comment by elcortegano** [comment]
Version is v2.29.0-16-gc9473fc.
You are right, I was getting this warnings, but I just ignored them (my mistake). In origin this reads are supposed to be mated, I will check where the problem comes from at an earlier stage.
The issue can be probable closed, it works as expected without using -fq2.
Thank you for the help, and sorry for any inconvenience.
