### ISSUE TITLE
Installation and pre-compiled binaries

### ISSUE THREAD

**Issue by Jon-bioinfo** [arq5x/bedtools2#802]
The first instruction on the installation page is about using pre-compiled binaries, but they seem to not be present for the latest versions, and were only made for 2.28.0

**Comment by arq5x** [comment]
Thanks, this has been fixed for release 2.29.2:
https://github.com/arq5x/bedtools2/releases/tag/v2.29.2

download `bedtools.static.binary` then `mv bedtools.static.binary bedtools`, then `chmod a+x bedtools`
