### ISSUE TITLE
Bedtools intersect drops bam header line in latest version

### ISSUE THREAD

**Issue by jfreimer** [arq5x/bedtools2#803]
I am trying to use bedtools intersect and it drops the sorted status in the bam file header in bedtools 2.29.1, but not in 2.29.0

`bedtools intersect -v -abam test1.bam -b test.bed -wa > test2.bam`

2.29.0
`@HD	VN:1.0	SO:coordinate
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559`

2.29.1
`@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559
@SQ	SN:chr4	LN:190214555`

**Comment by 38** [comment]
Hi, could you please share the file to repo this?

**Comment by dinvlad** [comment]
We're experiencing exactly the same issue! In our case, it's
```
bedtools pairtobed -abam stdin -b hg19.bed < in.bam
```

**Comment by arq5x** [comment]
Hi @38,

The following will reproduce the problem:

    wget http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam
    samtools sort wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam -o wgEncodeUwRepliSeqBg02esG1bAlnRep1.sorted.bam

Note the sorted file with have the sorted indicator in the first line of the header with `samtools view -H wgEncodeUwRepliSeqBg02esG1bAlnRep1.sorted.bam | less`

Intersect that sorted file with a bed file, the header will lose the sorted indicator.

    cat test.bed
    chr1	10000000	20000000

    bedtools intersect -a wgEncodeUwRepliSeqBg02esG1bAlnRep1.sorted.bam -b test.bed > wgEncodeUwRepliSeqBg02esG1bAlnRep1.sorted.intersecting.bam

**Comment by 38** [comment]
Hi @arq5x , Just add a fix to this issue

**Comment by arq5x** [comment]
Thanks so much for catching this. Now fixed in master thanks to @38
