### ISSUE TITLE
genomecov coverage of the whole genome(s) 

### ISSUE THREAD

**Issue by iminkin** [arq5x/bedtools2#808]
Hi,

I am using bedtools v2.29.0-14-gea5e914. When I run the following command: 

`genomecov -max 1 -i blocks.gff -g genome.bed`

I notice the following. For each separate chromosome sum of the coverage values for 0 and for 1 is roughly 1. It makes sense since each position is either covered (0), or has some coverage bigger than 1. However, for the whole genome (in this case two genomes collapsed together actually), it gives the following values that do not sum up to 1:

genome  0       470364211       6335479704      0.0742429
genome  1       1570148197      6335479704      0.247834

Why is it the case? Files can be downloaded from https://drive.google.com/file/d/1opAyVA-fif-0BVRemqddFkJK1fM4vTRo/view?usp=sharing

**Comment by arq5x** [comment]
Thanks for reporting this. It appears to be a regression subsequent to version 2.27. I will look into it and provide a patch asap.

**Comment by arq5x** [comment]
There are 41351 distinct chromosomes in your genome.bed file.
    wc -l genome.bed
   41351 genome.bed

Yet there are 24787 distinct chromosomes in your blocks.gff file.

    cut -f 1 blocks.gff | sort | uniq > blockschroms.txt
    wc -l blockschroms.txt

The report is reflecting the fact that 41351 - 24787 chromosomes had zero coverage.
