### ISSUE TITLE
strange behavior with bedtools intersect 

### ISSUE THREAD

**Issue by vinay-swamy** [arq5x/bedtools2#809]
Hi I'm encountering some strange behavior with bedtools intersect
Input files 
a.bed
```
GL000008.2	118286	119434	Pituitary_00000002	999	*
GL000008.2	158006	158759	Pituitary_00000012	999	+
GL000009.2	78532	79175	Pituitary_00000033	999	*
GL000194.1	53551	115054	Pituitary_00000056	999	-
GL000194.1	53551	115054	Pituitary_00000051	999	- 
GL000194.1	53589	55865	Pituitary_00000055	999	- 
GL000194.1	53591	115063	Pituitary_00000058	999	-
GL000194.1	53593	115089	Pituitary_00000050	999	-
GL000194.1	53593	115089	Pituitary_00000047	999	-
GL000194.1	53606	74372	Pituitary_00000049	999	- 
```

b.bed
```
GL000194.1	48590	120018	ensembl	999	-
GL000194.1	48594	120055	ensembl	999	-
```

when I run 
`bedtools intersect -v -s  -a a.bed -b b.bed` , it should return 
```
GL000008.2	118286	119434	Pituitary_00000002	999	*
GL000008.2	158006	158759	Pituitary_00000012	999	+
GL000009.2	78532	79175	Pituitary_00000033	999	*
```
as the remaining features in a.bed are all contained in b.bed

I instead get 
```
GL000008.2	118286	119434	Pituitary_00000002	999	*
GL000008.2	158006	158759	Pituitary_00000012	999	+
GL000009.2	78532	79175	Pituitary_00000033	999	*
GL000194.1	53551	115054	Pituitary_00000056	999	-
GL000194.1	53551	115054	Pituitary_00000051	999	-
GL000194.1	53589	55865	Pituitary_00000055	999	-
GL000194.1	53591	115063	Pituitary_00000058	999	-
GL000194.1	53593	115089	Pituitary_00000050	999	-
GL000194.1	53593	115089	Pituitary_00000047	999	-
GL000194.1	53606	74372	Pituitary_00000049	999	-
```
similarly, when I run `bedtools intersect -s  -a a.bed -b b.bed`, it get nothing, when I should get all the entries on GL000194.1 in a.bed.

Am I doing something wrong? I'm using bedtools 2.29.2 on MacOS

**Comment by arq5x** [comment]
Changing the "*" strand in a.bed to "+" seems to fix the issue, but I need to look into why.

**Comment by arq5x** [comment]
I suspect some cryptic differences in whitespace after the strand column in your files or differences in the actual character used in your files.  Could you test for this and also attach your actual files so I can have a look.  I suspect this because I cannot reproduce this with my own test files designed to emulate this behavior.

**Comment by vinay-swamy** [comment]
There's no white space in the strand column, as best as I can tell. Here are the files 

[b.bed.zip](https://github.com/arq5x/bedtools2/files/4020222/b.bed.zip)
[a.bed.zip](https://github.com/arq5x/bedtools2/files/4020223/a.bed.zip)

**Comment by 38** [comment]
Just a quick look

> There's no white space in the strand column, as best as I can tell. Here are the files

Actually there's some lines with whitespace trailer. 

![image](https://user-images.githubusercontent.com/3023614/73680392-618f7480-4679-11ea-9965-01fba43f81b4.png)

Please note line 5,6 and 10 are the lines with whitespace.

**Comment by arq5x** [comment]
The issue is that bedtools did not recognize "*" as a valid strand character. It now does in master.  Also, you will need to clean up the extract whitespace, as those become different strand values for bedtools.
