### ISSUE TITLE
running annotate with -names on an empty bed causes huge output file

### ISSUE THREAD

**Issue by sebweyn** [arq5x/bedtools2#816]
As part of a pipeline we are running `annotate` on some automatically generated BED files. It turns out that providing an empty BED to `annotate` together with the `-names` parameter results in the writing of a multi-GB string to STDOUT after a substantial runtime. Expected output should be only the column names. Thanks!

```
# file contents
$ cat empty.bed
$ cat one_region.bed
chr1	10000	10001	region	0	+

# running with names parameter
$ time bedtools annotate -counts -s -i empty.bed -files one_region.bed -names region > empty.overlap

real	3m4.811s
user	2m53.310s
sys	0m6.834s
$ ls -l empty.overlap
-rw-r--r--  1 sebastien  staff  4294967304 Jan 22 14:07 empty.overlap

# running without names parameter
$ time bedtools annotate -counts -s -i empty.bed -files one_region.bed > empty.overlap

real	0m0.015s
user	0m0.003s
sys	0m0.006s
$ ls -l empty.overlap
-rw-r--r--  1 sebastien  staff  0 Jan 22 14:07 empty.overlap

```

**Comment by jmarshall** [comment]
For an empty file, annotate attempts to print out -1 tab characters — which ends up being 4GB of them. Oops :smile:

Fixed by PR #820.
