### ISSUE TITLE
Bedtools intersect raises warnings and works slowly

### ISSUE THREAD

**Issue by tprodanov** [arq5x/bedtools2#834]
Possible similar to #814:
When I try to use `bedtools intersect` for any bed files compressed with `bgzip`, it raises warnings
`[W::sam_read1] Parse error at line 1`.

Also, I don't think `bedtools` uses tabix index, because it takes 12 seconds to find regions from the first file that intersect a single basepair region from the second file.

I have the following versions of bedtools and samtools:
```
> bedtools --version
bedtools v2.27.1
> samtools --version
samtools 1.10
Using htslib 1.10.2
```

**Comment by arq5x** [comment]
Thanks for reporting, I think this has to do with recent integration of htslib. 

As for the Tabix index piece, no bedtools does not use tabix indices. If you are looking to do intersections on a handful of intervals, Tabix is a better choice. Things flip in favor of bedtools when intersecting ~10,000 intervals or more.

**Comment by tprodanov** [comment]
Okay, thank you!

**Comment by arq5x** [comment]
These warnings are no suppressed in the master branch on Github.
