### ISSUE TITLE
RNA getfasta reverse v 2.29.2

### ISSUE THREAD

**Issue by aspitaleri** [arq5x/bedtools2#836]
Hi
issue getfasta option in version 2.29.2:
file.bed:
chr1	0	10	candidate_1	55	-
chr1	0	10	candidate_2	161	+

File-RNA.fasta
>chr1 
uugaccgaug

~/bedtool2/bin/bedtools getfasta -fi ../FIle-RNA.fasta -bed file.bed -s -name

>candidate_1::chr1:0-10(-)
catcggtcaa
>candidate_2::chr1:0-10(+)
uugaccgaug

I was expecting 

>candidate_1::chr1:0-10(-)
ca**u**cgg**u**caa
>candidate_2::chr1:0-10(+)
uugaccgaug

**Comment by arq5x** [comment]
This appears to be a bug in the reverse complement code, which is easy to fix. More generally, there is a problem with RNA in that unless there is a U in the reference sequence, bedtools cannot _know_ the sequence is RNA without being explicitly told. This suggests the need for a `--rna` switch.

**Comment by arq5x** [comment]
Fixed in master with use of the new `-rna` option. Thanks for reporting this.

**Comment by aspitaleri** [comment]
Hi, tested the master right now and it worked for me. Thanks for your help.
