### ISSUE TITLE
intersectBed Received illegal bin number -1 from getBin call

### ISSUE THREAD

**Issue by asmariyaz23** [arq5x/bedtools2#838]
While trying to intersect 2 VCF files to find variants that reciprocal overlap 90%. I get the following error:

```
intersectBed -a trimmed.FAM1_MU006.nanovar.pass.vcf -b trimmed.FAM1_MU007.nanovar.pass.vcf -r -f 0.90

ERROR: Received illegal bin number -1 from getBin call.
Maximum values is: 2396745
This typically means that your coordinates are
negative or too large to represent in the data
structure bedtools uses to find intersections.ERROR: Unable to add record to tree.
```

Could you please guide me as to what might be causing the error? I had the same samples called by another caller and those I was able to intersect without an issue so I don't understand what maybe going wrong here?

**Comment by arq5x** [comment]
I suspect this error will disappear with version 2.29.2. Please reopen if not the case.

**Comment by asmariyaz23** [comment]
Hello, I was using 2.29.1 earlier and then I upgraded it to 2.29.2 but I get the same error. Could you kindly take a look if possible? 

[VCF1](https://drive.google.com/open?id=1hHnyRAM-hdctyu1amm5ZaJwIcpKvNShk)
[VCF2](https://drive.google.com/open?id=12l9mWD3VAb0Ez9Y_OOfHgnkVgjJWtDlP)
