### ISSUE TITLE
bedtools intersect fails when using process subtitution on zsh

### ISSUE THREAD

**Issue by tedil** [arq5x/bedtools2#841]
When calling `bedtools intersect -a a.bed -b <(cat b.tmp)`<sup>1</sup> bedtools exits with:
 ```Error: line number 1 of file /proc/self/fd/11 has 2 fields, but 5 were expected.```

However, when first writing the contents to a file, i.e. `cat b.tmp > b.bed`, and then using `bedtools intersect -a a.bed -b b.bed`, everything works fine.

Here are the smallest examples I could reproduce the behaviour with: [`a.bed`](https://gist.githubusercontent.com/tedil/ba9cc8f954ab88139645b43df14cc34b/raw/d5e1b83d43164d36957c100ccc09b8bd99c997bf/a.bed) and [`b.tmp`](https://gist.githubusercontent.com/tedil/6dca26330502256bfdd94776e19fadd4/raw/dd823a5ffcd7b7e0f7b41c19d8058c79b65b99fb/b.tmp).

This might be related to #643.
Version: bedtools v2.29.2

<sup>1</sup> _Note that `cat b.tmp` might be a more complex command invocation, this is just for illustrative purposes_

**Comment by arq5x** [comment]
I am unable to reproduce this. What version?

**Comment by tedil** [comment]
bedtools           bioconda/linux-64::bedtools-2.29.2-hc088bd4_0

**Comment by tedil** [comment]
Ah, turns out this is a problem with zsh vs bash.
It does work on zsh with the `=(...)` style substitution (which uses tempfiles) instead of the `<(...)` list style substitution (uses /dev/fd or FIFO)

**Comment by arq5x** [comment]
Thanks for detailing this issue, @jmarshall and sorry for just now coming back to it. My understanding was that the rewinding was being done with an internal buffer, but it sounds like that may not be the case. Bedtools does this to "guess" at the file format. Generally, it seems to work well, but it appears this is not working for ZSH process substitutions. Do I have that right?

**Comment by arq5x** [comment]
I wonder if there is a more general approach to handling FIFOs across shells. Will look into it.
