### ISSUE TITLE
bedtools merge read sequences from bam

### ISSUE THREAD

**Issue by JuliaMarkowski** [arq5x/bedtools2#844]
Hi! I want to merge overlapping reads in a bam file to get in silico long reads and was happy when I found bedtools merge. However, I only get the start and end position of the merged read, not an actually merged read sequence. I know one can have different operations on specific columns, but it seems to me that merging read sequences is not supported. Is there any way to do this with bedtools merge? Thanks!

**Comment by arq5x** [comment]
The `merge` tool cannot merge the raw sequences in the BAM file (.e.g, how would it resolve differences?). However, you can take the merged intervals and extract the sequence from the reference genome with the `getfasta` tool. Would this help?

**Comment by JuliaMarkowski** [comment]
Thanks @arq5x ! This is a nice idea, unfortunately, in my case this does not help, since those reads contain genomic variants. Therefore I can't rely on the reference sequence. The _in silico_ long reads would have helped me in a phasing problem. I will try to merge the reads with WhatsHap `--merge-reads`. Thanks again!
