### ISSUE TITLE
coverage error

### ISSUE THREAD

**Issue by Johnnywang92** [arq5x/bedtools2#858]
bedtools coverage error when I tried to get bam coverage informations.

The bam file size is 6.5G, aligned with bwa-mem2, sorted with samtools.

Using bedtools v2.26.0 in ubuntu 18.04:
`coverageBed -b sorted.bam -a unsorted.bed > coverageBed.txt`, need 137 GB MEM could cause memory leak(test in 128 GB and 512GB machine)

then I add  '-sorted' to the command, `coverageBed -sorted -b sorted.bam -a sorted.bed > coverageBed.txt`, got error message as below shows :

> ERROR: chromomsome sort ordering for file sorted.bam is inconsistent with other files. Record was:
> 10	60466	60616	E00528:379:HN2KVCCXY:4:2104:27925:41673/1	27	+

Same error shows in  bedtools v2.25.0,[ bedtools version 2.29.2](https://github.com/arq5x/bedtools2/releases/download/v2.29.2/bedtools.static.binary) in ubuntu 16.04

I also tried in ubuntu 14.04 with bedtools v2.17.0 in docker:
`coverageBed -abam sorted.bam -b unsorted.bed > coverageBed.txt` only 3 GB MEM is needed and worked slow but well.

How to fix this? Thanks for your time.

**Comment by arq5x** [comment]
If either of the two files is sorted differently by chromosome or either is not sorted lexicographically by chromosome, then you will get an error. If both are sorted identically and that sort order is not lexicographic, then you need to specify a `-genome` file that declares the expected order of chromosomes

**Comment by Johnnywang92** [comment]
> If either of the two files is sorted differently by chromosome or either is not sorted lexicographically by chromosome, then you will get an error. If both are sorted identically and that sort order is not lexicographic, then you need to specify a `-genome` file that declares the expected order of chromosomes

Thanks for your help, it worked.
