### ISSUE TITLE
createsequencedictionary error

### ISSUE THREAD

**Issue by elbakrifz** [arq5x/bedtools2#861]
hello everyone, I was running this CML : java -jar /Users/mac/Downloads/picard-2.jar CreateSequenceDictionary                                        R=/Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.fasta                                        O=/Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.dict
I get :  
INFO	2020-09-15 17:44:01	CreateSequenceDictionary	

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CreateSequenceDictionary -R /Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.fasta -O /Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.dict
**********

17:44:02.037 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/mac/Downloads/picard-2.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Tue Sep 15 17:44:02 WEST 2020] CreateSequenceDictionary OUTPUT=/Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.dict REFERENCE=/Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.fasta    TRUNCATE_NAMES_AT_WHITESPACE=true NUM_SEQUENCES=2147483647 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Sep 15 17:44:02 WEST 2020] Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.0
[Tue Sep 15 17:44:02 WEST 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0,02 minutes.
Runtime.totalMemory()=128974848
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" picard.PicardException: /Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.dict already exists.  Delete this file and try again, or specify a different output file.
	at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:220)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by arq5x** [comment]
This looks like a Picard problem, not bedtools.
