### ISSUE TITLE
How to map BEDPE based structural variation to human genes? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [arq5x/bedtools2#862]
Hi Aaron, 

Thanks for the great contribution to define BEDPE format for structural variation, however, is there any follow approach to mapping BEDPE-based structure variation to related human genes (BED or GTF)?  

Thanks. 

Shicheng

**Comment by arq5x** [comment]
The only such method is the `pairtobed` tool in bedtools. It will look for different combinations of overlaps between a BEDPE file and a BED or GTF file.
