### ISSUE TITLE
bedtools getfasta -split with single exon

### ISSUE THREAD

**Issue by amirkarger** [arq5x/bedtools2#865]
I just downloaded the latest bedtools. When I run `bedtools getfasta -split` with two exons, it works. When I run with one exon, it doesn't.

```
cat a.bed12
chr1    0       20      ENST00000466557.1       0       +       0       20      0       1       2       3

cat a.fa
>chr1
aaaaannnnnnnnnnttttt

./bedtools.static.binary getfasta -fi a.fa -bed a.bed12 -split
>chr1:0-20
aaaaannnnnnnnnnttttt
```

But:

```
cat a.bed12
chr1    0       20      ENST00000466557.1       0       +       0       20      0       2       2,3     3,17

./bedtools.static.binary getfasta -fi a.fa -bed a.bed12 -split
>chr1:0-20
aattt
```

Are you not allowed to run getfasta with single exons? What am I not seeing in this super-simple example?

**Comment by arq5x** [comment]
Thanks for reporting this - a long undetected bug. I will fix and send a patch in the morning

**Comment by amirkarger** [comment]
Thanks for the quick response. Good to know I'm not halluciniating.

**Comment by arq5x** [comment]
Now fixed in master

**Comment by amirkarger** [comment]
Works on a tiny file. Will check with a bigger file shortly. Thanks for the quick fix!

**Comment by amirkarger** [comment]
... and worked a big file with real proteins too. Thanks.
