### ISSUE TITLE
bedtools bamtofastq with empty bam file outputs one zero-length fastq sequence

### ISSUE THREAD

**Issue by tshtatland** [arq5x/bedtools2#866]
`bedtools bamtofastq` with empty bam file input is expected to write an empty fastq file. I got 1 sequence in the output with zero length. 

Some downstream tools (notably `kraken2`) can handle such fastq files and treat them literally as having 1 sequence, which results in mismatch in counting reads downstream.

To reproduce:
```
$ cat /dev/null | bedtools bamtofastq -i stdin -fq /dev/stdout -fq2 /dev/null
@/1

+

```
Or this:
```
samtools view /dev/null | bedtools bamtofastq -i stdin -fq /dev/stdout -fq2 /dev/null
[main_samview] fail to read the header from "/dev/null".
@/1

+

```
Note that this error message comes from `samtools view`: 
```
[main_samview] fail to read the header from "/dev/null".
```

I am using bedtools version v2.29.2 installed using conda on CentOS Linux release 7.4.1708.

**Comment by arq5x** [comment]
Thanks for reporting. Fixed in master.

**Comment by tshtatland** [comment]
@arq5x Thank you for fixing it so quickly. And huge thank you for developing and maintaining bedtools! It is a great package: fast, powerful, super useful for a variety of applications, has excellent documentation - love it!
