### ISSUE TITLE
bedtools binary missing intersectBed function

### ISSUE THREAD

**Issue by moldach** [arq5x/bedtools2#876]
I'm getting an error that the `intersectBed` function is missing from the latest binary?

```
$ cd ~/bin
$ wget https://github.com/arq5x/bedtools2/releases/download/v2.29.2/bedtools.static.binary
$ mv bedtools.static.binary bedtools
$ chmod +x bedtools

$ bedtools intersectBed
error: unrecognized command: intersectBed
```

**Comment by arq5x** [comment]
`intersectBed` is a shortcut for `bedtools intersect`

**Comment by moldach** [comment]
Well...that's confusing... guess I can change my code or compile to get the `intersectBed` binary then. Thanks.

**Comment by arq5x** [comment]
Here are more details. Either should work, but you are mixing invocation types.
https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html#usage-and-option-summary

**Comment by moldach** [comment]
Yeah updating tools on a new HPC from code someone had written in the past.
Just for _fun_ what's the reason for dual-invocation? (or it's historical purpose)

**Comment by arq5x** [comment]
it started out as multiple independent binaries. move to a single binary with subcommands for simplicity
