### ISSUE TITLE
getfasta returns incorrect sequence

### ISSUE THREAD

**Issue by sandrejev** [arq5x/bedtools2#877]
Bedtools getfasta sometimes (quite often really) misses last nucleotide from the requested range. Here is an example

wget http://hgdownload.cse.ucsc.edu/goldenpath/mm9/bigZips/mm9.fa.gz
gunzip mm9.fa.gz

samtools faidx mm9.fa "chr1:24113506-24113509" "chr17:57244924-57244927" "chr1:24113516-24113519" "chr17:57244934-57244937" -i --mark-strand sign
>chr1:24113506-24113509(-)
GGGA
>chr17:57244924-57244927(-)
GCGA
>chr1:24113516-24113519(-)
TGTT
>chr17:57244934-57244937(-)
GGTG

bedtools getfasta -fi mm9.fa.gz -bed tmp/primers_alignments_pos.bed -bedOut -s
chr1	24113505	24113509	Chr6_70Mb_plus_sgRNA_3321	0	-	GGGA
chr17	57244923	57244927	Chr4_51Mb_plus_sgRNA_313442	0	-	CGA
chr1	24113515	24113519	Chr6_70Mb_plus_sgRNA_3321	0	-	TGTT
chr17	57244933	57244937	Chr4_51Mb_plus_sgRNA_313442	0	-	GGTG

**Comment by arq5x** [comment]
I am not sure what is happening, but not only can I not reproduce the result of truncated sequences, but following your same commands, I get a very different sequence.

    wget http://hgdownload.cse.ucsc.edu/goldenpath/mm9/bigZips/mm9.fa.gz
    gunzip mm9.fa.gz
    samtools faidx mm9.fa "chr1:24113506-24113509" "chr17:57244924-57244927" "chr1:24113516-24113519" "chr17:57244934-57244937" -i --mark-strand sign
    >chr1:24113506-24113509(-)
    ctaa
    >chr17:57244924-57244927(-)
    TTCT
    >chr1:24113516-24113519(-)
    caag
    >chr17:57244934-57244937(-)
    AGAC

    # note I made test.bed following the intervals in your example output.
    cat test.bed
    chr1	24113505	24113509	Chr6_70Mb_plus_sgRNA_3321	0	-
    chr17	57244923	57244927	Chr4_51Mb_plus_sgRNA_313442	0 	-
    chr1	24113515	24113519	Chr6_70Mb_plus_sgRNA_3321	0 	-
    chr17	57244933	57244937	Chr4_51Mb_plus_sgRNA_313442	0 	-

    bedtools getfasta -fi mm9.fa -bed test.bed -bedOut -s
    chr1	24113505	24113509	Chr6_70Mb_plus_sgRNA_3321	0	-	ctaa
    chr17	57244923	57244927	Chr4_51Mb_plus_sgRNA_313442	0 	-	TTCT
    chr1	24113515	24113519	Chr6_70Mb_plus_sgRNA_3321	0 	-	caag
    chr17	57244933	57244937	Chr4_51Mb_plus_sgRNA_313442	0 	-	AGAC

**Comment by arq5x** [comment]
I suspect something is off with your files.
