### ISSUE TITLE
bedtools nuc throws a segmentation fault, when the reference genome is compressed using bgzip

### ISSUE THREAD

**Issue by dvav** [arq5x/bedtools2#879]
The following code throws a segmentation fault:
```
bedtools makewindows -g <path to genomes>/GRCh38.sizes -w 1000 > GRCh38.w1KB.bed                                                                                
bedtools nuc -fi <path to genomes>/GRCh38.fna.gz -bed GRCh38.w1KB.bed > GRCh38.w1KB.nuc.bed
```
The error persists when I try to process each chromosome separately. However, if I use the de-compressed genome GRCh38.fna, the above code works as expected. 

Any ideas?

PS: I use bedtools v2.29.2 on Linux

**Comment by mmendez12** [comment]
I am having this issue as well with bedtools v2.30 on Linux.

Any thoughts?

**Comment by arq5x** [comment]
All bedtools commands require an uncompressed FASTA.

**Comment by mmendez12** [comment]
Thanks
