### ISSUE TITLE
bedtools coverage should have a -sorted option

### ISSUE THREAD

**Issue by mdshw5** [arq5x/bedtools2#88]
This is a duplicate of the issue opened here: https://github.com/arq5x/bedtools/issues/77. I'm opening it on this repository because it seems like the other issues tracker should be abandoned. Note my commend [in the docs](https://github.com/arq5x/bedtools/issues/77) stating that `intersect` behaves differently than `coverage` for my purpose. Thanks!

**Comment by arq5x** [comment]
All done for 2.24.0.
