### ISSUE TITLE
bedtools sort -chrThenSizeA does not sort by chr position

### ISSUE THREAD

**Issue by mmokrejs** [arq5x/bedtools2#884]
Hi,
  I wonder why some entries get never sorted using. Note on the second row "should be" 2189552.

```
$ bedtools sort -chrThenSizeA -i broken.bed | head
chr1	2189550	2189551	32
chr1	2189551	2189552	35
chr1	2189578	2189579	44
chr1	2189579	2189580	43
chr1	2189597	2189598	41
chr1	2189598	2189599	40
chr1	2189599	2189600	41
chr1	2189600	2189601	39
chr1	2189601	2189602	40
chr1	2189602	2189603	41
$

$ grep -n 2189552 broken.bed
2:chr1	2189551	2189552	35
9251:chr1	2189552	2189554	36
$
```

This gets caught by 

```
$ ... | bedtools merge -i - -o median -c 4 -d 0
Error: Sorted input specified, but the file - has the following out of order record
chr1	2189552	2189554	36
$
```

In contrary, `sort-bed` 2.4.26 utility from http://bioinformatics.oxfordjournals.org/content/28/14/1919.abstract works.

I want to sort by chr name and then by chr position, nothing fancy. Seems `-chrThenSizeA` the closest option. I use 2.29.2 version. Thank you.

[test.bed.txt](https://github.com/arq5x/bedtools2/files/5724185/test.bed.txt)

**Comment by arq5x** [comment]
As the name of the option implies, this sorts by chrom, then intervals by their size, not start position.

By default, bedtools sort sorts by chrom, then start. That said, a faster option is UNIX sort: `sort -k1,1 -k2,2n in.bed > out.sorted.bed`

**Comment by mmokrejs** [comment]
Thanks. Please make it clear in the runtime help text. commonly, default settings are emphasized in some way. If the default "sort by chrom, then start" has no dedicated runtime option, make this clear in the help output elsewhere. Or ideally, just make an option for this (another reason is in the next sentence).

The `sort -k1,1 -k2,2n in.bed` will break place `chr10` before `chr2` so that is why I was hoping `bedtools` will do the natural sort for me. Bedtools also complain about

```
***** WARNING: File /dev/fd/63 has inconsistent naming convention for record:
HLA-A*01:01:01:01	0	3503	0
```

so I have to `grep`-away those lines. I guess the sorting would be wrong with the simple unix sort too. Similarly with unassigned chromosome loci, etc. Basically, you know what ordering have the hg19 and hg38 files which I want to achieve. ;-)

**Comment by arq5x** [comment]
will do.  Use UNIX version sort for natural sorting (`sort -V`).
