### ISSUE TITLE
BedTools gets grumpy with bgzipped BED files

### ISSUE THREAD

**Issue by dzerbino** [arq5x/bedtools2#888]
Hello Aaron et al,

Happy New Year, I hope you are all doing well.

Moving from v2.26.0 to .2.29.2 we started getting unexpected warnings when using bedtools on bgzipped BED files as opposed to gzipped BED files. These warnings are problematic because then pybedtools raises an error.

Intriguingly these warnings suggest bedtools thinks the bgzipped BED is a SAM file, however the end results appear to be correct:

```
> bedtools intersect -wa -a /path/to/bgzipped/files/DHS.bed.gz -b /path/to/bgzipped/files/Ensembl_TSSs.bed.gz > bzgipped.bed
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
> bedtools intersect -wa -a /path/to/gzipped/files/DHS.bed.gz -b /path/to/gzipped/files/Ensembl_TSSs.bed.gz > gzipped.bed
> diff -q bgzipped.bed gzipped.bed 
> bedtools --version
bedtools v2.29.2
```

I did a quick regression test with my previous installation (v.2.26.0) and the warnings did not show up then:
```
> bedtools.bak intersect -wa -a /path/to/bgzipped/files/DHS.bed.gz -b /path/to/bgzipped/files/Ensembl_TSSs.bed.gz > bgzipped.bed
> bedtools.bak intersect -wa -a /path/to/gzipped/files/DHS.bed.gz -b /path/to/gzipped/files/Ensembl_TSSs.bed.gz > gzipped.bed
> diff -q bgzipped.bed gzipped.bed 
> bedtools.bak --version
bedtools v2.26.0
```

Thank you for your help and your software,

Daniel

**Comment by jmarshall** [comment]
These warnings were also observed in #814, which noted that they're a since-fixed HTSlib problem so the best way to fix them would be to update bedtools's embedded HTSlib. It's bad news (and probably motivating :smile:) that they lead to errors from pybedtools!

**Comment by arq5x** [comment]
Thanks for reporting this, @dzerbino - @38 could you have a look at updating the internal htslib?

**Comment by dzerbino** [comment]
Thanks all!

**Comment by arq5x** [comment]
@38 feels that this is fixed in master. I am going to test this weekend. Time for a new release.

**Comment by arq5x** [comment]
Yep, it is fixed in master. Will put out a new release with some recent speed improvements from @38 by the end of the day Monday.

**Comment by dzerbino** [comment]
Thanks @38 and @arq5x !
