### ISSUE TITLE
request: bedtools intersect argument to suppress warning of inconsistent naming convention

### ISSUE THREAD

**Issue by dgordon562** [arq5x/bedtools2#892]
Hi, Aaron,

Thanks for bedtools!   We use it like breathing!

All of our genomes will give this warning because all of them contain both chromosomes and unplaced contigs.  The unplaced contigs come from various programs that have their own naming conventions and it is useful to use to not rename them.  So all of our genomes give the warning:
***** WARNING: File ... has inconsistent naming convention for record:

Scripts give so many of these that it is hard to see the output.  I could redirect stderr but I would want to be able to see any other warnings.  So it would be great if you could just add a flag to suppress this particular warning.

Thanks!
David Gordon
Eichler Lab

**Comment by arq5x** [comment]
Hi David,

Nice to hear from you and thanks for using bedtools. Have you tried the `-nonamecheck` option to suppress the warnings?

**Comment by dgordon562** [comment]
great!  thanks, Aaron!
