### ISSUE TITLE
bedtools unionbedg wrong output

### ISSUE THREAD

**Issue by mcjmigdal** [arq5x/bedtools2#893]
Hi,

I would like to report an issue I've found while working with bedtools unionbedg. 
I am using: 
```
> bedtools --version
bedtools v2.29.2
```

As I found out "united" scores deviates from expected values. Here is an example of one position from a bdg files I am working on. However, there are more rows showing similar deviations.

```
> bedtools unionbedg -i in* > test.bdg
> grep -e "1\s59577904" in* test.bdg 
in1.txt:1       59577904        59577909        8.60278
in2.txt:1       59577904        59577909        2.65470
in3.txt:1       59577904        59577909        8.35058
in4.txt:1       59577904        59577909        6.86913
in5.txt:1       59577904        59577909        3.48244
test.bdg:1      59577904        59577909        0       0       8.35058 6.86913 3.48244
```

As you can see the values from `in1.bdg` and `in2.bdg` are getting zeroed in the output file. This happens quite a lot and I found it input length dependent with zeroed values being more frequent towards end of the output.

You can find the input files I've used below. All of them have the same range values and differs only by the score column.

[in3.txt](https://github.com/arq5x/bedtools2/files/5852308/in3.txt)
[in4.txt](https://github.com/arq5x/bedtools2/files/5852309/in4.txt)
[in5.txt](https://github.com/arq5x/bedtools2/files/5852311/in5.txt)
[in2.txt](https://github.com/arq5x/bedtools2/files/5852313/in2.txt)
[in1.txt](https://github.com/arq5x/bedtools2/files/5852314/in1.txt)

**Comment by arq5x** [comment]
This is odd indeed. I will try to dig into this and get back to you.

**Comment by arq5x** [comment]
Looks like things start to go awry at coordinate "59571188", where right afterwards, there are three duplicate entries for `1	59571207	59571247`. The code should ideally detect such duplicates, as they violate the BEDG spec, but in the meantime, could you modify your pipeline to prevent duplicates?

**Comment by arq5x** [comment]
grep -C 8 59571188 ~/Desktop/in1.*
1	59571082	59571084	2.80316
1	59571084	59571089	9.33386
1	59571089	59571126	5.62244
1	59571126	59571136	5.02187
1	59571136	59571141	8.96362
1	59571141	59571144	5.98018
1	59571144	59571151	0.83299
1	59571151	59571163	8.45662
1	59571163	59571188	9.48174
1	59571188	59571207	3.77147
1	59571207	59571247	8.43195
1	59571207	59571247	0.64165
1	59571207	59571247	2.45834
1	59571247	59571260	7.24445
1	59571260	59571262	0.23635
1	59571262	59571274	6.30322
1	59571274	59571286	3.54003
1	59571286	59571301	5.14273

**Comment by arq5x** [comment]
`1	59571207	59571247` is another set of duplicates.

**Comment by mcjmigdal** [comment]
Huh, good catch! I will de-duplicate those inputs and see if the problem is gone.

**Comment by arq5x** [comment]
Also make sure all files are sorted by start prior to running the tool. `sort -k1,1 -k2,2n in >in.sorted`

**Comment by mcjmigdal** [comment]
Removing the duplicates does the trick.

```
for input in in*.txt; do 
awk '
BEGIN { prev_start=0; prev_end=0 } 
{ if($2 != prev_start && $3 != prev_end){ print $0 }; prev_start=$2; prev_end=$3 }' < ${input} > ${input%.txt}_dedup.txt
done
```

Thanks for help, I haven't catch this duplication happening! I'll try to track down my pipeline to see where those come from.

I guess we can close this issue.

**Comment by mcjmigdal** [comment]
Got it, my bad... Thank you again and sorry for taking your time!

**Comment by arq5x** [comment]
No problem at all.
