### ISSUE TITLE
pre-compiled binary for 2.30.0?

### ISSUE THREAD

**Issue by kapsakcj** [arq5x/bedtools2#897]
Hi Aaron and the bedtools team, 

I was wondering if you all plan on releasing a static, pre-compiled binary for the v2.30.0 release? There was one available for the last release, but there is no binary under 'Assets': https://github.com/arq5x/bedtools2/releases/tag/v2.30.0

Having a static binary available makes it a breeze to put bedtools inside a docker image, so I really appreciate your efforts for creating them.

Best,
Curtis

**Comment by arq5x** [comment]
Good catch, will do!

**Comment by arq5x** [comment]
Thanks for the reminder. I added this to the release.

**Comment by kapsakcj** [comment]
Thank you! It runs as expected!
