### ISSUE TITLE
bedtools genomecov -5 or -3 position option 

### ISSUE THREAD

**Issue by camelest** [arq5x/bedtools2#905]
Hi, thank you for the continuous effort to maintain this fantastic tool.

I'm using bedtools v2.29.2 on Ubuntu 18.04. My question is about the behavior of -5 (or -3) option.
After mapping by STAR of single-ended RNA-seq data, I'm trying to extract the counts of 5' (or 3') position of all aligned reads by the code below in a strand specific way.

`samtools view -u -q 20 Aligned.sortedByCoord.out.bam | genomeCoverageBed -ibam /dev/stdin -bg -5 -strand + | sort -k1,1 -k2,2n > 5position.rev.bedGraph`

By reading the manual, my understanding is that this would give us a bedGraph file, which contains positions of a length of 1 bp in every row and the counts for that position. Something like this.

`chr1   10000 10001  2`
`chr1   10003  10004 3`

However, when I actually ran the code, I got small portion of positions with 2 base-length or sometimes even 3 base-length or more. Something like this.

`chr 1  10000 10002 2`
`chr 1  10003 10006 3`

I looked back into the bam file but couldn't figure out what happened. Is this related to "softclipped" base  or is my understand wrong?

Thank you for your help. Since I'm quite new to this area, I apologize for any unclearness.

**Comment by arq5x** [comment]
BEDGRAPH format reports intervals where all positions in the interval have the same depth.

**Comment by camelest** [comment]
Thank you for your reply. To clarify, when "-5" option combined with "-bg" option, does the result of
`chr1 10000 10002 2`,
mean that I have 2 reads with 5'-end at 10000 and 2 reads with 5'-end at 10001?

**Comment by arq5x** [comment]
Yes.

**Comment by camelest** [comment]
Thank you for the rapid reply. Just to add one more thing, is there any difference between results of 
`chr1 10000 10001 1`
`chr1 10001 10002 1`
and
`chr1 10000 10002 1`? How does bedtools decide which result to be presented?

I really appreciate your kind reply.

**Comment by arq5x** [comment]
They are two versions of reporting the same thing but only the former is valid BEDGRAPH format.

**Comment by camelest** [comment]
Thank you for your input. This was really helpful.
