### ISSUE TITLE
Bug in the outputting format of bedtools intersect for certain file only

### ISSUE THREAD

**Issue by priyatamapandey** [arq5x/bedtools2#914]
Hi,
I am using bedtools intersect command for annotating my bed file. I have 2 files one is gene annotation file and other is bed file with the coordinate which need to be annotate.  I am using the bellow command
```
bedtools intersect \
-a /annotationFiles/annotation.bed \
-b /sample/bedfile.bed \
-wo > gene_overlap.txt
```

I am attaching the screenshot of all the three files here. My input files are tab delimited but there are 2 column in the final output file which got merged. It was expected to be the tab delimitation among the columns. Command is working fine for most of the file but not working well for few files as well. I am not able to find the error in the formatting of my input file. The last screenshot of the file shows the 2 column with values  1 and 1 mostly got merge and become 11 in that column. 

bedfile.bed
<img width="812" alt="Screen Shot 2021-05-12 at 4 21 15 PM" src="https://user-images.githubusercontent.com/17990280/118056882-99d33780-b33f-11eb-96d8-62906a1d0013.png">
annotation.bed
<img width="1162" alt="Screen Shot 2021-05-12 at 4 22 11 PM" src="https://user-images.githubusercontent.com/17990280/118056890-9cce2800-b33f-11eb-8c0c-0bf54bd17c0b.png">
gene_overlap.txt
<img width="1144" alt="Screen Shot 2021-05-12 at 4 24 25 PM" src="https://user-images.githubusercontent.com/17990280/118056891-9dff5500-b33f-11eb-8308-391b063b060d.png">

Any help would be appreciated.
Please let me know, I can send the file if needed.

Thank you,
Priya

**Comment by arq5x** [comment]
Can you let us know what version of bedtools you are using and share input files (ideally as concise as possible) that reproduce the problem?

**Comment by priyatamapandey** [comment]
Hi,
Thank you for your reply. I am using version bedtools2/2.27.1. 
Attached please find the two files.
[Archive.zip](https://github.com/arq5x/bedtools2/files/6496542/Archive.zip)

Please let me know if anything else needed.
Thank you,
priya

**Comment by arq5x** [comment]
I am fairly confident this is a bug that does not exist in the current version (2.30). Could you try with the latest version?

**Comment by priyatamapandey** [comment]
Hi, I am updated with the latest version but still come-up with the same error. Again FYI, It is working fine with the bunch of bed files only giving the error for couple of bed files and it worked fine with the earlier file which I attached in my earlier comment but gave me same error for couple of other bed files. I have checked these bed files are tab separated. 
Please let me if you need any of the file to cross check it.
Thank you for your help
Priya

**Comment by arq5x** [comment]
Your file "rs2241604_chr5\:1057112_qtls_hugin.bed" has a mix of tabs and spaces that I messing up the output.  You can remove the spaces with the following.

    sed -e 's/ //g' rs2241604_chr5\:1057112_qtls_hugin.bed > rs2241604_chr5\:1057112_qtls_hugin.fixed.bed

```
bedtools intersect -a rs2241604_chr5\:1057112_qtls_hugin.fixed.bed -b hg19_gene.bed -wo | head
chr5	40000	80000	1040000	1080000	1	0	1	1	1	chr5	58312	59030	ENSG00000250020.1	+	  "RP11-811I15.1"	718
chr5	80000	120000	1040000	1080000	1	0	1	1	1	chr5	92265	139978	ENSG00000249430.1	+	  "CTD-2231H16.1"	27735
chr5	120000	160000	1040000	1080000	2	0	1	1	1	chr5	144201	144312	ENSG00000199540.1	-	  "Y_RNA"	111
chr5	120000	160000	1040000	1080000	2	0	1	1	1	chr5	140372	190085	ENSG00000153404.9	+	  "PLEKHG4B"	19628
chr5	120000	160000	1040000	1080000	2	0	1	1	1	chr5	92265	139978	ENSG00000249430.1	+	  "CTD-2231H16.1"	19978
chr5	160000	200000	1040000	1080000	1	0	1	1	1	chr5	191625	195468	ENSG00000185028.3	+	  "LRRC14B"	3843
chr5	160000	200000	1040000	1080000	1	0	1	1	1	chr5	195892	196456	ENSG00000261434.1	+	  "CTD-2083E4.7"	564
chr5	160000	200000	1040000	1080000	1	0	1	1	1	chr5	140372	190085	ENSG00000153404.9	+	  "PLEKHG4B"	30085
chr5	160000	200000	1040000	1080000	1	0	1	1	1	chr5	196985	218330	ENSG00000164366.3	-	  "CCDC127"	3015
chr5	240000	280000	1040000	1080000	4	0	1	1	1	chr5	269972	271631	ENSG00000248925.1	-	  "CTD-2083E4.6"	1659
```

**Comment by priyatamapandey** [comment]
Thank you, I am running these in a pipeline which is creating these bed files using R script and at the next step annotationing these using bedtools.  I thought tab separation would take care of this but  got it now that I need to remove whitespace if It generates in the files. Thank you for finding the cause of error. 

Best,
Priya
