### ISSUE TITLE
intersect returns 'std::length_error'

### ISSUE THREAD

**Issue by elcortegano** [arq5x/bedtools2#916]
`bedtools intersect` is returning the following error:

    terminate called after throwing an instance of 'std::length_error'
      what():  basic_string::_M_replace
    Aborted (core dumped)

I am extremely confused about it, since the mainVCF file used has a standard format (is generated by `bcftools`) and the BED file as second input was obtained via `bedtools`. Below are the commands used:

    bcftools concat *gz > file.vcf
    bcftools sort tmp.vcf > file.sort.vcf
    bedtools merge -header -i file.sort.vcf > file.sort.merged.bed
    bedtools intersect -header -a file.sort.vcf -b file.sort.merged.bed  > file.sort.merged.vcf

Version of bedtools is 2.30.0

**Comment by arq5x** [comment]
Could you share the the first 10 data lines of the VCF and the BED file?

**Comment by elcortegano** [comment]
Hi @arq5x , thank you for the reply. This made me realize that the error comes from `file.sort.merged.bed`. When merging the VCF file, the merged file has a BED format (with only three columns), and not a VCF format. Since the `-header` option is used, it cointains however all the VCF metadata on the top of the file. As consequence, the format is not recognizable.

If `bedtools merge` is run without `-header` above, `bedtools intersect` runs with no error.
