### ISSUE TITLE
bamtofastq documentation uses outdated samtools invocation

### ISSUE THREAD

**Issue by rmzelle** [arq5x/bedtools2#920]
https://bedtools.readthedocs.io/en/latest/content/tools/bamtofastq.html (https://github.com/arq5x/bedtools2/blob/master/docs/content/tools/bamtofastq.rst) currently says:

> One can sort the BAM file by query name with `samtools sort -n aln.bam aln.qsort`.

and

> `  $ samtools sort -n aln.bam aln.qsort`

I believe that this is a legacy incantation that is no longer supported in samtools (it fails for me in samtools 1.9). For documentation on this change, see:

http://www.htslib.org/doc/samtools-sort.html:

>  Note
> 
> Historically samtools sort also accepted a less flexible way of specifying the final and temporary output filenames:
> 
> samtools sort [-f] [-o] in.bam out.prefix
> 
> This has now been removed. The previous out.prefix argument (and -f option, if any) should be changed to an appropriate combination of -T PREFIX and -o FILE. The previous -o option should be removed, as output defaults to standard output.

It looks like the change was made in 2015 with samtools 1.3. See https://github.com/samtools/samtools/commit/f78373cbda8f6a2406a345fbbb02f6d374a9984e and https://github.com/samtools/samtools/releases/tag/1.3 ("The obsolete samtools sort in.bam out.prefix usage has been removed. If you are still using ‑f, ‑o, or out.prefix, convert to use -T PREFIX and/or -o FILE instead.").

**Comment by rmzelle** [comment]
I think `samtools sort -n aln.bam > aln.qsort.bam` would correct the documentation here.

**Comment by jmarshall** [comment]
You're quite right about this style of incantation having been long since removed.

I'd recommend

```
samtools sort -n -o aln.qsort.bam aln.bam
```

Or if bamtofastq can read from standard input, this could demonstrate piping samtools sort into bedtools bamtofastq.

**Comment by arq5x** [comment]
Thanks for bringing this up and providing an update, @jmarshall. Docs are updated and pushed to master.

**Comment by rmzelle** [comment]
@arq5x, there seems to be two more instances that haven't been updated yet:

https://github.com/arq5x/bedtools2/blame/49caf321ab29b2905bd84993e032cb7198491662/docs/content/tools/bamtofastq.rst#L81
and
https://github.com/arq5x/bedtools2/blame/49caf321ab29b2905bd84993e032cb7198491662/docs/content/tools/bamtofastq.rst#L86

**Comment by arq5x** [comment]
Thanks so much for catching my laziness!  Fixed.
