### ISSUE TITLE
Tabs deleted in bedtools closest output

### ISSUE THREAD

**Issue by umasstr** [arq5x/bedtools2#922]
Bedtools closest runs the below command to completion without error. BEDs are sorted (-k1,1 -k2,2n). Oddly, the output eliminates several field separators at random. Output looks normal if I eliminate the score column (5) from -a. I guess can bedtools not handle non-integer scores?
bedtools v2.26.0

`$ bedtools closest -a sig_pELS.sort.bed -b ../../genomes/TSS/hg38_tss.near.sort.bed`

> chr1    chr196351659079206589669165907921H38E139UCK2    0.0133289569769029
> chr1    chr139082017398340173942201739835H38E141NAV1    0.0431276787399517
> chr1    chr125182261480022612553226148003H38E142ACBD3   0.0439807989814505

`$ head sig_pELS.sort.bed`

> chr1    165896351       165896694       EH38E1393927    0.0133289569769029
> chr1    201739082       201739420       EH38E1412039    0.0431276787399517

`head ../../genomes/TSS/hg38_tss.near.sort.bed`

> chr1    11873   11874   DDX11L1
> chr1    17436   17437   WASH7P
> chr1    29370   29371   WASH7P

**Comment by arq5x** [comment]
Please test with the current version and reopen if the problem persists.
