### ISSUE TITLE
Character limit on NAME field in BED files?

### ISSUE THREAD

**Issue by jfass** [arq5x/bedtools2#925]
I'm intersecting 4-column BED files, with the 4th column being the NAME field, but the name fields have a bunch of annotation data stuffed in them, delimited by "|" characters. (It's an ugly solution, I know). But it looks like those fields get truncated after 999 characters in the results of an 'intersect' command.

Is there any way to get around this?

**Comment by arq5x** [comment]
@38 can you please have a look at this?

**Comment by arq5x** [comment]
Just to confirm, are you using version 2.30?

**Comment by jfass** [comment]
Yes, on MacOS!

**Comment by arq5x** [comment]
Could you share a few lines of your file to reproduce the problem?
