### ISSUE TITLE
Erroneous intersection between VCF and BED

### ISSUE THREAD

**Issue by bangbangphil** [arq5x/bedtools2#926]
While intersecting VCF files with BED coordinates, I came up with a retained variant from an intersection that was not in any interval from the BED file given. Here is a short example with a single variant VCF and a single interval BED that is not containing the variant; using bedtools v2.30.0-13-gedcc3ebb

input files:

a.vcf:
```
##fileformat=VCFv4.2
4	3477869	.	CGCCCCGCCTGACCGTGATGCCCTCTCGCCCCGCCCACCCTCGATGCCCTCTCACCTCACCCGCCCATGATGCCCTCTCGCCCCGCCTGCCCGTGATGCCCTCTCACCCCACCCGCCCGTGATGCCCTCTCACCCCACCCGCCCGTGATGTCCTCTCACCCTGCCCGCCCGTGATGCCCTCTT	C	372.60	PASS	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.469;DP=248;ExcessHet=3.0103;FS=16.785;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=1.50;ReadPosRankSum=-1.492;SOR=0.190	GT:AD:DP:GQ:PL	0/1:192,56:248:99:380,0,7131
```

b.bed:
```
chr4	3478018	3478319	DOK7	0	+
```

Results of command `bedtools intersect -a a.vcf -b b.bed -wb`
```
chr4	3477869	.	CGCCCCGCCTGACCGTGATGCCCTCTCGCCCCGCCCACCCTCGATGCCCTCTCACCTCACCCGCCCATGATGCCCTCTCGCCCCGCCTGCCCGTGATGCCCTCTCACCCCACCCGCCCGTGATGCCCTCTCACCCCACCCGCCCGTGATGTCCTCTCACCCTGCCCGCCCGTGATGCCCTCTT	C	372.60	PASS	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.469;DP=248;ExcessHet=3.0103;FS=16.785;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=1.50;ReadPosRankSum=-1.492;SOR=0.190	GT:AD:DP:GQ:PL	0/1:192,56:248:99:380,0,7131	4	3478018	3478319	DOK7	0	+
```

Note that the expected result was an empty output, as the variant at chr4:3477869 is not in range chr4:3478018-3478319

However, if I modify the variant in VCF file to be a simple SNV instead of a long deletion (see file content below), at the same position. I have the expected empty result from intersection with BED file.
```
##fileformat=VCFv4.2
chr4	3477869	.	G	C	372.60	PASS	AC=1;AF=0.500;AN=2;BaseQRankSum=-0.469;DP=248;ExcessHet=3.0103;FS=16.785;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.000;QD=1.50;ReadPosRankSum=-1.492;SOR=0.190	GT:AD:DP:GQ:PL	0/1:192,56:248:99:380,0,7131
```

Is there some side-effect bug of having a long deletion in input VCF?

**Comment by bangbangphil** [comment]
Oh, wait a minute, are you expanding the position coordinate form the input VCF to match the range of deletion? That would make sense as its about 183nt making it go into the BED interval ... is that it?

**Comment by arq5x** [comment]
Yes, that is correct. The deleted interval starts at 3477869 but ends at 3477869+(length of deleted seq), thus intersection.
