### ISSUE TITLE
[Feature request] Allow Minimum overlap, bedtools intersect -f to be negative?

### ISSUE THREAD

**Issue by YichaoOU** [arq5x/bedtools2#931]
Hello,

Can we specify a negative value for `-f` in `bedtools intersect`? That will mean a gap between A and B. 

Could be a stupid suggestion.

Thanks,
Yichao

**Comment by arq5x** [comment]
Not a stupid question at all. Use the `closest` tool. It will find the closest overlapping (if they exist) and non-overlapping interals.

**Comment by arq5x** [comment]
You can also use `window` to find overlapping intervals within N bp.
