### ISSUE TITLE
NotImplementedError:

### ISSUE THREAD

**Issue by starboyvarun** [arq5x/bedtools2#943]
![1](https://user-images.githubusercontent.com/26819449/131072525-7e6ef801-6dd1-49bb-b02e-a83e08b9c75c.JPG)
![2](https://user-images.githubusercontent.com/26819449/131072530-f192b380-c157-44c8-af8b-561d2ec0d6cf.JPG)

I have installed bedtools still getting an error shown in the figure.
please can you tell me how should I install bedtools properly in google collab?

**Comment by jmarshall** [comment]
(Also spuriously reported as samtools/samtools#1488 where the OP's issue appears to have been resolved.)

**Comment by arq5x** [comment]
Thanks for clarifying and closing.
