### ISSUE TITLE
NotImplementedError: 

### ISSUE THREAD

**Issue by starboyvarun** [arq5x/bedtools2#944]
![3](https://user-images.githubusercontent.com/26819449/131239526-020d3c6d-432b-46bc-ae05-2475314d2911.JPG)

![2](https://user-images.githubusercontent.com/26819449/131239457-69badde4-638e-4990-865a-30d99825b502.JPG)

![1](https://user-images.githubusercontent.com/26819449/131239462-0b8606fa-1128-42a6-8d5d-90e9b99987cd.JPG)

I keep getting this error even after installing bedtools can you tell me how to solve it.
I am running my code on google collab.
Thank you.

@arq5x

**Comment by starboyvarun** [comment]
If anyone gets this error do comment.  I have solved this error. Do tag me.
Thanks!

**Comment by arq5x** [comment]
pybedtools requires that bedtools is installed and in your PATH. Have you installed bedtools as well?  Any other ideas, @daler ?

**Comment by daler** [comment]
Yep, that's by far the most common issue. Bedtools is not installed with pip, you need to install it separately. Alternatively if you install pybedtools with [bioconda](https://bioconda.github.io) then bedtools does come with it.

**Comment by starboyvarun** [comment]
@arq5x @daler  actually I was using Google-colab, 
1. I tried installing with pip.
2. I also tried :
![10](https://user-images.githubusercontent.com/26819449/133547316-f6fbdd5c-50b5-41a4-99a3-977e520e80af.JPG)
3. I even install pybedtools with bioconda.Still got the error.
4. Then finally I did ```apt-get install bedtools```   sys.path.append is not going to work, because bedtools is not a python program. sys.path.append modifies the PYTHONPATH environment variable.
Thanks!

**Comment by starboyvarun** [comment]
@arq5x @daler  feel free to ask if you have any more questions.
Thanks.

**Comment by daler** [comment]
I'm not familiar with colab, there may be specific ways to install using that.

Staying within Python, maybe try something like this before importing pybedtools:

```python
import os
os.environ["PATH"] = os.environ['PATH'] + ":" + "/content/janggu/bedtools2/bin"
```

You can also try 

```python
import pybedtools
pybedtools.set_bedtools_path("/content/janggu/bedtools2/bin")
```

**Comment by starboyvarun** [comment]
@daler 
I did something similar in point 2, but not from os I did it from sys.
And I also wrote in point 4. that it worked for me fine. If you try implementing it using colab just try using apt-get.
It works.
Thanks.

**Comment by daler** [comment]
Ah, that was not clear. Glad it works though.

**Comment by starboyvarun** [comment]
@daler  thanks. It took me 1 week though.

**Comment by starboyvarun** [comment]
Google colab is not very friendly for Bioinformatics, even tensor-flow older versions don't get installed in colab.

**Comment by starboyvarun** [comment]
I think I should close this issue now. As the issue has already been resolved and I have solved the particular issue using point 4, from my previous comment.
Thank You.
