### ISSUE TITLE
whether bedtools can select a certain number of cells from the BED file

### ISSUE THREAD

**Issue by qimiaonnegliguo** [arq5x/bedtools2#946]
Hello! I am a beginner in bioinformatics. I want to know whether bedtools can select a certain number of cells from the BED file. For example, I now have a BED file containing ATAC information for 1000 cells. I just want to choose 500 of them. I want to know whether this work can be performed by bedtools. I am very grateful for your help.

**Comment by arq5x** [comment]
I need more information. Can you provide an example of what you have and what you want to achieve?

**Comment by qimiaonnegliguo** [comment]
The following is  the head of the BED file for more than 1500 cells:
chr1    10009   10149   ST-E00317:1025:HFGLJCCX2:1:1118:19218:47861/2   40      +
chr1    10009   10105   ST-E00317:1025:HFGLJCCX2:1:1123:30340:8025/2    31      +
chr1    10009   10150   ST-E00317:1025:HFGLJCCX2:1:1124:20121:65634/2   32      +
chr1    10011   10137   ST-E00317:1025:HFGLJCCX2:1:1207:3843:48230/2    60      -
chr1    10015   10167   ST-E00317:1025:HFGLJCCX2:1:2203:9546:40917/2    42      -
chr1    10021   10167   ST-E00317:1025:HFGLJCCX2:1:1110:5538:40091/2    51      -
chr1    10051   10124   ST-E00317:1025:HFGLJCCX2:1:1207:3843:48230/1    40      +
chr1    10057   10133   ST-E00317:1025:HFGLJCCX2:1:1110:5538:40091/1    40      +
chr1    10057   10133   ST-E00317:1025:HFGLJCCX2:1:2203:9546:40917/1    40      +
chr1    10067   10142   ST-E00317:1025:HFGLJCCX2:1:1123:30340:8025/1    31      -
chr1    10069   10141   ST-E00317:1025:HFGLJCCX2:1:2121:11982:62189/1   53      +
chr1    10069   10209   ST-E00317:1025:HFGLJCCX2:1:2121:11982:62189/2   52      -
chr1    10084   10156   ST-E00317:1025:HFGLJCCX2:1:1118:19218:47861/1   40      -
chr1    10089   10162   ST-E00317:1025:HFGLJCCX2:1:1124:20121:65634/1   32      -
chr1    10109   10179   ST-E00317:1025:HFGLJCCX2:1:2210:32491:27785/1   40      +
chr1    10159   10215   ST-E00317:1025:HFGLJCCX2:1:1107:8927:14775/2    60      +
chr1    10159   10215   ST-E00317:1025:HFGLJCCX2:1:1107:8927:14775/1    58      -
chr1    10177   10284   ST-E00317:1025:HFGLJCCX2:1:2210:32491:27785/2   40      -
chr1    10323   10449   ST-E00317:1025:HFGLJCCX2:1:1117:10470:19698/2   40      +
chr1    10323   10455   ST-E00317:1025:HFGLJCCX2:1:2120:18923:59903/2   43      +
chr1    10323   10455   ST-E00317:1025:HFGLJCCX2:1:2216:24931:21614/2   36      +
chr1    10330   10455   ST-E00317:1025:HFGLJCCX2:1:2108:6076:19821/2    50      +
chr1    10342   10416   ST-E00317:1025:HFGLJCCX2:1:1214:24972:38737/1   41      +
chr1    10342   10442   ST-E00317:1025:HFGLJCCX2:1:1214:24972:38737/2   60      -
chr1    10359   10442   ST-E00317:1025:HFGLJCCX2:1:2217:11150:1854/2    51      +
chr1    10367   10442   ST-E00317:1025:HFGLJCCX2:1:2217:11150:1854/1    52      -
chr1    10370   10441   ST-E00317:1025:HFGLJCCX2:1:1124:10247:16604/1   40      +
chr1    10370   10467   ST-E00317:1025:HFGLJCCX2:1:1124:10247:16604/2   40      -
chr1    10372   10449   ST-E00317:1025:HFGLJCCX2:1:1117:10470:19698/1   46      -
chr1    10378   10454   ST-E00317:1025:HFGLJCCX2:1:2216:24931:21614/1   36      -
chr1    10381   10455   ST-E00317:1025:HFGLJCCX2:1:2120:18923:59903/1   40      -
chr1    10390   10436   ST-E00317:1025:HFGLJCCX2:1:2108:6076:19821/1    40      -
chr1    10432   10506   ST-E00317:1025:HFGLJCCX2:1:1218:11231:45910/1   57      +
chr1    10432   10563   ST-E00317:1025:HFGLJCCX2:1:1218:11231:45910/2   53      -
chr1    13293   13347   ST-E00317:1025:HFGLJCCX2:1:1120:3884:25587/1    54      +
chr1    13293   13347   ST-E00317:1025:HFGLJCCX2:1:1120:3884:25587/2    54      -
chr1    15912   15984   ST-E00317:1025:HFGLJCCX2:1:1106:19684:58655/1   47      +
chr1    15912   15996   ST-E00317:1025:HFGLJCCX2:1:1106:19684:58655/2   46      -
chr1    16217   16277   ST-E00317:1025:HFGLJCCX2:1:1121:25367:65124/2   47      +
chr1    16217   16277   ST-E00317:1025:HFGLJCCX2:1:1121:25367:65124/1   47      -


I just want to get a subset of this file, maybe peaks for 500 cells because the number of the peaks are too large. Could you please tell whether bedtools could offer help? I'm very grateful for your help.

**Comment by arq5x** [comment]
Sorry, I don't think what you want is possible with these data. This looks like the result of converting BAM to BED format. Unfortunately, I do not think the read IDs (column 4) tell you anything about the cell of origin. I would talk to someone in your group about the origin of the data and what may be possible.
