### ISSUE TITLE
bedtools groupby giving indentical lines

### ISSUE THREAD

**Issue by baigal628** [arq5x/bedtools2#948]
Hi,

I am trying to count the single-cell reads for each barcode that overlap with the peak regions and I have an intersected bed files looks like that.
chr10	100009612	100010329	chr10	100009293	100009853	AGATAGAAGTTCGTTG	1
chr10	100009612	100010329	chr10	100009343	100009695	TGCTTTAAGTAGCAAT	3
chr10	100009612	100010329	chr10	100009401	100009661	GCGGGTTCATCCCGGA	2
chr10	100009612	100010329	chr10	100009423	100009649	TTTGGCCAGATCTAAG	4
chr10	100009612	100010329	chr10	100009428	100009905	ATGTCGAGTACGACCC	1
chr10	100009612	100010329	chr10	100009433	100009666	TTACTTGCAGCGCGTT	2
 
I am grouping by peak and cell barcodes, then counting the number of lines in each group using the command `bedtools groupby -g 1,2,3,7 -c 7 -o count -i intersect_pbmc_500.bed`. But I found some identical lines in the output that are not grouped. Could you help me see what is the problem with that?

`$ groupby -g 1,2,3,7 -c 7 -o count -i intersect_pbmc_500.bed | sort | head`
chr10	100009612	100010329	AACCGATTCCAGGTCG	1
**chr10	100009612	100010329	AACCTGAGTTAGGAGC	1
chr10	100009612	100010329	AACCTGAGTTAGGAGC	1**
chr10	100009612	100010329	AACCTTTAGTAGTCGG	1
chr10	100009612	100010329	AACGGGATCCGGCGAT	1

Thanks,
Gali

**Comment by arq5x** [comment]
Hi Gali,

Please make sure your file is sorted using the same criteria as your group criteria. This is expected but not enforced by groupby (much like the UNX `uniq` command)

    sort -k1,1 -k2,2 -k3,3 -k7,7 intersect_pbmc_500.bed | $ groupby -g 1,2,3,7 -c 7 -o count -i

**Comment by baigal628** [comment]
That solved my problem! 

Thanks,
Gali
