### ISSUE TITLE
bedtools bamtofastq difference in version 2.29.1 and 2.30

### ISSUE THREAD

**Issue by FenggChengg** [arq5x/bedtools2#951]
Hi all, 

I tried to convert my hifi raw reads (.bam) to fastq format with bedtools2 in two different version, 2.29.1 and 2.30. But they gave totally different fastq size. Is there anyone know what could be the reason?

The command:

bedtools bamtofastq -i Gucris_MPI_ccs.bam -fq Gucris_MPI_ccs.fq

But from bedtools version 2.29.1, the fastq size is : 67,154,194,933
       from bedtools version 2.30, the fastq size is : 134,308,389,866

Why this happened? I used the same command and input. And interestingly, I did the downstream analysis for both of them, the version 2.30 always gave a lot of error. But everything went smoothly for version 2.29.1. 

Many thanks in advance, if you have any experience about this.

**Comment by arq5x** [comment]
I would recommend samtools for this purpose.

**Comment by houahe** [comment]
I think this is because the fastq file output by bedtools-2.30 is duplicated. For example, there are originally 500 reads, but it will output 1000 reads, which contain 500 duplicate reads.
