### ISSUE TITLE
fisher "number of db intervals" incorrect 50% of the time

### ISSUE THREAD

**Issue by joshscurll** [arq5x/bedtools2#954]
For several tests in which I first ran
$   bedtools fisher -a <file1.bed> -b <file2.bed> -g <human.hg38.genome>
and then ran the same command with the -a and -b files reversed, i.e.
$   bedtools fisher -b <file1.bed> -a <file2.bed> -g <human.hg38.genome>,
I found that the "number of db intervals" was always incorrect in exactly one of the two queries. The "number of query intervals" was always correct, while the "number of db intervals" was always correct in one of the two queries but lower than the true number of db intervals in the other query. There was no obvious way to predict which ordering of the -a and -b files would give the correct or incorrect number of db queries -- e.g. it didn't always affect the larger BED file or always affect the smaller BED file. 

The regions in each input BED file were unique/non-overlapping (within each BED file) so this issue has nothing to do with merging overlapping intervals within the same BED file. Also, the actual ordering of the -a and -b arguments in the command line did not affect this issue, so this issue is not analogous to issue #940. In other words, if
$   bedtools fisher -b <file1.bed> -a <file2.bed> -g <human.hg38.genome>
yielded the wrong "number of db intervals", then so too did
$   bedtools fisher -a <file2.bed> -b <file1.bed> -g <human.hg38.genome>.

If bedtools fisher uses a more general bedtools function to read the file passed to the -b option, then it would be important to make sure that this bug doesn't also affect other bedtools commands.

**Comment by arq5x** [comment]
Thanks for reporting this. Fixed.
