### ISSUE TITLE
bedtools coverage cannot deal with some sorted genome

### ISSUE THREAD

**Issue by yech1990** [arq5x/bedtools2#964]
For mouse genome, the chromosome are usually sorted in this way in the bam file, but if we sorted the bed file by sort command in linux, there will be some inconsistency.
 
![image](https://user-images.githubusercontent.com/5415510/149647523-cbad30b2-e7ca-412e-b1b0-e01f8b2bb6d5.png)

**Comment by arq5x** [comment]
The description of the problem is a bit unclear, but I think I understand you want to use an atypical sort order?  If so, provide a `-g` genome file that establishes the desired order.
