### ISSUE TITLE
genomeCoverageBed warning when using commandline example from docs 

### ISSUE THREAD

**Issue by awgymer** [arq5x/bedtools2#968]
Using `bedtools == v2.27.1`

The docs have this line in the usage and options summary.
```
samtools view -b <BAM> | genomeCoverageBed -ibam stdin -g hg18.genome
```

However when running `genomeCoverageBed -ibam <mybamfile> -g <mygenome>` I get the following:

```
*****
*****WARNING: Genome (-g) files are ignored when BAM input is provided. 
*****
```

Is the warning accurate? If so why the example command in the docs?

**Comment by arq5x** [comment]
Yes, the warning is correct. Updating the docs.
