### ISSUE TITLE
terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by asmlgkj** [arq5x/bedtools2#972]
Thanks a lot for building such a powerful tool for bed.
It works very well in the past.
but when I get mutaion postion from TCGA MAF,
then sort first, when merge, it gives the error.

file downloaded: http://api.gdc.cancer.gov/data/1c8cfe5f-e52d-41ba-94da-f15ea1337efc

Mutations - [mc3.v0.2.8.PUBLIC.maf.gz](http://api.gdc.cancer.gov/data/1c8cfe5f-e52d-41ba-94da-f15ea1337efc)

awk '{print "chr"$5"\t"$6"\t"$7}'  mc3.v0.2.8.PUBLIC.maf > mc3.v0.2.8.PUBLIC.maf.bed
sort -k1,1V -k2,2n -k3,3n   mc3.v0.2.8.PUBLIC.maf.bed > mc3.v0.2.8.PUBLIC.maf.bed.sort

bedtools merge -i mc3.v0.2.8.PUBLIC.maf.bed.sort > mc3.v0.2.8.PUBLIC.maf.bed.sort.merge
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoll
Aborted (core dumped)

**Comment by asmlgkj** [comment]
chr1    13283   13283
chr1    13308   13308
chr1    13372   13372
chr1    13428   13428
chr1    13465   13465
chr1    13501   13501
chr1    13501   13501
chr1    13503   13503
chr1    13507   13507
chr1    13515   13515
chr1    13516   13516
chr1    13516   13516
chr1    13521   13521
chr1    13523   13523
chr1    13588   13588
chr1    69345   69345
chr1    69379   69379
chr1    69379   69379
chr1    69408   69433
chr1    69495   69495
chr1    69516   69516
chr1    69517   69517
chr1    69517   69517
chr1    69523   69523
chr1    69538   69538
chr1    69561   69561


<br>
some lines of my file

**Comment by arq5x** [comment]
Is this behavior observed with the latest version (2.30.0)?

**Comment by asmlgkj** [comment]
it has been solved because of my inut, sorry, thanks a lot

**Comment by pi-zz-a** [comment]
@asmlgkj I am experiencing the same problem but cannot find a problem with my input. Can you tell me what was the problem in yours?

**Comment by asmlgkj** [comment]
because my file has a column name, so it went error@[pi-zz-a](https://github.com/pi-zz-a)
