### ISSUE TITLE
bedtools (v2.30.0) merge misses result when not using zcat

### ISSUE THREAD

**Issue by mebbert** [arq5x/bedtools2#975]
Hello,
I was just testing a few commands out with a dummy `.bed.gz` file where I get different results whether I call `bedtools merge -i <input>.gz` or whether I call `zcat <input>.gz | bedtools merge -i stdin`. The `zcat` command is correct.

Here are the exact calls and results:
```
> bedtools merge -i test.bed.gz
1	10000	20000
```

``` 
> zcat test.bed.gz | bedtools merge -i stdin
1	10000	20000
5	55554	66666
```

Looks like a bug to me, but maybe I've done something funky? I've attached `test.bed.gz` to replicate the issue: [test.bed.gz](https://github.com/arq5x/bedtools2/files/8091320/test.bed.gz)

**Comment by arq5x** [comment]
Thanks for finding and reporting this. @38 just fixed this in master. Was a problem with the way the decompression code distinguished BGZF from "plain old GZ"

**Comment by mebbert** [comment]
I think that's the fastest I have ever had a bug fixed. :-)
