### ISSUE TITLE
Description of columns in the bedtools documentation is missing/not actual.

### ISSUE THREAD

**Issue by JaZwy** [arq5x/bedtools2#977]
I run this command (version 2.26.0):

bedtools coverage -a reference_4kbp.bed -b reads.bed > output

output:

chr1      0           4000     2369    4000    4000    1.0000000
chr1      4000     8000     2578    4000    4000    1.0000000
chr1      8000     12000   2655    4000    4000    1.0000000
chr1      16000   20000   4543    4000    4000    1.0000000
chr1      20000   24000   2669    4000    4000    1.0000000

I couldn't find exact meaning of these columns. I found only column's description for over ten columns (13 - 16 columns), which is not the exact output (at least for this version).  
If I understand well, 1. col. (chr1) - name of reference, 2. col (0) - window start, 3. col (4000) - window end, 4. col (2369) - number of reads mapped in the 4 kbp window???, 5. col. (4000) - ???, 6. col. (4000) - ???, 7. col. (1.000) - average of 5/6.

I would need to find the number of reads per window (is it column four?). If yes, how could I normalize it to compare with other samples?

**Comment by arq5x** [comment]
Sorry for the delay - details here: https://bedtools.readthedocs.io/en/latest/content/tools/coverage.html#default-behavior
