### ISSUE TITLE
Error: Sorted input specified, but the file stdin has the following record with a different sort order than the genomeFile

### ISSUE THREAD

**Issue by drowsygoat** [arq5x/bedtools2#978]
I'm trying to circumvent this error, but to no avail:

`Error: Sorted input specified, but the file stdin has the following record with a different sort order than the genomeFile gen.bed`

It seems that my files are sorted correctly, though I [link](https://drive.google.com/drive/folders/1Jedk1xcP_W-Q6rlAJlEw0eH00jTlACS2?usp=sharing) to them here in case someone finds a while to try it.

Here is the command I used:
`cat RT3h_R2_subsampled_mismatch_positions_sorted_chr_arranged.txt | bedtools coverage -a stdin -b test.bam -counts -sorted -split -g gen.bed > out.bed`

**Comment by arq5x** [comment]
I used the "check" `-c` option to test if your file was sorted by chrom and then start position and as you can see it is not:

    sort -c -k1,1 -k2,2n RT3h_R2_subsampled_mismatch_positions_sorted_chr_arranged.txt
sort: RT3h_R2_subsampled_mismatch_positions_sorted_chr_arranged.txt:26: disorder: chr1	10074292	10074293	ENSMUSG00000056763	+	TC	TRUE

You could fix this with:

    sort -k1,1 -k2,2n RT3h_R2_subsampled_mismatch_positions_sorted_chr_arranged.txt > RT3h_R2_subsampled_mismatch_positions_sorted_chr_arranged.sorted.txt
