### ISSUE TITLE
`bedtools complement` working differently when passing a BED file or a subset of it

### ISSUE THREAD

**Issue by MatteoSchiavinato** [arq5x/bedtools2#979]
Hi, 
I am working with a BED file which I want to get the complement of. Here is the BED file (ends in txt due to GitHub's file format limitation): [Full BED file](https://github.com/arq5x/bedtools2/files/8133530/test_before.txt)

When I try to complement it, I get the complement BED line but it starts with an interval going from 1 to -1, which of course is impossible and throws an error in the further step of my pipeline. Since the pipeline is based on `pybedtools`, this makes the program crash with no option to filter out this line before. The error **does not** come from pybedtools: I tried both with it and with the standard command line bedtools. 

Here is the complemented BED file: [Complemented BED file](https://github.com/arq5x/bedtools2/files/8133567/test_after.txt)

If I limit the complement step only to the sequence that is throwing problems, excluding the other chromosomes, the problem goes "away", but it creates an interval from 0 to 0 instead of from 1 to -1 in the beginning. 

See the first line of the output file (2nd in this list): 
- [Subset BED file](https://github.com/arq5x/bedtools2/files/8133528/test_before.subset.txt), 
- [Complement of the subset](https://github.com/arq5x/bedtools2/files/8133600/test_after.subset.txt)

Here are the genome files to reproduce my steps: 
- [Full genome file](https://github.com/arq5x/bedtools2/files/8133624/genome_file.txt)
- [Subset genome file](https://github.com/arq5x/bedtools2/files/8133622/genome_file.subset.txt)

I hope you can help me!

**Comment by arq5x** [comment]
Thanks for providing example files. This seems to work fine for me with the latest release (2.30).

```
bedtools --version
bedtools v2.30.0

head test_before.txt
NC_030976.1	0	103
NC_030976.1	133	43368
NC_030976.1	43396	135620
NC_030976.1	135915	135926
NC_030976.1	136077	136092
NC_030976.1	136376	136391
NC_030976.1	136470	136480
NC_030976.1	137534	137551
NC_030976.1	137825	137835
NC_030976.1	138303	138314

bedtools complement -i test_before.txt -g genome_file.txt | head
NC_030976.1	103	133
NC_030976.1	43368	43396
NC_030976.1	135620	135915
NC_030976.1	135926	136077
NC_030976.1	136092	136376
NC_030976.1	136391	136470
NC_030976.1	136480	137534
NC_030976.1	137551	137825
NC_030976.1	137835	138303
NC_030976.1	138314	140157
```
