### ISSUE TITLE
error with bedtools maskfasta

### ISSUE THREAD

**Issue by raungar** [arq5x/bedtools2#985]
When I run the command `bedtools maskfasta -fi $fa_in -bed $bed -fo $fa_out`  I get the following error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted
```

I get the error with versions bedtools2/2.30.0 and bedtools/2.27.1. 

All files come from here: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.39_GRCh38.p13/GRCh38_major_release_seqs_for_alignment_pipelines/ 

```
fa_in=GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna.gz
bed=GCA_000001405.15_GRCh38_GRC_exclusions.bed
fa_out=GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set_MASKED.fna.gz
```

Thanks,
Rachel

**Comment by arq5x** [comment]
I am pretty sure maskfasta must use uncompressed input.  The output could be compressed with:

    bedtools maskfasta -fi $fa_in -bed $bed -fo /dev/stdout | gzip > $fa_out

**Comment by raungar** [comment]
Hi-

Thank you, uncompressing the input worked.

Thanks!
-Rachel
