### ISSUE TITLE
Why does the sixth column of the non-chain-specific bed file show +&- ?

### ISSUE THREAD

**Issue by 5Tony** [arq5x/bedtools2#991]
Hi all,

I used a set of non-chain specific data, and after STAR comparison, I used bamTobed to convert the bam file to bed format, but +&- appeared in the strand column (Sixth column) .

## Will the non-strand-specific data show +&- in the strand column (Sixth column)? How can I get the strand column (Sixth column) to not show +&-?
![image](https://user-images.githubusercontent.com/66477501/166945823-17729459-9f06-47f0-b257-38b86fbb3631.png)

**Comment by arq5x** [comment]
I am sorry, but I cannot make out what the problem is. Can you clarify with a specific record by contrasting your expected versus observed result?

**Comment by 5Tony** [comment]
Hi arq5x,
 
I am using a set of data that is unstranded in a library way, but this fastq after STAR or hisat2 mapping transforms the bam file to a bed6 file using bedtools bamTobed. By convention, the sixth column (strand column) of the non-chain-specific bed6 should be .(This. represents the expected result and does not represent punctuation) , but I get +-. How can I get the sixth column (strand column) as .(This. represents the expected result and does not represent punctuation) .



This is the expected situation：



This is the observed situation：



This email is the same as Github's reply(https://github.com/arq5x/bedtools2/issues/991#issuecomment-1125227287), and I look forward to your response.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arq5x/bedtools2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 晚上11:14
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [arq5x/bedtools2] Why does the sixth column of the non-chain-specific bed file show +&amp;- ? (Issue #991)





 
I am sorry, but I cannot make out what the problem is. Can you clarify with a specific record by contrasting your expected versus observed result?

**Comment by arq5x** [comment]
Bedtools is simply reporting the strand provided in the BAM file, as defined by the aligner.
