### ISSUE TITLE
"moving average" to coverage signal with bedtools

### ISSUE THREAD

**Issue by Shicheng-Guo** [arq5x/bedtools2#992]
Dear Team, 

I am wondering is there an option/function to perform "moving average" to coverage signal with bedtools?

something like: `bedtools movingAverage -i a.bed --start --end --bin 200 --out `

Thanks. 

Shicheng

**Comment by arq5x** [comment]
Unfortunately, no. However, you could compute something like this with a script that processes the per-base depth output of `genomecov`.
