### ISSUE TITLE
Document making a "genome file" from FASTA

### ISSUE THREAD

**Issue by peterjc** [arq5x/bedtools2#996]
Some of the bedtools have a ``-g`` option wanting a "genome file" as described here:

https://bedtools.readthedocs.io/en/latest/content/general-usage.html#genome-file-format

i.e. 2-column tab separated table, with reference sequence name and length.

The documentation does not describe how best to generate such a file from a FASTA file (e.g. working with a local assembly rather than a reference like human or mouse).

I'll write a quick script to do this, but expected there to be an official bedtools implementation but I could not find it.

**Comment by jmarshall** [comment]
For many years, I've been meaning to write a PR making it more explicit that bedtools ignores columns beyond the first two (I assume this is still the case), and hence that _.fai_ files are suitable for use with these `‑g` options.

Hence `samtools faidx` is a suitable way to generate such a file.

**Comment by arq5x** [comment]
added docs for the faidx solution to master. thanks all.

**Comment by arq5x** [comment]
added command-line tips as well
