### ISSUE TITLE
filtering BED files by region length

### ISSUE THREAD

**Issue by peterjc** [arq5x/bedtools2#997]
Is there anything in bedtools to help with filtering a feature file by region length? e.g.

* Given a genome annotation, find me all the exons over 3000bp.
* Given a mask showing the location of all the "N" in the genome, find those under 100bp.
* Given a mask of high coverage regions, find those at least 500bp long.

I can solve this easily with a simple script computing lengths from the difference in BED columns 2 and 3, but was surprised not to find anything built-in after searching the documentation. Am I overlooking something? Thanks.

**Comment by arq5x** [comment]
No, there is nothing like this. I generally just use awk but I see your point that a basic filtering tool would be nice.
