### ISSUE TITLE
bedtools complement ". Exiting...illegal number "

### ISSUE THREAD

**Issue by marija-kra** [arq5x/bedtools2#998]
Hi,

I'm running bedtools v2.30.0-50-g8c0d2cc3 on macOS and have this error when trying to run bedtools complement:

`". Exiting...illegal number "43341`

The command I ran:
`bedtools complement -i /path/to/file.bed -g /path/to/genome/file.txt > outputfile.txt`

The genome file is in the specified format in a tab-separated *.txt file:
tig00000001	43341
tig00000002	5080222
tig00000004	129278
tig00000008	99441

Any suggestions for how to resolve this error? Thanks!

**Comment by yaaminiv** [comment]
I got a similar error running `complementBed`  v2.30.0 on macOS: `ERROR: illegal number ":primary". Exiting...` 

input file:

```
KN805525.1	ensembl	exon	2500	2651	.	-	.	gene_id "ENSFHEG00000014345"; gene_version "1"; transcript_id "ENSFHET00000020248"; transcript_version "1"; exon_number "4"; gene_name "cdx1a"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "cdx1a-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSFHEE00000192221"; exon_version "1";
KN805525.1	ensembl	exon	5166	5274	.	-	.	gene_id "ENSFHEG00000014345"; gene_version "1"; transcript_id "ENSFHET00000020248"; transcript_version "1"; exon_number "3"; gene_name "cdx1a"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "cdx1a-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSFHEE00000072033"; exon_version "1";
KN805525.1	ensembl	exon	8335	8483	.	-	.	gene_id "ENSFHEG00000014345"; gene_version "1"; transcript_id "ENSFHET00000020248"; transcript_version "1"; exon_number "2"; gene_name "cdx1a"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "cdx1a-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSFHEE00000192263"; exon_version "1";
KN805525.1	ensembl	exon	10201	10348	.	-	.	gene_id "ENSFHEG00000014345"; gene_version "1"; transcript_id "ENSFHET00000020248"; transcript_version "1"; exon_number "1"; gene_name "cdx1a"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "cdx1a-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSFHEE00000072050"; exon_version "1";
KN805525.1	ensembl	exon	38959	38960	.	+	.	gene_id "ENSFHEG00000014326"; gene_version "1"; transcript_id "ENSFHET00000020197"; transcript_version "1"; exon_number "1"; gene_name "pdgfrb"; gene_source "ensembl"; gene_biotype "protein_coding"; transcript_name "pdgfrb-201"; transcript_source "ensembl"; transcript_biotype "protein_coding"; exon_id "ENSFHEE00000192162"; exon_version "1";
```

genome file: 

```
KN805525.1	6356336
KN805526.1	6250690
KN811289.1	6115441
KN811310.1	5246820
KN811405.1	5058772
```

**Comment by arq5x** [comment]
@yaaminiv I am unable to reproduce the error with the input you provided. Works fine for me.  Is there a large file you could share that generates the error?

@marija-kra I would need to see the contents of the input bed file to help.

**Comment by yaaminiv** [comment]
> @yaaminiv I am unable to reproduce the error with the input you provided. Works fine for me. Is there a large file you could share that generates the error?

@arq5x The exon.gff file can be found at this link: https://osf.io/7un5h/

genome file: https://github.com/yaaminiv/killifish-hypoxia-RRBS/blob/main/genome-features/mummichog.chrom.length

This is the code I used:

```
{bedtoolsDirectory}/complementBed \
-i Fundulus_heteroclitus-3.0.2.105-exon.gff \
-g mummichog.chrom.length \
> Fundulus_heteroclitus-3.0.2.105-nonCDS.bed
```

**Comment by arq5x** [comment]
You problem is this odd length for Mt:

    grep primary mummichog.chrom.length
    MT	:primary

**Comment by yaaminiv** [comment]
> You problem is this odd length for Mt:
> 
> ```
> grep primary mummichog.chrom.length
> MT	:primary
> ```
> 
> Must be an integer

Thanks!

**Comment by marija-kra** [comment]
Hi @arq5x, I uploaded both the genome file and bed [here](https://drive.google.com/drive/folders/1gZx-ZRYlqEg8rA1sek_ReOpB4YyZdm7x?usp=sharing). I wonder if the fact that the bed is mostly in regions that are 1 base long might be the issue.

**Comment by marija-kra** [comment]
> 

You seem to be correct! 
`ASCII text, with CRLF line terminators`

**Comment by arq5x** [comment]
Yes, the "^M" indicates a window line ending:

    cat -t ~/Desktop/canu_tb427_ont.contigs_pilon_4x_bedtools_genome.txt | head -n 2
    tig00000001^I43341^M
    tig00000002^I5080222^M

You can fix this with `sed` or `tr`. Here is an approach that works with tr (remove the `\r`):


    cat canu_tb427_ont.contigs_pilon_4x_bedtools_genome.txt \
    | tr -d '\r' \
    > canu_tb427_ont.contigs_pilon_4x_bedtools_genome.UNIX.txt

**Comment by marija-kra** [comment]
Thanks, @arq5x and @jmarshall ! It seems to work now.

**Comment by arq5x** [comment]
Glad to hear it. Thanks as always for your help, @jmarshall

**Comment by jmarshall** [comment]
No problem — I should have noticed that when I first glanced at the reported error message a couple of days ago! 😄 

Most parts of bedtools — e.g. the main BED file parsers — can happily accept either Unix- or Windows-style line termination. The genome file reader is a bit of an outlier, so PR #999 suggests making `-g` accept Windows-style files on reading too. Which would be a small fix to make @marija-kra's problem go away entirely.
